### ISSUE TITLE
서브시스템_팩맘 아트 리소스 제작3

### ISSUE THREAD

**Issue by yanggang3** [GG-Studio-990001/Grayed-Game#167]
#157에 이어서 라플리 디버프 버전 수정, 먼지유령 종류 추가, 타일맵 보완/수정하는 작업 진행하였습니다.

https://drive.google.com/file/d/17t7VK08ADGpehxIfDrREZ0y30vKRT6dB/view?usp=drive_link
타일맵 32 x 32 로 크기 수정한 버전입니다. 8가지 모양의 타일에 상하/좌우반전해서 29개입니다!

https://drive.google.com/file/d/1LbQZngfGMGj1ZTXhFMgE5ma7bz1Q7MKO/view?usp=drive_link
기본 먼지유령에 명도가 더 높은 색상 추가로 제작했습니다. 

https://drive.google.com/file/d/1BpnvZxV-I17bp4wLtHK5qfYH-qfEsS2V/view?usp=drive_link
기존 팩맨에서 코인이었던 걸 비눗방울로 바꿔고, 청소기 아이템입니다.

https://drive.google.com/file/d/19HwNCy_KTi73WQKDKRPMCE7RqQ03mDCE/view?usp=drive_link
팩맘 최종버전으로, 기절하는 모션 추가하였습니다.

https://drive.google.com/file/d/1EAGPvcHOBhPs61SGcinbh6MAcQCqIqMF/view?usp=drive_link
라플리 디버프 버전을 조금 수정하였습니다.

이 리소스들로 적용되는 장면을 보고 팀원분들과 상의하여 더 디벨롭하겠습니다.
피드백은 언제나 환영입니다.. 감사합니다!

**Comment by CreatorLDH** [comment]
우연님이 피드백을 너무 잘주셔서 저는 할 말이 없네요.
고생하셨습니다들!!!

**근데 코인에서 비눗방울로... 왜 바꼈죠?**

**Comment by wooyn730** [comment]
세화님 이따 회의 때 저희 비정기 회의 시간 잡아요!!!!

++
ㅋㅋㅋㅋ 비눗방울 저 없을 땨 이야기가 된 게 아니군요?
*동호님 굵은 글씨 무섭ㄷㄷ*

저도 궁금햤는데.. 세화님 혼나야겠다..... (농담)

**Comment by yanggang3** [comment]
@wooyn730 요구사항 자세히 알려주셔서 감사합니다!
이따 회의 끝나고 더 얘기해보아요
비눗방울은 꼭 다시 수정하겠습니다...
