### ISSUE TITLE
[Universe] 일러스트 제작_01

### ISSUE THREAD

**Issue by yanggang3** [GG-Studio-990001/Grayed-Game#323]
게임 인트로의 라플리가 등장하는 장면 작업하기.

**Comment by yanggang3** [comment]
저번주부터 감기가 잘 안나아서 작업 며칠만 뒤로 미뤄야할 것 같아요... 너무 죄송합니다..

**Comment by wooyn730** [comment]
24-03-08

개인 사유로 인한 작업 기한 연장
