### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#361]
# Title

## 설명

타이틀 작업 관련 이슈들 모아두기 (WBS)

## 아트
@royalbluesm 
- #326 
- #327 
- #338 
- #372 

## 사운드
@Songkihwa 
- #354 
- #369 

## 플밍
@wooyn730 
- #360
- #371 
- #382

**Comment by wooyn730** [comment]
구드에 [_Title 폴더](https://drive.google.com/drive/folders/1INLtWT-ZWQPTkGZs5huHQKbszeqtA9-a) 생성 후 아트, 사운드 이동했습니다~

**Comment by fkdl0048** [comment]
@wooyn730 수정된 사항 빌드로 볼 수 있나요?

**Comment by wooyn730** [comment]
@fkdl0048 

수정된 아트 올라오면 적용해서 올리려고 했습니다
아니어도 7시 전에는 빌드 올려놓겠습니다
