### ISSUE TITLE
시나리오 구체화 기초작업

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#368]
향후 기획에 바탕이 될 '[시나리오 구체화 기초작업](https://drive.google.com/file/d/1VvVcdUBibp3_ULE6qnnbE1rGRjzJyrUy/view?usp=sharing)' 문서를 작성했습니다.
아이디어 제안의 차원에서 읽어주시면 감사하겠습니다.

## 1. 라플리의 의미
**라플리**
잊혀진 게임을 서로 연결해주는 존재이며 플레이어(캐릭터)이자 게임 그 자체

**Why 연결?**
아무리 수많은 게임들이 잊혀지더라도, 게임이라는 것 자체는 늘 존재하고 있다.
그러므로 잊혀진 게임들은 완전히 사라질 수조차 없으며 그저 누군가 다시 기억해내기를 기다리는 것뿐이었다.
그러나 그 기다림은 오랫동안 지속되었기에 잊혀진 게임은 서로에 의해 의지하여 버티고자 하나둘씩 어딘가로 모이게 되었다.
그곳은 잊혀진 게임들이 오는 마을, GG TOWN이다.
	→ 라플리는 깊은 기억 속에 파묻힌 잔해 같은 게임들이 잊혀지지 않도록 다시 일깨우고 	서로를 조합해 게임에 접속 및 플레이하는 연결의 힘을 가짐
	→ 중요한 것은 이런 힘을 가진 라플리조차도 잊혀졌기 때문에 마을에 왔다는 사실

**연결의 2가지 측면**
[1] 장르간의 연결 (게임 플레이적 측면)

- 	서로 다른 게임의 장르를 연결하여 플레이할 수 있는 시스템 구조
- 	게임 내내 지속됨

[2] 라플리와 GameOver 유저간의 연결 (메타적 측면)

- 	라플리는 유저에 의해 GameOver의 플레이어(캐릭터)로서 기억되고 있음
- 	못된 마음을 먹은 누군가(예: Bad라플리)는 유저를 빼앗아 자신과 연결시키려 할 것
- 	이렇게 단절이 될 경우, 유저는 라플리를 게임으로서 되찾아 연결하고자 플레이하게 됨

→ 즉, 게임 내내 지속되게끔 기획할 필요가 없음 (Ch3,4에서 활용해 국면전환 가능)

## 2. 스토리 Develop
**엔딩**
‘라플리’라는 게임을 찾고 있는 유저에게 가기 위해 웜홀에 뛰어든다.

**라플리의 목적성**
- 연결의 힘을 활용해 마을을 탐험하며 리소스 마운틴 아래로 막혀 있던 웜홀을 뚫기 (=목표)
- GG Town을 벗어나 유저와 진정한 연결을 통해 자신의 의미를 되살리기 (=엔딩)

**마을 구조 확장**
리소스홀 : 잊혀진 게임들이 위에서 떨어지는 구역
리소스 마운틴 : 잊혀진 게임들이 쌓여 마치 산처럼 모여 있는 구역
웜홀 : 잊혀진 게임을 누군가 다시 찾을 때만 열리는 구역, 리소스 마운틴 맨 아래에서 막혀 있음

**웜홀이 막힌 이유 (택1)**
[1] 웜홀 위로 너무 많은 게임이 쌓여 리소스 마운틴이 형성되는 바람에 웜홀이 제 기능을 못함
[2] 누군가 고의적으로 잊혀진 게임의 귀환을 막고자 웜홀의 가동을 방해함

**Bad라플리의 성장배경**
유저가 게임을 실행했지만 라플리는 마을 깊숙한 곳에서 잊혀진 채 잠들어 깨어나지 못했다.
결국 게임은 라플리를 새로 복제하여 관념적인 존재로 게임에 참여시키게 된다.
그와 동시에 본체에서 무언가 빠져나가는 느낌을 알아챈 라플리가 눈을 뜨지만, 이미 게임이라는 의식은 사라진 채 껍데기만 남은 존재가 되고 말았다는 것을 알게 된다.
그렇게 다시 게임이라는 존재로 거듭나기 유저를 맹목적으로 갈구한다.
새로운 라플리가 유저와 함께 마을을 돌아다니고 있는 것을 발견한 라플리는 분노에 휩싸이며 유저를 강탈하기 위해 리소스 숭배 집단에 접근하여 나쁜 계획을 세운 Bad라플리로 전락한다.
→ Bad라플리와 강제 연결되면 게임을 처음부터 시작 (마을 재방문, 시야 확장, 화면 글리치)

**전체 사건 플로우 확장**
발단1 : 쓰러진 라플리는 마을 사람들에 의해 발견되고 자신의 가치를 증명함 (=튜토리얼)
발단2 : 마을에 입성, 사람들과 교류하며 마을에 대해 이해하게 되고 심마니로 인정을 받음 (=Ch1)
전개 : 리소스 숭배 집단의 등장과 대립 (=Ch2)
위기 : 리소스 숭배 집단의 대장이자 또 다른 나 ‘Bad라플리’와 조우, 유저를 강탈해 감 (=Ch3)
절정 : 고밀도의 뒤섞임 현상 발생, 마을을 재방문하여 라플리를 찾아내 다시 연결 (=Ch4)
결말 : 리소스 마운틴 내부를 탐험, 웜홀을 뚫고 그 아래로 뛰어듦 (=Ch5, 엔딩)

**고민되는 점**
- 리소스 숭배 집단의 흑막이 Bad라플리였다는 서사가 부족함
- 라플리와 다시 연결된 이후 Bad라플리의 행방
- 엔딩 이후 남겨진 게임들, 마을 사람들의 행방

**Comment by fkdl0048** [comment]
# 피드백

회의 때 말을 했지만, 기록과 다시 한번 읽어보고 생각을 정리해봤습니다.

과거에 기획적으로 불완전한 부분을 스토리적으로 많이 걱정하시고 작성하신 느낌이 듭니다. 디렉팅적으로 제가 강조하고 싶었던 `메타적인 요소`와 `게임`이란 핵심적인 부분을 잘 담아주신 것 같습니다. 이후에 기획되는 내용에서도 어렵겠지만 지금처럼 잘 만들어주시면 좋을 것 같습니다.

## 라플리의 의미

> → 중요한 것은 이런 힘을 가진 라플리조차도 잊혀졌기 때문에 마을에 왔다는 사실

현재 플레이어에 의해 기억되고 있음 -> 게임을 플레이 하는 플레이어 특성 (다시하기, 설정창 등등)

컨텐츠적으론 아마 위에 적은 플레이어의 특성이 잘 들어나야 할 것 같습니다.

>  Bad라플리

배드라플리에 관하여 어떤 존재인지 좀 더 구체화가 필요해보입니다. 라플리의 오리진 게임의 파생인지? (현재 스토리에 밀접하게 포함된 이미테이션 게임의 형태로 라플리 게임의 파생적인지?)

배드라플리는 이 마을의 시스템에 대한 이해가 다 끝난 상태여야 할 것 같습니다

1. 라플리와 밀접한 관련이 있거나
2. 라플리가 접속 게임에서 살아서 돌아온 것을 보고 의문을 가지고 유저의 존재를 알아냄?

## 스토리

읽다보니 생각이 든 것은 라플리가 결국 자신이 원래 있는 게임으로 돌아가는 것이 좋겠다는 생각도 든 것 같습니다.

현재 라플리가 자아가 거의 없고, 저번 게임 엔딩으로 게임을 다시 켰을 때, 라플리가 온 게임의 화면만 나온다와 같은 기획을 생각한다면..?

or 게임은 플레이 하는 사람이 있어야 생명력을 얻는다. 

-- 작성중..

**Comment by wooyn730** [comment]
해당 이슈의 `시나리오 구체화 기초작업` 문서와 [이전 기획 비정기 회의](https://github.com/GG-Studio-990001/GameOver/issues/373)의 `장르변환 당위성 고민` 문서를 읽고, 또 그 외 등등 들었던 생각들을 정리해서 달아봅니다!

생각 내추럴하게 다 적을테니 후루룩 읽어주시길..
뭐 하나라도 건질만한 것이 나오길 바라며...

---

### 1) 마을 구조의 확장

`웜홀` 아이디어 너무 좋다
화이트홀이 블랙홀의 이론적 반대현상인 것처럼..
들어가는 곳이 있으면 나오는 곳이 있다는 아이디어가 합당하고 세계관에 잘 맞아보임

잊혀짐 => 구멍A => GG Town(마을) => 구멍B => 기억됨의 흐름?

GG Town이 연옥(천국과 지옥 사이의 위치)라는 느낌이 들기도 했음

### 1-1) 막 써보는 스토리A (휴게소와 할아버지)

원래 모든 것들은 때론 잊혀지고, 때론 기억되길 반복됨
이는 자연스럽고 건강한 현상임
GG Town은 그 과정에서 휴게소처럼 사용되는 공간
(인기 없는 게임이 머물기도, 인기 있는 게임도 버그/업데이트로 인해 가끔 머물다 가기도도 하는 공간)
![image](https://github.com/GG-Studio-990001/GameOver/assets/80298207/9b142541-9a6e-437d-a0f6-31985e45b9a9)
_주먹왕 랄프의 이런 이미지도 생각남. 터미널 같은?_

아주 컬러풀하고 생기 있는 공간임
물론 이미 흑백이 되고 기억을 잃은 존재도 있겠지
그 중 하나가 잊혀진지 오래된 할아버지 NPC
완전 초반에 마을에 정착하여 살아감
휴게소 통감자 파는거마냥 게임 리소스들을 재화로 거래하고 쓰기 시작한 초기 인물 중 하나임
근데 파밍하다가 웜홀을 발견한 거임
자기가 재화로 쓸 것들이 구멍으로 빠져나가는 것들을 보고 홀을 막아버림 (악의가 있을지도 없을지도?)

그 후 마을은 첫 번째 혼돈의 시기를 겪음
보통 잠깐 머물다 가는 공간인데 웜홀이 막힘으로서 수 많은 NPC들이 돌아가지 못함
패닉하고 절망해서 다 불타고 막 싸우고 황폐화됨
이를 중재하는 역할(늙은 엘프 여성)로 겨우 안정을 되찾기 시작
그 동안 존재하던 NPC들은 점차 색도 잃어가고 기억도 잃어감 (아트풍도 획일화(도트화)됨)
대부분 NPC들은 자신은 원래 마을에서 존재하기 시작했던 것이라고 생각함
(할아버지 NPC도 지가 막은거 까먹음...)

이후에 마을에 떨어지는 게임 리소스들은 아주 빠른 속도로 마을에 동화됨
(왜냐면 마을엔 이미 색이 너무 없어?)
그러던 중 라플리가 마을에 도착함

그러다 마을에 두 번째 혼돈의 시기가 시작됨
웜홀이 막혀서 리소스들이 너무 많이 쌓이고 아무데나 쌓이는거임
그러고 라플리가 해결

이 이야기의 구멍: 
왜 라플리 말고 다른 캐릭터들은 구멍으로 안떨어졌는가?
라플리가 좀 더 특별한 존재로 보여야 함 (색이 있다던가, 그래픽이 다르다던가)

### 1-2) 웜홀 용어에 대해

웜홀은 `우주 공간에서 블랙홀과 화이트홀을 연결하는 통로를 의미하는 가상의 개념`이라고 함. (라고 위키백과가 그럼)

그 둘을 연결한 통로라고 하면 마을이 그런 존재가 아닐까?
현실 세상에서 게임이 사라지고 나온다면
리소스홀 == 블랙홀, 웜홀 == 화이트홀?

리소스홀 / 웜홀 말고 좀 더 직관적인 이름은 없을까

아님 기억통로-망각통로, Remember Hole-Oblivion Hole..

### 2) Bad 라플리

이 세상에 문제가 있고, 주인공이 해결하는 과정에서
악역의 등장은 게임에 개연성?을 부여하는 존재인 듯

### 2-1) 막 써보는 스토리B (Bad 라플리들)

모든 게임이 그렇듯 게임이 시작될 때마다 존재가 생성됨
마을에도 이미 비슷하거나 동일하게 생긴 존재들이 있음

Bad 라플리는 우리 라플리보다 먼저 온거임..
Bad 라플리는 집단일 수도 있음
라플리가 여러명인거임
처음 등장한 Bad 라플리가 자아가 쎄고 성격이 나쁨

Bad 라플리 집단들은 리소스홀에서 캐릭터들이 떨어지면
바로 납치하고 자기 무리로 만듦
왜냐면 얘네는 잊혀진지 얼마 안됐잖아 너무 질투나는거야
(그래서 라플리는 정말 간만에 리소스홀에서 떨어진 사람인거임)

그러다가 라플리가 또 떨어졌어
근데 납치하려고 갔는데 웬걸? 얘는 플레이어랑 연결돼있어
Bad 라플리 집단 질투나서 미쳐버림

그래서 라플리 괴롭힘

그러다 결말 쯔음에 웜홀이 있었고, 막힌게 제3자라는 것을 알게됨 
잊힌게 아닐 수도 있구나 누가 막았던 거구나🥹 정화되어버리기ㅣ

### 3) 마을 사람들의 행방

아직 색이 남아있는 + 의식이 있는 존재들은 돌아가고
그 외 이미 정착한지 너무 오래된 존재들은 남아있기..
대신 GG Town에 앞으로 거쳐갈 낯선자들과 잘 지내는 것임

### 4) 장르의 변환

개발자의 입장에서 장르의 변환?
하나의 마을을 다양한 시선으로 플레이어에게 보여주며
새로운 경험을 제공하고 스토리를 풀어감.

하지만 장르 바꾸고 싶다고 막 바꾸는 게임은 없을거임..
장르는 게임의 정체성 중 하나이기도 하니까...

근데 우리 게임은 장르를 변환하기로 구성을 잡음
그럼 현재 스토리에서 장르 변환의 당위성은 어떻게 되는가?

다른 게임
에보랜드 => 게임의 역사, 발전 과정이 주임. 그 사이에서 자연스럽게 변화가 일어남
I hate this game => 각 스테이지 클리어를 목적으로 스테이지마다 변주가 들어감
이건 게임이 아닙니다 => (잘 모름) 플레이어가 게임 속 존재?를 괴롭히기 위해 여기저기 탐험하며 게임 세상을 돌아다님

_(신박한 게임들 검색하다가 [이 영상](https://www.youtube.com/watch?v=eEDStxYTkuM) 보고 옴)_

여러개 구경하면서 느낀 점
=> 현재 시스템도 단순한 편이 아닌데 장르 변환까지 추가하여 다른 게임들처럼 한 줄로 설명될 세계관, 일관성을 가질 수 있을까?

흠 어렵다 초심으로 돌아가서
우리 게임의 키워드는 `게임` + `잊혀짐`?
여기에서 장르를 변환해야 하는 이유는 뭘까...

잊혀진 게임들이 모이는 마을 + 그 안에서 접속하거나 UI 획득을 통해 게임 속 게임 플레이 가능 + 결국 게임이 너무 많이 쌓여버린 이 마을의 문제점 해결
이라는 현재의 설정에서 장르를 변환한다는 것을 추가해야 하는 이유는..?

장르를 챕터에 1:1 대응 시키지 않고 **UI를 획득한 게임 플레이의 확장**으로 생각한다면 어떨까?
SLG UI를 획득해서 SLG를 플레이하는 것처럼............. 비주얼 노벨도 동일한 메커니즘이라면.................................
_챕터는 개념적인 분류일 뿐...._

**Comment by Sumindd** [comment]
저는 기획 회의 때 감상을 이야기 했기 때문에 기록만 할 겸 간단히 적겠습니다!

### 사건 플로우

플로우가 직관적이고 대립하는 존재가 명확해져서 좋습니다. Bad라플리의 역할이나 자세한 설정은 주제나 엔딩 방향을 정한 후에 다듬어보면 될 것 같습니다. 시나리오 재밌을 것 같아요!

### 연결

저는 이 시나리오에서 핵심이 되는 단어가 '연결'이라고 느꼈습니다. 그래서 주제나 방향 자체를 '유저'와 라플리의 '연결'을 통한 무언가(성장 혹은 깨달음?)로 잡고 가면 될 것 같다고 말씀드렸습니다. 라플리는 결국 다른 NPC들과 다를 것이 없지만, 유저가 라플리에게 '연결'되어 플레이 했기 때문에 접속 게임에서도 탈출했고, 데자뷰 같은 능력도 얻게 되면서 특별해졌다고 볼 수 있기 때문입니다. 그래서 현재 고민 중인 장르 변환 당위성 역시 유저와의 연결과 연관 짓거나 자연스럽게 이어지는 방향으로 나아가면 좋을 것 같습니다.

**Comment by royalbluesm** [comment]
### 주인공을 방해하는 악역의 등장
스토리의 양 축이 단단히 세워진 것 같아서 악역을 등장시킨 것은 좋은 생각인 것 같습니다. 저번에도 얘기가 나온 것처럼 어떤 버그가 있어서 원본 라플리에게 나쁜 영향을 끼쳤다든가... 아니면 이전의 플레이어가 폭력적이고 악한 성향의 플레이를 해서 (언더테일의 학살 루트처럼) 성격이 그렇게 굳어진 라플리가 되었다는 설도 괜찮을 것 같습니다.  사실 악역이 알고보니 또 다른 주인공이었다, 라는 스토리는 굉장히 메이저하면서도 재밌는 소재이기 때문에 당위성과 개연성을 다듬으면 충분히 매력적인 스토리가 나올 것 같아요. 

배드 라플리가 상징하는 것과, 우리가 조종하는 라플리가 상징하는 것을 서로 대립시켜서, 정-반-합의 스토리 구조로 나아가는 것이 정석적이지 않을까 싶습니다. 이 경우 배드라플리는 교화되고 마을 사람들은 GG TOWN에서 평화로운 일상을 이어나가다 웜홀로 나갈 때를 기다리며 살게 되지 않을까 싶네요.

###연결
수민님이 말씀해주신 것처럼 주인공의 핵심 능력인 '연결'은 서사적으로 중요한 열쇠가 될 수 있다고 생각합니다. 대부분의 창작물에서 '연'을 소중한 가치로 생각하는 것처럼, 연결이 단순히 게임 내에서 서로 다른 게임을 연결해주는 능력에서 그치지 않고 라플리, 혹은 플레이어만이 가진 힘 (언더테일에서의 의지 같은)으로써 기능할 수 있으면 좋겠다고 생각합니다.
