### ISSUE TITLE
[CH1] 플로야드 맵 세부 오브젝트 연구

### ISSUE THREAD

**Issue by gomgom172** [GG-Studio-990001/Grayed-Game#370]
- #353 
해당 이슈에서 이어서 플로야드 맵 세부 오브젝트 그래픽 연구 진행합니다.

### 작업 계획
- 플로야드 맵 디테일 추가를 위해 오브젝트를 작업합니다.
- 맵과 어울릴 수 있는 오브젝트 그래픽을 연구합니다.

> 톤
> 디테일 다양화, 크기 비례 무시 & 크기 다양화
> 게임 리소스처럼 보이도록 or 오브젝트 다양성

지난번 피드백에 달아주셨던 내용 토대로 여러 시도를 해볼 예정입니다.

우선은 레퍼런스 연구 → 오브젝트 수정 및 다양화 시도 → 그래픽 조정 등의 단계로 진행되게 될 것 같습니다. (진행 중 수정 가능성 높음)

차후 과정을 업데이트하겠습니다.

# 240331 업데이트

![0331-2](https://github.com/GG-Studio-990001/GameOver/assets/162591960/ef49a6c0-d8b9-44c9-bea3-a427c2777b6b)

아이디어와 그래픽 스타일 위주로 봐 주시면 감사하겠습니다.

### 염두에 둔 부분
- 리소스 간 크기 비례 무시 & 크기 다양화
- 게임 간 해상도 차이 표현(아직 눈에 띄는 구현은 못했습니다… 비교적 최신 사양의 게임을 표현할 때에는 픽셀 디테일을 좀 더 올려서 작업하는 식으로 표현하게 될 것 같아요!)
- 게임 리소스처럼 보이도록 (해당 게임을 모르는 사람에게도 '고전게임 리소스구나' 싶을 수 있도록)
- 측면으로 꽂혀 있거나 절반 정도 보이는 구도(+픽셀아트의 규칙을 깨지 않을 것)

### 아직 표현되지 않은 부분
- 오브젝트 다양성

톤앤매너를 깨지 않으면서 게임 리소스를 표현할 수 있는 그래픽 연구가 우선이라 판단하여 세부 오브젝트 종류는 보류하고 작업 진행했습니다. 

(버려진 안)
![0331-3](https://github.com/GG-Studio-990001/GameOver/assets/162591960/5ab98eea-5aad-4d6a-9221-2efb7b640fc1)

그래픽 스타일만 고민하다가 묘사 위주의 작업도 염두에 두었었는데, 그래픽 스타일을 포함하여 게임 전체의 방향성과도 맞지 않다고 판단하여 폐기했습니다. (자신 있는 분야가 아니기도 하고요)

고민이 많아 우선 갈무리하였습니다. 아이디어와 의견 언제나 환영합니다 ^_ㅠ

**Comment by fkdl0048** [comment]
이우님도 마찬가지로 작업하시게 될 내용 좀 더 세부적으로 나눠서 작성해주시면 좋을 것 같습니다.

이 작업을 왜 하는지, 어떻게 할 것인지, 단계로 나눠서 작성해주세요!

**Comment by gomgom172** [comment]
240331 작업내용 업데이트했습니다.

**Comment by Sumindd** [comment]
처음에 보고 어느 부분에 넣은 건지 못 알아챘을 정도로 너무 잘 녹아든 것 같습니다! 크기가 다르게 들어가는 걸 당연히 앞쪽 레이어에 배치하는 것만 생각했는데 완전 뒤쪽에 커다랗게 넣으니까 더 풍성해보이고 자연스럽네요 역시 아트의 눈은 다른 것 같습니다. 전체적으로 피드백도 잘 반영된 것 같고, 너무 좋아졌다고 느껴집니다!

**Comment by fkdl0048** [comment]
저도 시야에서 벗어나서 배치하게 된 모습이 더 마음에 드네요, 시각적으로 어떤 세계관인지 시야가 너 넓어진 것 같습니다.

**Comment by wooyn730** [comment]
매우 크고 누가봐도 게임인 리소스들을 맨 뒤에 배치하니까 세계관이 살아나네요!
풍성해보인다는 의견에도 공감합니다.

저는 개인적으로 버려진 버전도 꽤 마음에 들어요.
특히 한 픽셀의 크기?가 다른 리소스과 동일해서 통일감이 들어보인다는 점?

**Comment by roweclaw** [comment]
저도 뒷 배경에 리소스들이 너무 자연스럽게 배치되어서 깜짝 놀랐어요! 리소스들간의 크기 비례 무시, 크기 다양화가 정말 잘 적용된 것 같습니다. 금이 간 부분도 분해되는 중인 듯하게 표현되어 있어서 훨씬 세계관 표현이 잘 되어 보입니다!!
