### ISSUE TITLE
[CH1] 튜토리얼 세부 플로우

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#375]
- #373

위 이슈에서 진행했던 [튜토리얼 세부 플로우](https://drive.google.com/file/d/1c1_5pCo5gXFhCar2Nc3nsAWVMK-MICk0/view?usp=sharing)를 문서로 정리합니다.

### 플로우 목차

1 : 라플리 떨어지고 팩맘 찾기
2 : 팩맘 접속과 탈출
3 : 3매치 퍼즐
4 : SLG 얻어서 마마고 컴퍼니 건설
5 : 마마고 컴퍼니 보상 + 6 : 기계어 번역팩 획득
7 : 마을 입구로

### 세부 플로우

_문서에서 확인 부탁드립니다._

### 고민되는 점

> 5- ①	: ‘마마고’ NPC가 등장해 우리 상점을 만들어 주어서 감사하다는 말을 꺼낸다.

[ 5-1 ]에서 발전기가 삭제된 마마고 컴퍼니에서 내부를 보여줘야 할 필요성이 없다. 내부 요소를 살리기 위해서는 직원 고용 등의 활용이 필요한데, 지금의 아트는 내부에 이미 직원들이 많이 존재하는 상태이다. 여기서 2가지 문제 발생.
1. 이제 막 건설된 마마고 컴퍼니 안에 직원이 꽉 차 있는 것이 어색하다고 느껴진다.
2. 직원 고용 콘텐츠를 활용해 내부를 채워가려고 하니, 쯔꾸르 탑뷰 리소스는 튜토리얼에서만 쓰일 텐데 이를 위해 튜토리얼을 늘릴 필요는 없다.

→ 우선 생각한 대안 : 건설 시 코인 소모해 ‘시간 단축’을 시키는데, 건설뿐만 아니라 마마고 컴퍼니의 경영적 성장까지 진행되는 시간이 빨리 흐르게 하는 것으로 포함하여 직원이 늘어나게 되었다. 그 결과 이미 직원이 있는 발전된 상태의 마마고 컴퍼니를 완성하게 되는 것으로 하기.

**Comment by fkdl0048** [comment]
튜토리얼 플로우는 현재 기획된 시스템과 세계관을 잘 보여주는 것에 집중해야 한다고 생각합니다. 순서는 정해졌으니 다음 주에는 해당 순서로 동작하는 빌드를 만드는 것을 목표로 잡으면 좋겠네요. 세부 플로우도 해당 파일을 기점으로 구체화하는게 좋을 것 같아요.

> [ 5-1 ]에서 발전기가 삭제된 마마고 컴퍼니에서 내부를 보여줘야 할 필요성이 없다.

마마고 컴퍼니 내부는 보여주는게 좋다고 생각하긴 합니다. 이후에 2챕터에서 지속적인 언어팩이 필요하다면 마마고 컴퍼니를 방문하게 될 텐데, 비주얼 노벨에서 이동은 장소의 개념이 더 적당할 것 같다는 생각입니다. 해당 장소가 탑다운에서 봤던 형태와 달라진 모습을 보고 게임에 대한 이해도가 올라갈 것 같습니다.

**Comment by royalbluesm** [comment]
저도 마마고 컴퍼니 내부를 보여줘야 한다는 필요성은 느낍니다. 직접 석재와 목재를 수집해 건설했는데 > 맵이 생겼네? 신기하다~ 라는 경험도 줄 수 있을 것 같고요. 처음부터 내부에 직원이 꽉 차있는 점에 대해서는... 직원의 수를 2~3명 정도로 조절하면 크게 어색하지 않을 것 같다는 게 제 의견입니다.

**Comment by jeongopo** [comment]
플로우가 좀더 통일성있어지고 연결성이 늘어난게 좋네요 ! 여러 게임 장르를 연결하고, 그 과정에서 하나의 게임이라는 느낌을 주는 것이 쉬운 일이 아닌데 기획분들 너무너무 고생 많으십니다..!


## 서브게임 시스템에 대한 앞으로의 우려..?
> 3매치 리소스가 라플리의 바로 앞을 가로막으며 보드판의 형태로 떨어진다.

> 색이 조금 남아있는 SLG UI를 획득한다.

서브게임들이 "서브"라고는 하지만 결국 서브게임들 간의 어떤 일관성은 있어야 한다고 보는데, 현재까지는 리소스 UI가 등장하고 서브게임들에게 접근하는 방식으로 유지되고 있다고 생각합니다. 이제 점점 구체화하거나 추가적인 서브게임들이 등장할 때에도 이런 부분들이 유지되었으면 좋겠습니다. 
 모호한 말이지만,, 아무리 서브게임이더라도 조작이나 게임 조작을 알려주는 서사 등이 비슷해야 할 것 같다는 의미로 이해해주시면 감사하겠습니다 (_ _ ) 유저가 서브게임이라고 인지할 수 있는 포인트가 동일한 것도 중요할 것 같습니다.

## 마마고 컴퍼니의 내부
 내부를 보여주는 것에 대해서는 저는 이후 다른 챕터에서도 활용된다는 전제 하에, 프롤로그에서는 안보여주거나 직원수가 엄청 적은 상태여도 좋을 것 같습니다. 그러다 이후에 다른 챕터에서 다시 갔을 때 성장한 컴퍼니 모습을 보여주는 식으로 진행해도 재밌을 것 같습니다 !

## 사소한 제안..
> 마마고 컴퍼니가 건설되려면 24시간이라는 시간이 필요하다. 옆에 보이는 코인 아이콘을 클릭하여 코인을 소모해 시간을 축소시켜야 한다.

24시간이라는 수치를 보고 바로 재화가 필요해! 라는 생각이 들지가 의문이라, 아예 엄청 터무니없는 수치의 값을 주는게 좋을것같습니다

**Comment by gomgom172** [comment]
추가 아이디어 정도로 선택 참고 해주시면 감사하겠습니다.

> 마마고에게 감사의 의미로 게임의 [옵션(번역, 사운드)]를 선물받는다.

사운드를 따로 획득하는 것도 재미있는 요소 같습니다. (SLG UI(석재 말풍선?)도 따로 획득하는 요소라면 통일성도 있을 것 같고요.) 마마고가 _우린 어디에 쓰는 물건인지 모르겠는데 일단 주워뒀다. 너에겐 쓸모가 있을지도 모르겠다._ 같은 방식으로 건네줘도 괜찮겠다고 생각했습니다. (게임 플레이 세팅에 필수적인 부분을 제외하고, 이 팩을 장착하면 뭔가 사운드에 변화가 생긴다든지, 특정 부분만 조정할 수 있게 되어서 해당 요소가 기믹 풀이와 이어진다든지….)

### 마마고 컴퍼니
비주얼적인 측면에서도 내부 맵을 남겨두는 것이 좋겠다고 생각합니다. 플로야드 맵→ 사이즈가 다른 실내 맵 전환

내부 맵을 보여주는 것이 좋겠다는 의견에 동의합니다. 플로야드 맵→ 사이즈가 다른 실내 맵으로의 전환이 비주얼적인 측면에서도 환기가 될 수 있을 것 같고요. 설정적인 측면을 잘 조절해서 남겨둘 수 있었으면 하는 생각입니다.

**Comment by Sumindd** [comment]
**우연님의 질문에 대한 답변**

### 1. 이를 지켜서 정말 색이 있는 리소스에 가까이 가지 않고 헤멘다면?
이건 스크립트로 조율해야하는 문제인 것 같습니다. 오히려 강조를 많이하고, 다양한 NPC에게 관련 대사를 넣어 힌트로 작용하게 만들 예정입니다.
그런데 아마 첫 맵이고 정말 할 수 있는 게 없어서 그렇게 헤맬 것 같진 않습니다!

### 2. 3매치 퍼즐에서 보여주고 싶은 것은 하늘에서 리소스가 떨어진다는 사실 뿐인지?
네 맞습니다. 리소스가 주로 떨어지는 지역은 마을 밖이고(피해서 마을 자리를 잡았을테니..) 라플리 외에도 일상적으로 리소스가 하늘에서 떨어진다는 세계관을 마을에 진입하기 전에 제 3자의 입장으로 보여주면 좋을 것 같아 삭제하지 않았습니다. 가벼운 수준의 접속도 있어야 추후 다른 챕터에서도 기믹으로 사용하기에 용이할 것 같고요. 
그렇지만 역시 가장 큰 이유는 이미 프로그래밍까지 완료된 기획이라 아까운 것도 좀 큰 것 같네요..

### 3. 4-3으로 인해 마우스 상호작용이 활성화되는 게 맞는지?
네 맞습니다. 4-3에서 마우스 커서 UI를 얻으면서 활성화 되고, SLG UI가 파괴된 후에는 다시 비활성화 됩니다. 
(그런데 아마 비주얼 노벨 장르 때문에 금방 다시 활성화 되지 않을까....)

### 4. 여러 건물이 있다면 SLG는 추후 재활용되고 다른 건물들을 구매하게 될 수 있는건지? 아니라면 다른 건물들이 존재하는 이유는? 
그래서 일단은 #385 기획서에서 건물 선택창 자체를 삭제했습니다. 추후 유사한 기능이 재활용된다면 선택창을 만들고 튜토리얼에도 추가할 것 같습니다. 
개인적으로는 재활용하고 싶은데 현재 설정상으론 역접속이 끝나면 UI가 파괴된다고 되어있어서 좀 더 고민해보아야 할 것 같습니다.

### 5. 전체적인 맵의 모습이 궁금함
- #385 에 추가해뒀습니다!

### 6. 그 동안 사운드가 없다가 5-2에서 추가되는 건지? / 7.옵션 == 설정?
보통 게임 설정에 있는 대표적인 것이 사운드 음량 조절이라 이렇게 표기되어 있었고 급하게 수정하다가 옵션창 관련 내용이 뭉개진 것 같습니다.
결론: 실수입니다.. 신경 쓰지 않으셔도 됩니다!

### 7. 팩맘을 깨지 못한다면 어떻게 되는지
기존 기획과 반대로 갈 것 같습니다.
팩맘을 깨야 팩맘 게임기에서 튕겨져 나가고(탈출) 못깨면 영원히 팩맘 속에서..

### 8. 현재 대화창 UI에는 이름과 대사만 있고 얼굴이 없어 해결책으로 한 번에 3명 이상 대화하는 것을 지양하자고 한 걸로 아는데 그렇지 않은 것 같음
이 부분은 처음 알았습니다..! 스크립트 작업 해주실 수빈님과 좀 더 자세하게 전달해주시면 좋을 것 같습니다.
개인적으로는 튜토리얼부터 다양한 캐릭터가 나오는 것보단 주요 인물인 달러,파머,R2-Mon만 등장하고 이들에게 집중시키는 것이 좋을 것 같다는 생각이 듭니다.. 3명 정도면(심지어 1명은 로봇) 크게 헷갈리지 않을 것 같고요.

### 9. 라플리는 건설 시간(24시간) 동안 코인을 획득하고 소모해 시간을 단축시키는 것 말고 할 수 있는 게 없는지?
애초에 코인을 모으는 것이 해결법인 기믹입니다. 모바일 게임이라면 24시간 방치했겠지만, PC 패키지 게임이기에 24시간이라는 긴 시간은 단축을 유도하는 시간 설정일 뿐 큰 의미가 없습니다. 그래서 현정님이 주신 아이디어처럼 터무니 없는 시간으로 늘리는 방향도 고민해보면 좋을 것 같습니다!

세세한 질문 해주셔서 감사합니다!

**Comment by wooyn730** [comment]
궁금했던 부분들 정말 잘 이해되었습니다 정말 감사합니다 ^_^ 👍
(특히 1, 2번은 이유 들으니 바로 수긍 완료)

참고로 8번은 해당 문서 3-2에 '마을 사람1'이 등장해서 꺼냈던 이야긴데
주요 인물로만 배치한다면 문제되지 않을 것 같기도 합니다.

`3인 이상 대화 지양` 정안님 기획서 중 일부로, Document 파일 내에 있었던 것 같은데
정리된 건지 다시 찾으려고 하니까 안보이네요..!

팩맘을 깨지 못하면 아예 게임 오버?
나쁘지 않은데 현재 팩맘이 많이 쉬운 편은 아니라 조금 걱정이 되긴 하네요
여러번 해보면 금방 쉬워지지만요..

**Comment by Songkihwa** [comment]
플로우 문서 관련하여 여러 고민들 많이 하시느라 고생 많으셨습니다 !
앞에 댓글에서 잘 설명해주셔서 제가 말하고 싶은 건 딱 두 가지인데 

마마고 컴퍼니 내부에 관련한 것은 저도 댓글 달아주신 다른 팀원들과 같은 의견으로 마마고 컴퍼니를 보여줬으면 좋겠고 글에 써주신 대안 방법이 자연스럽고 좋아보입니다. 

현재 팩맘 게임은 제가 생각하기에 첫 판부터 한번에 깰 수 있는 게임은 아니라고 생각되는데 깨지못하면 영원히 팩맘에 있는게 튜토리얼 느낌보다는 본 게임 느낌이 나는 것 같아요..! 근데 또 팩맘에만 갇혀서 계속 팩맘을 플레이하는 걸 기믹적으로 풀어낸다면 또 다른 재미요소가 될 수 있을 듯 합니다!

잘 설명해주셔서 전체적인 튜토리얼 플로우가 이해가 잘 됐습니다ㅎㅎ
이번주에도 빠이팅입니당
