### ISSUE TITLE
[CH1] 플로야드 맵 세부 오브젝트 작업

### ISSUE THREAD

**Issue by gomgom172** [GG-Studio-990001/Grayed-Game#383]
- #370
해당 이슈에서 이어서 플로야드 맵 세부 오브젝트 그래픽 작업 진행합니다.

### 작업 계획
- 플로야드 맵 디테일 추가를 위해 오브젝트를 작업합니다.

# 240331

![0331-2](https://github.com/GG-Studio-990001/GameOver/assets/162591960/ef49a6c0-d8b9-44c9-bea3-a427c2777b6b)

### 염두에 둬야 할 부분
- 리소스 간 크기 비례 무시 & 크기 다양화
- 게임 간 해상도 차이 표현
- 게임 리소스처럼 보이도록 (해당 게임을 모르는 사람에게도 '고전게임 리소스구나' 싶을 수 있도록)
- 측면으로 꽂혀 있거나 절반 정도 보이는 구도(+픽셀아트의 규칙을 깨지 않을 것)
- 오브젝트 다양성

# 240407
![0407](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/2cc781ae-10b9-4445-87ed-80513979440c)

작업 진행 중입니다.

<img width="326" alt="스크린샷 2024-04-07 오후 6 54 52" src="https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/57c756e5-ddde-46cf-8053-e8656a24be78">

상호작용 스크립트를 작성할 때 좀 더 쓸거리가 있는 오브젝트가 있으면 어떨까 싶어 이런 방식으로 배치했습니다. (해당 오브젝트에 말을 걸면 주변 NPC가 위험해! 그건 언제 터질지 몰라 하고 말해준다거나….) 라플리가 직접 상호작용할 수 있는 오브젝트는 깨져 있거나, 여러 방식으로 위험하다거나, 완전히 박살나 있다거나 등등 다양한 방법으로 변주를 넣는 것이 좋을 것 같아 우선은 보류해 두었습니다.

<img width="692" alt="스크린샷 2024-04-07 오후 7 20 07" src="https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/7ef8320f-f45d-410b-8782-3a481de10b61">

(이런 느낌.)

<img width="620" alt="스크린샷 2024-04-07 오후 6 57 26" src="https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/a0b8d03f-4e38-49fc-9476-4251f2973728">

오브젝트 사이즈 자체가 작은 리소스들은 이런 방식으로 표현될 것 같습니다. (겉으로 튀어나오는 부분만 주변 실루엣과 같은 색상으로 테두리 처리)

![0407object](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/c1f14650-5ec8-4a2a-8036-37a4a6eb0262)

오브젝트를 먼저 제작하고 맵 위에 올려 가공을 거치기 때문에, 이후로는 맵 리메이크와 1챕터 스토리 정리가 끝난 후에 재작업하는 것이 좋을 것 같다는 의견입니다.

**진행된 부분**

- 작은 오브젝트의 그래픽 처리 문제
- 리소스 활용 부분 관련 고민

**더 진행해야 할 부분**

- 리소스 간 해상도 차이 (해당 부분은 레퍼런스 정리 후 리소스를 모티브가 되는 게임 별로 분류하여 다시 재작업해야 할 필요성이 있어 보입니다.)
- 3D 게임 리소스 (인지도 높은 3D 게임이면서도 바로 알아볼 수 있는 아이코닉한 요소가 어떤 게 있을지 찾고 있습니다.)

작업하다 보면 고민할 부분이 계속 새로 생기네요. ㅜㅜ
이번주는 우선 이 정도로 갈무리하였습니다. 감사합니다.

**Comment by gomgom172** [comment]
240407 업데이트 되었습니다.

**Comment by gomgom172** [comment]
![0407-1](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/4286d6a8-37be-4698-acda-22819f0c8b42)
어제 보여드린다고 말씀드렸던 시작 지점 이동 키 부분도 함께 달아두겠습니다.

**Comment by wooyn730** [comment]
폭탄 그림 귀엽네요! (슈퍼마리오 폭탄병이 생각나기도 하네요)
아마 저기 마마고 지어지는 자리로 알고 있는데 _아마도..?_
갑작스럽지만 이거 보니까 마마고는 마을도 아닌 밖(입구)에
혼자 지어지니까 주변에 건축물이나 분수 같은 것들이 좀 더 있어도 좋겠다는 생각이 드네요
(쫌 불쌍할지도...)

물약 리소스 같은 경우에는 단순히 기울어져 있거나 금 가 있는 것 뿐만 아니라
안에 액체도 기울어지고, 새어나오기도 하는 부분이 매력적이네요!!

화살표 키 그린 것도 따로 키보드 리소스 그려서 올리는 것보다 잘 어울리는 것 같습니다

앞으로 진행할 부분도 정리해서 적어주시는 부분이 정말 좋습니다 👍
잘 연구하고 계신 것 같아요
_피드백 드릴게 별로 없네여~~~_

**Comment by Sumindd** [comment]
인지도 높은 3D 게임.. 롤이나 배그 같은 완전 메이저 온라인 게임 쪽으로 방향 잡아보면 어떨까요?
우연님이 마마고 컴퍼니 앞에 장식 요소도 있으면 좋을 것 같다고 하셨으니까 롤의 넥서스나 포탑, 파판의 에테라이트 같은 걸 좀 부숴서 꽂아둬도 큼직하고 괜찮을 것 같네요! 비슷한 요소가 다양한 게임에서 나오니까 게임이 특정 되지 않으면서도 알아볼만해서 적당한 것 같습니다. 단순히 조사 요소니까 꼭 작은 아이템이 바닥에 떨어진 모습을 생각하지 않으셨으면 좋겠습니다(혹시나 해서 적어둡니다!)
폭탄은 그 자리에 마마고 컴퍼니가 지어질 예정이라 위치는 옮겨야 할 것 같습니다. 폭탄이랑 물병 깨진 이미지 자체는 너무 귀엽네요!! 완전 맘에 들어요
저도 딱히 피드백은 할 거 없는 것 같습니다 관련 기획 빠르게 작업해서 가져오겠습니다~
