### ISSUE TITLE
[Ch1 Main] 맵 리소스 리사이징 및 수정 작업

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/Grayed-Game#384]
**상세**
1. CH1 맵 리소스를 화면 해상도에 맞게 리사이징합니다.
2. CH1 맵 리소스의 톤앤매너를 통일시킵니다.

**비고**
최대한 빌드 먼저 뽑을 수 있게 리소스의 리사이징은 이번주 내로 끝내는 것을 목표로 하겠습니다. ..

**파일**
리사이징한 리소스는 [Ch1 폴더](https://drive.google.com/drive/folders/1Ev4wLdt2JVngAtFRKGvI_zRAjLE3gCDj?usp=sharing)에, 캐릭터 스프라이트는 [캐릭터 폴더](https://drive.google.com/drive/folders/1n9BeEAncWHCryg3RRbfaVo6b_f3WB6Fx?usp=sharing)에 넣어놨습니다. 마마고 내부 같은 경우는 전체적으로 뜯어고쳐야 해서, 우선은 현재 있는 리소스 활용 바랍니다 !! 기존 리소스와 달리 리소스 사이즈 그대로 적용하면 1920x1080 화면에 딱 맞습니다.

**Comment by fkdl0048** [comment]
@royalbluesm 민지님 토요일 전인 금요일에 리소스를 받을 수 있을까요?

- #386 

해당 작업에 바로 사용하고 싶습니다!

**Comment by royalbluesm** [comment]
@fkdl0048 금요일 낮 중으로 드리겠습니다!
