### ISSUE TITLE
세계관 설정 정리 문서화

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#388]
- #380
-  위 이슈에서 논의한 장르변환 필요성을 포함한 설정, 속성을 정리한 문서를 작성합니다.

---

## 4/4
[세계관 설정 정리 문서](https://drive.google.com/file/d/1A5mDjpXsAmfeLb-oh8jk7PBOxZ5nmSoB/view?usp=drive_link)를 업로드 하였습니다.

고민되는 점

~~2.2.3.번 최종적으로 장르팩을 사용할 때의 실행법과 연출 구체화 필요~~
업데이트 완료

## 4/7
[업데이트](https://drive.google.com/file/d/1CAuFXQ2Zav4SJdtedx2dSp4NZxr9CRAK/view?usp=sharing) 진행하였습니다.

고민되는 점
1.4.2번 : 역접속 - 마을 주민들은 게임 속 리소스일 뿐이므로 만졌을 때 아무 일도 일어나지 않는다.
- `색있음 == 위험함` 설정 때문에 만졌을 때 넉백처럼 튕겨져 나가는 등 조금의 현상 발생이 필요할 수 있다. 하지만, 어차피 주민과 색이 있는 UI가 접촉하는 상황이 게임 중에 일어나거나 보여지지 않을거라면 설정 없어도 됨
    - 주민과 색이 있는 UI가 접촉하는 상황이 게임 중에 일어나게 될 경우, 설정 재논의

**Comment by roweclaw** [comment]
본문에 문서를 업로드 했습니다. 확인 부탁드려요!

**Comment by wooyn730** [comment]
게임을 이끄는 데 주요한 설정과 용어들이 깔끔하게 잘 정리되어 있네요!!
명료해서 좋습니다~ 잘 읽었습니다.

제 코멘트는 읽다가 생각나는 것들이 많이 적혀있으니 유의해 주시길 바랍니다 ㅎㅎㅎ

(1)
색, 접속 등 주요한 용어들이 잘 정리된 것 같습니다!

추가로 게임이 부서지는 것과 분해되는 것도 문서로 정리되면 어떨까 합니다.
상대적으로 사소한 설정이지만 정해지면 아트에도 도움이 되지 않을까 싶습니다.
제가 생각하기로는 아래와 같은 느낌입니다.

**부서짐**
- 물리적 충격으로 인해 리소스가 금이 가거나 조각남
- 예
   - 하늘에서 떨어지며 바닥과 부딪힐 때
   - 색을 완전히 잃은 후에 주민이 물리적 충격을 가했을 때?

**분해됨**
- 하나의 게임이 리소스 단위로 나눠짐
- 예
   - 하늘에서 떨어지며 자연 분해 (e.g., 3 매치 퍼즐)
   - (역접속된 후) 게임의 목표를 달성했을 때 (소멸의 전 단계..?)

쓰다 보니까 역접속 이후에 UI 말고 장르팩도 부서지는지,
부서졌는데 색이 있는 경우가 존재하는지(이런 경우는 아마 접속 불가? 아니면 후반에 혼돈스러운 요소로 등장?)
의 경우도 궁금하네요.

(2)
`접속`이 게임에게 '업데이트'로 인식된다는 설정과
또 주민들이 `탈출`하지 못하는 이유가 유저의 연결이 없기 때문이라는 설정 좋습니다!!
세계관이 딱딱 맞아가는 느낌이에요.

`역접속`의 경우 마을 주민들은 불가능하다고 쓰여 있는데
접촉 시 어떻게 될지 궁금합니다.

색 있음 == 위험함 이라는 이야기에 따르면 뭔가 부정적인 일이 일어나는 게 맞을 것 같기도 하고요..

(3)
현재 세계관에서 색의 유무가 중요하게 사용되는데
원래 흑백인 게임의 경우 어떻게 판별될지가 궁금합니다.

(만약 마을 주민이 흑백 게임팩에 접속되어 실종된다면?
아무도 목격 못함=> 미스터리/색이 있는 게임팩 만졌나보다../안보이네
누군가 목격함=> 주변에 펜스나 폴리스라인 등으로 경고
이런 것도 재밌을 것 같네요)

(라플리가 떨어지자마자 흑백인 이유도 사실 잊혀지지 않았는데(유저가 있으니까) 원래 흑백 게임 주인공이라 흑백인 것?)

그리고 유저의 편의성을 위한 색맹 모드/색약 모드를 지원할 수 있는 방법도 함께 생각해보면 좋을 것 같습니다.
(생각난 건 리소스가 빛나는 것처럼 보여주기? 타이틀 먼지 효과로 요청했던 것처럼 발광효과..)

(4)
저번 기획 회의 이후 R2-MON이 아주아주 중요한 캐릭터가 된 것 같은데
설정이 많이 바뀌었으니
이 부분도 문서로 정리되면 좋을 것 같습니다.

**Comment by roweclaw** [comment]
우연님 피드백의 답변입니다!

### (1)
[업데이트 된 문서](https://drive.google.com/drive/folders/1Pbyjg_Fi56Jz2wkP0JPZUUAMtKAEgMzF)에서 `1.6.분해`로 내용을 정리했습니다.
부서짐과 분해됨을 따로 분리하지 않고 '분해'라는 용어 아래 각기 다른 경우가 있음을 명시해두었어요.

> 쓰다 보니까 역접속 이후에 UI 말고 장르팩도 부서지는지,

 장르팩도 역접속이 가능한 대상으로 분류했기 때문에 UI팩과 마찬가지로 탈피 이후 작은 조각으로 분해됩니다. 

> 부서졌는데 색이 있는 경우가 존재하는지(이런 경우는 아마 접속 불가? 아니면 후반에 혼돈스러운 요소로 등장?)의 경우도 궁금하네요.

질문해주신 '부서짐'은 1.6.3번에 해당하는 것 같은데요, 이 경우 분해된 후의 색은 존재하지 않습니다. 작은 조각인 상태로는 재활용할 수 없다는 설정(1.5.2번)으로 인해 만약 색이 생긴다면 모든 조각을 이어 붙여서 수리한 이후에 희미하게 색이 생길 수도 있겠네요. 그 외의 1.6.1, 1.6.2번 안에서는 색이 있어 접속 가능한 것(팩맘 등)과 색이 없어 접속이 불가능한 것(평범하게 널브러진 리소스 등)이 있습니다.

### (2)

> 역접속의 경우 마을 주민들은 불가능하다고 쓰여 있는데 접촉 시 어떻게 될지 궁금합니다. 색 있음 == 위험함 이라는 이야기에 따르면 뭔가 부정적인 일이 일어나는 게 맞을 것 같기도 하고요..

어제 기획 회의 때  '마을 주민들은 리소스일 뿐이므로 만졌을 때 아무 일도 일어나지 않는다.'라고 정리가 되어서 1.4.2번에 추가를 해두었는데요, 지금 다시 생각해보니 조금의 현상이 발생하는 게 맞겠다는 생각이 듭니다. 만졌을 때 넉백처럼 튕겨져 나간다든지? 이런 현상이 있어야 말씀하신 `색있음 == 위험함`에 일치하게 되니까요. 이 부분은 재논의 해보겠습니다!

### (3)
> 원래 흑백인 게임의 경우 어떻게 판별될지가 궁금합니다.

제 생각에는 색이라는 게임의 속성 때문에 불가피한 경우가 아니라면 흑백 게임은 등장하지 않을 것 같습니다. 이후 기획 하다가 흑백 게임이 필요해지면 다시 고민해도 될 듯 해요.

> 그리고 유저의 편의성을 위한 색맹 모드/색약 모드를 지원할 수 있는 방법도 함께 생각해보면 좋을 것 같습니다.

색맹/색약 모드로 편의성 높이는 것에 찬성입니다. 저도 가장 좋은 건 리소스가 빛나게 보이는 것인 거 같아요!

### (4)
> 저번 기획 회의 이후 R2-MON이 아주아주 중요한 캐릭터가 된 것 같은데 설정이 많이 바뀌었으니 이 부분도 문서로 정리되면 좋을 것 같습니다.

말씀해주신대로 R2-MON은 메타 캐릭터로서 구체화할 부분이 많아서 따로 문서화하여 정리하겠습니다!

**Comment by roweclaw** [comment]
본문에 업데이트 및 고민되는 점을 추가했습니다. 확인 부탁드려요!

**Comment by royalbluesm** [comment]
문서 정독했습니다. 현 시점에선 모순되는 설정 없이 탄탄하게 잘 짜인 것 같습니다. 색이나 접속, 분해의 개념도 게임 내의 흐름에 자연스럽게 녹아들 수 있는 설정인 것 같아요. 전에 설정을 위한 게임이 되지는 않는지, 너무 억지스럽게 설정을 집어넣지는 않았는지 우려되는 부분이 있었는데, 이 점도 확실히 매끄럽게 잘 다듬어진 것 같습니다. 또 이러한 스토리게임의 경우 고유명사 남발 때문에 진입장벽이 생기는 경우가 많은데 리소스홀, 웜홀 등 일부 지명을 제외하면 직관적으로 알아들을 수 있는 네이밍이라 더 좋은 것 같아요.

궁금한 점...

1. 일반 리소스와 ㅇㅇ팩은 다른 개념인 걸까요? 라플리가 접속/역접속을 할 수 있는 대상은 팩에만 한정되는 것인지, 아니면 널려 있는 일반 리소스들과도 상호작용이 가능한 것인지 궁금합니다.

2. 일반 UI팩이나 게임팩과 달리 장르팩은 R2-MON만이 제작할 수 있는 것으로 이해했는데 맞을까요?

**Comment by wooyn730** [comment]
### (2) + 고민

저는 오히려 회의 때 들으면서 '아무 일도 일어나지 않는다'도 나쁘지 않다고 생각했습니다.

어차피 주민과 색이 있는 UI가 접촉하는 상황이 게임 중에 일어나거나 보여지지 않을거라면 넘어가도 되겠다라는 생각이 들었네요!!

### 그 외

답변주셔서 감사합니다! 잘 이해했습니다.

문서 업데이트도 깔끔하게 잘 된 것 같습니다.
질문 할 게 없네여~

**Comment by roweclaw** [comment]
민지님 질문의 답변입니다!

1.
> 일반 리소스와 ㅇㅇ팩은 다른 개념인 걸까요? 라플리가 접속/역접속을 할 수 있는 대상은 팩에만 한정되는 것인지, 아니면 널려 있는 일반 리소스들과도 상호작용이 가능한 것인지 궁금합니다.

접속/역접속을 할 수 있는 대상은 색이 있는 팩에만 한정되는 것이 맞습니다.
널려 있는 일반 리소스의 경우 현재 기획상 색이 없어서 상호작용을 하더라도 '평범해보인다./쓸모없어보인다.' 와 같은 간단한 스크립트 출력 후 아무 일도 일어나지 않도록 되어 있습니다. 

2.
> 일반 UI팩이나 게임팩과 달리 장르팩은 R2-MON만이 제작할 수 있는 것으로 이해했는데 맞을까요?

네, 장르팩은 R2-MON만이 제작할 수 있는 것이 맞습니다. 기획 초기에는 '마을 주민의 문제를 해결하기 위해 장르팩을 사용'하여 장르를 변환하니까 해당 주민이 장르팩을 줘야하는 것이 아닌가하는 고민이 있었는데, 이렇게 되면 [ 색있음→접속됨→실종→위험 ]이라는 전설에 어긋나버려서 기계인 R2-MON을 장르 제작공으로 변경하였습니다. 마마고의 장르버전이라고 생각해주시면 됩니다!

**Comment by roweclaw** [comment]
[[240602] 세계관 설정 정리](https://drive.google.com/file/d/1rNvWDoRXRVBcxbDB8ZCTmXdZGtbi2BP3/view?usp=sharing)

**추가된 내용**
1.7. 다시하기
① 게임팩 접속 시, 해당 팩의 내부에서 게임을 다시 할 수 있게 재시작 하는 기능이다.
② 게임 오버와 같이 클리어를 하지 못한 상황에서만 사용할 수 있다.
③ 적용되는 대상은 라플리뿐이다.

- 연결되어 있는 유저로 인해 기회를 다시 주는 것이기 때문이다.
- 라플리는 인식하지 못하는 위쪽 레이어에서 이루어진다.
