### ISSUE TITLE
[Char] R2-MON, BAD라플리 캐릭터 구체화

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#397]
아래 두 캐릭터의 설정을 구체화하여 문서로 작성합니다.

- R2-MON : 장르 제작공, 메타 캐릭터
- BAD라플리 : 설명요정 → 유저 인식 (메타) → BAD라플리로 흑화

## 240412

> 작업 현황
- [기획 피그마](https://www.figma.com/file/LNsoGFh5f3jQ1rCPQB2O9f/Grayed-Game?type=design&node-id=0-1&mode=design&t=tIzZr5dftCxdXZQr-0)에서 두 캐릭터의 설정을 정리하다가, 설명요정의 서사가 복잡하여 이를 우선순위로 두기로 하였습니다.
- [설명요정 캐릭터 구체화 1차 문서](https://drive.google.com/file/d/1jrROe19BBoFIMRs899jdWlpLlME4jbit/view?usp=sharing) 작성 (모순 발견 후 서사를 재설정하기 위함입니다.)

++
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/92532398/346fa64e-2d8f-43c7-a559-66084fbdeb31)

 
> 앞으로 할 일
- 캐릭터별로 챕터 진행도에 따라 변화해가는 과정 정리

**Comment by fkdl0048** [comment]
제가 생각하기 저랑 같이 제일 말을 많이 해봐야 하는 분이 수빈님인 것 같습니다 ㅎ.. 현재 주어진 캐릭터 성격도 많고 고려해야 하는 세계관 내용도 많으신데, 생각하실 때 많이 스트레스를 받으실 수 있을 것 같습니다..! 

그때마다 저와 이야기를 해보시거나, 작업을 작은 단위로 만들어서 좀 더 쉽게 진행하셔도 좋습니다! 최대한 팀원들에게 피드백을 요청하셔서 다같이 만들어가시는 그림을 그려주셨으면 합니다!

**Comment by Sumindd** [comment]
> 종합 피드백

고민: 만약 스킵 안 하고 튜토리얼을 천천히 읽는 유저가 있다면 어떻게 전개해야 할까..? 역으로 스킵해야 스토리에 몰입이 되는 구조가 되진 않을까,,?

그래서 아예 악역이 되는 이유 자체가 흑화보다는 다른 방향으로 찾아보아야 범용적인 스토리+유저와의 연결이라는 주제에 가까워지지 않을까 생각이 듭니다. 지금 방향으로 가면 주제와 대립 존재의 방향이 어긋날 수도 있을 것 같아서 조금 걱정이 됩니다.. 그런데 역시 두 방향이 각자 매력이 있으면서도 서로 모순이 돼서 저도 해결 방안에 대해서는 마땅히 떠오르지 않네요.. 어렵지만 저도 열심히 고민해보겠습니다..

3.2 트라우마에서 고통 받고 있다는 증거에 대한 아이디어는 너무 좋습니다! 재밌을 것 같아요.
그리고 3.4 잘못된 결핍 충족 방식으로 가는 흐름도 자연스러운 것 같습니다.

> 주제에서 조금 벗어난 이야기

피드백 작성하다가 떠오른 아이디어인데 "달라진 팩맘 등으로 재접속 시켜 복수하는" 부분에서 리소스와 시스템을 어긋나게 만들어서 게임을 혼란스럽게 만드는 것도 재미있을 것 같습니다. 예를 들면 꽃병 리소스에서 총알이 나가고, 맵 리소스와 아이템 리소스가 뒤집혀서 아이템 리소스가 벽의 역할을, 벽 타일이 아이템의 역할을 한다던지, 사운드가 섞여서 나온다던지.. 물론 먼 이야기이고 아이디어를 많이 다듬어야겠지만 그냥 생각난 김에 적어만 둡니다!

**Comment by wooyn730** [comment]
설명 요정이 악역이었다는 설정 처음 듣고 너무 좋았어서 아직도 두근두근하네요
문서도 잘 읽었습니닷

빨리 쓰려고 음슴체 썼습니다 죄송함다!
사실 피드백보다는 또 제 상상의 나래를 펼쳐보았으므로... 역시 이번에도 가볍게 읽어주시길 바랍니다.

### 생각
과
### 아이디어
그리고
**++**
만 읽어주셔도 됨니다

---

## 모순 해결

### 이해한 바
Bad 라플리가 되어야 하는 이유 => "라플리를 따라해서 유저를 뺏어온다"
여기서 발생하는 모순: 스킵만 하는 유저를 싫어할 것이다. 근데 왜 뺏음?

### 생각
일단 Bad 라플리는 아이디어 중 하나이므로 붙여도 되고 안붙여도 됨
근데 붙여도 개연성만 있으면 충분히 괜찮음
또한 매력적인 설정이기도 함! 라플리는 표정이 없으니까 화난 표정과 대비되면 좋을 듯
(라플리에 빨간색으로 눈썹이랑 입 그린거 너무귀여움 ㅋㅋㅋ)
(라플리의 외관을 따라한다면 젤다 Navi처럼 원래 외관은 밍숭맹숭한게 좋을 듯)
암튼 그래서 기존에 생각해둔 Bad 라플리 서사를 그대로 붙여주려면 모순을 해결해야 함.

### 아이디어
"유저를 좋아하니 뺏는다"라는 설정을 유지하려면 마을 세계관을 결합하면 어떨까?

Bad 라플리는 아직 색이 있으므로 잊혀진지 얼마 안되었음
하지만 원래 인기 게임 출신이었고 그 잊혀지는 잠시 동안의 시간 조차 너무 불안했던 거임
+
이 마을에는 '잊혀진 게임'들이 모인다는 특수성이 있음
따라서 Bad 라플리는 `이 유저(=나)가 마지막일 수도 있다`라고 생각해서 집착함

**셀프 정리**
Bad 라플리는 원래 자아가 있고 메타픽션 캐릭터임
왜냐면 항상 제4의 벽을 넘어 유저에게 설명해주는 것이 일이었기 때문

원래 자기 역할(설명)이 스킵 당하는 것은 평소 콤플렉스(트라우마)였지만
그 동안은 인기 게임이라 그냥저냥 참고 살았음 (어차피 자신을 찾는 뉴비가 존재하므로)
하지만 마을에 와서는 잊혀지다가 유저를 만났는데 (이 유저가 마지막일수도 있는데) 또 스킵해버리니 불안감에 흑화해버린거임

++
여기다 웜홀과 연관지어 좀 더 설정 추가해본다면
Bad 라플리는 색이 조금 천천히 빠지는 중이었음 (이유는 원래 인기게임이라서가 될 수도 있고, 자아가 강해서일 수도 있고..)
그러는 동안 수 없이 잊혀져 떨어지고 색을 잃는 게임 리소스들을 본다면 좀 더 미칠 이유가 될 수 있을 듯

## 결말과 연결지어보기

### 마지막 챕터
마지막 챕터에서는 아마 맵도 엉망이 될 것이고, 접속 게임들도 극한의 난이도여야 함
그리고 이 경험을 위해서는 유저가 조작하는 라플리가 강탈당해야 함
(그래야 극한의 난이도가 된 접속 게임에 제 발로 들어갈 테니까)

### 유저 강탈
Bad 라플리 성격은 얀데레에 가깝지 않을까..
왜냐면 유저를 좋아해서 집착하면서도, 고통을 주며 자신의 소중함을 알기를 원하니까
그래서 Bad 라플리가 되어버린 것

### Bad라플리와의 끝맺음(?)
Bad 라플리로부터 원래 라플리를 돌려받으려면 결국 극한난이도 접속 게임들을 깨야함

_(몇번 게임 오버를 거치면서 깨기 => 노말 루트?)_

그리고 그 과정에서 Bad 라플리가 마음을 고쳐먹어야 하지 않을까?

만약 웜홀과의 연관성을 준다면
극난 접겜을 하는 과정에서 웜홀이 해결되어 (다시 뚫려서) 현실로 돌아갈 수 있게 되므로
정신을 차리게 된다면 어떨까 함
_(1>5 순서로 챕터를 갔다가 다시 5>1 챕터로 돌아오면 1챕터에 알고보니 웜홀도 있었던 설정..)_

### _분기점 (걍 써봄)_
_아마 스킵 여부 (몽땅 스킵, 적당히 스킵, 스킵 X)로 갈리면 좋지 않을까?
근데 흑화를 유도하려면 설명을 길게 한다거나 잡담을 섞는다거나 하는 방법도 있을듯.._

_또한 극난 접겜을 몇번을 게임 오버 당하고 결국 깨느냐도 분기점이 될 수 있을 듯_

### 마음대로 생각해서 써 본 답

- 유저를 강탈해서 이루고자 하는 목표는?
   - 유저에게 고통주며 자신의 소중함 깨닫게 하기
- 설명요정은 라플리에게 역접속 된 상태인데, 어떻게 자발적으로 탈피하여 bad라플리로 변하게 할 것인가
   - (상상) 후반부에 마지막 접속 게임에 들어갔을 때 게임 화면이 깨져서 마을과 겹쳐보이는 연출
   - 질투와 사랑은 아주 강력한 힘이라고 생각함
- bad라플리가 되었을 때 유저와 연결되는 방법은?
   - 라플리 얼굴이 바뀌고 라플리 대사창을 통해 유저에게 말 거는 식
- 그 연결을 해제하고 다시 라플리와 연결되는 방법은?
   - 엔딩에 따라 해당 연출이 필요 없을수도 있지 않을까
- 그 이후 bad라플리는 어떻게 되는 것인가, 소멸? 설명요정으로 복귀?
   - 아무래도 게임 자체라기보단 게임 일부(UI나 팩의 개념)라고 생각되므로 소멸에 한 표.. (웜홀 뚫려서 정신 차리기 의견과는 모순되지만)

**++**
적혀있는대로 알투몬과의 대립이 기대됨!!

현재 접속 게임은 재접속을 조금씩 유도하는 방향인데 (팩맘도 그렇고)
최초가 아니더라도 계속 등장하여 설명하면 스킵하도록 자연스럽게 유도할 수 있지 않을까?

상호작용을 못하는 부분이 결핍이 될 수는 있겠지만
'라플리' 또한 자아 없이 유저가 조작하는 대상이기 때문에 결핍이 해소될 것 같지는 않다는 생각...
대신 라플리가 되어 이동을 마음대로는 할 수 있을듯?

**Comment by gomgom172** [comment]
### 설명요정 구체화

> 고민: 만약 스킵 안 하고 튜토리얼을 천천히 읽는 유저가 있다면 어떻게 전개해야 할까..? 역으로 스킵해야 스토리에 몰입이 되는 구조가 되진 않을까,,?

같은 의견입니다. (저도 튜토리얼 설명 하나하나 읽어보는 편이라서….) 현재 설명요정의 결핍에는 유저의 스킵을 필수적으로 요구하는 상황이 전제로 잡혀 있어서, 설명요정의 설명을 모두 듣고 넘어가는 유저에게는 부자연스럽게 느껴질 수 있을 것 같습니다.

피그마에 적혀 있는 내용처럼, 튜토리얼 설명을 터무니없을 만큼 아주 길게 하거나 귀찮을 때까지 반복해서 들려주거나 해서 스킵할 건덕지를 주는 방안을 생각해 보았습니다. 스킵을 누를 때까지 말풍선이 끝나지 않고 계속 넘어가게 만들거나요. 다만 스킵을 원하지 않는 유저에게도 스킵을 강요하는 느낌이 될까봐 걱정입니다.

> 고통받고 있다는 증거 : 스킵하면서 말하려다가 숨차서 얼굴 빨개지기, 문장이 꼬이거나 맞춤법
틀리기, 글씨크기나 폰트를 뒤죽박죽 섞어 쓰기

해당 부분 무척 흥미로워 보입니다. 👍 연출적인 면에서 꼭 가져갈 수 있었으면 좋겠다는 생각이 드네요!




### 던져보는 아이디어


‘자신의 역할’을 중요하게 여기는 캐릭터라면 1회성 엑스트라의 입장에 초점을 두는 건 어떨까요? ‘설명’의 역할을 부여받은 설명요정이, 튜토리얼이 끝나고 자신의 역할이 끝나면 더이상 존재의의를 가지지 못하는 것에 대해 분노한다거나…. 자신의 존재에 대한 욕망(게임을 움직이는 주체인 ‘유저’와 이어져 있는 순간에 대한 갈망) 내지 자신을 필요로 하기를 바라는 욕망 등을 가지고 있다면 어떨까요? 라플리에게서 유저를 뺏어 오고자 하는 마음도 비슷한 방식으로 설명할 수 있지 않을지 (BAD 라플리라는 역할을 스스로에게 부여해서 이 게임에서 존재의의를 갖고자 한다… 라는 끼워맞추기라든지) 생각해 보았습니다!


가볍게 읽고 넘겨주세요. 튜토리얼 캐릭터→흑막 캐릭터로의 역할 변화는 처음 들었을 때에도 그랬지만 언제 보아도 정말 매력적이어서 늘 기대가 됩니다. 기획 파이팅입니다…!

**Comment by roweclaw** [comment]
수민님, 우연님, 이우님 피드백에 대한 통합 답변입니다!


## 1. 스킵 유도 고민
> 고민: 만약 스킵 안 하고 튜토리얼을 천천히 읽는 유저가 있다면 어떻게 전개해야 할까..? 역으로 스킵해야 스토리에 몰입이 되는 구조가 되진 않을까,,?

> 피그마에 적혀 있는 내용처럼, 튜토리얼 설명을 터무니없을 만큼 아주 길게 하거나 귀찮을 때까지 반복해서 들려주거나 해서 스킵할 건덕지를 주는 방안을 생각해 보았습니다. 스킵을 누를 때까지 말풍선이 끝나지 않고 계속 넘어가게 만들거나요. 다만 스킵을 원하지 않는 유저에게도 스킵을 강요하는 느낌이 될까봐 걱정입니다.

- #387 

위 이슈에서는 '설명을 스킵하는 것을 계기로 유저라는 존재를 깨닫는다'라고 논의도 있었고, '설명'요정인 만큼 그의 설명을 듣지 않는 행위가 조금씩 쌓여서 후반부에 큰 반전을 줄 수 있는 요소로 작용할 수 있겠다고 생각했습니다. 다만, 우려해주신대로 스킵을 유도하기 위해서 설명이 터무니없을 정도로 길거나 귀찮을 때까지 반복하는 방법을 썼을 때 원치 않는 스킵을 강요하는 느낌이 들 수 있을 것 같기도 해서 다른 방안을 추가로 생각해봤습니다.

- 스킵을 유저의 자율에만 맡기지 말고, R2-MON을 통해 스킵하도록 유도하기
   - R2-MON은 GRAYED GAME의 오리지널 캐릭터이고 유저를 인식하는 메타 캐릭터라는 점을 활용
   - (예시, Ch2에서) 이 세계관은 잊혀진 게임들이 오는 곳이고 대부분 너가 아는 게임일 거니까 굳이 열심히 설명 들을 필요 없다! 마을 사람이 사라졌으니까 이 상황을 빨리 해결하는 게 더 우선이니 시간을 효율적으로 써라!
   - (예시, 만약 유저가 진짜 단 한 번도 스킵을 안 누른 경우를 대비해 Ch4에서) R2-MON이 설명요정을 오해하고 스킵을 대신 눌러버려서 설명요정이 급발진 흑화 (...)

이렇게 하면 스킵을 하지 않던 유저들도 처음 한 번 정도는 설명을 듣다가 이후 반복되는 말이 나오면 스킵을 하게 되지 않을까 싶어요..!  R2-MON은 유저의 조력자이고 유저와 함께 설명요정과 대립하게 되는 존재인 만큼 설명요정이 흑화하는 이유에 R2-MON도 한 몫 하게 되는 거죠..

> 아마 스킵 여부 (몽땅 스킵, 적당히 스킵, 스킵 X)로 갈리면 좋지 않을까?

그래서 현재 생각은 분기점이 위와 같이 스킵 여부로는 나뉘지 않고, 유저의 스킵에 의해 설명요정이 악역이 되는 시나리오를 기획하고 싶다! 입니다. _당신이 무심코 누른 스킵이 누군가에겐 상처가 됩니다... (개발자의 마음일지도?)_


## 2. 모순 해결
> Bad 라플리는 원래 자아가 있고 메타픽션 캐릭터임
왜냐면 항상 제4의 벽을 넘어 유저에게 설명해주는 것이 일이었기 때문

저도 BAD라플리의 기존 설정을 활용하기 위해 자아를 부여해볼까 고민했지만 일단 보류하게 되었는데요. 그 이유는 ` BAD라플리가 '라플리'의 본체였고 유저를 맹목적으로 갈구한다`는 원래의 설정에서는 가능할 수 있지만, 현재는 `설명요정이라는 캐릭터가 유저의 스킵 등의 다른 계기를 통해서 흑화하게 되는 서사`인데 여기에 원래부터 자아가 있었다는 설정이 추가 될 경우 스토리가 너무 딥해질 거 같았기 때문입니다.

따라서, 피드백들을 쭉 읽어봤을 때 설명요정의 악역 스토리를 깔끔하게 가져가려면 기존의 BAD라플리 설정은 제외하되, `다른 이유`를 만들어서 라플리를 따라한 모습으로 악역이 되면 좋을 거 같네요. `다른 이유`는 곧 악역의 결핍과 연결되는 부분인데, 우연님 말씀처럼

> 상호작용을 못하는 부분이 결핍이 될 수는 있겠지만
'라플리' 또한 자아 없이 유저가 조작하는 대상이기 때문에 결핍이 해소될 것 같지는 않다는 생각...

제가 허술했던 부분을 잘 집어주셔서 감사합니다.!! 결핍 내용도 보충해야 할 것 같습니다. 


## + 참고할 아이디어

> 하지만 마을에 와서는 잊혀지다가 유저를 만났는데 (이 유저가 마지막일수도 있는데) 또 스킵해버리니 불안감에 흑화해버린거임

> ‘자신의 역할’을 중요하게 여기는 캐릭터라면 1회성 엑스트라의 입장에 초점을 두는 건 어떨까요? ‘설명’의 역할을 부여받은 설명요정이, 튜토리얼이 끝나고 자신의 역할이 끝나면 더이상 존재의의를 가지지 못하는 것에 대해 분노한다거나…. 자신의 존재에 대한 욕망(게임을 움직이는 주체인 ‘유저’와 이어져 있는 순간에 대한 갈망) 내지 자신을 필요로 하기를 바라는 욕망 등을 가지고 있다면 어떨까요? 라플리에게서 유저를 뺏어 오고자 하는 마음도 비슷한 방식으로 설명할 수 있지 않을지 (BAD 라플리라는 역할을 스스로에게 부여해서 이 게임에서 존재의의를 갖고자 한다… 라는 끼워맞추기라든지) 생각해 보았습니다!

좋은 아이디어 감사합니다. 참고해서 업데이트 진행해보겠습니다!

**Comment by fkdl0048** [comment]
## 피드백

### 설명요정

위 내용을 토대로 Bad 라플리 == 설명요정에서 벗어나는 점은 좋은 것 같습니다. 설명요정에 대한 아이디어를 좀 더 보충하자면, 튜토리얼이라는 시스템 상 해당 요정은 라플리와 소통하는 것이 아닌 "유저와 소통한다"가 핵심인 것 같습니다. 라플리는 유저와 소통을 위해 사용하는 매개체에 불과하다는 생각도 듭니다.

추가적으로 그런 설명요정 리소스는 유저에 대한 애착이 있을 것 같습니다. 따라서 튜토리얼 도중 애착이 생기는 과정을 상황적으로 연출한다면 스킵을 유도할 수 있을 것 같습니다. 예를 들어 게임 설명 도중에 대사가 멈추고 같이 시간을 보내는 등 튜토리얼 자체의 진행을 제한하여서 보여줘도 재밌을 것 같네요!

저번에 논의한 내용대로 게임의 속성이나 설정들이 자세해지는 것은 좋지만, 그런 내용들이 유저로 하여금 피로감을 느낄 정도의 깊이로 가지 않았으면 합니다. 저희끼리는 머리를 싸매고 이야기를 해야하겠지만, 유저들은 이해가능한 재밌는 수준의 스토리만 느끼는게 좋을 것 같습니다!

**Comment by wooyn730** [comment]
> 저번에 논의한 내용대로 게임의 속성이나 설정들이 자세해지는 것은 좋지만, 그런 내용들이 유저로 하여금 피로감을 느낄 정도의 깊이로 가지 않았으면 합니다. 저희끼리는 머리를 싸매고 이야기를 해야하겠지만, 유저들은 이해가능한 재밌는 수준의 스토리만 느끼는게 좋을 것 같습니다!

저도 정말 동의합니다

**Comment by royalbluesm** [comment]
현재 설정이 가지는 여러 의문점들에 대해선 다른 분들이 괜찮은 지적을 많이 해주시니 저는 떠오른 아이디어 하나 적고 가겠습니다...

1. 설명요정이라는 포지션에서 필요한 건 "설명을 해주다가 스킵당하는 역할" 이 핵심이라고 생각합니다. 따라서 이 역할만 충족시킬 수 있다면 캐릭터의 정체성을 설명요정으로만 한정짓지 않아도 괜찮지 않을까? 라는 생각이 드네요.

2. 원래 R2-MON과 같은 주인공의 조력자 역할이었는데, 주인공은 설명을 해줄 때마다 스킵하질 않나, 혹은 처음엔 내 말에 귀를 기울였으면서 고인물이 되어갈수록 무시하지 않나... 이런 '조력자로서의 서러움'이라는 속성이 추가되면 더 유저가 납득하기 쉬운 흑화 이유가 되지 않을까? 라고 생각합니다.

3. 이를 위해선 라플리를 조종하는 유저 이전에도 설명요정을 거쳐간 '주인공'들이 존재해야 하는데, 이 선대 주인공들이 존재한다면 어떨까요...? 이거라면 GG를 플레이하는 유저가 설명을 스킵하지 않는 성실한 플레이어더라도 설명요정이 화가 나 있는 이유도 설명할 수 있다 생각합니다.

4. 종합하자면, '라플리 이전에도 설명요정이 설명을 해주는 대상들이 있었음' + '단순히 설명 역이 아닌, 주인공의 조력자 역할이었는데 버려짐'이라는 서사를 추가한다면, 많은 점들이 해소되지 않을까 싶습니다.

**Comment by roweclaw** [comment]
## 피드백 총 정리 

### 스킵 유도 방안
1. 튜토리얼 설명을 터무니없을 만큼 아주 길게 하거나 귀찮을 때까지 반복해서 들려주기, 스킵을 누를 때까지 말풍선이 끝나지 않고 계속 넘어가게 만들기.
2. 스킵을 유저의 자율에만 맡기지 말고, R2-MON이 스킵을 하는 게 좋다는 식의 말을 유저에게 하거나 직접 스킵에 개입하기.
3. 튜토리얼 도중 애착이 생기는 과정을 상황적으로 연출하기, 게임 설명 도중에 대사가 멈추고 같이 시간을 보내는 등 튜토리얼 자체의 진행을 제한해 보여주기.

### 만약 유저가 스킵하지 않으면?
'라플리 이전에도 설명요정이 설명을 해주는 대상들이 있었음' + '단순히 설명 역이 아닌, 주인공의 조력자 역할이었는데 버려짐'이라는 서사를 추가
→ GG를 플레이하는 유저가 설명을 스킵하지 않는 성실한 플레이어더라도 설명요정이 화가 나 있는 이유도 설명할 수 있다.

### 악역의 결핍 보충방안
1. 마을에 와서는 잊혀지다가 유저를 만났고 이 유저가 마지막일수도 있는데 또 스킵해버리니 불안감에 흑화
2. 설명’의 역할을 부여받은 설명요정이, 튜토리얼이 끝나고 자신의 역할이 끝나면 더이상 존재의의를 가지지 못하는 것에 대해 분노


### 유저 강탈 이유 보충방안
게임을 움직이는 주체인 ‘유저’와 이어져 있는 순간에 대한 갈망을 채우기 위해 BAD 라플리라는 역할을 스스로에게 부여해서 이 게임에서 존재의의를 갖고자 한다.
