### ISSUE TITLE
[CH1] Scene 1 오브젝트, 3매치 퍼즐 맵

### ISSUE THREAD

**Issue by gomgom172** [GG-Studio-990001/Grayed-Game#398]
0413 [임시 파일](https://drive.google.com/drive/folders/1syXs8KmT3J3epprWf-kl46qxYtd7Za7T?usp=share_link)

---

**240407 작업 계획**
Scene 1 리소스 A-D
3매치 퍼즐 맵과 리소스 작업합니다.

3매치 퍼즐 맵과 리소스 러프 및 구상은 시스템 플로우 재정리 문서 확인 후,
가능한 수요일(4/10)까지 전달드릴 예정입니다.
맵 구상은 논의에 따라 1-2주 소요될 수 있을 것 같습니다.

Scene 1 리소스 A-D와 3매치 리소스(젤리)는 이번주까지 작업 예정입니다.

# 240412 진행 상황
0410 문서 확인 후 작업 진행하였습니다.

![0412-ver2](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/a2c69d2c-3708-45dd-b7f3-07f6b0ceec5a)

시스템 문서의 리소스 배치를 재현한 버전입니다. (리소스 무더기 사이에 꽂힌 퍼즐판은 우선 임의 모형으로 제작하였습니다.)

<img width="767" alt="스크린샷 2024-04-12 오후 9 33 42" src="https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/455a0e6e-1f9c-4b9c-a26f-5d83a79afeee">

각 오브젝트는 32*32로 작업하였으며, 타일 한 칸도 같은 사이즈입니다.
퍼즐맵 형태 자체는 리소스 배치 가이드에 따라 변경 가능합니다.

## 캔디 크러쉬 사가 구체화에 대한 제안

![0412](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/97a6783c-8c2a-4c25-bb03-5b323dbbba38)

![0412-2](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/c42d78e0-1ceb-419a-9c86-b00c4d98b535)

해당 게임 레퍼런스를 확인하며, 이미테이션 느낌을 내려면
```
1. 모든 타일칸에 오브젝트가 배치되어 있어야 함
2. 맵이 정확한 형태를 가져야 함(퍼즐판 모양임을 한눈에 보일 수 있도록)
```
위 두 부분이 중요하다고 생각했습니다.

현재의 몸으로 밀어서 움직이는 방식에는 라플리가 움직일 수 있는 빈 타일맵이 필수적으로 필요하므로,

라플리가 고정 방해물 외 리소스(젤리빈, 초콜릿, 지팡이 사탕 등) 위나 옆을 걸어다닐 수 있고, 리소스를 들어올려 다른 리소스 자리에 올려놓으면 두 리소스 자리가 바뀌는 형태여야 원본 게임의 느낌에 가장 가까워질 것 같다고 생각합니다.

 _(캔크사의 경우에는 상하좌우 1칸과 교환하는 형식인데, 라플리는 너무 무거워서 오래는 걸을 수 없어서 1칸까지만 이동 가능 정도로 치환하면 어떨까요)_

캔디 크러쉬 사가와는 화면 비율, 플레이 매체(휴대전화/컴퓨터), 플레이 방식(터치 드래그 방식/마우스 혹은 키보드 조작)이 모두 다르기 때문에, 비주얼적인 부분은 가능한 원본을 따라가야 할 것 같다고 생각합니다. 이 부분에 대해서 기획 분들과 플머 분들의 의견이 궁금합니다.

맵 구상하며 생각해 본 개인 의견이므로 제가 모르는 부분이 있거나 의견 주실 부분 있다면 편히 말씀 부탁드립니다!

# 240413 진행 상황

<img width="511" alt="스크린샷 2024-04-13 오후 10 29 07" src="https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/07ad246d-0bd6-4dd6-9b73-011a867a804f">

<img width="833" alt="스크린샷 2024-04-13 오후 10 57 38" src="https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/14e4bd00-2dec-4e03-8196-9d178d1d5bc5">

Scene 1 오브젝트와 3매치 퍼즐 젤리 바리에이션을 작업했습니다.
[임시 파일](https://drive.google.com/drive/folders/1syXs8KmT3J3epprWf-kl46qxYtd7Za7T?usp=share_link) 우선 이쪽에 폴더를 생성해 넣어두었습니다!

![0413scene1 6esource_e g](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/1fcb6750-c9b2-47a6-a26f-88fffc42e3e2)

어색하지 않게 작업해 보려고 노력 중인데 쉽지 않네요… 좀 더 작업해 보아야 할 것 같습니다. 오브젝트 제작 후 후처리가 필요할 것 같은데(그림자 작업 등) 이 부분은 맵 수정 완료 후 들어가는 게 좋을 것 같습니다.

**Comment by gomgom172** [comment]
240412 업데이트되었습니다.

**Comment by Sumindd** [comment]
> 기획자의 의견

직관적으로 3매치 퍼즐임을 느끼려면 후자 이미지가 확실히 낫다고 생각합니다. 
그런데 사실 개인적으로는 게임 리소스와의 모든 결합에서 시스템까지 결합해야 한다고 생각하진 않습니다. 정말 일부 리소스만이 결합된 상태에서 전혀 다른 시스템이 붙어서 작동해도 어색하지 않은 게임이라고 생각합니다. 
GRAYED GAME에서 시스템(프로그래밍?)도 별개의 리소스라고 볼 것인지, 이미지만을 리소스로 볼 것이며 이미지 리소스엔 해당하는 게임의 시스템이 수반된다고 설정을 잡을지 이야기 나누어보면 좋을 것 같습니다! 
그리고 이미 기획이나 프로그래밍이 어느정도 완성된 시스템이라 아예 시스템을 바꾸기엔 인풋이 빡셀 것 같습니다..! (플밍 파트의 의견이 더 중요할 것 같네요) 저는 조금 아쉽더라도 튜토리얼이니까 이런 것도 있다는 걸 보여주는 식으로 라이트하게 넘어가고 추후 챕터에 조금 더 신경쓰는 것이 더 좋지 않을까 싶습니다..

> 아트 피드백

도트는 너무 귀엽습니다. 특히 폭탄이 동글동글해서 너무 마음에 듭니다! 다만 지팡이 사탕의 머리(?)부분이 배치했을 때도 조금 각진 느낌이 들어서 조금만 더 둥글게 다듬으면 좋지 않을까 의견을 내봅니다..!
그리고 확실히 기존 시스템에 해당하는 이미지가 상대적으로 휑해보이긴 하네요.. 저도 시스템 관련해서 조금 더 고민을 해보겠습니다.. 
그리고 맵은 둘레에 좀 더 여유가 필요해보입니다! (이동 칸 기준 2칸 이상씩?) 이동 시킬 수 있는 공간이 필요해서 꽉 차게 넣는다는 느낌보다는 테두리가 널널하게 "존재"한다는 방향으로 가는 것이 좋을 것 같습니다!

**Comment by wooyn730** [comment]
기획이랑 아트에 대해 두루두루 언급했습니다!
피드백을 빨리 작성하기 위해 음슴체를 썼으므로 양해 부탁드립니다 ㅠ

### 내 맘대로 리소스 떨어지는 과정 구체화
하늘에서 떨어진 게임이 '3매치 퍼즐'임
'3매치 퍼즐'은 하늘에서 떨어지는 동안 분해가 됨 (또는 떨어지다 리소스 무더기에 부딪혀 분해가 된 후 한번 더 튕김)
'3매치 퍼즐' UI 중 일부는 다리를 부수고,
'3매치 퍼즐' 중 캔디들을 모아놓은 보따리는 동굴 천장을 뚫고 동굴 안으로 떨어짐

(이렇게 생각한 이유들)
1) 3매치 퍼즐 UI가 다리를 부수는 걸 보여준다면 동굴 내부에서 진행되는 것이 3매치임이 좀 더 명확할 거 같음
2) 보따리는 그냥 귀여워서! 다른 사탕 박스거나일수도 있고.. (근데 맵 모양에 따라 보따리가 동굴 천장을 뚫는 건 안보일수도..)
3) 동굴의 재료(?) 또한 리소스들이라고 생각함. 따라서 천장 부분 사이사이 구멍이 있고, 사탕 보따리가 떨어질 수 있을 거 같음

++
이건 구구절절 생각해본거고
게임 상에서는 `'3매치 퍼즐' 앱 아이콘이 금 가있는 상태로 다리를 부순다~` 정도 보여주면 좋지 않을까...

### 내가 생각한 동굴의 모습
이우님의 구체화 버전이 마음에 들었음
하지만 두 사탕을 바꾸는 것은 개발 비용이 쎄다고 생각함
따라서 빈 공간을 만들어 기존 구현대로 밀 수 있게 배치
그래서 변경된 그림은 이러함!
![그륌판](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/4e8121c4-d2f8-48ea-8506-22ad30cc36b6)

일단 사탕이 많이 차 있는게 확실히 3매치 퍼즐 같은 느낌을 주는 듯 (이우님 의견대로)
또한 밀 수 있으려면 테두리가 여유로워야할 듯 (수민님 의견대로)

돌은 있어도 되고 없어도 되지만 너무 많지 않았으면 좋겠음

(나름 열심히 그렸읍니다)

(이거 진짜 탈출할 수 있게 은근 머리 써서 배치해보앗습니다;; 딱 보이시는쥐?)

### 폭탄의 필요성
폭탄의 필요성에 대해 의문이 듦
기획서에는 "다리 건설 전에 사용하던 동굴 길"로 되어있는데 왜 다른 한쪽이 막혀있으며, 그 앞에 폭탄이 있는지 궁금함.
뚫린 반대쪽 입구로 나가면 아무튼 상관 없는 거 아닐까?
(하지만 폭탄 그림이 너무 귀엽다;;;)

### 아트 피드백
지팡이사탕 위아래가 둥글면 이쁠 것 같다는 수민님 의견에 동의함
또한 젤리빈이랑 지팡이 모두 빨간색이라 하나는 색을 바꿔주면 좀 더 알록달록하고 예쁘지 않을까 싶음

개인적으로는 마을은 '잊혀진 게임'이 모이므로 너무 잘 그리면 안될 것 같기도 함(?)
B급 느낌이 나면 좋을 것 같음 근데 물론 잘그리고 귀여우면 좋음
=> 앞으로 조금 뇌절하더라도 아트의 창의력을 자유롭게 뽐내보는 건 어떨까 함

(뜨거운 아아 같은 소리 같기도 함 죄송합니다 ㅎㅎㅎㅎ)

**Comment by Sumindd** [comment]
> 우연님의 질문에 대한 답변

한 쪽 방향을 막고 굳이 폭탄을 뒀던 이유는 일단 기존 기획서의 배치나 세부 기획을 최대한 안 건드리는 선에서 생각하다보니
기존: SLG UI를 먹어서 해결
수정: 무언가 버튼을 눌러서 탈출 -> (동굴로 위치 바뀌면서) 탈출구를 만들기 위한 폭탄 트리거
이렇게 생각의 흐름이 흘러갔습니다.. 사실 기존 기획서의 세부 기획을 갈아 엎고, 밀도 높이는 방향으로(젤리 리소스 많이 배치) 가면 아예 길을 뚫고 지나가는 쪽이 자연스러울 것 같습니다!

**Comment by gomgom172** [comment]
프로그래밍 구현이 얼마나 어려울지 감이 안 와서 우선 의견 던져보았는데, 말씀해주신 대로 개발 비용 측면에서 문제가 있을 것 같네요. 말씀해주신 부분 이해했습니다.

우연님이 그려주신 그림대로 테두리가 여유롭고 젤리가 더 많이 차 있는 방향이 좋을 것 같다는 의견입니다. (비주얼적으로도 3매치 퍼즐이 충분히 잘 연상되는 것 같습니다.👍) 맵 스케치는 우선 잠시 보류해두고, 작은 리소스들 먼저 작업하도록 하겠습니다!


**아트 피드백 관련**

> 지팡이 사탕의 머리(?)부분이 배치했을 때도 조금 각진 느낌이 들어서 조금만 더 둥글게 다듬으면 좋지 않을까 의견을 내봅니다..!

> 그리고 맵은 둘레에 좀 더 여유가 필요해보입니다!

> 젤리빈이랑 지팡이 모두 빨간색이라 하나는 색을 바꿔주면 좀 더 알록달록하고 예쁘지 않을까 싶음

> B급 느낌이 나면 좋을 것 같음

모두 확인했습니다. (해당 사항 모두 OK/젤리 리소스는 의견 취합 후 바리에이션+수정본을 토요일 밤 중으로 업데이트할 예정입니다.)


> 이전에 보석이었을 때는 깨지는 과정 애니메이션? 스프라이트를 받았는데 젤리도 깨지는 과정 그려주시는지 궁금함

작업 가능합니다. (해당 부분은 젤리 형태 픽스 후 작업 들어가면 될 것 같습니다.)


> 바닥은 타일맵으로 받으면 좋을 듯!

확인했습니다. 타일맵으로 붙일 수 있도록 작업해 보겠습니다!
원하시는 규격 있으시면 말씀해 주시면 좋을 것 같습니다. (없을 시 32*32로 작업하게 될 것 같습니다. 빨간 네모칸 한 칸입니다!)

**Comment by gomgom172** [comment]
240413 작업 진행+파일 업데이트되었습니다!

**Comment by wooyn730** [comment]
큰 오브젝트들 느낌 너무 좋은데요?
(근데 가장 오른쪽거는 몬가요?)

맵도 다음주에 나오고 오브젝트들도 꽤 나왔으니 조만간 플밍이랑 아트 같이 라이팅에 대해 얘기해봐요~
(2D라 저런 그림자까지 구현은 안되겠지만) 빛에 대한 이야기는 슬슬 해보면 좋을 것 같아요

지팡이 사탕은 수정 후 버전이 훨씬 마음에 드네요!!
색이 다른 젤리들은 배치된 모습을 봐야 어떤 게 가장 어울릴지 알 것 같아요
(근데 이미 빨간 젤리를 계속 봐서 그런가 빨간 젤리가 제일 잘 어울리는 것 같기도 하고;;;)

**Comment by gomgom172** [comment]
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/4e1b9437-745d-4f74-b3bd-6a516ab03316)

가장 오른쪽 오브젝트는 갤러그 형태를 따왔습니다.
라이팅 부분도 확인했습니다!
회의 때 이것저것 더 자세히 얘기해 보면 좋을 것 같습니다.

피드백 감사합니다 👍👍

**Comment by royalbluesm** [comment]
맵에 있는 큰 리소스들 아이디어 너무 좋습니다!! 제가 내지 못한 아이디어를 보완해주시니 항상 감사할 따름입니다...
다만 그 리소스들만 픽셀 크기가 다른 건 지나치게 이질적이지 않나 하는 생각이 듭니다. (리소스들 간 이질감이 드는 것 자체는 좋지만, 너무 붕 뜨는것 같은 느낌?) 큰 리소스들을 원근감을 무시하고 배치하는 건 좋으나, 픽셀 단위까지 크게 변경하신 이유가 있는지 궁금합니다.

**Comment by wooyn730** [comment]
엇 저는 픽셀 크기 똑같아서 좋다고 생각했는데..! 다른가요?

**Comment by fkdl0048** [comment]
저도 아트 2분이 다른 시각으로 게임을 접근해서 다른 리소스를 그려주는 부분이 너무 만족스럽네요. 진짜 협업하는 느낌이라 좋아요. 다만 픽셀 단위는 통일 했으면 합니다. (다르다면?) 이건 전 아트 팀원분들이나 기획의도 상 현재 뷰가 한 장르로 통일되어 있기 때문에 인게임의 뷰는 모두 동일해야 한다는 의견입니다
