### ISSUE TITLE
[CH1] 컷씬 설계

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#399]
# [CH1] 컷씬 설계

## 용어

<details><summary> 정리 </summary>

### 연출
연출은 본디 연극에서 쓰기 시작한 용어로, 배우의 연기, 배경 음악, 무대의 조명 등으로 공연을 만드는 일을 이르며, 정의상으로는 감독이 자신의 메시지를 효과적으로 전달하기 위해 연극에서 동원하는 모든 시청각적 수단을 일컫는다. 이후 용어가 퍼져 영화, 게임, 방송 등 영상 컨탠츠를 포함한 다양한 장르에서도 사용되고 있다.

### 컷씬(Cut Scene)
비 상호작용적인 시퀀스 혹은 비 상호작용적이고 게임플레이에 비간섭적인 비디오 시퀀스를 말하는 것이며, 배경 스토리를 설명하거나, 플롯을 진행시키거나, 플레이어가 달성해야할 목표를 이미지로 묘사하는 기법 중 하나이다. (이벤트씬이라고도 한다.)

### 타임라인(Time Line)
씬의 게임 오브젝트에 연결된 트랙과 클립을 시각적으로 정렬하고 컷씬, 시네마틱 영상, 게임플레이 시퀀스를 생성할 수 있는 유니티의 기능

### 얀 스피너(Yarn Spinner)
유니티 패키지 중 하나로 현재 대화 시스템으로써 사용하는 기능

### 정리
연출은 포괄적인 용어이므로 이러한 작업들은 컷씬 작업이라고 부르는 게 맞는 듯.
타임라인과 얀 스피너는 컷씬을 제작할 때 사용할 주요 도구로 다른 직군을 위해 한 번 정리해봄~~
</details>

## 계획

- 수민님의 [전체 시스템 문서 3차](https://github.com/GG-Studio-990001/Grayed-Game/issues/416)를 보면서 컷씬 정리
   - (항상 가장 최근의 문서를 참고)
- 기획 문서에서 컷씬만 따로 뽑아 정리
- 컷씬에서 공통으로 사용될 기능들 정리
- 그 외 생각들 정리

## 컷씬 정리

[CH1 컷씬 설계(구글 스프레드 시트)](https://docs.google.com/spreadsheets/d/1g2I75ii3xcIzwMrdC2BNauJWuTdAExU3uq7Wzg3TMhM/edit#gid=0)에 정리

## 기능 정리

- 컷씬 시작, 컷씬 끝
- 주인공의 움직임과 상호작용 막기
   - 설정창은 아마 가능하도록...?
   - 타임스케일 0일 때 타임라인도 멈추는지 확인 필요
- 컷씬이 끝나면 해당 컷씬을 보여줬다는 것을 기록
   - 게임 세이브 관련임
   - 현재 게임 세이브가 딱히 없으므로 끝날 때마다 자동으로 저장
- 대부분의 컷씬에는 다이얼로그(대화)가 들어감
- 일부 컷씬에는 카메라 움직임(또는 줌인/아웃)이 들어감
   - 현재 `Pixel Perfect Camera`가 `Camera`를 오버라이딩 하고 있는데, 부드러운 줌인/아웃을 위해서는 `Camera`의 기능을 사용할 듯 (되는지는 모름)

### 상호작용 활성화/비활성화
컷씬시작=> 상호작용 비활성화 / 컷씬끝=> 상호작용 활성화 이렇게 하면 편리하긴 함
하지만 주민들이 먼저 맵을 넘어가는 컷씬 같은 경우에는
컷씬이 끝나기 전이더라도 주인공 움직임은 풀어줘도 될 듯
(주민들이 맵 넘어갈 때까지 기다리는 시간이 긺, 대신 주민들을 따라잡을 수는 없어야 함)

### 진행도
컷씬 진행도로 게임 진행도를 알 수 있음
주민들과의 대화(구현)도 내가 관리해야 할 듯..
(컷씬 진행도를 판별하고 대사 출력)
선형적인 구조이므로 챕터1 진행도는 bool 배열보다는 float로 표시하면 될 듯

### 고정 연출
종류: 접속, 탈출, 역접속, 탈피, 장르팩 교체
~현재 팩맘 접속은 모자이크같은 쉐이더로 되어있음
이거 계속 갈건지도 정해야하고 나머지도 이야기해봐야 함~
**기획 비정기 회의 참여 후 판단**
- 대사창으로 모두 처리(e.g., 언어팩을 장착하였습니다.)
- 씬이 바뀔 때 모자이크 처리 (팩맘, 장르팩) 
- SLG UI 장착은 대사창만 처리 (구현 확인 후 화면을 가릴 필요가 있다면 모자이크 처리)

### 움직임
가능한 자동이동을 최소화하면 좋겠음
직접 움직이게 유도하는 것이 좀 더 자율적으로 보일 것 같음

## 그 외

정안님 wait 관련해서 타임라인과 얀 스피너 충돌? 이 있다고 들었는데 한 번 물어봐야 할 듯

정안님 상호작용, 움직임 코드 다시 뜯어보기

수빈님이 스크립트 작업이 선행되면 좋겠는데 작업 언제 가능하신지 체크하기

**Comment by fkdl0048** [comment]
연출 작업을 어떻게 만들면 좋을지 같이 이야기 해봐도 좋을 것 같아요. 너무 부담을 가지기 보단 "2~3명이서 같이 만들어 보자"라는 생각으로 해보시는 걸 추천드립니다! 같이 설계를 해보고 막히면 같이 이야기를 해보는 방식으로!

개인적 성장으로도 1챕터에서 지속적으로 활용되는 연출 자체에 대한 컨트롤러를 제작한다고 하면 좋은 경험이 되실겁니다

**Comment by wooyn730** [comment]
자체 판단하에 작업 연기하겠습니다.
맵 리소스 작업과 스크립트 작업 보다 선행되면 추후 수정해야할 부분이 훨씬 많을 것 같습니다.

하지만 너무 늦어지지 않게 다음주나 다다음주에는 최소 설계 작업은 시작하려고 합니다.
가능하다면 중간 발표(5/11) 전까지 연출 작업 마무리해서 챕터 1을 완성하고 싶네요.

자세한 건 회의 때 이야기하겠습니다.
