### ISSUE TITLE
[CH1] 튜토리얼 SLG 시스템 구현

### ISSUE THREAD

**Issue by jeongopo** [GG-Studio-990001/Grayed-Game#400]
## 목표기능
- SLG에서 사용하는 세부 아이템 획득 시스템
- 현실 시간 기준으로 감소하는 건설 시간 표시

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/b6487880-d0e1-44cb-ab37-c21c982ff766)

### 세부 논의사항
- 기존의 다른 씬과 충돌되지 않도록 기존 씬을 복제한 후 작업
- UI는 임시 이미지로 작업 이후 교체

## 참고문서

[기획 피그마](https://www.figma.com/file/LNsoGFh5f3jQ1rCPQB2O9f/Grayed-Game?type=design&node-id=0-1&mode=design&t=tIzZr5dftCxdXZQr-0) 

[CH1 플로우 문서](https://drive.google.com/file/d/14EZCzINkjewJhQIQjmr1D4sWA9sX4JiG/view)

## 작업 중의 고민사항
- 중간에 재접속 시 시간 표시의 변경점은?

----

4/10 에 작업진행할 예정입니다.

**Comment by fkdl0048** [comment]
현정님도 아마 코드를 무의미하게 읽는 것 보단, 작업 하시면서 프로젝트 파악하시는게 더 좋다는 것을 잘 알고 계신 것 같아서 크게 걱정은 되지 않지만, 분명하게 이해가 안되는 부분들이나 고쳐야 할 부분들이 보이실 것 같습니다!

SLG는 작은 시스템이니 완벽할 필요는 없으니까 같이 이야기 해보고, 만들어 보면 좋을 것 같습니다!

**Comment by jeongopo** [comment]
## 0410 작업내용 
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/639cbdbb-2c8d-43b1-b3b9-1d094cef240a)

- SLGActionComponent 를 통해 SLG 컨텐츠와 관련된 함수들 제공
- 메인객체에 Sprite 이미지 데이터 포함해서 실제 Interaction 객체에서 참조하도록 함
- SLGSpots 하위의 객체 위치들 중 랜덤 n개를 선택해 보이도록 만들어줌
어떤 식으로 구조 잡을지 고민하느라 실제로 작업을 얼마 못했네요... 구조만 결정되면 좀더 빠르게 작업 가능할것같습니다 😅

### 이후 작업 예정
- [ ] 상호작용 오브젝트들을 마우스 클릭으로 획득할 수 있도록 하는 작업
- [ ] ConstructionUI 표시하는 작업
- [ ] 획득한 목재, 돌의 재화를 UI에도 업데이트해주는 작업
등등.. 할게 많이 남았습니다.

## 이슈
- 씬 복사해서 오브젝트좀 정리했더니 카메라가 안움직여요... 😢

## 플밍 작업중 궁금증
(나중에 회의때 구두로 여쭤보는 편이 좋을 것 같네요)
### Controller, Data, Manager 의 기능을 어떤 식으로 정의하고 있는지? 
보통 조작이 달라지면 Controller로 인식하고 있었고, Data 파일은 어떤 범위를 기준으로 쓰고 계신지 등이 궁금합니다.

### 각 서브게임들에게 필요한 객체들이 어떤 것이 있는지?
만약 각 서브게임들마다 각각 정의해줘야 할 객체가 있으면 그것들도 인터페이스를 정의하면 좋겠습니다. 또는 아예 하나의 큰 공용 객체를 만들고 그 파일을 같이 작업하는 방식으로 해야할 것 같습니다.

### SubContent 마다 Data 를 따로 둘 것인지? 
우선 SLG 팝업 아이콘 데이터를 객체에 미리 넣어두고 참조하는 방향으로 작업했는데, 챕터별로 스프라이트 데이터 등을 저장하는 공용의 데이터 객체가 있으면 좋을 것 같습니다.

## 기획자분들에게 확인해야할 점
- SLG 아이콘의 최대 개수 제한은 몇개?
- SLG 건설 창의 시간 표시 실제로 흐르게 둘 것인지?

**Comment by Sumindd** [comment]
> SLG 아이콘의 최대 개수 제한은 몇개?
제가 정확한 뜻을 이해했는지 모르겠는데, 말풍선이 뜨는 위치가 3곳으로 고정되어 있으며 각 말풍선은 플레이어가 3번 이동했을 때마다 랜덤 아이템(목재, 석재) 말풍선으로 리스폰 됩니다. 각 아이템(목재, 석재)는 최대 99개까지 수집 가능합니다. MAX값을 설정해두고 싶으신 거라면 최대 수집 개수 제한인 99개를 고려해서 적당히 설정해주시면 될 것 같습니다..!

> SLG 건설 창의 시간 표시 실제로 흐르게 둘 것인지?
저는 실제로 흐르게 두고 싶습니다! 그래서 초단위까지 넣었으며 24시간은 헷갈릴 수도 있을 것 같다고 하여 99:00:01 부터 줄어들게 기획서 수정할 예정입니다.

**Comment by fkdl0048** [comment]
플밍에서 기존 작업에 대해서 답변이 필요한 영역과 작업 플로우에 대한 설명은 따로 회의 끝나고 시간을 잡아서 3명이서 이야기 해보면 좋을 것 같네요

**Comment by jeongopo** [comment]
@Sumindd  수민님 답변 감사합니다 ㅎㅎ!
조금만 추가질문 드려도 될까요?

> SLG 건설 창의 시간 표시 실제로 흐르게 둘 것인지? 

위 질문 관련해서 게임 재접속 시에는 어떻게 될지 궁금합니다
SLG 시작되는 타임을 게임 데이터에 저장해서 이어서 보여주도록 해야하는것인지..
그런 디테일은 필요없으시다면 그냥 **SLG 가 처음 시작되는 순간과, 이후 재접속해서 SLG 시스템 초기 세팅이 될 때**를 기준으로만 흐르게 만들어도 괜찮을까요?

**Comment by Sumindd** [comment]
게임 데이터에 저장하면 좋겠지만 품이 많이 들어간다면, 시간 단축 유도라는 기획 의도에 집중해 말씀해 주신 대로 구현해도 괜찮을 것 같습니다!

**Comment by wooyn730** [comment]
저도 게임 데이터에 저장한다에 한표~~

**Comment by jeongopo** [comment]
## 0416 작업내용
- SLG 오브젝트 UI로 클릭되는 기능
- 클릭된 오브젝트 타입에 맞는 행동 실행
  - 자원 획득

### 이후 작업 예정
- [ ] ConstructionUI 표시하는 작업
- [ ] 맵 3번 이동 시 에셋 재생성되는 작업
- [ ] 건설 UI 시간 표시 감소
- [ ] 코인 획득과의 연결?
여전히 할게 많군요...

## 이슈...
오브젝트의 UI 클릭을 Ray 로 체크하도록 했을 때 Colider가 잡히지 않는 문제
### 해결되지 않을 경우 
대안 1 ) 카메라 움직임에 따라 UI에 위치 변경되도록 작업
대안 2 ) Button을 추가해서 각각의 캔버스에 작업?

## 플밍 작업 중 궁금한 점
- Confiner 의 역할은?

**Comment by fkdl0048** [comment]
이슈의 오브젝트 UI 클릭의 경우 Ray로 체크할 때, 레이어 관련으로 Colider를 해결했던 것 같은데, 알려주시면 같이 알아보겠습니다. Confiner은 현재 시네머신으로 카메라 이동 범위를 제한하고 있어서 해당 카메라 영역을 담는 콜라이더 입니다.

시네머신 Extention에 있습니다.

**Comment by jeongopo** [comment]
흠 우선 코드는 제 브랜치에 다 올라가있는 상태입니다
Raycast 를 마우스 클릭 시에 마우스 위치로 보내서 충돌된 객체를 인식하도록 작업했는데,
Confiner 만 인식되고 제가 만든 오브젝트들은 충돌 자체가 인식이 안되네요

말씀해주신대로 레이어 문제거나, 제가 만든 오브젝트들에 어떤 설정들이 빠졌을 것 같습니다
한번 더 체크해보겠습니다 ~

**Comment by fkdl0048** [comment]
기억으론 Ray을 쏠 때 충돌 가능한 레이어만 설정할 수 있다고 해서 충돌 처리할 오브젝트에 설정할 레이어를  따로 만드시고 작업하셔도 될 것 같다는 생각이 드는데.. 가능하다면 회의 때나 작업 해결되시면 화면 보면서 같이 이야기 해보면 좋을 것 같네요!

**Comment by jeongopo** [comment]
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/fafbade5-503f-48d3-b940-967bfb17366c)
흠 이 위치 그대로 raycast 이벤트 자체가 충돌이 발생하지를 않네요... 가까이 가면 상호작용이 되던데 뭔가 다른 문제가 있는것같습니다,, 
이 문제 해결하기 위해 좀더 시간이 필요할 것 같아, 내일 밤에 추가작업 진행하겠습니다.

**Comment by jeongopo** [comment]
## 0422 작업내용
----
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/5c5e0468-2a84-4a46-9da3-25bcf6b15a8e)
(다시는 개발자의 UI실력을 믿지마시길 ㅎ)

- 마우스 인터렉션을 통해 자원 획득 UI 연결
- 건설 UI 표시 및 버튼 연결
- 건설 잔여시간 표시 및 시간 감소 (SLG 모드 시작된 시간 기준으로만 작업. 데이터로는 저장X)

### 2D 마우스 인터렉션 이슈 해결
PixelPerfectCamera를 사용하면 ScreenToWorldPoint의 [좌표가 틀어지는 문제](https://www.reddit.com/r/Unity2D/comments/xf68en/pixel_perfect_camera_issue/)가 있네요
가장 큰 문제는 2D 오브젝트 인터렉션을 위해서는 카메라 Viewport 옵션을 ortho 로 바꿔주어야 하는데, **PP 카메라 옵션이 Perspective projection을 오버라이드**한다는 점입니다. 
우선 코드 상에서 마우스 인터렉션 시에만 잠시 projection 타입을 ortho로 설정해서 인터렉션 가능하도록 작업했습니다.
(대부분 2D 게임에서 Ortho를 쓰는경우가 많을것같은데 이 카메라는 왜 Perespctive로 되어있는지는 궁금하네요.. 🤔)

이후 지금 제 작업처럼 맵 오브젝트에 UI를 추가해서 인터렉션해야하는 경우가 많다면 이 카메라를 써야하는지도 재고해보는것이 좋겠습니다. 아니면 코드 상에서 ortho로만 수정하든지요!

### 이후 작업 예정

- [ ] 건설 창 팝업 떠있는 경우, 다른 UI 표시되지 않도록 수정
- [ ] 에셋 팝업들 Index로 관리하도록 수정
- [ ] 맵 n회 이동 시 재생성되는 작업

- [ ] 시간 게임데이터로 빼서 재접속해도 남아있도록 수정?
- [ ] 건설가능여부 판단 후 건설, OR 건설 안되는 처리
- [ ] 코인 관련해서도 정리

----

## 협업
### 정안님께 질문
Q. @fkdl0048  SLG 건설가능 시간을 게임데이터로 빼는 작업이 지금 필요할까요?
오히려 지금하는게 더 테스트에 방해가될 수도 있겠다는 생각이 드는것같기도해서요

### 기획자분들께 질문 (사소함)
Q. 건설불가능 시 버튼 인터렉트에서의 다른 제어는 필요 없을까요? 소리가 난다든지,, 불가능하다는 팝업이 따로 뜬다든지요


----


+자기반성
바쁘고 컨디션이 안좋았어서 코드상태가 말이 아니네요.. 날잡고 한번 다시 정리하겠습니다
구조도 잘못짠게 많아서 아쉽네요 흠 ...

**Comment by jeongopo** [comment]
앗 아닙니다! 이런 처리는 금방하기도하고, 사소하니까요
빠른답변 감사합니다 ㅎㅎ

**Comment by fkdl0048** [comment]
> Q. @fkdl0048 SLG 건설가능 시간을 게임데이터로 빼는 작업이 지금 필요할까요?
오히려 지금하는게 더 테스트에 방해가될 수도 있겠다는 생각이 드는것같기도해서요

현정님 판단이 그렇다면 당연하게 뒤로 넣어서 작업하는게 맞다고 생각합니다. 해당 부분이 필요하다고 생각하고 나중에 확장성만 생각해서 미리 조절해둔다면 문제될 것 같지 않습니다..!

> 2D 마우스 인터렉션 이슈 해결

생각보다 더 복잡한 문제였네요.. 처음 알게된 오류라서 신기하네요.. 배워갑니다! 카메라가 Perespctive인지 몰랐었는데, 초기에 설정한 카메라에서 시네머신으로 옮기면서 변경된건지.. 코드에서 복잡하게 처리하는 것보다 카메라 설정을 바꾸는 것이 더 합리적일  것 같습니다.

**Comment by jeongopo** [comment]
### 0429 작업
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/35c08122-81c7-40ad-a43f-9e9457cec061)
(새로운 목재가 생성된 모습..)

- Ch1 안에 Ch1CommonData 생성 -> 스테이지 이동 카운트 값, 팩맘으로 얻을 코인 관리를 위해
- 건축 UI 에서 마우스 클릭 시 뒷 배경 클릭되는 문제 수정
- 스테이지 5번 이동 시 돌아오면 새로운 자원 남아있도록 함


### 이후 작업 예정
- [ ]  시간 게임데이터로 빼서 재접속해도 남아있도록 기능은 만들어두기
- [ ] 건설가능여부 판단 후 건설, OR 건설 안되는 처리
- [ ] 코인 관련해서도 정리
- [ ] 에셋 팝업들 Index로 관리하도록 수정


----

### 협업
- To 기획, 아트.. 건설 UI 작업이 아직 안되긴했습니다만,, 건설 버튼과 시간 단축 버튼이 별도로 존재해야 합니다
- @wooyn730  팩맘의 코인 획득 로직과 연결하려고하는데 어디에 넣으면 될까요?

**Comment by jeongopo** [comment]
## 0509 작업
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/2ada7b9d-40c8-4ed0-b3d6-8709eee5c508)
(오늘도 비주얼은 비루합니다.. 네)

- 시간 게임데이터로 빼서 작업가능
- 건설가능여부 판단 -> 건설
- 코인 보유 시 가속 처리 (코인은 직접 CommonData 에서 값 수정)

### 프로그램팀 공유사항
- 건설 시작 시 시간과 SLGStageFlow 를 GameData에 포함했습니다.
- SLG 흐름을 Enum으로 관리합니다.

### 작업예정
- [ ] UI visible 관련 자잘한 문제 해결
- [ ] Asset UI 표시가 꼬이는 문제 해결
- [ ] 그 외 자잘한 폴리싱
- [ ] 코드정리

@wooyn730  @fkdl0048 
시간 1주일정도 더 필요할것같습니다. 럭키 작업 아직 일정 잡힌게 아니라면 한 주 더 작업해도될까요?

**Comment by wooyn730** [comment]
안그래도 현정님 시간 어려우실 것 같아서 럭키는 제가 진행할 것 같습니다!

가능하면 월요일까지 끝내주시면 좋겠습니다. (정~ 안돼도 화수..)

CH1 씬에 병합 먼저 부탁드려요! 이후에는 저번에 말씀드렸던 것처럼 작업 시간 안겹치게 진행해봐요~

**Comment by jeongopo** [comment]
아하 알겠습니다! 월요일에 끝내볼게요~

**Comment by jeongopo** [comment]
##0514 작업내용

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/366a9d38-d705-4cff-b8a1-eaa4f9635508)
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/8d157100-9d1f-45ca-b6ed-c31692a0093d)
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/1f71e66b-7a17-429c-878f-eedc79aed5a6)
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/f14d1bfe-d7c6-4b1c-b139-d50ec58422b9)

- SaveData와 연결해서 SLG 플로우 완성
- UI, 맵 작업된대로 연결 (아트분들 나중에 제대로 들어갔는지 확인해주세요)
- 팩맘과 연결해서 코인으로 모드 종료하거나, 시간 기다려서 종료되도록 작업  (우선 초 값으로만 해뒀는데 나중에 혹시 테스트필요하시면 ,, 스트링 값으로 시간 조절하는 기능 작업?)


기타등등.. 끝냈습니다 실수로 메인에 그대로 작업했네요 ㅜㅜ 
다들 도와주셔서 감사하고 일정을 잘못알아서 너무 촉박하게해서 죄송합니다 (_ _ ) 다음엔 미리하겠습니다
버그있으면 알려주세요... 그럼 전 이만 좀 자고 출근하러..
