### ISSUE TITLE
[Ch1 Main] 맵 리소스 수정 작업 02

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/Grayed-Game#402]
**상세**
- #385 #396 문서를 참고하여 맵 리소스를 수정합니다. 수정 내역은 다음과 같습니다.
1. 맵 좌우 반전 작업
2. 변경된 플로우에 맞게 리소스 위치 재배치
3. 첫번째 맵 상하 폭 확장
4. 3매치 퍼즐 연출에 맞게 길 폭 수정
5. 자동차 삭제 등 전반적인 수정 작업

수정해야 하는 리소스들의 양이 방대한 관계로 2~3주 정도 잡고 작업을 진행하고자 합니다. 그동안의 빌드는 기존 임시 파일로 뽑아주시길 바랍니다...

**0414 추가**
1. 타이틀 화면 먼지 없애기
2. 그라데이션 넣을지말지 고민...
3. 맵. 최신판 기획서 보고 고치기
4. 리소스 분리해서 작은 단위로  
5. 플로야드 맵 먼지 없애기

**0421 추가**
1. 맨 왼쪽 돌무더기 방향키 / 스페이스바 추가
2. 무너진 다리 리소스 추가
3. 리소스 드릴 때 앞부분 분해해서 드리기

**중간과정 보고**
1. 캐릭터 스프라이트 원 사이즈로 되돌려서 폴더에 업로드했습니다.
4. 
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/67b04c22-5785-4683-aabf-5ec33e9aeeaf)
좌우반전 후 길 폭 수정, 마을 입구 가로폭 확장 등 공사 진행 중입니다. 추가로 정신사나웠던 조명들 삭제 후 일부분에만 넣을 예정입니다. 길가에 있는 리소스들은 더 작은 단위로 분해해서 배치할 수 있도록 하겠습니다.

**중간과정 보고2**
1. 타이틀 화면 구멍난거 메꿨습니다.
2. 그라데이션은 심사숙고 후 있는 편이 예쁜것 같아서 있는 버전으로 넣었습니다. (기존 폴더에 있습니다.)
5. 맵 고치고 리소스 분리했습니다.
6. 라플리가 떨어진 곳...좀더 웜홀 아래에 리소스가 쌓여있는 느낌이 들면 좋을 것 같아서 살짝 수정했습니다.
![floyard_new_preview](https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/fd9f01d3-6ed4-44d0-a522-afe2a64320d1)

**최종**
![FloyardPreview](https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/f6998486-4dc0-41b8-a405-0c69440df411)

[폴더](https://drive.google.com/drive/folders/1VjB41mGWXgvx3sCflsg0CmwQcfSxdQ3Y?usp=drive_link)에 투명화 리소스 넣어뒀습니다.

**Comment by fkdl0048** [comment]
추가로 라플리 수정된 버전으로 주셔야 합니다!

**Comment by fkdl0048** [comment]
중간과정을 보고 해주셔서 작업 흐름을 이해하기 좋네요!

**Comment by royalbluesm** [comment]
0427 최종본 업로드 완료
