### ISSUE TITLE
[Title] 리소스 리사이징 작업

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/Grayed-Game#403]
**상세**
리소스 원래 사이즈로 드리겠습니다. (빨리)
다만 제가 현재 작업중인 타이틀 로고가 있어 그것까지 함께 적용하면 좋을 것 같아 수요일 오후까지 드리는 걸로 하겠습니다.

**파일**
480x270사이즈 파일로 되돌렸습니다. 
[폴더](https://drive.google.com/drive/folders/1t-fEnjDGhnkUUhS2kaeBrgVKMBij9LRa?usp=drive_link) 확인해주세요~

**Comment by wooyn730** [comment]
파일 잘 확인했습니다 감사합니다

질문이랑 요청 몇개 있어서 남깁니다!

![320576536-232038a7-7ca2-4697-bf60-22a503376216](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/4cd6fad4-83c8-440e-9f02-3434fad2fdbe)
_[타이틀 로고 및 네이밍 관련 이슈](https://github.com/GG-Studio-990001/Grayed-Game/issues/407)의 이미지_

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/69cc184b-1bb1-4f77-afed-943368f18153)
_현재 적용한 이미지 (캡쳐해서 화질구지긴 함)_

<br>

### 질문 (1)
이슈 이미지의 배경, 라플리는 구 버전인게 맞나요?

### 질문 (2)
주신 'Press Any Key'는 이슈 이미지보다 두꺼운데 의도하신거 맞나요?

1+2는 제가 Art 폴더에 있는거 적용했으니 맞다고 생각하지만
달라서 헷갈리기도 하고, 기분탓인지 이슈 이미지가 더 이쁜 것 같아서 말씀 드립니다 ^_^;
_역시 아트의 배치인가?_

### 요청 (1)
'Press Any Key' 대신 'Press space bar to start' 또는 'Press space bar'로 주실 수 있나요? (대소문자 상관 없이)

지금 사용하고 있는 입력 시스템에서 아무키나 입력을 받는 기능을 제공해주지 않아서 구현이 조금 복잡하더라고요
그래서 무난하게 스페이스 바로 해도 되지 않을까 싶습니다.

하지만 안되는 건 물론 아니기 때문에
Any Key가 더 이뻐보인다거나.. 등의 이유가 있다면 다시 고려해보겠습니다!

**Comment by royalbluesm** [comment]
질문 1) 이슈 이미지의 배경과 라플리 모두 신버전입니다 구버전으로 보이나요...?
질문 2) 의도한것 맞습니다만 지금 보니 얇은 버전이 더 예뻐보여서 (오락가락해서 죄송합니다) 새 파일에 얇은 버전으로 다시 넣었습니다.
요청 1) 스페이스바로 변경한 이미지 넣어드렸습니다~

**Comment by wooyn730** [comment]
@royalbluesm 

질문 2, 요청 1 확인했습니다! 감사합니다
저도 얇은 버전이 더 이뻐보여요!

해당 이슈 이미지 저는 완전 구버전으로 보이는데요..? 
![ㅂㄱ](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/e743bb52-2914-4657-85ed-7c7832756a0b)

**Comment by royalbluesm** [comment]
아 이슈 이미지 말씀하신 거였군요!! 이슈 이미지는 구버전인게 맞습니다 art폴더에 있는 파일들이 진짜예용~

**Comment by wooyn730** [comment]
아 그쳐? 확인 감사합니다~~

근데 민지님이 배치해준 이미지 보니까 개인적으로 예전 배경이 어두워서 예뻐보여요
하단의 글씨도 흰색이고 먼지에 빛도 추가돼서 확실히 대비되는 느낌.. _(주관적 견해였읍니다)_

**Comment by wooyn730** [comment]
배경 이미지 새로 올라온 거 적용하는데 가장 하단이 비어있어서 새로 주시면 좋을 것 같습니다
그리고 점 두개는 의도하신 거 맞나요??

_(제가 원래 이런 거 신경써서... ㅈㅅㅈㅅ)_

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/575af58c-52a1-40df-b0c3-ea6310d83e9b)
