### ISSUE TITLE
[CH1] 튜토리얼 캔디 크러시 사가 구체화

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/Grayed-Game#406]
# [CH1] 튜토리얼 캔디 크러시 사가 구체화

- #375 

현재 구현되어 있는 기능에서 아트 적용 및 시스템 구체화를 진행합니다.

## 현재 구현 상황

- 몸으로 밀어서 움직이고, 3개를 만들면 블럭이 파괴된다.
- 모든 블럭이 파괴되면 해당 시스템이 클리어로 이벤트를 준다.

## 구현 예정

- 기획에서 요구하는 추가적인 사항

## ETC

- 캔디 크러시 사가로 네이밍을 확정?
- 작업은 간단하지만, 아마 메인에서 다른 문제되는 기능들이 많을 것 같아서 다른 플밍과 협업이 주를 이룰 것 같음

## 04/14

작업 추가

- 어드레서블 데이터 확인
- setting x 키 바인딩

*따로 작업 빼서 해야할 듯*

## 04/27

- [x] 리소스 적용 작업 (타일맵, 블럭, 등)
- [x] 로직 수정 (테스트 코드 및 기본 로직 수정)
- [x] 타일맵으로 수정
- [x] 룸 리셋
- [x] 룸 이동 연결

## 05/01

- [x] 1~3 맵 수정
- [x] 퍼즐 벽 막기
- [x] 클리어 조건 설정
- [x] 밀기 경합 (같이 밀기) 막기
- [x] 애니메이션 수정 Idle, 이펙트
- [x] 사운드 적용

## 05/03

- [ ] ~~라플리 리소스 수정~~
  - 수정 필요
- [x] 라플리 애니메이션 Idle 삭제
- [x] 라플리 레이어 수정
- [x] 스테이지 간격 조절
- [x] 젤리 움직임 간격값 조정
- [x] 2~3 맵 수정 적용

## 회의 수정 사항

- [x] 1, 3 맵 꺾어서
- [x] 카메라 배율 70

## 24-06-03

*빌드본 기준 수정요청 사항*

- [ ] 3Match 클리어 저장
- [ ] 퍼즐 움직임 속도 올리기 (조절)
- [ ] 테스트 코드 고치기
- [ ] 코드 정리 (Error 수정, 씬 삭제)

**Comment by fkdl0048** [comment]
이번 마일스톤은 일요일에 작업하기에 무리가 있어서 다음 주에 작업하겠습니다.. (시험이 내일이라)

**Comment by fkdl0048** [comment]
# 04/28

타일맵으로 변경되면서 실제 Position 값이랑 TilemapCellPosition값이 일치하지 않는 문제가 생겼는데, 여차여차 해결..
타일맵 크기에 맞게 수정하고 리셋, 연결 작업 등등을 작업

자새한 내용은 PR참고

@Sumindd 수민님 각 퍼즐 맵의 클리어 조건이 뭔가요? 현재는 모든 블럭 뿌셨을 경우인데, 수정 방향이 궁금합니다.

**Comment by Sumindd** [comment]
다음 맵으로 넘어가는 것이 클리어 조건입니다!

**Comment by fkdl0048** [comment]
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/84510455/16c367b7-6669-4dc2-80f8-1d58cd399bb3)

추가로 한 스테이지에서 여러 맵의 이동인가요? 다른 맵과 같이 스테이지 이동인가요?

**Comment by fkdl0048** [comment]
[빌드본](https://drive.google.com/file/d/1dDhh_q8ooXtYB8NnfZnxXJ8vQPQcfNFw/view?usp=drive_link)

현재 3매치 퍼즐 빌드본입니다.

수정 되어야 할 부분이랑 추가적인 설정, 기획 알려주시면 됩니다.

- 모든 퍼즐 스프라이트마다 애니메이션을 넣을 것인지?
- 터지는 이펙트?
- 사운드
- 2, 3 맵 구조

**Comment by Sumindd** [comment]
2,3 맵 구조를 짜고 있는데 혹시 같은 젤리 4개 혹은 5개를 한 줄로 만들었을 때도 터지게 해주실 수 있을까요?

**Comment by fkdl0048** [comment]
가능합니다~!

**Comment by fkdl0048** [comment]
@Sumindd 현재 기획서 상에 있는 퍼즐은 그대로 적용했습니다.

해보니 3번째 맵은 클리어가 가능하긴 하더라구요

**Comment by fkdl0048** [comment]
[빌드본](https://drive.google.com/file/d/1dLuzB_xsEwHUgzzB9rDK6LmI5hcFYYU_/view?usp=drive_link)

@Songkihwa 사운드 적용 확인해주시고 추가로 제작할 사운드 넘겨주세요~ (혹시 적용 안된 사운드 있으면 멘션주세요)
@Sumindd 2~3 한번 플레이 해보시면서 밸런스 잡으시면 될 것 같습니다.
@gomgom172 애니메이션 확인해주세요~ Idle 모두 동일한 프레임으로 잡으니까 이상해서 임의로 수정했습니다.

**Comment by gomgom172** [comment]
빌드본 확인했습니다! 사운드, 배치 한 번에 정리해서 보니 확실히 확인하기 편하네요. 감사합니다!

![0501_3matchresourceidle](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/8c853d72-79f0-43fd-985d-6ddc4ff69752)






![0501_3matchresourceidle-sheet-export](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/b93bf30e-47b8-4794-baef-26a03015c3ad)

(왼쪽 A, 오른쪽 B라고 가정)

그림 A, B 순으로 두었을 때
A (11프레임) → B (1프레임) → A (9프레임) → B (1프레임) → A (1프레임) → B (1프레임)
이렇게 한 사이클입니다.
(속도는 unity에서 임의로 조정해주시면 좋을 것 같습니다.
참고를 위해 적어놓았을 뿐 정확히 일치할 필요는 없습니다!
쫑긋→ 쫑긋쫑긋 정도만 보이면 충분합니다.)

혹시 전달이 잘 되지 않는 부분이 있으시면 내일 말씀드리겠습니다…!


다만 현재 빌드본에 적용된 애니메이션도 부담스럽지 않고 보기 편해서 좋아 보이네요.
일괄적으로 쫑긋거리지 않도록 젤리 타이밍을 각각 조정해 주신 부분은 너무 좋은 것 같습니다.




++

차후에 수정하실 부분일 수도 있지만 눈에 띄는 부분 일단 적어둡니다!

![Untitled](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/d7499efc-5cd6-4ba0-bb2b-347454188b4e)


오브젝트 해상도 깨짐

![Untitled-3](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/2f2bf1a1-bb7a-49d3-94f0-18d2452ea9b8)


타일맵 연결 부분 깨짐

++

![Untitled-2](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/dce698f6-65c1-4ea4-b425-29fab1cec593)


캐릭터 움직일 때 머리 위 깨짐

**Comment by fkdl0048** [comment]
> 쫑긋쫑긋

수정했습니다.

> 오브젝트 해상도 깨짐

확인하고 수정했습니다.

> 타일맵 연결 부분 깨짐

수정 했습니다.

> 캐릭터 움직일 때 머리 위 깨짐

이거 맵이랑 리소스 다 적용할 때 하겠습니다~

**Comment by wooyn730** [comment]
역시 구현된 것으로 보는 게 가장 좋은 것 같네요!
고생하셨습니다~
아래는 플레이하면서 발견한 것과 생각한 것입니다

https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/e848a2e2-ab20-4483-8d61-a8b9d5666c34

3라운드에서 2라운드로 넘어가면 바로 돌아와버리네요

<br>

https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/045eb3b7-fdb1-4444-9e24-7fd36313d114

마쉬멜로우 터트린 후에 젤리 터트리려고 움직이니 주변에 있는 초콜릿이 의도치않게 움직이는 모습입니다...
젤리들은 더 가볍게 밀 수 있고 의도치 않은 방향의 젤리들은 인식이 안 되면 좋겠네요

<br>

_그 외 생각_

라플리가 젤리(3매치 리소스) 위에 그려지는 게 좋을 것 같습니다.

그리고 라플리가 ↑ 방향으로 이동하다가(뒷모습) 방향키에서 손을 떼면 바로 정면(앞모습)으로 돌아오는데
다른 방향키 입력하기 전까지 계속 뒷모습을 보여주는 게 자연스러울 것 같습니다
(3 매치에서는 방향키 눌렀다 뗐다를 반복하는데 앞모습 뒷모습이 계속 반복되어 조금 무서운 느낌)

라플리 Idle 애니메이션도 굳이 없어도 되지 않을까 싶습니다.
(주변을 두리번거리는 듯한 모습 / 민지님 요청이었는지는 모르겠지만..)
라플리는 자아가 없으니 가장 수동적인 모션이 어울린다고 생각합니다.

**Comment by fkdl0048** [comment]
24-05-15 추가 작업

- [ ] 스테이지 1, 3  Mover 위치 변경 (맵에 걸리게)
- [ ] 스테이지 3 럭키 OnActive 때 터지게
