### ISSUE TITLE
[Title] 타이틀 로고 및 네이밍 관련

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/Grayed-Game#407]
우선 다 끝난 네이밍 이슈에 재점화를 해서 죄송하다는 말씀 박고 시작합니다.

몇개월간의 고행, 적지 않은 팀원분들의 동의를 얻어 확정된 게임 이름이라는 것은 알고 있으나... 타이틀에서, 또 게임 디자인적으로 가장 중요하다 할 수 있는 로고 타입 제작 도중에 진짜 마지막으로 한번만 더 여쭙고 싶어 이슈를 열게 되었습니다.

본론부터 말씀드리면 저는 제가 냈던 아이디어인 (제가 낸 아이디어여서는 아닙니다 정말로) GRAYED로 확정지으면 어떨까 하는 입장입니다.

아래는 타입을 결정하기까지 거쳤던 여러 고뇌의 과정들입니다. 다른 디자인 요소 모두 중요하지만, 로고 타입만큼은 게임의 얼굴이 되는 심볼이라고 생각하여 정말 많이 고민했습니다.

### **로고 타입 후보들**

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/e47d96b9-cd7f-4c26-aa6b-564a178cc576)
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/9e2fb4f4-1363-4882-84f6-75cac4d8a0ab)
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/0a2dd14b-8fee-4b6b-8e26-7d509ad3238c)

많은 재미있고 독창적인 폰트들을 발견할 수 있었습니다. 여러 폰트들의 적용과 리모델링 끝에,

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/cb2663a6-e607-4cd3-bf38-6099122e8f54)

위 서체 (Square Dance라는 서체를 기반으로 보기 좋도록 약간의 변형을 가한 모습)가 가시성, 응용성, 이후 상품화 가능성까지 고려했을 때 가장 최적의 형태라고 판단했습니다. 이 서체로 디자인을 픽스하여, 타이틀 화면에 적용해 보았습니다. 사실 타이틀화면 뿐 아니라 여러가지 목업을 해보는 것이 가장 정확하지만, 그러기엔 시간과 리소스가 너무 많이 들 거라 판단해 판단 재료가 이것밖에 없는 점 양해 부탁드립니다.

현재 작업 중인 로고 타입을 적용한 타이틀 화면입니다.

### **로고 타입 적용 화면**

![TitlePreviewfinal1](https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/de7d761a-2768-4702-866e-182245fc8ce2)
![TitlePreviewfinal2](https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/232038a7-7ca2-4697-bf60-22a503376216)

(앞 리소스들에 타입이 가려지는 건 무시하고 봐주세요. 지나치게 가려지는 오브젝트의 경우 약간의 수정을 거칠 예정입니다.)

### **왜 GRAYED여야만 하는가?**

원본 서체가 워낙 깔끔하고 가시성이 좋기 때문에 두 경우 다 나쁜 디자인처럼은 보이지 않습니다. 예쁘게 뽑혔습니다. 하지만 저는... 깔끔하게 GRAYED만이 적용된 화면을 보고, '너무 예쁘다...' 라고 생각해버렸습니다...

무엇이 grayed 해버린 걸까? grayed라는 것의 의미는 무엇일까? 상상력을 자극하는 형용사 하나... 이 게임 뭘까, 하는 궁금증이 들게 한다고 생각합니다.

디자이너의 관점으로 봤을 때도 좌우 균형이 잡힌 대칭 구도에서 한 글자의 단어만 대문에 박혀 있는 것이 더욱 안정적이고 깔끔하다는 인상을 받았습니다. 아트북이나 굿즈에 실렸을 때도 강하고 단단한 인상을 줄 것 같고, 어느 시상식의 작품명에 박혀 있어도 소위 '간지'라는 것이 날 것도 같고...

7명의 팀원분들이 만장일치로 선택해 주신 소중한 이름인데, 내가 감히 바꾸자는 의견을 내어도 괜찮을까? 하고 고민도 많이 했습니다. 하지만 게임의 얼굴이 되는 타이틀 화면과 로고를 작업하면서 좀 더 예쁘게 만들어 보고 싶다는 욕심이 끊이지 않았습니다. 그래서 송구하게도 마지막으로 의견을 여쭙고자 합니다.

게임 이름을 GRAYED로 픽스하는 건 어떨까요?

만약 이번에도 GRAYED GAME이 더 낫다는 의견이 많다면, 다시는 네이밍에 관해 입도 뻥긋하지 않겠습니다.
허나 저는 네이밍은 기획이면서도 디자인이라고 생각합니다. 디자이너의 욕심이라 생각해 주시고 의견 한 번만 주고 가시면 감사드리겠습니다. 읽어주셔서 감사합니다!! 

_해당 사안은 마일스톤에 등록된 할 일이 아닌, 제가 따로 진행하고 있던 프로젝트(학교 과제 겸 로고와 상품화 패키지를 디자인하고 있었습니다.)이기 때문에 마일스톤에는 넣지 않겠습니다._

**Comment by Songkihwa** [comment]
민지님의 심도있는 고민이 글에서 다 느껴지네요...
타이틀 화면으로 보면 확실히 Game이 들어간게 너무 꽉차서 별로인 것 같기도 하네요 ,,, 서체가 뚱뚱해서 그런 것 같기도 하고..

제 개인적인 의견으로는 수많은 잊혀진 게임들이 존재하는 컨셉이다 보니 이름에 Game이 들어갔으면.. 하는 생각이 있긴 합니다ㅎㅎ... 
하지만 저는 Grayed로 바꿔도 좋습니다!! 다른 분들 의견 들어봐야할 것 같아요 Grayed도 간결하고 타이틀 화면에도 이쁜 것 같구 좋습니닷><

**Comment by fkdl0048** [comment]
이런 부분이 논의되고, 이슈화 되는 것은 너무 좋습니다. 팀원분들께도 꼭 말씀드리고 싶은 부분이 게임을 만드는 과정에서 혼자 고민하지 말고 이렇게 의견을 나눠줬으면 합니다..! 또한 자신이 생각하는 더 좋은 방향을 이렇게 어필해주시는 것도 정말 감사합니다 ㅠㅠ..

디자인과 기획은 강하게 결합되어 있는 부분이라 어디 손을 들어주기가 어렵네요.. 아트적인 디자인이냐, 기획적인 디자인이냐의 문제로 이어질 것 같은데, 저도 Grayed와 같이 간결한, 궁금한 디자인도 좋습니다.

다만, 이 게임이 관통하는 주제가 전체적으로 `게임`을 담고 있기에 `Grayed Game`에서 말하는 게임이라는 의미보다 좀 더 관념적인 게임을 말한다고 생각합니다. Grayed Game이 뜻하는 바를 게임 플레이 이후에 여러 유저들이 자율적으로 해석이 가능한 여지가 좀 더 있을 수 있다고 생각합니다..

다만, 이 게임이 어디 홈페이지나 홍보를 한다고 했을 때, Grayed Game보다는 Grayed가 좀 더 간결하고 눈에 들어올 것 같긴 합니다.

**Comment by gomgom172** [comment]
로고 폰트 너무 예쁘고 잘 어울리네요!

저는 그래픽적 시선으로는 GRAYED가 단연 돋보인다고 생각합니다. 볼드한 서체에 짧고 강렬한 단어가 주는 임팩트가 무척 매력적이에요. 타이틀 화면 그래픽과 어울려 눈길을 사로잡는 힘 그 자체로 완성도가 확 올라가 보인다고 생각합니다.

다만 제 시선은 기획보다는 아트 시선에 훨씬 가깝겠기도 하고, 게임 주제를 한 번에 파악하려면 기존 타이틀을 사용하는 게 적절하겠다는 생각이네요… 다른 분들 의견을 모두 들어봐야 할 것 같습니다.

게임 메인 타이틀은 GRAYED로 두되 부제를 붙인다거나, 게임 내에서 소제목으로 표현해 보여준다거나(CH 1. Grayed Game… 같은 식.) 해서 타협점을 찾는 것도 방법이 될 수 있지 않을까 하는 의견입니다.

**Comment by wooyn730** [comment]
우선 이렇게 욕심 내주시고, 아이디어를 적극 어필하는 모습이 보기 좋습니다 ><
게임에 대한 애정이 있으니 가능한 일이라고 생각합니다!

추가된 폰트 후보들(3번째 이미지)이 전보다 훨씬 귀엽네요!
적용화면도 보니까 훨씬 완성도가 높아보입니다.
폰트가 뚱뚱해서 그런지 `GRAYED`로 적용된 게 조금 더 좋아보이기도 하네요.

게임 이름에 대해 생각해봤을 때는 아직은 역시 `Grayed Game` 쪽에 마음이 기웁니다.
이유는 기화님 정안님과 동일하고, (이름 결정 때도 어필했지만) 줄이면 GG가 되는 점이 매력적으로 느껴지기 때문입니다.
하지만 디자인적으로 `GRAYED`나, 부르거나 언급할 때 깔끔하고 간결하다는 점은 인정하므로
게임 이름 변경에 대해선 마음은 조금 열려있습니다 ^_^

**Comment by jeongopo** [comment]
와 적용된 로고 너무 예쁩니다!
다른 분들과 비슷한 의견인 것 같은데 타이틀 로고에 한해서 Game 을 생략하는것에는 찬성하지만, 게임 이름 자체에는 Game 이 들어가는게 좋을것같습니다~

**Comment by roweclaw** [comment]
볼드하면서도 도트 느낌이 나는 폰트가 정말 잘 어울립니다!
타이틀 화면 디자인 속  `GRAYED`라는 한 단어가 주는 무게와 대칭구도의 깔끔함이 마음에 들어서 혹하긴 하네요.....

그래서 정말 많은 고민과 생각을 거치게 되었는데, 저의 의견은 `GRAYED GAME`이면 더 좋을 거 같아요. 이유는 다음과 같습니다.

1. 게임의 주제로서도 게임 전체를 관통하는 단어로도 game은 정말 정말 중요하기 때문에, 게임 이름에서부터 이 점을 꼭 어필해야 한다고 생각합니다. game을 생략해버린다면 직관적인 네이밍이 주는 이점을 포기해야 하니까요..
2. grayed라는 형용사가 궁금증이 들게 한다는 점은 동의하지만 그 뒤에 game이 붙었을 때 더 빛을 발하는 것 같아요. 게임은 왜 grayed 해버린 걸까?, grayed 해버린 게임은 어떻게 되는 걸까?처럼 '게임'에 포커스를 둔 채 뻗어나갈 수 있는 상상력을 제공하는 이름을 붙이고 싶습니다.

따라서 우선 `GRAYED GAME`에 한 표를 던지고, 추후 모든 팀원분들의 의견을 종합했을 때 나오는 결과를 따르겠습니다!!

**Comment by Sumindd** [comment]
저도 수빈님과 같은 의견이라 자세한 이유는 생략하겠습니다.
디자인만 봤을 때는 GRAYED가 깔끔하고 예쁘지만 게임을 관통하는 이름은 역시 GRAYED GAME인 것 같습니다.. 
저도 GRAYED GAME에 한 표 던지고, 다른 팀원분들의 의견 종합해서 나온 결과에 따르겠습니다!

**Comment by royalbluesm** [comment]
의견 감사합니다! 회의때 의견 취합하는 걸로 하고 이슈 닫아두겠습니다~
