### ISSUE TITLE
[Char] R2-MON, BAD라플리 캐릭터 구체화 2차

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#417]
아래 이슈를 바탕으로 이어서 작업합니다.
- #397
- #419 

## 240420

[[240420] R2-MON, 럭키 캐릭터 구체화 2차](https://drive.google.com/file/d/1i7P1LfC8UfYQ-Jtf8zyyejerkKHVnUew/view?usp=sharing) 문서를 작성했습니다.

> 목차별 유의사항

### 장르 제작공 'R2-MON'
기존 설정에서 변경된 부분을 `하늘색 칸`으로 표시하였습니다.

### 튜토리얼 설명 및 악역 캐릭터 '럭키'
기존의 BAD 라플리가 `원래 라플리의 본체로서 유저를 갈구한다`는 설정을 제외했고,
이후 악역이 되었을 때 라플리를 모방한 외형으로 변한다는 점만 가져왔습니다.
그 외에는 '럭키'만의 새로운 설정으로 구체화했습니다.

### 전체 사건 플로우 변경 (임시)
두 캐릭터의 구체화에 따라 이에 맞게 전체 사건 플로우를 임시로 변경했습니다.

### 캐릭터의 챕터별 변화 과정
두 캐릭터의 역할과 메타성이 챕터가 진행됨에 따라 변화해가는 과정을 표로 정리했습니다.
전체 사건 플로우가 추후 확정됨에 따라 바뀔 가능성이 있습니다.

> 위 문서에서 고민되는 점
1. R2-MON과 럭키는 서로 희미하게 알지만 싫어하는 존재로 단순히 정해두었는데, 더 깊은 연관성이 필요할지 고민입니다. 
2. 악역은 주인공의 목표를 방해하는 존재로서 엔딩과 연관짓기 위해, '럭키'가 고의로 웜홀을 막았다는 설정을 부여하였습니다. (참고 : [시나리오 구체화 기초작업](https://drive.google.com/file/d/1VvVcdUBibp3_ULE6qnnbE1rGRjzJyrUy/view?usp=sharing) 문서에서 `웜홀이 막힌 이유 (택1)` 중의 2번)
따라서 '럭키'를 최종적으로 물리치는 것이 웜홀을 뚫어내게 되는 계기 등으로 연결할 생각인데 엔딩의 형태와 함께 조금 더 구체화되면 좋을 것 같습니다.
3. 아트와 사운드 설정을 적어두긴 했지만 보시기에 다른 설정이 더 나을 거 같다면 변경 가능하니 말씀 부탁드립니다!

> 별도로 고민되는 점
1. 확실한 대립관계가 구체적으로 형성됨에 따라 이전의 대립적 관계였던 리소스 숭배집단을 시나리오에서 제외하게 될 것 같습니다. 그래서 게임 심마니 직업도 살짝 애매해진 것 같지만, 그래도 마을 주민들이 활용할 자원을 파밍한다고 생각하면 그대로 가져가도 상관 없어 보입니다.
2. 리소스홀과 웜홀의 용어를 변경하는 것이 필요해보입니다. _(전에 우연님이 말씀하셨던 망각통로, 기억통로가 저는 좋았어요!)_

**Comment by roweclaw** [comment]
240420 작업 현황 업데이트 했습니다. (시험기간이어서 예상보다 늦어지게 되었습니다. 죄송합니다...ㅠㅠ)

**Comment by Sumindd** [comment]
잘 읽었습니다. 깔끔하게 정리해주셔서 감사합니다! 제가 읽어봤을 때에는 딱히 빠진 부분 없는 것 같습니다.
그리고 전체 사건 플로우 리뉴얼 덕분에 앞으로의 장르 정하는데 참고할 수 있을 것 같아 좋습니다. 
럭키랑 R2-Mon이 개성있는 역할을 맡게 된 것 같아 앞으로 스토리가 기대됩니다!

**Comment by fkdl0048** [comment]
기존 문서와 형식이 같아서 잘 읽었습니다. 마지막의 챕터별 캐릭터 변화과정이 가장 이해하기 좋은 표의 모습이라 다른 분들이 보시기에 가장 쉽게 이해가 될 것 같습니다..! 감사합니

**Comment by wooyn730** [comment]
### 읽어보고 느낀 점

바뀐 거 색상으로 따로 표시해주시는거 좋아요!!

R2-Mon은 바뀐 게 많아서 '기존 설정에서 수정한다' 보다는 '새로 짜되 괜찮은 부분은 가져온다' 정도가 괜찮지 않을까 해요

(그렇게 생각한 이유: 대표적 성격(특히 "기계이므로 감정이 없고"), 도덕관은 지금 설정이랑 다르지 않나? 싶고 종교관도 아직 활용 여부를 모르니까..)

럭키 정보에 7 많이 들어가있는거랑 별명 수다댕이 귀여워요 ㅋㅋㅋㅋ

럭키의 성장배경과 동기를 읽어보니 수빈님이 짜주실 스크립트도 꽤 기대되네요 ><
잘 읽었습니다! 잘 정리돼서 재밌게 읽었어요



###

**Comment by wooyn730** [comment]
### 읽어보고 느낀 점

바뀐 거 색상으로 따로 표시해주시는거 좋아요!!

R2-Mon은 바뀐 게 많아서 '기존 설정에서 수정한다' 보다는 '새로 짜되 괜찮은 부분은 가져온다' 정도가 괜찮지 않을까 해요

(그렇게 생각한 이유: 대표적 성격(특히 "기계이므로 감정이 없고"), 도덕관은 지금 설정이랑 다르지 않나? 싶고 종교관도 아직 활용 여부를 모르니까..)

_그리고 개인적으로 R2-Mon... 로봇치고(?) 귀엽게 생겨서 호감이 갈만한 외형이었으면....._

럭키 정보에 7 많이 들어가있는거랑 별명 수다댕이 귀여워요 ㅋㅋㅋㅋ

럭키의 성장배경과 동기를 읽어보니 수빈님이 짜주실 스크립트도 꽤 기대되네요 ><

잘 읽었습니다! 잘 정리돼서 재밌게 읽었어요

### 문서 고민에 대한 생각

1. 저는 지금은 이 정도의 연결고리가 딱 괜찮다고 생각해요! 
2. 웜홀과 럭키를 연결시키는 것은 좋은데 저는 기존에는 설명팩의 형태를 띄다가 역접속 이후 UI보다 높은 단계에 존재한다고 생각했어서.. 웜홀을 어떻게 막게되는지 궁금하네요

### 별도 고민에 대한 생각

1. 저도 리소스 숭배집단과 심마니 집단의 필요성을 못느꼈습니다. 그래서 바뀐 문서에 알투몬에 모자랑 땀수건을 빼고 사이렌을 다는 등 외형적으로 바뀐 게 좋았어요!! 다른 캐릭터들도 밀짚모자를 쓴다기 보다는 다양한 개성을 드러냈으면 좋겠습니다. (파머 정도는 괜찮을지도..)
2. 용어 변경 좋아요~ 근데 주민들 설정에 따라 달라지지 않을까 해요 _(주민들이 잊혀져서 이 마을로 온 것을 알고 있는가? 아니라면 '망각통로' 불가)_ 초반 챕터에는 '리소스홀' 같은 용어를 쓰다가 챕터 4~5 때 럭키가 통로들의 정확한 정체(?)를 밝히는 것도 좋을 것 같아요.

**Comment by Songkihwa** [comment]
상세한 캐릭터 설명과 챕터별 변화 과정을 잘 적어주셔서 이해가 잘 됐습니다 !! 작업하시느라 고생하셨습니다 :) 사운드 적어주신대로 진행해도 좋을 것 같아요ㅎㅎ

**Comment by gomgom172** [comment]
한눈에 이해할 수 있게 정리되어 있어서 무척 재미있게 읽었네요! 좋은 문서 감사합니다. 두 캐릭터가 매력있게 정리되어서 앞으로가 기대되고 궁금한 마음입니다.

+ “무우엇으흘~ 도오와~ 드륄~ 끼야요오오~” 너무 귀여워요…. 작업 너무 고생 많으셨습니다. 👍

**Comment by royalbluesm** [comment]
강아지 모티브인게 개인적으로 맘에들어요 ~~ 유저에게 쓸데없는 도움을 주려고 애쓴다는 점에서는 언더테일의 알피스가, 기능 정지 기믹은 문예부의 모니카가 생각나는군요..
