### ISSUE TITLE
[CH1] Scene 1 오브젝트, 3매치 퍼즐 맵 02

### ISSUE THREAD

**Issue by gomgom172** [GG-Studio-990001/Grayed-Game#418]
- #398 에서 이어서 작업 진행합니다.

[240421 리소스 구글 드라이브 링크](https://drive.google.com/drive/folders/11qUP7Kjl6nDCfjsWeqWq7fq_YJr7cV2o?usp=share_link)

Scene 1 리소스 A-D
3매치 퍼즐 맵과 리소스 작업 진행합니다.

**4/20(토)까지(가능하면 미리) 전달드릴 파일**

- 3매치 퍼즐 맵
- 3매치 퍼즐 리소스(젤리) 최종본

(업로드가 늦어져 죄송합니다.)

# 240421 진행 상황

### 진행된 부분

![0421_3matchresource-export](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/12667e9d-0f14-44a0-90d1-5a7cfbcaa460)

- B급 게임 느낌을 살리기 위해 추가안을 작업해 보았습니다.
적당히 귀여우면서 이미테이션 게임이라는 느낌을 주고 싶어 동물화 아이디어를 섞어보았습니다. 플랫한 느낌이 오히려 괜찮아 보이기도 하는데, 의견 받아보고 싶습니다. (물고기 사탕 같은 느낌으로 생각했는데, 모아놓고 보니 막대사탕이 빠지면 캔크사 같은 느낌이 덜하기는 하네요….)

첫 번째 줄은 완성본이므로 바로 리소스로 사용되어도 무관할 것 같습니다. 구글 드라이브 파일 업데이트해두었습니다.

---

![0421](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/ae445df1-7349-4ff9-acba-320a1b8943a2)

![0421-2](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/80c3b262-7dc9-49d2-95bb-ee292ac468bb)

![0421-3](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/6c5846b6-47d8-4efa-94c8-4fb09314c557)

- 3매치 퍼즐 타일맵을 작업 중입니다.
한 타일 32*32 사이즈입니다. 퀄리티 자체는 비슷하게, (3색 단색) 자연스러움만 손보는 쪽으로 작업하게 될 것 같습니다. 현재 파츠로 3매치 맵 제작은 모두 가능합니다.

맵 파일은 아직 진행중이므로 따로 업로드하지 않았습니다. 필요시 말씀 주시면 바로 첨부하겠습니다!

---

### 진행해야 할 부분
**작업 진행 예정**

- Scene 1 리소스 A-D 연구 및 구체화

![0421_scene1 6resource-export](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/0958cf6b-00ff-4a2d-8366-4424b37d3dd3)

![0421scene1 6esource_e g](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/8d48b08a-47ab-4475-b2cb-2140b81c761c)

아웃라인 컬러 변경 버전 정도만 우선 올려두었습니다. 아직 방향성을 잡지 못해서, (회의 당시에도 너무 튀는 것 같다/오브젝트라면 튀어도 되지 않나로 의견이 갈렸던 것 같습니다…) 급하지 않다면 이 부분은 맵 리메이크가 끝나면 마저 작업하고 싶습니다. ^_ㅠ

각방향 의견 환영합니다!

**Comment by gomgom172** [comment]
240421 업데이트되었습니다.

**Comment by fkdl0048** [comment]
B급 감성 너무 좋은데요..? 개인적으로 이런 부분은 아트분들이 자유롭게 만지셔도 될 것 같다는 생각입니다. C급까지 내려가도 좋아요. '평범한 게임이 잊혀졌다'도 좋지만, 지향하는 것은 병맛요소가 들어간, 잊혀질 수 밖에 없는 게임들이면 좋을 것 같습니다.

회의 중에 이야기가 나온 럭키의 연장선으로 이 게임은 3매치 퍼즐이지만 잘못된 레벨 디자인(마지막 맵은 깰 수 없음)으로 세상에서 잊혀진 게임이다. 라고 풀이해도 될 것 같아요. 시나리오 상 럭키의 역할이 필요하고 이를 스토리에 연결 시켜서 선형적 구조를 가져가기에도 좋아보이네요

**Comment by Sumindd** [comment]
너무 귀여워요! 저는 2번째, 3번째 줄 둘 중에서 고르면 충분할 것 같습니다! 아니면 물고기+막대사탕까지 해서 4종류로 해도 괜찮을 것 같습니다. 이젠 단계도 3단계까지 있으니 제가 열심히 짜보겠습니다!
씬 1.6 리소스는 저도 맵 나온 이후에 마저 작업하는 것이 좋을 것 같다고 생각합니다.

**Comment by wooyn730** [comment]
### 3 매치 퍼즐

B급 코멘트 남겼던게 이렇게 작업이 되다니!!!
보자마자 넘 해피했네요 ^____^ 너무 좋아요
동물이랑 결합한 것도 너무 귀엽구요..
(물고기 빼고 다 고양이랑 결합한 거 같은데 맞나요?)

일단 3가지 중에는 3안이 가장 마음에 들어요! 특히 젤리랑 초콜릿!
왜 두개가 제일 좋은지 곰곰이 생각해봤는데 부피감이 있는 게 좋은 것 같아요
(세개가 만나면 터져야하기도 하니까?)
그리고 레드-브라운 톤이 잘 어울리는 것 같은 느낌...
![캰디](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/8f0d9abc-8be7-4730-8b98-702a425f70c3)
그래서 아이디어를 조금 내보면 이런 동그란 사탕이랑 마쉬멜로우는 어떨까 함니다
(물론 저스트 마이 의견 🙃..)

그리고 수민님 말대로 4종류도 좋을 것 같아요!
3개로 맵이 느니까 사탕종류도 4개면 더 다양한 배치나 난이도 높은 배치가 가능할 것 같습니다~~

타일맵 완성 궁금하네요
알아서 잘 주실 것 같은 느낌니 드네요...

### 1.6 리소스

일단 아웃라인 색 바뀌니까 더 자연스러워 보여요!

저도 요 리소스들이 1.6에 나오는 거를 회의 때 알았던 거 같은데
(그냥 큰 오브젝트들 그려주신줄...)
아마 그 때 만능설명팩이랑 팩맘게임팩은 작지 않냐 이런 얘기가 나왔던 것 같아요
맵 작업 이후에 더 작업하시는 것도 찬성이고
만능설명팩이랑 팩맘게임팩이 나온 후에 잘 어울리는지 봐야할 것 같아요!

[팩맘게임팩](https://drive.google.com/drive/folders/1B-itkoNbIUxQQ14WkwqthQAqNJLoA-ii)은 여기 있는데 현재 맵이랑 다른 리소스들이 계속 구체화되고 톤앤매너가 맞춰져가니까 (죻은 과정)
이것도 다시 그리게 될 것 같다는 생각이 드네요...

**Comment by Songkihwa** [comment]
B급 감성 넘 귀엽고 우리 게임이랑 잘 어울리는 것 같아요 ><..!! 고생하셨습니닷ㅎㅎ

**Comment by roweclaw** [comment]
캔크사 리소스는 두번째 줄처럼 볼터치가 있는게 더 B급처럼 보이고 귀여워서 정말 마음에 들어요!
그리고 개인적으로 막대사탕에 있는 얼굴이 잘 안보여서 이 부분만 수정되면 더 좋을 것 같습니다.
물고기도 좋은데 지금은 진짜 리얼 물고기처럼 보여서 뭔가 무지개 빛깔이나 하트가 있다거나 하면 캔크사처럼 보이지 않을까 싶어요 ㅎㅎ


1.6 리소스는 확실히 아웃라인이 연해지면서 맵이랑 톤앤매너가 잘 맞아 보여요. 아직 접속팩 등 다른 것들이랑 고려할 게 많아서, 이우님 말씀대로 맵 리메이크가 끝나고 방향성 확인 후 작업하셔도 괜찮을 것 같습니다!! 


++ 정안님 피드백에서 기획에 참고할 아이디어 픽해둡니다.
> 럭키의 연장선으로 이 게임은 3매치 퍼즐이지만 잘못된 레벨 디자인(마지막 맵은 깰 수 없음)으로 세상에서 잊혀진 게임이다. 라고 풀이해도 될 것 같아요. 시나리오 상 럭키의 역할이 필요하고 이를 스토리에 연결 시켜서 선형적 구조를 가져가기에도 좋아보이네요

**Comment by royalbluesm** [comment]
캔크사 이미테이션 느낌 좋네요! 귀여워요~~ 물고기는 위에서 말씀해주신 대로 색만 변경하면 더 사탕같아 보이지 않을까 싶습니다. 연핑크색이라던가...?

리소스는 수정해주신 느낌 너무 좋습니다! 특히 명암 넣는 방식도 기존 리소스랑 잘 맞물리는것 같아 위화감이 덜해졌다고 보여요. 우측 상단의 주사기...? 같은 오브젝트만 묘사 밀도가 튀는 것 같아, 조금만 더 단순화해 주시면 톤앤매너가 더 잘 맞지 않을까 싶습니다
