### ISSUE TITLE
[Ch1] 캔디 크러쉬 사가 SFX 제작

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/Grayed-Game#424]
캔디 크러쉬 사가 아트를 참고하여 밀기 + 터지는 SFX 제작 예정

------------

기획 문서와 아트의 비주얼만 참고하여 지금 현재 상황에서 만들 수 있는 사운드인 [3개가 맞춰져서 터지는 소리](https://drive.google.com/file/d/1efmLXngcb1TCRln8NIQLbKZjYz-9uGzu/view?usp=drive_link) + [폭탄이 터지면서 동굴에서 문이 열리는 소리](https://drive.google.com/file/d/1efmLXngcb1TCRln8NIQLbKZjYz-9uGzu/view?usp=drive_link)를 간단하게 만들어봤습니다. 

제가 생각한 우리 게임 느낌과 2D로 진행된다는 점이 캔디 크러쉬 사가의 원래 사운드를 비슷하게 따라하기에는 너무 화려해서 적합하지 않다는 생각이 들어서 수민님이 코멘트로 달아주신 애니팡 사운드애 많이 덜어내서 작업해보았습니다.

> 원래 레퍼런스 게임 사운드를 생각하셨다면 조금 실망하실 수도 있을 것 같긴 합니다 ,,, 

일단 다량으로 터지는 소리는 3개 터지는 소리가 오케이 받아야 거기에 맞게 다량으로 터지는 사운드도 제작할 수 있을 것 같아서 3개 터지는 사운드 먼저 올려드립니다!

폭탄 터지는 소리는 폭탄 터지면서 동굴이 흔들리고 거기서 탈출하게 된다는걸로 이해하고 사운드를 한번 만들어봤는데 괜찮나요 ..?! 

> 사실 지금 폭탄 사운드는 제 마음에 썩 들지는 않아서 다시 고심해서 만들어보도록 하겠습니다 !! (더 아기자기한 폭탄 사운드였으면 좋겠어서요ㅎㅎ)

이번주 작업은 이정도 해봤는데 아직 애니메이션이 나온 것도 아니고 사운드를 입힌 영상을 올려드린 것도 아니라서 정확하게 판단하기가 어려우실 것 같습니다,,ㅠㅠ 느낌만 어떤지 간단히 봐주시면 감사하겠습니당 ㅎㅎ

**Comment by wooyn730** [comment]
이 다음 작업은 NPC들 말소리(달러, 파머, R2-Mon)도 괜찮을 것 같습니다!

**Comment by Songkihwa** [comment]
캔디 크러쉬 사가 관련해서 원하시는 사운드 있으시면 코멘트 남겨주시면 좋을 것 같습니당 ><

**Comment by Sumindd** [comment]
캔디 크러쉬 사가 사운드는 이미 찾아보셨을 것 같아서.. 저는 [애니팡 터치](https://youtube.com/shorts/_g523AgunNs?si=20evccCrCWovBbtw)라는 게임의 사운드가 맘에 들었습니다! 
1. 젤리니까 무거운 소리보다는 동글동글보글보글한 소리도 귀여울 것 같습니다! 그리고 저희는 터지는 횟수가 한 라운드에 많지 않아 보통 이런 3매치 퍼즐에서 한 번에 다량이 터질 때 나는 큰 소리가 터질 때 항상 나도 크게 부담이 없을 것 같습니다.
2. 밀 때는 퍼즐게임에서 3개 터질 때 나는 가벼운 퐁 소리, 터질 땐 다량이 터지는 소리들을 위주로 레퍼런스로 잡으면 충분할 것 같습니다! 
3. 이건 아이디어인데 동굴 내부라서 조금 울려도 괜찮을까..?라는 생각이 드네요.. 근데 오히려 별로일지 어떨지는 모르겠습니다.. 적당히 판단 부탁드립니다..!

사실 3매치 퍼즐 관련 사운드는 이미지가 확고하고 기획적으로 중요한 이미지가 따로 없어서 기화님의 재량대로 작업하셔도 충분할 것 같습니다! 제 취향으로 찾아보았으니 적당히 참고만 하시면 될 것 같습니다. 늦게 보내드려 죄송합니다..!

**Comment by Sumindd** [comment]
일단 폭탄 터지는 사운드 링크가 잘못된 것 같습니다..! 그런데 그것보다 기획이 변경돼서 폭탄이 아예 삭제되었습니다ㅠ 총 3라운드로 진행되며 막혀있는 길을 퍼즐을 통해 뚫어서 통과하는 기믹으로 변경되었습니다. 
- #416  자세한 내용은 가장 최신 기획서 확인 부탁드립니다! (또 수정해야하지만..) 
사운드 자체는 젤리의 종류 관계없이 통상적으로 잘 어울릴 것 같습니다! 빌드에 붙여서 확인해보면 좋을 것 같습니다.

**Comment by Songkihwa** [comment]
앗.. 제가 3차를 아직 못 봤군요.....😭 그렇다면 다들 3개 터지는 소리만 들어주시면 감사하겠습니다 !!!

**Comment by wooyn730** [comment]
귀여운 소리 좋네요!
수민님 의견 반영해서 살짝 울리게 준 것 같은 것도 좋아요!
하지만 역시 말씀대로 빌드로 확인해보면 좋겠네요 ^_^

**Comment by roweclaw** [comment]
저도 사운드가 귀여운 3매치 하는 느낌이라 좋고,  리소스랑도 잘 어울릴 것 같아서 어서 빌드에서 확인해보고싶네요!!

**Comment by gomgom172** [comment]
바로 듣기에도 젤리가 뽁 터지는 소리 같아서 무척 귀엽네요… 살짝 울리는 부분도 디테일이 추가되어서 마음에 듭니다. 적용된 버전 얼른 보고 싶네요👍

**Comment by Songkihwa** [comment]
https://github.com/GG-Studio-990001/Grayed-Game/issues/271#issue-2082061465
@wooyn730 
R2-mon 텍스트는 전에 만들어뒀었는데 확인 한번 부탁드립니다!
피드백 받아보고 고칠 거 있으면 새로 만들고 아니면 잘라서 파일 업로드 하겠습니당
R2 mon말고 다른 NPC 텍스트들도 사운드가 달라야할까요?

**Comment by wooyn730** [comment]
NPC 마다 말소리가 다르면 좋을 것 같긴 합니다! [참고자료-언더테일](https://www.youtube.com/watch?v=tEOCKdHcGYo)
_여러명 있는 영상을 아무거나 가져왔습니다..._

물론 지금 당장 필요한 작업은 아니고 나중에 이런 작업 하시면 좋겠다 싶어서요!
아니면 피치만 다른 몇가지 말소리를 돌려 써도 될 것 같고요

알투몬은 해당 이슈 확인했는데 조금 적용하기 애매하긴 하네요...
저는 먼지들처럼 한 음절씩 주시면 조합하는 게 좋을 것 같은데 어떠세요?

그리고 개인적으로는 알투몬은 이제 중요한 친구가 되어버려서 좀 더 듣기 편한 효과음이 좋지 않을까 싶기도 합니다..

**Comment by Songkihwa** [comment]
저번에 단순하게 기계음이라는 얘기만 듣고 러프하게 작업했던거기도 하고 기계 로봇음 자체가 듣기 편한 소리는 아니여서 조금 어렵네욧 ....
알투몬 원하시는 사운드 레퍼런스가 있다면 들려주시면 제가 작업하기 편할 것 같습니당!!

오케이하면 한 음절씩 잘라서 올리려고 했었는데 다들 확인 못하신 것 같아여ㅠㅠ

NPC들마다 다른 말소리는 나중에 기획분들과 얘기해서 정확하게 어떤 느낌의 말소리를 원하는건지 한번 얘기 나눠보도록 하겠습니닷ㅎㅎ

**Comment by roweclaw** [comment]
### R2-MON 레퍼런스

[morusque](https://youtu.be/2YeUJJ4xAC4?si=_BKj2Q6Zg8tUYa7g&t=4898)
[seamus](https://youtu.be/2YeUJJ4xAC4?si=eg_Bj1g-nyUS7s3v&t=5499)

제가 생각했을 때 R2-MON은 유저를 좋아하고 친절하고 가끔 개그코드도 섞는 캐릭터이다보니
현재 있는 사운드보다는 조금 더 부드러운 말소리가 좋을 것 같아요! 
레퍼런스는 Stray에서 찾았는데 미묘한 차이가 있지만 전체적인 톤은 비슷한 것 같아서 2가지 다 들고 왔어요.
괜찮으면 이런 사운드를 베이스로 해서 기화님이 R2-MON에 더 어울리게끔 바꿔주셔도 좋아요!

그리고 나머지 NPC들 말소리도 있으면 좋을 것 같은데
아직  딱 맞는 레퍼런스를 찾지 못하여.. 회의 전까지 더 알아보겠습니다!

( 생각해둔 이미지 )
달러 - 도도함과 인자함 그 사이
파머 - 호탕, 쾌활
마마고 - 안 시끄러운 짹짹소리
럭키 - 명랑,
