### ISSUE TITLE
[Pacmom] 팩맘 엔딩씬 수정

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#425]
[[CH1] 전체 시스템 문서 3차](https://github.com/GG-Studio-990001/Grayed-Game/issues/416) 참고

### 엔딩씬 (결과창)

간단한 작업이지만 고민되는 부분이 조금 있어서 후보 뽑아서 보여줄 예정
- 코인 개수 올라가는 애니메이션이랑 캐릭터 연출이 겹치면 부산스러워보일지 않을지
- 코인 개수 올라갈 때 효과음 넣으면 배경음이랑 겹치는데 괜찮을지
- 그 외 'You Win'과 'Reward', 코인 개수 폰트 사이즈 고민 등

### 컨트롤러

추가로 컨트롤러 따로 만들어서 사용하기
(기존엔 CH1 컨트롤러 사용했음 하지만 접속게임은 컨트롤러 따로 두는 게 낫다고 판단)
팩맘 스크립트에서 일단 기존 컨트롤러 비활성화 해두고,
나중에 적절한 CH1 스크립트로 옮길 예정 (팩맘 접속 연출 픽스될 때 쯤)

---

### 컨트롤러 문제

접속게임을 위한 스크립트 작성함
근데 팩맘이 끝난 후 CH1으로 갔을 때 esc를 눌러 설정창을 켜면 누르면 destroy된 오브젝트에 접근한다는 오류가 뜸
하지만 CH1 설정창은 뜸 (??)

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/df0ebf7b-9ed8-4f12-9eb9-36c3e42c51d5)

예상1: 팩맘에서 만든 컨트롤이 꺼지지 않는다
=> 타이틀에서 만든 컨드롤과 같은 방법으로 끄는데 타이틀 컨트롤은 잘 꺼짐. 또한 오류 코드가 내 스크립트를 가리키고 있지 않음

예상2: CH1에서 처음에 할당한 설정창이 destroy된 후 CH1을 다시 불렀을 때 이전 설정창(destroy된)도 같이 불러서 오류가 생긴다

실험: CH1->Pacmom->CH1 시 오류 발생, Pacmom->CH1 시 오류 발생 안함

결론: 이건듯. 정안님이랑 이야기해보기

++
컨트롤러는 `Dispose()` 가능. IDisposable 인스턴스를 상속받고 있다.

[참고자료](https://chomdoo.tistory.com/15)

**Comment by wooyn730** [comment]
## 엔딩씬 골라주세요

이 코멘트만 읽어주셔도 됩니다!
4가지 버전으로 뽑아봤습니다.

사실 구현하려고 생각해보니까 코인 애니메이션이나 사운드가 들어가면 정신사나울 것 같다는 느낌이 들었는데 저번 코멘트에 이미 애니메이션 의견을 남겼어서 보여드리려고 한 번 구현해봤습니다.
저는 역시 1번이 무난하고 나은 것 같습니다..

### 1) 코인개수 안올라감
https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/f9cbc44d-18b4-4794-b0e1-ea5fd956cfb7

### 2) 코인개수 0.02초마다 올라감
https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/5af167e0-bb9f-4fa1-8650-a7295f8d8b6e

### 3) 코인개수 0.01초마다 올라감
https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/ad2b8044-45f2-49dd-b50a-1162871807b6

### 4) 코인개수 0.01초마다 올라감 + 코인 사운드
https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/6bf093b7-98cd-4f73-8090-9cf8eb04ced5

**++**
![스크린샷 2024-04-21 173134](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/fe78650b-57f4-41a4-9d4a-3d99c2c86b86)
대문자 YOU WIN

**그 외 폰트 크기나 배치 등 다른 의견 환영합니다**

**Comment by Sumindd** [comment]
- You Win!은 소문자가 더 좋은 것 같습니다.
- 코인 사운드는 없는 편이 나을 것 같습니다. 넣더라도 훨씬 소리를 줄여야 할 것 같고요.
- 저도 코인 개수 안 올라가는 게 깔끔해 보이는데 Blink나 Bounce 효과 있으면 좀 더 좋을 것 같습니다!

**Comment by gomgom172** [comment]
- 저도 You Win!은 소문자가 더 좋아 보입니다.
- 말씀대로 1번이 가장 깔끔한 것 같습니다. 코인 개수가 올라가는 버전으로 간다면 0.01초보다 좀 더 빨라야 하지 않을까 합니다. (엄청 빠르게 코인 개수 올라감→멈춤→그 후 팩맘 캐릭터들 나오며 엔딩 사운드 재생? 하는 쪽이 좀 더 매끄럽지 않을까 생각했습니다.)

**Comment by roweclaw** [comment]
- 대문자보다는 소문자가 더 잘 읽혀서 You win! 이 좋습니다.
- 저도 1번이 보기도 편하고 깔끔해서 제일 좋아 보여요!

**Comment by royalbluesm** [comment]
저는 1번 아니면 3번이 좋아보이네요~ 하나의 사운드는 한 번만 사용되는 것이 디자인상 깔끔해 보입니다

**Comment by wooyn730** [comment]
1번으로 픽스하겠습니다~
또 다른 좋은 아이디어 있으면 주셔도 좋아요

**Comment by wooyn730** [comment]
2024-05-04

- 팩맘 키 바인딩 설정
- 팩맘 엔딩 1번으로 설정
- 리워드 코인 저장
