### ISSUE TITLE
[Char] 럭키 캐릭터 디자인 및 스프라이트 작업

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/Grayed-Game#427]
**상세**
- #417 문서를 참고해 럭키 캐릭터 디자인 및 스프라이트를 작업합니다.
- 

https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/e3625abc-454c-4343-b970-eebda64a69b4

https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/36a2a6bb-fc67-4264-b1f4-2d66e9cd9539

https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/4290b56d-5cd4-463a-babf-17ad28638327

https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/4e13d78f-35aa-4dff-8f75-fb5afe974137

확인해주시고 문제없으면 시퀀스파일로 드리겠습니다 

**파일**

[Character 폴더](https://drive.google.com/drive/folders/1n9BeEAncWHCryg3RRbfaVo6b_f3WB6Fx?usp=drive_link)에 시퀀스 png 파일 넣어놨습니다.

**Comment by fkdl0048** [comment]
시간이 별로 없었는데, 빠르게 럭키에 대한 애니메이션을 제작해주셔서 좋네요! 지금과 같이 사용한다면? 현재 1챕터에서 진행되는 애니메이션이 부족한 게 없는지 기획쪽에서 한번 확인을 해주는 것이 좋을 것 같습니다.

3매치에서 물고기를 물고가는? 애니메이션은 지금은 없는게 맞을까요?

전체적인 디자인은 저도 마음에 들어서 이대로 쭉 갔으면 합니다. 지금처럼 단순한 움직임도 좋지만 애니메이션 사이에 프레임이 깨지지 않을까라는 걱정이 되는데, 이건 한번 적용해보고 수정을 하면 될 것 같습니다.

일단 파일 올려주시면 확인해볼께요!

**Comment by Sumindd** [comment]
- 물고기 젤리를 물고 등장해서 맵에 두고 가는 모션도 추가적으로 필요할 것 같습니다! 제가 리스트에서 깜빡했습니다 죄송합니다.  [리스트](https://docs.google.com/spreadsheets/d/1xLu0o7xpz4A3foy7fB_kl-RDrlTBvMuX/edit?usp=sharing&ouid=102142728386857128653&rtpof=true&sd=true)에 추가했습니다!
- 혹시 왼쪽 방향으로 이동은 이미지 반전 시켜서 사용하나요?
- 종이 크기가 세로로 조금만 더 크면 좋을 것 같은데 이건 다른 분들 의견도 궁금하네요.

**Comment by wooyn730** [comment]
바로 작업해서 올려주시는 거 좋아요 👍

> 종이 크기가 세로로 조금만 더 크면 좋을 것 같은데

저도 종이가 더 크면 좋겠어요!

그리고 럭키 팔이 생각보다 더 짧아서... 
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/7ce15b8e-4599-41e7-b305-c3a5f7e76d22)
그냥은 안되고 이런 걸로 가리켜야할 것 같은데요?

**Comment by gomgom172** [comment]
- 저도 종이가 좀 더 컸으면 좋겠습니다! 일반 주민 사이즈라고 가정하면 그림이 생각보다 작아 보이지 않을까 싶습니다.
- 포인팅 모션 손가락 막대로 주는 것에 한 표 얹어봅니다!

애니메이팅 너무 귀여워요! 목걸이와 열쇠도 자연스럽게 잘 들어간 것 같습니다. 👍👍

**Comment by royalbluesm** [comment]
@Sumindd 종이 크기가 더 컸으면 좋겠다는 건 캔버스 사이즈를 말하는 걸까요? 아니면 럭키 자체의 크기를 말씀하시는 걸까요

**Comment by wooyn730** [comment]
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/74b5317e-5de6-4257-bf70-e88b372ca2b5)
럭키가 들고있는 요 종이요!

**Comment by royalbluesm** [comment]
아하 알겠습니다~~

**Comment by royalbluesm** [comment]
https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/58c5e7bf-938f-4087-941e-aa99ecc9bddf


https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/24411d5f-b0d3-4bb6-870d-34b5d4f894c5


https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/df316767-8509-4562-bd82-25bc96c819a4


https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/4aabbdab-e461-4f5b-b596-759f81daffb2

보여주기, 가리키기 수정하고 박수, 물고기 모션 추가했습니다.

**Comment by royalbluesm** [comment]
파일 드라이브에 올려뒀습니다~

**Comment by fkdl0048** [comment]
확인했는데, 애니메이션끼리 합쳐서 주셔야 할 것 같습니다!

**Comment by royalbluesm** [comment]
아틀라스 이미지로 달라는 말씀이실까요?

**Comment by fkdl0048** [comment]
네네!

**Comment by fkdl0048** [comment]
@royalbluesm 아틀라스로 이미지 주시고, 라플리 캐릭터도 저번에 말씀드린 머리 쪽 스프라이트 깨지는 문제 해결해주시면 감사합니다..!

**Comment by wooyn730** [comment]
아틀라스 이미지 확인했는데요, 빈공간이 많이보여서 스프라이트 간 간격 좀 더 붙여서 올려주시면 감사하겠습니다 ~!!
라플리랑 럭키 아틀라스 수정본 일요일 낮까지 가능할까요?
