### ISSUE TITLE
[CH1] 대사 스크립트 작성

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#428]
Ch1에서 나올 대사를 스크립트로 작성합니다.
- 컷신 대사
- NPC 대사
- 팩맘, 3매치, SLG에서 럭키가 말하는 튜토리얼

## 240426
작성된 [스크립트 (Scene1~4)](https://drive.google.com/drive/folders/1DfjAmTRxn-p1GPEtlyn-b0mNKqVY5MGW) 를 우선적으로 업로드했습니다.

파일명에서 s1은 Scene1을 뜻하고 그 뒤에는 제가 대사 작성할 때 기억하기 편하게 임의로 단어를 붙였는데
혹시 보기 불편하거나 알기 어렵다면 추후 변경하도록 하겠습니다.

남은 작업들도 이번주 내까지 할 수 있을 것 같아서 나중에 수정하더라도 일단 1차적으로 끝내보겠습니다.

> 이후 할 일

- [x] Scene 5 : 마마고 컴퍼니
- [x] Scene 6 : R2-MON 장르팩
- [x] 기타 : 경비원 대사

## 240427

[모든 스크립트](https://drive.google.com/drive/folders/126eSPNQGkJWib_OdH1hBMDwiesdeaU5s)를 업로드 했습니다.

나뉘어져 있던 파일을 공통의 Scene으로 묶고 내부에서 title로 구분하였습니다.
경비원 대사만 npc.yarn으로 작성하였습니다.

> 고민되는 점

[s2_pacmomLucky]에서 럭키의 튜토리얼 중지 버튼(스킵) 설명은
다음 챕터에 넣는 게 더 좋을 것 같아서 보류했는데
혹시 지금 꼭 넣어야 한다면 추가하겠습니다.

**Comment by roweclaw** [comment]
작업 중간 현황을 본문에 업로드했습니다. 읽어보시고 다른 의견 있으면 남은 작업하면서 수정해서 같이 가져오겠습니다.

**Comment by fkdl0048** [comment]
한 스크립트당 하나의 파일보단 씬 하나당 파일 하나로 만드는게 좋을 수 있겠다는 생각이 드는데, 파일 이름을 s1로 두고 내부에서 title로 구분하는 건 어떠신가요?

**Comment by roweclaw** [comment]
중간 업로드 수정사항이 포함된 모든 스크립트 작성을 완료하여 본문에 추가했습니다!

**Comment by wooyn730** [comment]
_제 졸업유무가 달린 시험을 치느라 피드백이 많이 늦었습니다 ㅠㅠ 제송.._

스크립트 잘 읽었습니다!

스크립트 빠르게 주셨네요 이제 제 일만 남았군요...
맞춰가는 과정에서 많이 연락 드릴 것 같습니다! (꽤 많이..)
화이팅입니다 ><

---

### 팩맘

지금 팩맘 인트로 대사가 옛날 다이얼로그를 참고하신 것 같은데
현재 다이얼로그 위치는 [여기](https://github.com/GG-Studio-990001/Grayed-Game/blob/main/Assets/_CH1/_Pacmom/Dialogues/PacMomDialog.yarn)입니다... ㅠㅠ
작업하면서 수정을 수시로 했기 때문에 구드에 수정본을 올리지 않았는데 진작 말씀 드렸어야됐을 것 같아요 죄송해요 😱
이 파일 베이스로 수정해주시고 컷씬 2.2는 따로 주시면 좋을 것 같습니다

<br>

(우선 라플리는 목숨이 없고, 먼지는 '먼지유령'이라고 해도 상관 없으나 지금은 그냥 '먼지' 컨셉만 남은 캐릭터입니다.)

럭키의 팩맘 설명은 좀 더 디테일한 설명이 들어가고,
먼지 대사는 룰 상관 없이 캐릭터성을 살렸으면 좋겠습니다.

팩맘 주요 규칙 _(팩맘 기획 문서 참고해주셔도 좋습니다)_
- 팩맘을 잡으면 팩맘의 목숨이 하나 깎이고 코인(절반)을 뺏을 수 있음
- 먼지가 팩맘을 잡으면 팩맘 코인(절반)이 필드에 떨어짐
- 팩맘이 청소기를 먹으면 '청소시간'이 됨 (10초 지속)
- 청소시간에는 팩맘과 부딪혔을 때 내가 죽고 코인(절반)을 뺏김
- 팩맘이 먼지나 라플리를 먹으면 위치가 초기화됨
- 팩맘보다 코인을 많이 모으면 승리 (제한시간이 끝나거나 또는 필드에 남은 코인 개수가 0일 때)
- 팩맘을 3번 잡으면 팩맘이 죽음 (팩맘을 죽이면 무조건 코인을 더 많이 갖게 되므로 승리)

<br>

### 그 외

지금 폰트가 일본어 지원이 안될텐데 그 부분은 어떻게 처리할지 조금 고민이 되네요

<br>

알투몬 번역 전 대사는 [이진법](https://charactercalculator.com/ko/binary-translator/)으로 말해도 재밌을 것 같다는 생각이 들었습니다 (근데 조금만 말해도 숫자 개 긺)

<br>

럭키 마지막 대사로 "그럼 행운을 빕니다." 나오는 거 너무 좋네요!
하지만 럭키 등장할 때마다 동일한 6 문장이 반복되는 건 조금 루즈하지 않을까 싶습니다..

<br>

_말투에 대한 개인적인 의견_

럭키 캐릭터 논의할 때 개의 '친근함'에 대해서 이야기 나왔던 것 같은데 반말+발랄한 말투면 정 들기 더 좋지 않을까 해요

알투몬 캐릭터성도 엄청 강하고 플레이어와 많이 접촉하는 캐릭터인데 말투도 너무 특이해서 좀 무난하고 귀여운 말투여도 좋지 않을까~ 싶은 마음도 있습니다. 
하지만 개그코드가 들어간 건 좋아요! (눈물샘 ㄱㅇㅇ..)

**Comment by gomgom172** [comment]
스크립트 무척 즐겁게 읽었습니다!
각각의 말투로 쓰인 대사를 읽으니 캐릭터성이 좀 더 바로 다가오는 것 같아요.
내용적인 측면은 기획 파트 분들께서 잘 짚어주신 것 같아 여타 의견만 남겨두겠습니다.

### 그 외

코딩 들어가시기 전에 비문 검수하고 지나가는 게 편하지 않을까 싶어 의견 남겨봅니다!
유명한 사이트라 다들 아실 것 같지만, 추천 사이트 하나 함께 첨부하겠습니다. [부산대 맞춤법 검사기](http://speller.cs.pusan.ac.kr) (문법까지 잡아줘서 유용한 사이트) 더불어 스크립트 내 말줄임표를 한 개로 통일하면 어떨까 싶은 소소한 의견입니다. (현재는 ..와 …이 번갈아 나와서요!)

늦은 의견 지나갑니다… 작업 너무 고생 많으셨습니다👍
