### ISSUE TITLE
[CH1] Scene 1 오브젝트, 3매치 퍼즐 맵 03

### ISSUE THREAD

**Issue by gomgom172** [GG-Studio-990001/Grayed-Game#429]
---

- #398
- #418 에서 이어서 작업 진행합니다.

[240423 파일 업데이트](https://drive.google.com/drive/folders/11qUP7Kjl6nDCfjsWeqWq7fq_YJr7cV2o?usp=share_link)

3매치 퍼즐 맵과 리소스 작업 진행합니다.

3매치 타일맵 파일을 4/23(화)까지 전달 예정입니다. (전달 완료)
젤리 바리에이션을 추가로 작업합니다. (전달 완료)

+ (240428) scene 1 리소스 작업, 젤리 애니메이션 진행하겠습니다.

# 240423 작업 진행

타일맵 파일과 젤리 리소스가 추가되었습니다.

![0423tilemap](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/342613a7-9a1e-4379-99e3-41a79e9ada60)

![0423tilemapguide1](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/d8e68b60-ff12-4e82-aa4f-47ff141b8c15)

![0423tilemap2](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/5b676867-ffe9-4b26-98cd-d2e1de588987)

(빈 부분 없이 1줄에 10칸씩 배치한 슬라이스용 파일입니다.)

![0423tilemapguide2-2](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/5f74f62a-48c3-49c8-ac61-450b3410bb9c)

![0423tilemapguide2-1](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/e13becf9-7dea-4d17-85b6-858247e42a81)

---

+ 피드백 받은 후 타일 6개로 수정하였습니다. (4/23 16:36)

![0423tilemap3](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/e76ecd27-6488-44d8-86db-365a2ae6629b)

![0423tilemapguide3](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/98c129e5-11f1-4bec-b1b2-ca88c0ead9fe)

(4방향 모두 동일)

![0424_3matchresource-2](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/cad07133-67e5-4819-bfbe-ada09776aec5)

두 가지 버전 임시 파일입니다.
확인 후 문제 있으면 말씀 부탁드립니다!

---

# 240501 작업 진행

[240501 파일 업데이트](https://drive.google.com/drive/folders/11qUP7Kjl6nDCfjsWeqWq7fq_YJr7cV2o?usp=share_link)

빌드 볼 때 3매치 퍼즐 애니메이션 들어간 버전도 함께 보면 좋을 것 같아 젤리 애니메이션 먼저 작업했습니다.

![0501_3matchresource](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/196362bf-3663-4b8f-8971-7fe981fce46b)

![0501_3matchresource2](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/10f52dd7-0189-4250-807e-a5ff03619052)

![0501e g](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/3de9c4aa-3688-4f07-aa89-cd84f5d80793)

클릭해서 보시면 좀 더 매끄럽게 재생됩니다!

[애니팡 젤리 터지는 애니메이션](https://youtu.be/QcYK-KV-HBQ?si=zwSh_h2IRDPp-Smu) 주로 참고했습니다. (터질 때 오브젝트 표정 변화, 하얀색 아웃라인)

![0501_3matchresourceidle](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/a807374d-913d-46fe-a3b7-827154c888b2)

대기 애니메이션 함께 추가했습니다! (1(길게)→2→1(길게)→2→1→2→1(길게) 반복)
파일 업로드 완료했습니다.

**Comment by gomgom172** [comment]
240423 업데이트되었습니다.
확인 부탁드립니다! @fkdl0048

**Comment by wooyn730** [comment]
마쉬멜로우냥이 너무너무너무 귀여워요 ^___^
톤도 맞추니까 통일감있고 좋네요!

물고기도 귀엽지만 저는 회의 때 이우님이 말씀하셨던
고양이화(?)로 통일 + 터질 때 고양이 효과음이 정말 마음에 들었어서
4고양이는 생각 없으신지.. 궁금합니다

---

타일맵은 빈 칸 없이 딱 붙여 주신거 좋습니다

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/61cb3e31-4a33-4eeb-8ec1-38073e0954c0)
근데 배치할 때 회전이 가능하기 때문에
4/1만 타일맵으로 만들어서 주신다고 생각하면 되지 않을까요?



![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/9bec4fac-af32-4c28-baa1-53f4badefd53)

근데 제가 봤을 때는 요 6개만 수정해서 주시면 되지 않을까 싶어요..!!



참고로 지금 팩맘의 타일맵은 바닥 제외 6장입니다

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/2253e2ea-2cf0-494b-b372-221fcbda6a75)

**Comment by Sumindd** [comment]
저는 고양이 3마리라 하나는 물고기여도 좋을 것 같아요! 귀여워요 
럭키가 물고기 물고 갈 수 있게 구상해보겠습니다(??) 
4가지로 생각하고 맵 짜보겠습니다 늘려주셔서 감사합니다!

**Comment by gomgom172** [comment]
답변 감사합니다! 말씀해주신 내용 반영하여 6개 타일로 줄여보았습니다.
어떻게 드리면 좋을까 고민이 많았는데 간단한 방법이 있었네요….
5, 9는 디테일을 추가하려고 변화를 줬는데, 우선은 같은 용도끼리 통일한 버전(3번) 함께 넣어두었습니다.

![0423tilemap3](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/65250eb1-ce9a-4983-b124-7a9f08638f96)

고양이는 좀 더 고민해보겠습니다! 지나가다 한 번씩 의견 주시면 감사하겠습니다 👍

**Comment by wooyn730** [comment]
_(저도 타일맵 기존에 어떻게 받았는지 설명을 해주면좋을지 이우님이 생각해보는게 좋을지 속으로 계속 고민하다가 회의 때 이야기 나온 ㄹ자(?)도 모르겠고 딱히 안물어보시는 것 같아서 넘겼어여..)_
_하지만 타일맵 처음이라고 하셨던 것 같은데 구상 잘 해주셨다고 생각합니다_

<br>

> 럭키가 물고기 물고 갈 수 있게 구상해보겠습니다

수민님 코멘트 보니 럭키가 마지막 맵에서 하나를 치워준다면 (물고 가서 도와준다면) 물고기인게 제일 어울릴것 같네요!!

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/04d994ee-2b07-45fe-8c31-accac1f52545)

제가 배치했던 건 3가지 종류지만 막대사탕은 밀어서 터트리는 걸로 활용은 안되는데(2개 활용)
1라운드에서 3배치 2활용,
2라운드에서 3배치 3활용,
3라운드에서 4배치 3활용 (물고기는 1라운드의 막대사탕 같은 존재 + 럭키가 물고 갈 것)
하면 좋지 않을까... (효과음을 야옹으로 하고 물고기는 터질 일 없게..)

이 코멘트는 진짜 참고만 해주세용

**Comment by fkdl0048** [comment]
@gomgom172 확인했습니다.

가능하시다면 해당 파일 구드 링크를 같이 걸어주시면 더 감사합니다..! (본문에)

**Comment by gomgom172** [comment]
감사합니다! 확인했습니다.
본문에 파일 이미지 링크 각각(리소스 이미지/타일맵 이미지 각각 하나씩 링크 첨부 형태로…) 걸어놓으면 될까요?
현재는 가장 상단에 통파일 링크(3매치 퍼즐 파일)가 있는데, 위 형태의 첨부 원하시는 게 맞는지 확인차 여쭤봅니다!

**Comment by fkdl0048** [comment]
아아 제목쪽에 링크가 걸려있네요 지금 확인했습니다!

**Comment by gomgom172** [comment]
240501 젤리 애니메이션 작업 업데이트되었습니다.

**Comment by fkdl0048** [comment]
기본 Idle 애니메이션은 일단 보류일까요?

**Comment by fkdl0048** [comment]
느낌이 너무 좋아서 적용한 상태로 빠르게 보여드리는 게 좋을 것 같아요. 하얀색 아웃라인이 있으니까 더 느낌이 살아나는 것 같습니다.

**Comment by gomgom172** [comment]
번잡할까봐 고민 중이었는데 있는 쪽이 좀 더 어울릴 것 같네요!
저녁 중으로 idle 애니메이션도 업데이트하겠습니다.

idle 파일 + 터지는 애니메이션 파일 함께 올린 후에 알람 드려도 될까요?

**Comment by fkdl0048** [comment]
네네~ 주시면 사운드, 애니메이션 적용된 버전으로 빌드해서 올려드릴께요

**Comment by gomgom172** [comment]
본문과 드라이브 업데이트 완료했습니다. 확인 부탁드립니다!

**Comment by Sumindd** [comment]
너무 귀엽습니다.. 애니메이션도 이런 식으로 터지는 건 생각해보지 못했는데 너무 귀엽고 잘 어울리네요!
저도 흰색 라인 생기는 게 너무 좋습니다. 그리고 터질 때 젤리들 표정 ><표정으로 바뀌는 것도 디테일이 좋아요. 물고기 흔들릴 때 꼬리 흔들리는 것도 마음에 듭니다.
빌드본 플레이 해봤는데 퍼즐에 보는 맛, 듣는 맛도 생기니까 훨씬 재미있게 플레이 한 것 같습니다!

**Comment by wooyn730** [comment]
터질 때 애니메이션(특히 흰색 아웃라인)과 Idle 애니메이션 모두 너무 좋네요 귀여워요 ><
수고하셨습니다!!!!!!!!!!!!
