### ISSUE TITLE
챕터2 프로토타입

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#433]
### 순서
- 임시로 사용할 배경 찾아서 흑백으로 만들기
- 민지님 컨셉아트에서 라플리와 알투몬 누끼따고 흑백으로 만들기
- 임시 스크립트 작성하기
- 임시 스크립트 적용하기
- 화자가 아닌 사람 어둡게 처리하기
- 대화 끝나면 장소 이동 버튼 뜨게 하기
- 장소 이동 버튼 누르면 투비컨티뉴드 뜨게 하기

### 추후 할 것
- 설정창 연결
- 챕터1과 연결
- 스프라이트, 스크립트 교체

++
민지님한테 배경도 요청해야함
장소 이동 버튼 맵 형식으로 변경 (맵 이미지도 요청해야함.. 아마 민지?)
기화님한테 배경음 요청해야함

**Comment by wooyn730** [comment]
2024-05-04

전체화면 최적화
키 바인딩 (설정창)
BGM (심심해서 마마고 BGM 넣어둠 ㅎㅎ..)

++
CH1도 카메라에 ScreenResolution 붙여야됨

**Comment by wooyn730** [comment]
(많이 바뀐 건 없지만) [오늘자 빌드본](https://drive.google.com/file/d/1Y_Qm-i4AfpFWBO4iVEcYcCBAmQKwNGs3/view?usp=drive_link)입니다

**Comment by Sumindd** [comment]
CH2 시스템에 대해 고민 중인데 장소 이동 시스템을 넣을지 말지 고민이 됩니다.. CH2의 시스템은 일요일 회의 시간에 이야기 해보거나 기획 회의를 한 번 더 해보면 좋을 것 같아요! 일단 SGM에는 특별한 기능 없이 현재 빌드본에 들어가 있는 것처럼 스크립트 대화 정도까지만 보여주면 될 것 같습니다. 벌써 만들어주시다니 너무 좋네요!
