### ISSUE TITLE
[CH1] 연출 배치 피그마

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#438]
컷씬과 럭키 배치를 스크립트 연출과 함께 피그마로 작성합니다.

## 240504 업데이트
[기획 피그마](https://www.figma.com/file/LNsoGFh5f3jQ1rCPQB2O9f/Grayed-Game?type=design&node-id=0-1&mode=design&t=tIzZr5dftCxdXZQr-0)

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/92532398/a8befce5-ecce-43fa-9b5d-41cc60b69aa3)

++
~SLG 설명하는 럭키 누락돼서 추가해서 업뎃할게요!~ 추가완료

**Comment by roweclaw** [comment]
240504 업데이트 했습니다!

**Comment by Sumindd** [comment]
확인했습니다!
3매치 퍼즐 1라운드 : 럭키는 1라운드를 클리어할 때까지 라플리의 맵 출입과 관계 없이 1라운드에 머문다. 
플밍 직군 참고하시면 좋을 것 같아 위 내용 추가해뒀습니다.
정리 깔끔하게 해주셔서 감사합니다.
