### ISSUE TITLE
[CH1] Scene 1 오브젝트 04

### ISSUE THREAD

**Issue by Kiwwwicat** [GG-Studio-990001/Grayed-Game#441]
---

- #398
- #418
- #429 에서 이어서 작업 진행합니다.

# 작업 계획

<img width="1037" alt="스크린샷 2024-05-05 오후 8 41 17" src="https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/8615500d-0171-4308-a6ec-9649806f1339">

작업 진행 중입니다.

**염두에 둘 부분**
톤앤매너 통일, 조사 불가능한 오브젝트와 구분 가능하도록

# 240512 작업 진행

![0512FloyardBackground-export](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/8a40c70b-92bc-4c3e-967e-8c180594c059)

![0512object-export](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/a554e41e-43df-48ca-892b-0fe03fb3d4be)

Scene 1 오브젝트와 만능설명팩, 팩맘 게임팩 작업했습니다.

![0512FloyardBackground-export2](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/15ecbacc-5983-4cf1-8461-d7b1432fce81)

고민하다 작은 오브젝트 위주로 작업했는데 큰 오브젝트 섞은 버전도 같이 올려둡니다!

파일 둘다 업데이트해두었습니다.

[파일 링크](https://drive.google.com/drive/folders/1Ev4wLdt2JVngAtFRKGvI_zRAjLE3gCDj?usp=share_link)

++

![0512rock](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/d937a082-5e39-4605-969d-8e8f6bcb615b)
![sample0512](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/1f81cb96-1912-4ebb-b85b-dae1b4d590dc)

팩맘/만능설명팩 옆 장애물 업데이트했습니다!

[파일 링크](https://drive.google.com/drive/folders/1Ev4wLdt2JVngAtFRKGvI_zRAjLE3gCDj?usp=share_link)

**Comment by gomgom172** [comment]
240512 업데이트되었습니다.

**Comment by wooyn730** [comment]
오브젝트 파일 위치가 어디인가요??

**Comment by gomgom172** [comment]
앗 죄송합니다 [이쪽](https://drive.google.com/drive/folders/1jkSkokp1PZMRFGP5teQO4nzEWVL0sFEE?usp=share_link)입니다!

**Comment by wooyn730** [comment]
안보이는ㄴ데요? ㅠㅠ

**Comment by gomgom172** [comment]
헉 죄송해요 파일을 착각했네요 이쪽입니다!!

**Comment by wooyn730** [comment]
ㅋㅋㅋㅋㅋㅋ 이우님.............

**Comment by gomgom172** [comment]
본문 링크랑 위에 코멘트 둘다 같은 링크로 업데이트해뒀습니다!! 죄송해요 ㅠㅠ

**Comment by wooyn730** [comment]
훼이크 쩔었다

**Comment by gomgom172** [comment]
😂💕 감사합니당…ㅠㅎㅎㅎㅎ

**Comment by wooyn730** [comment]
게임팩 걱정하시더니 저는 럭키랑 팩맘팩 너무 좋은데요?!!!!
링은 소닉링 같은데 맞나여?

**Comment by gomgom172** [comment]
네 맞습니다~!! 👍

**Comment by gomgom172** [comment]
양옆 장애물 리소스 업데이트했습니다! @wooyn730

**Comment by wooyn730** [comment]
오.. 제대로 낑겨있네요 👍
