### ISSUE TITLE
[CH1] 맵 교체 & 컷씬 구현 & 럭키 구현

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#444]
## 이전 작업

<details><summary> 1회차 작업 </summary>

### 맵&오브젝트

- [x] 맵 교체
- [x] 맵 콜라이더 따기
- [x] 리소스 배치
- [x] 리소스 콜라이더 따기
- [x] 장소 이동 수정
- [x] 장소 나누기
- [x] 이우님 오브젝트 배치

### 컷씬
- [x] 컷씬 1 임시 구현
- [x] 맵 화질 설정

약 6시간 작업
</details>

- #458 

<details><summary> 2회차 작업 </summary>

### 할 것

(1.5회차, 약 3시간)

- [x] 대사 자동으로 넘어가기 X
- [x] 상호작용 E키 -> 스페이스바로 변경
- [x] Sound 관련 용어 통일 (배경음악 BGM, 효과음 SFX)
- [x] 라플리 스프라이트 교체
- [x] 라플리 애니메이션 재설정 ([참고](https://jjong-ga.tistory.com/101))
- [x] 스크립트 수정본 적용
- [x] 팩맘게임팩 주변 오브젝트(돌) 배치
- [x] 맵 분할 수정
- [x] 컷씬1.1 후 달러 상호작용

(2회차, 약 9시간)

- [x] 디폴트 사운드값 0.5로 변경
- [x] 사운드 밸런스 조정된 파일로 교체
- [x] 3매치 야옹 사운드 적용
- [x] 팩맘 설정창 X, ESC키 버그 수정
- [x] 사운드 볼륨 조절 기능 임시 추가
- [x] 팩맘게임팩 스프라이트 교체
- [x] 3매치퍼즐 3스테이지 -> 2스테이지 이동 버그 수정
- [x] 마마고 건물 내부 스프라이트 교체
- [x] 컷씬1.1 후 파머, 알투몬 상호작용
- _===여기까지 0513 1차 빌드본===_
- [x] CH1 창모드/전체모드 설정
- [x] 대사 타이핑 효과음 적용
- [x] 인트로 새로운 버전 적용
- [x] 캐릭터 걷는 애니메이션
- [x] 캐릭터 점프 애니메이션
- [x] 캐릭터 애니메이션 클래스 분리
- [x] CH2 일러스트 교체
- _===럭키 시작, 팩맘 먼저 진행중 (19:00)===_
- [x] 럭키 다이얼로그 구현
- [x] 럭키 움직임& 애니메이션 적용
- [x] 럭키와 팩맘 연결
- [x] 팩맘 게임오버 => 팩맘 다시 로딩 (럭키 X, 먼지 대사 바뀜)
- [x] 팩맘 클리어 => CH1로 이동
- [x] 팩맘 클리어 후 재진입 시 임시 대사
- [x] 팩맘 끝나면 오프닝으로 돌아가는 버그
- _===여기까지 0513 2차 빌드본===_

### 메모

~민지님한테 마마고 내부, 라플리 새로 받음~
~수빈님께 오브젝트 별 대사 수정 요청드림~
~이우님이 팩맘게임팩 옆에 놓을 수 있는 돌 오브젝트 그려준다 하심~
~수민님이 인트로 일러스트 필요 없는 버전으로 수정해주신다 하심~

### 기록

`.SetEase(Ease.Linear);`
[참고](https://stackoverflow.com/questions/73598553/can-we-remove-the-smoothing-translate-with-domove)

### 문제

**팩맘 ESC, X 버튼 비동기화 문제**
esc에는 타임스케일 멈추는 기능을 넣었지만 X 버튼엔 안 넣어둠
동기화하는 방법을 찾으면 좋을 것 같은데 그것까진 모르겠고
esc에 기능 바인딩 하면서 x 버튼에도 바인딩 하면 좋겠다고 생각함
=> AddHandler로 부착했는데 여러번씩, 계속하면 수십번씩 호출됨
=> 결국 임시로 SettingUIView의 X버튼에 직접 기능을 넣어둠
정안님한테 물어볼 예정

**2럭키**

럭키는 카메라 따로 뒀는데
이미지로 할 땐 멀쩡하더니 스프라이트 렌더러 사용하니까 럭키가 두마리 보임
왤까..........
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/a743c026-514e-40fc-9de5-517a60791d76)

</details>

- #459 

<details><summary> 3회차 작업 </summary>

(12시간 작업 ㅠ)

- [x] 럭키 사운드 추가 (설명시 배경음, 획득시 효과음)
- [x] 로드 시 NPC들 위치 지정
- [x] 로드 시 스테이지와 라플리 위치 지정
- [x] 팩맘 첫 클리어 후 CH1 이동 시 컷씬 2.2 시작
- [x] 컷씬 2.2 대사 구현
- [x] 동굴 막기 (빠른 완성을 위한 임시조치)
- [x] 컷씬 2.2 이동 구현
- [x] 컷씬 3 구현
- [x] 3매치, 마마고 컴퍼니 가면 NPC 3인방 비활성화
- [x] 3매치 퍼즐 스테이지1 럭키 구현
- [x] 3매치 퍼즐 스테이지3 럭키 구현
- [x] 컷씬 3.1 구현
- [x] 컷씬 4.0 구현
- [x] 컷씬 4 상호작용 구현
- [x] 마마고 상호작용 구현
- [x] 비글, 진도 상호작용 구현
- [x] SLG팩 대사 출력, 씬4 전에 막아두기
- [x] SLG 럭키 구현
- [x] 마마고 건설 이후 연출 (컷씬 5.0)
- [x] 마마고 애니메이션 제작
- [x] 마마고 내부 연출 (컷씬 5.1)
- [x] 마마고 콜라이더 설정
- [x] 마마고 건설 이후 상호작용
- [x] 컷씬 56 제작..

### 메모

2차원 배열 [참고](https://dooding.tistory.com/23)

</details>

- #460 

---

## 4회차 간단 작업

(약 1시간 반)

- [x] Main씬 (새로시작/로드화면) 빌드에 포함
- [x] 기화님이 새 사운드 반영
- [x] 럭키 3매치 생선 터트리기
- _===0515 2차 빌드본===_
- [x] 3매치 confiner 수정
- [x] 럭키 SLG 설명 전 초기 위치 지정
- [x] 동굴에서 맵3 이동한 이후 NPC 위치 이상함 (라플리가 너무 빨리 넘어갔나봄)
- [x] 럭키 스테이지3 물고기 여러번 설명 안하게
- [x] 럭키 오류 수정 ❗❗❗❗❗ (임시로 3초 뒤 자동으로 넘어가게 설정)
- [x] 설정창 글씨 추가 (배경음/효과음 구분)
- _===0515 3차 빌드본===_
- [x] 네임박스 활성화 비활성화 오류
- _===0515 4차 빌드본===_
- [x] 맵 흔들릴 때 파머 점프 X
- _===0515 5차 빌드본===_

(4.5회차, 약 4시간)
- [x] 맵 넘어갈 때 NPC들이 먼저 사라지고 먼저 나오는 타이밍 이슈
- [x] CH1 창모드 시 정상 사이즈로 출력
- [x] 맵3 겹친 리소스 레이어 순위 설정
- [x] 설정 UI 조금 더 예쁘게
- [x] 글자 화질 개선
- [x] 맵3 오브젝트 화질 안좋은 거 수정
- [x] 마마고 가면 마마고 컴퍼니 브금 들리게
- [x] 동굴 들어가면 동굴 브금 들리게
- [x] CH2 폰트 변경

---

### 수정예정1

- NPC가 라플리가 말 거는 방향으로 돌아보도록 (빨리 구현 되면 후딱 넣고..)
- 스테이지 로드 코드 체크
- 페이드 애매한 부분 수정
- MapFront 처리
- 팩맘 설정창 활성화 시 다이얼로그 인풋, 움직임 막기
- 이미지 깨짐 ~(특히 파머 걸어갈 때)~
- 팩맘 시작할 때 라플리 위치가 정 중앙이 아닐 때가 있는 오류
- 씬 1.1에서 라플리가 두리번거리는 것 추가? (누가 주인공인지)

### 수정예정2

1
라플리와 오브젝트 처리
- 라플리의 머리와 발 콜라이더를 따로 제작
- 라플리 위(뒤)에 오브젝트가 있다면 라플리가 앞으로 오며 발 콜라이더와 충돌
- 라플리 아래(앞)에 오브젝트가 있다면 라플리가 뒤로 가며 머리 콜라이더와 충돌
- 그 외 동굴 입구 등은 아마 머리
- NPC들은 라플리와 Y좌표 비교해서 레이어 오더 변경?

2
안쓰는 리소스(특히 아트) 삭제 해야함

3
대사 넘기는 테스트 모드
AutoAdvance 체크, 0
UseTypewriterEffect 해제

4
팩맘 먼지들 대사 수정해야하는데
급하지 않으니 이건 나중에.........

5
맵 1, 2, 3 넘어갈 때 이전 y값 참고하면 좋을 듯

6
요청
민지님?/ 오프닝 일러스트 요청
민지님/ 화살표와 스페이스바 돌 주변에 esc도 추가 요청하기
민지님/ 럭키 폰트, 말풍선 요청
수빈님/ 다시 말 걸 때 상호작용 대사 달라지게(최소 2가지씩)
수빈님/ 다이얼로그 파일 쓰는 방식 공유
이우님/ 팩맘게임팩 주변 돌처럼 자잘한 돌들 더 요청
기화님/ CH2 배경음 요청

7
상호작용 인식률 구림
라플리에게 상호작용용 콜라이더 추가

8
엑스트라 NPC 추가..? 아트는 있던데

**Comment by wooyn730** [comment]
[0512 빌드본](https://drive.google.com/file/d/1F2Dn8jDulgPK55qwfL7AuqXxhbvtl-sD/view?usp=drive_link) 드립니다 😱

**Comment by royalbluesm** [comment]
팩맘 관련해서 중대한...? 버그 발견했는데 여기다 적어드리면 되나요?

**Comment by wooyn730** [comment]
@royalbluesm 
네..................... ㅜㅜ

**Comment by royalbluesm** [comment]
https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/1cd479a5-2d81-4b27-91bf-713c4417568a
동영상에 잡음이 좀 있으니 양해를... 팩맘 들어가서 인트로 진행중이었을 때 설정창을 두번정도 껐다 켰는데 설정창을 켰을때만 게임이 되고 반대로 설정창을 끄면 게임이 굳어버립니당

**Comment by wooyn730** [comment]
감사합니다! 쫄았는데 다행히도 아는 친구네요..(?)
설정창 X 버튼이 esc와 동기화가 제대로 안 되어있어서 그런 것 같습니다~~
후딱 고쳐보겠습니다 👍

**Comment by royalbluesm** [comment]
휴~~~ 파이팅!!

**Comment by Sumindd** [comment]
일단 현재 빌드 기준 피드백입니다! 이미 알고 있는 것도 많을 것 같아서 나중에 수정하실 때 확인만 해주시면 될 것 같습니다!

- 오프닝 컷씬에서 NPC얼굴이 보이면 2챕터에서의 임팩트가 떨어지지 않을까 염려됨.. 연출을 바꿔야 할 듯
-> 오늘 연출 정리해서 코멘트 달아두겠습니다! 
- 라플리 collider를 하반신 범위로 줄여야할 듯.. 이로 인해서 생기는 오류를 고치더라도.. 탑뷰라서 가까이 못 다가가는 게 어색하고 충분히 지나갈 수 있어보이는 공간에서 모두 이동이 막힌다.
- 전체적으로 맵과 글자의 화질이 깨져있다.. 
- 상호작용 space bar로 변경했는데 여전히 E 키이다.
- 컷씬이어도 스크립트 넘어가는 것은 space bar로 해야 함. 지금은 맵1에 있는 배경 속 키보드 오브젝트 볼 시간 여유가 없다.
- 맵1에서의 이동은 NPC들 걷는 애니메이션 속도와 맞춰야 할 듯(지금 너무 빨라서 미끄러짐)
- 현재 팩맘을 먼저 건들 수 있다. 양쪽을 아예 막아야 함
- 팩맘 끝나면 다시 오프닝으로 돌아가는 오류가 있음(이 이후 장면에 배경 사라지는 오류도 생김)

**Comment by wooyn730** [comment]
[0513 1차 빌드본](https://drive.google.com/file/d/1wFGtQukTOTLhvezh_2JlzyraFY25Isry/view?usp=drive_link)입니다!
저녁 9시쯤 2차 업로드할 예정입니다.

이슈에 완료된 작업, 예정인 작업 내역 참고해서 플레이해주세요!

특히 팩맘 사운드와 3매치 효과음 볼륨 확인 후 피드백 부탁드립니다.
(저는 코인 먹는 사운드 말고는 조금 작은 것 같습니다)
(3매치 효과음 타이밍 수정은 정안님께 요청드릴 예정입니다)

++
마마고 컴퍼니 직원 줄이자는 의견이 있던 걸로 기억해서 이렇게 배치해봤는데 괜찮나요?
![스크린샷 2024-05-13 143655](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/d04b9178-8deb-45a8-b955-4ddf9942a6c0)

**Comment by wooyn730** [comment]
[0513 2차 빌드본](https://drive.google.com/file/d/1Ox08JQ5eaC2s5Ya4qoOiFk7j2dwZuoz3/view?usp=drive_link)입니다.

작업 내용은 이슈 참고해주세요!

타이틀-CH1 씬1.1-팩맘(럭키)까지 진행되었습니다.

**Comment by Sumindd** [comment]
0513 2차 빌드본 확인했습니다!

- 오프닝 컷씬 0.04에서 다같이 걸어갈 때 파머 깨짐
- 리소스 조사에서 레이어 순서(파머 위에 라플리 어색)
![스크린샷 2024-05-14 013637](https://github.com/GG-Studio-990001/Grayed-Game/assets/84775854/0b75011f-047d-4eb4-a1b9-b6b69b093a1e)
- 럭키 sfx/bgm 추가 필요
- 설정창에 스크롤 조절 각각 어떤 설정인지라도 추가하면 좋을 것 같습니다!


럭키 너무 귀여워요! 고생 많으십니다..

**Comment by wooyn730** [comment]
[0515 빌드본](https://drive.google.com/file/d/1KR-D10kxh13YDLFF9Y3aKAENKvlLEZcz/view?usp=drive_link) 입니다
일단 끝?인데? 챕터2까지 있습니다

확인부탁!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
저도 바로 확인하려구요.......

**Comment by wooyn730** [comment]
3매치 퍼즐 스테이지3에서 럭키에서 잠깐 딴짓했는데 오류난 거 같음

키우면 좋겠는 사운드
- 타이틀
- 팩맘 오프닝 사운드
- 럭키 사운드
- 팩맘 엔딩 사운드

**Comment by wooyn730** [comment]
럭키 SLG 설명 중 끄면 진행 안됨

**Comment by wooyn730** [comment]
대사도 임의로 수정한 부분이 있습니다....
씬6에 알투몬 혼자 계속 말하는 부분(길어서) 등등..

**Comment by Sumindd** [comment]
2차 빌드 피드백

> 오류

- 팩맘 다시하러 가는 길에는 3매치가 클리어 상태로 남아있는데 팩맘을 하고 돌아오면 다시 미클리어 상태임
- SLG 말풍선 리스폰이 안 됨
- 럭키의 행운이 필요해?말고도 SLG 설명하러 나와서 멈추기도 함.. 
- 마마고 컴퍼니 완공 시, 자동으로 마마고 컴퍼니 안으로 들어가지는 것이 아니라 마마고가 밖에서 마마고 완공 후 대사를 하고, 마마고 컴퍼니로 입장 후, 라플리가 직접 걸어서 마마고 컴퍼니로 입장해야 합니다!
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/84775854/39ff15f8-eb6c-41f3-a725-939c8f323d56)
- SLG 재료 부족할 때만 글자색 빨간색이고 필요량 이상이면 파란색입니다! (당연히 이해할 거라 생각하고 기획서에 생략했습니다.. 좀 더 자세히 작성하겠습니다ㅠ)

> 추후 수정 권장

- #271  SLG 말풍선/버튼 클릭했을 때 사운드 추가 
- 마마고 컴퍼니 직원들도 잡다한 대사 있으면 좋을 것 같습니다.
- 마마고 컴퍼니 내부에서 마마고 의자 뒤쪽으로도 이동 가능하게 collider 수정해주시면 좋을 것 같습니다

오늘도 너무너무 고생 많으셨습니다!!! 빌드본으로 직접 보니까 너무 좋네요..

**Comment by gomgom172** [comment]
쭉 이어지게 보니 정말 감회가 색다르네요...!
최대한 지금까지 안 적힌 것 위주로 적어봤습니다!

- 팩맘 처음 접속인데 다회 접속 대사(또 왔어?) 출력되는 오류(럭키도 안 나옴)
- 팩맘 클리어 후 초기 위치(라플리 떨어진 곳)으로 돌아감
- 팩맘 플레이 중 클리어 정산 화면에서 먼지 말풍선들 나올 때 있음 (으악 청소기다! 같은 거)
- 럭키랑 얘기할 때 스페이스 바 누르면 멈출 때가 있는 듯?

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/fc6d390c-2ff2-4da3-affb-183266cdba50)
- 마마고 건설 팝업 글자 튀어나옴

- 가장 최신 버전 스크립트인지 확인해 주시면 좋을 것 같습니다. s2부터의 파일은 0509가 최신인 것 같은데, 인게임 스크립트와 드라이브의 스크립트가 다른 것 같아요. 지웠다 깔아도 게임 리플레이가 안 돼서 재확인은 못했습니다... 착오면 넘겨주세요!


급하지 않은 부분의 감상

- R2몬 이야기할 때 물결표보다 @#$#@ 이런 계열로 들어가는 게 어떨까 싶은 의견 (NPC들이 떠드는 소리 연출인가? 싶게 읽힐 때가 있어서)
- 처음 캐릭터들이 라플리에게 자기 가치 증명하라고 할 때 스토리 흐름이 좀 빠른 것도 같아서, 라플리가 떨어진 후 자유행동 타임 주고 캐릭터들 지나서 걸어가려고 하면 못 간다 넌 우리 소유다 가치 증명해라 말해도 좋을 것 같음


작업량이 어마어마하셨을 것 같은데 너무 고생 많으십니다bb

**Comment by wooyn730** [comment]
### 수민님과 이우님 피드백 체크

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/4855c11c-5d55-428d-aeae-b9483ea75d00)
수민님이 말씀하신 오류 2~4번은 SLG에서 럭키가 한 번 멈춰서 연쇄적으로 발생하는 오류입니다
럭키 오류 빨리 찾아보겠습니다..ㅠㅠ 근데 예상이 안되네요

> 팩맘 플레이 중 클리어 정산 화면에서 먼지 말풍선들 나올 때 있음 (으악 청소기다! 같은 거)

고친 줄 알았는데 한 번 더 체크해보겠습니다!

> 팩맘 처음 접속인데 다회 접속 대사(또 왔어?) 출력되는 오류(럭키도 안 나옴)

이거는 세이브파일이 남아있는 문제일 겁니다
이우님이 말씀하신 다른 버그 중에 세이브파일 이슈가 또 있을수도...

> 럭키랑 얘기할 때 스페이스 바 누르면 멈출 때가 있는 듯?

현재로서 가장 치명 버그..

> 가장 최신 버전 스크립트인지 확인해 주시면 좋을 것 같습니다.

제가 개발하면서 임의로 스크립트를 수정한 부분이 있습니다 ㅠㅠ (예: 럭키가 3매치에서 하나를 밀어 터트리는 것을 보여줌 => 개발 속도상 말로만 설명하는 걸로 일단 수정)

> 마마고 컴퍼니 내부에서 마마고 의자 뒤쪽으로도 이동 가능하게 collider 수정해주시면 좋을 것 같습니다

간단한거라 바로 수정..했는데 마마고 뒤로 이동하면 카메라가 한번씩 흔들리네요?
일단 지나갈 수 있게 해두고 카메라 튕기는 건 한 번 더 확인해봐야겠습니다

나머지 추후 수정과 감상 부분도 충분히 동의하는 부분입니다!
피드백 감사합니다

**Comment by gomgom172** [comment]
빠른 확인 감사합니다!
스크립트 부분은 이전에 수빈님께서 파일 전부 검수해 주셨는데 인게임에 검수 전 파일로 들어있는 것 같아서 말씀드렸어요! (마찬가지로 착오면 넘겨주세요) 우연님께서 따로 호흡 조절해 주신 부분은 다 좋은 것 같습니다👍

**Comment by wooyn730** [comment]
0509 파일로 넣었다고 생각했는데 전 파일인 부분 말씀해주실수 있을까요? 잘 모르겠네요..
(팩맘은 아직 적용안됨...)

**Comment by wooyn730** [comment]
[0515 2차 빌드본](https://drive.google.com/file/d/1DRJuyGD33cJD91C-1EeRuXh51Iyf5QSr/view?usp=drive_link)

**Comment by gomgom172** [comment]
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/821707ec-16df-45b3-9ea3-6c2343c76b9f)
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/536a92b4-2aa1-457d-bbdb-6e75708b0cf3)
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/78e926ad-7df5-457d-8638-898ee56a0e99)

올려주신 빌드로 다시 확인해봤습니다!
s2 파트부터 이전 파일인 것 같습니다.
(진행에는 문제 없으니 시간상 급한 부분 먼저 봐도 괜찮을 듯싶긴 하지만요!!)

새로 시작하기로 들어가니 팩맘 대사/럭키 안 나오는 문제는 전부 해결됐습니다!

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/557e4aad-3a01-4c5b-b788-5fc1c25389c2)

럭키 등장 이후 해당 지점으로 올라가면 럭키가 다시 등장하는 오류가 있습니다! 추가 발견하여 적어둡니다.

**Comment by wooyn730** [comment]
아하 말줄임표랑 띄어쓰기 같은 부분이었군요!!!
내용 같아서 읽어보고 뭐가 다르지?? 이랬네요 예리하시네요

일단 럭키 먼저 우선순위로 두겠습니다

> 럭키 등장 이후 해당 지점으로 올라가면 럭키가 다시 등장하는 오류가 있습니다! 추가 발견하여 적어둡니다.

헉 확인이요! 감사합니다~

**Comment by roweclaw** [comment]
제가 드디어 챕터2까지 플레이를 다 해봤습니다!!! 만세!!!

---

### 3매치 3라운드 럭키 "행운이 필요해?" 이후 멈춤 문제

껐다가 다시 켜서

- 새로하기 -> 같은 문제 발생
- 이어하기 -> 넘어가짐

---

### SLG UI 럭키 "뚝딱뚝딱.." 이후 멈춤 문제

껐다가 다시 켜서 
- 이어하기 -> 럭키는 안나오지만 플레이는 가능

---

다른 버그들은 이미 수민님과 이우님이 말씀해주신 부분과 같아서 생략하겠습니다.
우연님 너무너무 고생 많으셔요 👍👍

**Comment by wooyn730** [comment]
ㅋㅋㅋㅋㅋ 수빈님 축하드립니다
끝까지 하는 게 이렇게 기쁠줄은.. 🥲

제출용으로 럭키 3초 후에 자동으로 넘어가는 것도 넣어놨는데
여유 되시는 분들은 마지막으로 럭키 잘 되는지만 확인해주시면 감사하겠습니닷

[0515 3차 빌드본](https://drive.google.com/file/d/12m4ZkV8QK639EuIb4pLGCr7HEWW5hzGh/view?usp=drive_link)

**Comment by wooyn730** [comment]
럭키 스페이스바 안눌려도 넘어가는거 확인했슴다 ㄴㅇㅅ

**Comment by roweclaw** [comment]
저도 럭키 막혔던 부분에서 잘 넘어가지네요! 굿ㅎㅎ

**Comment by jeongopo** [comment]
5차 수정본 플레이해보다가 버그발견해서 여기다 제보하면 될까요?
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/521b0b8f-8749-4323-8d37-96c98e539f13)

3매치 3스테이지에서 스페이스바 연타하면서 밀었더니 한칸 더 밀려버림 .. 다른거 가지고와도 완성이 안돼서 길이 막혀서 진행을 못하네요 ..!

**Comment by fkdl0048** [comment]
3match 퍼즐 버그 확인해보겠읍니다

**Comment by jeongopo** [comment]
혹시 SLG 버그 어떻게 재현되나요?
제가 지금 해봣을때는 정상출력돼서 ..
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/cc3946c2-1507-420a-a60d-cafd9bdaad22)

**Comment by wooyn730** [comment]
저도 SLG 버그 몇번 떴었는데 저장데이터 꼬였을 때 그러는 거 같기도 해요

**Comment by jeongopo** [comment]
흠 진행정보가 저장이 안되는경우가 있나보네요 🤔

**Comment by fkdl0048** [comment]
3Match 퍼즐 안터지는 버그 해결해서 올려뒀습니다.

**Comment by Sumindd** [comment]
### 5차 빌드본 피드백

- 팩맘 승리 사운드 키워야 할 듯.. 들리긴 하는데 상대적으로 작다 
- 럭키가 물고기 젤리를 두고 가면 바로 터지는 것이 아니라 뒤쪽에서 젤리 하나 더 가져와서 해결하는 기믹인데 지금은 럭키가 두고가면 바로 터짐
- 마마고 컴퍼니 브금이 정작 마마고 컴퍼니 내부에선 안 나옴(ㅋㅋㅋㅠ)
- 여전히 석재 목재 말풍선이 리스폰 안 됨ㅠㅠ (만약 이거 이번에 고치기 어렵다면 옆 맵으로 다녀오라는 NPC 멘트로 하나 바꿔둬서 힌트라도 줘야할 듯..)
- 종료했다가 이어하기 하면 3매치 퍼즐 클리어 기록 날아감(다시 리셋) / 팩맘 다시 플레이하고 돌아와도 기록 날아감


> 추후 수정 권장

- 라플리가 말을 거는 방향으로 NPC들이 돌아보면 좋을 듯
- 하단 건설 아이콘..필요할까? 없으면 허전할 것 같긴한데 있을 거면 기능을 만들어줘야 할 듯.. 필요한 재화 빠르게 보기라던지
- 타이틀 화면에서 낙하할 때 옆에 리소스 쌓인 배경도 같이 빨라지면 좀 더 좋을 듯.. (라플리 낙하 속도 보다는 좀 느리게)

전체적으로 오류 많이 줄어서 너무 좋습니다! 파이팅!!!

**Comment by wooyn730** [comment]
> 팩맘 승리 사운드 키워야 할 듯.. 들리긴 하는데 상대적으로 작다

@Songkihwa 

팩맘 승리 사운드랑 인트로 도로롱?? 같은 일부 사운드 작은게 있어서 체크해서 다시 주시면 좋을 것 같아요

<br>

> 럭키가 물고기 젤리를 두고 가면 바로 터지는 것이 아니라 뒤쪽에서 젤리 하나 더 가져와서 해결하는 기믹인데 지금은 럭키가 두고가면 바로 터짐

헉 이건 제가 플로우 구체화랑 피그마만 보면서 작업해서 몰랐습니다...

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/8c66a428-b2af-4a8c-8061-65a1f25b9d19)
혹시 핑크물고기 두마리 있으면 뭐를 가져오면 터지는 건가요?
(근데 오늘 반영은 어려울듯.. 어차피 추후에 럭키 물고기 애니메이션도 넣어야함)

<br>

> 마마고 컴퍼니 브금이 정작 마마고 컴퍼니 내부에선 안 나옴(ㅋㅋㅋㅠ)

ㅋㅋㅋㅋㅋㅋㅋㅋ 이거 어제 기화랑 얘기하다가 CH2에만 넣어두고 뒤늦게 생각났는데
함 넣어보겠습니다
참고로 동굴 BGM도 따로 받아서 시간 되면 얘도 넣는걸로..

<br>

> 여전히 석재 목재 말풍선이 리스폰 안 됨ㅠㅠ 

이거는 제 파트는 아니지만 원래 옆 맵으로 갔다오면 리스폰 되는게 아닌가요?

<br>

### 수정 권장

> 라플리가 말을 거는 방향으로 NPC들이 돌아보면 좋을 듯

이거 제가 지금 빨리 구현할 수 있으면 넣어볼게요~

<br>

> 하단 건설 아이콘..필요할까?

(제 파트는 아니지만2) 저도 별 기능 없어서 빼도 될듯.. 어차피 이제 뽀글 말풍선(?) 안에 넣는걸로 바뀌었으니

<br>

> 타이틀 화면에서 낙하할 때 옆에 리소스 쌓인 배경도 같이 빨라지면 좀 더 좋을 듯..

저는 사실 라플리 떨어질 때 리소스들 멈췄는데 (이제 땅에 가까워졌다는 느낌으로..) 한 번 빠르게 해볼게요!

**Comment by Sumindd** [comment]
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/84775854/09935f2a-f7fa-4ef5-a3a1-35836fb20029)
- 물고기 젤리가 바로 터지면 유저들이 막혔는지 인지도 아직 안 한 상태로 문제 해결이 될 것 같습니다ㅠ

- 석재, 목재는 라플리가 3발자국 이동했을 때 리스폰이라는 의도였는데 다시 기획서 읽어보니까 헷갈리게 적었네요..
근데 럭키가 부족하면 옆으로 갔다와보라고 하니까 오히려 아무것도 모르고 플레이하면 문제 없을 것 같습니다!!
- 낙하는.. 사실 바꿨을 때 더 나을지 별로일지 감이 안 와서 해보시고 별로면 그냥 원래대로 가도 될 것 같습니다
