### ISSUE TITLE
[Ch1] 캔디크러쉬사가 SFX 수정

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/Grayed-Game#448]
빌드본에 맞춰서 더 딱 맞게 사운드 수정 예정

-------

원래 사운드에서 젤리가 딱 맞춰질 때 나는 사운드 + 애니메이션 모션에 맞춘 사운드 + 터질 때 냐옹 사운드를 추가해서 수정해봤습니다!
[수정한 사운드 영상](https://drive.google.com/file/d/1SIJUL0wYz4brhjoZhrmP3ZpiOj6sgeU6/view?usp=drive_link) 첨부합니당
미는 사운드는 그냥 없는 게 깔끔할 것 같아서 일단 안 넣었는데 혹시 원하신다면 넣겠습니당 편하게 말씀해주세요ㅎㅎ

일단 [냐옹 들어간 사운드](https://drive.google.com/file/d/1xTh3gTQeRRu5tGZ8_Ooo58urljBdwW1E/view?usp=drive_link) / [없는 사운드](https://drive.google.com/file/d/1NXusnoWXTRxHKn-QHc1dp65BLDCTK4f5/view?usp=drive_link) 둘 다 구드에 올릴테니 확인해보시고 괜찮은 거 넣어주세요!

앗 근데 제가 원하는 타이밍은 딱 이 영상대로를 원하는데 혹시 가능할까요? 젤리가 세개가 맞춰질 때부터 사운드가 딱 시작되면 맞을 것 같아서요!! 

피드백 환영합니닷 언제라도 의견 주세요 ㅎㅎ

**Comment by gomgom172** [comment]
영상과 함께 보니 너무 귀엽네요! 👍
저는 냐옹 소리가 들어가는 쪽이 재치 있는 매력이 느껴져서 마음에 듭니다.
작게/짧게라도 젤리 밀 때 사운드가 들어가면 좋지 않을까 싶은데, 젤리 터질 때 사운드가 많으니 깔끔한 편이 좋을까도 싶네요… 다른 분들 의견도 들어보고 정하면 좋을 것 같습니다!

**Comment by wooyn730** [comment]
냐옹 버전 좋아요!!!! 더 귀엽네요 ^_^
저도 미는 소리 적용된 버전도 궁금하네요. 작고 무겁지 않게 들어가면 괜찮을 것 같아요~
