### ISSUE TITLE
[Ch1] R2-Mon 텍스트 사운드 

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/Grayed-Game#449]
#424 속 코멘트의 레퍼런스 참고하여 R2-mon 텍스트 사운드 제작 예정

---------

일단 레퍼런스랑 비슷하게 작업해보려고 했고 기계음이지만 듣기 좋은 소리로 만들려고 노력 해봤습니다!
레퍼런스 게임은 되게 사실적에다가 텍스트가 나올 때 소리가 다 나오는 것도 아니더라구요
2D에서의 텍스트를 생각해서 저번처럼 한 음절씩 나온다고 가정하여 만들어봤습니다. 
[R2-Mon 텍스트 사운드](https://drive.google.com/file/d/1A6tvb4aPVkc2mNu2pG03u5o807ekV2gd/view?usp=drive_link)

오케이 받으면 한 음절씩 끊은 파일 업로드 하겠습니당
피드백 환영입니다 언제든지 수정 가능합니닷ㅎㅎ

**Comment by roweclaw** [comment]
확실히 더 부드러워진 기계음인데 살짝 묵직해서 R2-MON이랑 잘 어울리네요!
듣기에도 좋은 것 같습니다. 저는 이대로 적용해도 괜찮아보여요!!

**Comment by wooyn730** [comment]
저도 괜찮은 것 같습니다 승인 ^_^~
