### ISSUE TITLE
통합 기획서 작성

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/Grayed-Game#453]
- SGM 제출용 통합 기획서 작성 (월요일 작성)

**Comment by Sumindd** [comment]
[통합 기획서](https://docs.google.com/document/d/14LNGWgeF_Op3xxgwabOGhhmHymFvPLhO/edit?usp=drive_link&ouid=102142728386857128653&rtpof=true&sd=true) 작성 중인 문서입니다.
동호님의 총기획서에서 틀만 남기고 전체적으로 수정 중입니다..

**Comment by Sumindd** [comment]
[기획서 1차 pdf](https://drive.google.com/file/d/1I51ZL_Xpp_RbzTFL2ZymoeQPU92G2eSn/view?usp=sharing)
수빈님께 전달 받은 ppt 마저 채웠습니다.
기획 의도를 제가 임의로 적어서 문장 점검 필요하고, 빌드 나오면 스크린샷 추가 해야할 것 같습니다. 확인 부탁드립니다!

[기획서 편집 공유](https://www.miricanvas.com/v/137gpcb)는 이쪽입니다!

**Comment by roweclaw** [comment]
[기획서 2차 pdf](https://drive.google.com/drive/folders/1ay6cV1zOdKE6or1DIlsIzZbb53uh-xEE)
문장 점검 및 디자인 수정 진행했습니다. 아직 스크린샷은 추가하지 않았습니다!

[기획서 2차 편집 공유](https://www.miricanvas.com/v/137m4xr) 링크입니다.

**Comment by wooyn730** [comment]
좋다.. 잘만들었다.....

**Comment by Sumindd** [comment]
[기획서 3차 pdf](https://drive.google.com/file/d/16vATOQ7u4gAchVRO7wiGC7OTG4-NW6wz/view?usp=sharing)
스크린샷 추가하고, 맞춤법 검사기 전범위로 돌려서 오타 수정했습니다. 
잊혀진->잊힌 (지금이라도 익숙해지는 게 나을 것 같음..)

[기획서 3차 편집 공유](https://www.miricanvas.com/v/137mpc2) 링크입니다.

**Comment by roweclaw** [comment]
[기획서 4차 pdf](https://drive.google.com/file/d/1mSKFXIepAyJCvo2XMDIgj45Glm7b3ePB/view?usp=sharing)

읽다가 발견한 사소한 사항들 수정했습니다.
2쪽 : '게임플로우' 목차 삭제, '기존' 시스템의 차별화 ->'기본'
7쪽 : 라플리 설명 중 '잊' -> '잊힌'

[기획서 4차 편집 공유](https://www.miricanvas.com/v/137n6gg) 링크입니다.
