### ISSUE TITLE
전체 사운드 밸런스 중간 체크

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/Grayed-Game#454]
SGM 지원에 대비하여 빌드본에 맞춰서 사운드 밸런스 잡을 예정

------------

팩맘 + 캔디크러쉬 사가 냐옹 사운드 전체적으로 내렸습니다~!!

[캔디크러쉬사가 냐옹](https://drive.google.com/file/d/1nlaEMMOE2iIo8tVRZtndPahIHWGOlCIA/view?usp=drive_link)

[팩맘 리소스](https://drive.google.com/drive/folders/1gF9c-UPHcAMoo2oZsJUr1dM4evyZVJO5?usp=drive_link)

@wooyn730 
이걸로 갈아서 껴주시면 될 것 같습니다!
제가 빌드 확인해보고 또 수정할 시간이 있어야할 것 같은데 혹시 적용하고 화요일까지 빌드본 뽑아주실 수 있으실까요?!

**Comment by Songkihwa** [comment]
우연님 확인해보시고 코멘트나 카톡으로 연락 주시면 감사하겠습니닷

**Comment by wooyn730** [comment]
사운드 디폴트값 0.5로 수정했습니다!
적용하고 오늘 중으로 빌드본 올릴게요~~

**Comment by wooyn730** [comment]
혹시 먼지 사운드도 수정되었나요?

**Comment by wooyn730** [comment]
@Songkihwa 

3 매치 효과음 냐옹 버전이 아니네요...!!

**Comment by Songkihwa** [comment]
앗 링크가 잘못 걸렸나봐욧 구드에 있는 meow  파일 사용하시면 됩니다!!!!ㅠㅠ

**Comment by wooyn730** [comment]
파일 위치도 주세요..! 못찾겠어요 ㅠ

**Comment by Songkihwa** [comment]
[타이틀 수정](https://drive.google.com/file/d/1uSgrRhJokNWQZHyAx27Z1sJeXFbstPl7/view?usp=drive_link)]

[럭키 비지엠 수정](https://drive.google.com/file/d/1-N0iSdYM9O7-4Bl7C6X2qMnY4VDiuSeh/view?usp=drive_link)
