### ISSUE TITLE
[CH1 Main] 마마고 컴퍼니, 라플리 리소스 수정

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/Grayed-Game#457]
마마고 리소스, 라플리 짤리는거 리소스 수정했습니다
https://drive.google.com/drive/folders/1Ev4wLdt2JVngAtFRKGvI_zRAjLE3gCDj?usp=drive_link

**Comment by wooyn730** [comment]
마마고 화분에 초록색 풀은요?!!

**Comment by royalbluesm** [comment]
빨리 올려드릴래다가 실수를... 다시 올렸습니다 (머쓱)
