### ISSUE TITLE
0.0.1 빌드 제출용 이슈

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/Grayed-Game#464]
# 0.0.1 빌드 제출용 이슈

현재 빌드를 기준으로 공모전 제출용 이슈입니다.

본몬에 있는 빌드본을 기준으로 수정사항, 버그등을 코멘트로 남겨주세요.

- [최종 빌드본2](https://drive.google.com/file/d/1Pk9HL3JUvw0YhpAFYO80ivdqWzfVrpJn/view?usp=drive_link)

*빌드본 업데이트는 본문에서만 수정해주세요*

**Comment by fkdl0048** [comment]
빌드 기준 제출전에 적용되면 좋을 것 같은 몇가지

- Main씬에서 새로시작, 이어하기, 설정 UI 글씨 영어, 백그라운드 지우기
- 인게임 글씨체 깨짐
- 3Match 퍼즐 3스테이지에서 맵으로 이동할 때 유령 NPC 등장
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/84510455/ca4c9331-4f03-43a8-876e-4c43e1ec99c1)
- 마을 입구 입장하려 할 때 `>` 문자 출력
- 라플리 Layer 동적 스프라이트 적용? (NPC와 라플리 레이어 겹침 문제)

저는 플레이 하면서 치명적인 버그는 발견하지 못했습니다.

**Comment by roweclaw** [comment]
## 버그
### 팩맘

- 팩맘이 하단 오른쪽 맨 구석자리에서 못 움직임 (위로 올라가야 하는데 계속 오른쪽으로 가려고 함.. 벽인데..)
![스크린샷 2024-05-15 192510](https://github.com/GG-Studio-990001/Grayed-Game/assets/92532398/8556ba23-9cc4-4de9-af63-1473051ebfba)

### 3매치
- 2라운드에서 빨간젤리 3개 모았는데 안터짐
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/92532398/9787aa50-0eeb-4d5b-9192-aebd06c30bc2)

- 3라운드에서 빨간젤리 3개 모았는데 안터짐, 그래서 이전 라운드 갔다 왔는데 초기화 안 됨
 ![스크린샷 2024-05-15 191845](https://github.com/GG-Studio-990001/Grayed-Game/assets/92532398/cb627b03-845e-48d8-944a-b966ecddbfd1)

- 다리 부서지기 전에 반대편 동굴 입구로 진입했다가 나올 때 맵 전환되는 동시에 NPC들이 나타남
![스크린샷 2024-05-15 201709](https://github.com/GG-Studio-990001/Grayed-Game/assets/92532398/2b1084f6-7769-41d6-a526-d86cacd167c1)


## 수정사항

- 라플리가 NPC 근처 지나갈때 위로 겹쳐짐 (R2-MON 밟는중;;;)
![스크린샷 2024-05-15 195754](https://github.com/GG-Studio-990001/Grayed-Game/assets/92532398/66c5c3fe-96f9-4663-88e0-7784756564e2)

- S4 마마고 대사 중 '저의 왼편에' -> '제 옆에' (마마고 기준은 왼편이 맞는데 화면 기준은 오른편이라 그냥 '옆'이 나을듯)
![스크린샷 2024-05-15 193345](https://github.com/GG-Studio-990001/Grayed-Game/assets/92532398/505661c3-ef29-42fb-aca9-1122468472cc)

- 선을 기준으로 라플리가 이동함에 따라 동그라미 표시된 리소스가 가려져 있다가 튀어나옴 (혹시 의도된 건가용..?)
![스크린샷 2024-05-15 200707](https://github.com/GG-Studio-990001/Grayed-Game/assets/92532398/bbca22c7-5069-4c51-91ca-fd0953bf5aff)
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/92532398/bf083e47-34a8-43e8-9329-ab41d0682285)

- 마을 입구로 다가갔을 때 진입 불가 대사가 뜨기 전, 아래와 같은 창이 뜸
![스크린샷 2024-05-15 201405](https://github.com/GG-Studio-990001/Grayed-Game/assets/92532398/fb2a5557-a94f-4828-8815-df3b04d06e0e)

## 기타
- 버그인지 뭔지 모르겠는데 럭키 없이도 3매치 3라운드 풀 수 있더라고요... 당황...
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/92532398/ef69f16c-c44a-44a8-b137-ea455140d083)

**Comment by fkdl0048** [comment]
3match 버그는 해결했는데, 지금 빌드본에 포함이 되어 있지 않습니다!
저 물고기는 제거 해야할 것 같습니다.

**Comment by wooyn730** [comment]
### 정안님 수빈님 피드백 체크

> Main씬에서 새로시작, 이어하기, 설정 UI 글씨 영어, 백그라운드 지우기

이거는 어떤 걸 말씀하시는 걸까요?

> 인게임 글씨체 깨짐
> 3Match 퍼즐 3스테이지에서 맵으로 이동할 때 유령 NPC 등장

수정했습니다

> 마을 입구 입장하려 할 때 > 문자 출력

이건 새로 뽑은 빌드에선 확인 안돼서 간헐적인지 해당 빌드본 이슈인지 체크해봐야겠습니다

> 라플리 Layer 동적 스프라이트 적용? (NPC와 라플리 레이어 겹침 문제)

라플리 상호작용 관련해선 추후 수정할 예정입니다

> 팩맘

처음보는 버근데 오ㅐ저래.. 😭

> 다리 부서지기 전에 반대편 동굴 입구로 진입했다가 나올 때 맵 전환되는 동시에 NPC들이 나타남
> 라플리가 NPC 근처 지나갈때 위로 겹쳐짐 (R2-MON 밟는중;;;)

정안님과 같은 내용

> S4 마마고 대사 중 '저의 왼편에' 

다음에 대사 전체적으로 한 번 검토하고 수정해서 주시는 게 나을 것 같습니다!

> 선을 기준으로 라플리가 이동함에 따라 동그라미 표시된 리소스가 가려져 있다가 튀어나옴 (혹시 의도된 건가용..?)

레이어 이슈였으며 현재는 수정하였습니다 (의도 아님 ㅋ)

> 버그인지 뭔지 모르겠는데 럭키 없이도 3매치 3라운드 풀 수 있더라고요... 당황...

이건 기획 잘못 이해한 이슈였습니다..
수민님이 코멘트로도 말씀해주셨고 추후 럭키 물고기 애니메이션과 함께 수정할 예정입니다

**Comment by fkdl0048** [comment]
> 이거는 어떤 걸 말씀하시는 걸까요?

이거는 디자인적으로 검정 배경에 영어 글씨로 수정했으면 하면 좀 더 완성도가 있어 보일 것 같습니다. (현재는 회색 배경에 하얀 버튼 존재)

> 라플리 Layer 동적 스프라이트 적용? (NPC와 라플리 레이어 겹침 문제)

https://www.youtube.com/watch?v=itcRjAjxccE&t=210s

이 방법으로 해결하면 될 것 같습니다.

**Comment by wooyn730** [comment]
본문 빌드본 업데이트 했습니다.

![스크린샷 2024-05-15 205532](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/8e2aaa5b-8a5d-4a0c-bc9f-88e825a3b3bb)
다음과 같은 작업을 하였습니다
(또한 정안님 3매치 수정도 포함되어있음)

화질 개선 방법 몰라서 좀 오래걸렸는데 꽤나 만족쓰;;

![스크린샷 2024-05-15 192100](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/60233a4e-defb-409d-915a-0cd1f2dfc5dc)
![스크린샷 2024-05-15 192232](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/1267ebd2-ab42-439a-8f4b-723d78f3b7c8)

<br>

저는 여기까지....
치명 버그가 있다면 또 오겠습니다..
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/cd894f28-f755-4f10-8e72-09f31a4bbe80)

**Comment by Sumindd** [comment]
### 최종 빌드본1 피드백

- 원래 안 그랬던 것 같은데 맵 bgm이 맵 이동 할 때마다 처음부터 다시 시작되네요,,? 사운드 쪽이 뭔가 꼬인 것 같습니다.. 
- 만능게임번역팩 안 먹고 바로 동굴 갔다가 돌아와서 제대로 플레이 할 때 : 클리어 이력이 있어도 럭키 대사가 변하지 않고, 럭키가 퇴장한 이후에도 1라운드 내내 럭키 브금이 들립니다.. 3라운드 때도 마찬가지고요. 이번에는 무리더라도 순서 꼬아서 플레이했을 때의 상황도 점검 필요할 것 같습니다!

**Comment by wooyn730** [comment]
> 만능게임번역팩 안 먹고 바로 동굴 갔다가 돌아와서 제대로 플레이 할 때

아직 처리 안해서 막아뒀는데.. 더 확실히 막아뒀습니다..

배경음은 체크해보겠습니다 흑흑..

++
![스크린샷 2024-05-15 230542](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/62b7bc4b-90a6-4f34-982b-5cb1fa6972ea)
![스크린샷 2024-05-15 230502](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/f76a1382-18a2-4fa6-8ae3-e0c404563d0f)

테스트하다 꺽쇠 찾았네요 ㅋ큐

**Comment by wooyn730** [comment]
- BGM 다시시작 버그 수정
- 팩맘 전 동굴 확실히 막기
- 경비견 꺽쇠 출력 버그 수정

해당사항 수정 후 본문 빌드 최종본2로 업뎃했습니다~!

**Comment by wooyn730** [comment]
지금 3매치 저장 안되는거 맞나요??

**Comment by fkdl0048** [comment]
현재 버전에서요?
