### ISSUE TITLE
[CH2] 서브 게임 시스템 문서 

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/Grayed-Game#469]
- 서브 게임 2가지 (RPG 인벤토리, TCG)와 접속 게임(2D 횡스크롤) 시스템 문서를 실용성에 집중해서 작성합니다.
- CH2의 시스템 흐름을 정리합니다. 

---
### 240709 업데이트

[CH2 메인 시스템 엑셀 문서](https://docs.google.com/spreadsheets/d/194fhktwPwPIqMRTjkU2daeICYB073aA0bIQ6IXufdyw/edit?usp=sharing)

### 240711 업데이트

[CH2 시스템 기획서](https://drive.google.com/file/d/1zRwkp8zPn0p_Q_EfbkdoYlaQqFzZdnbR/view?usp=sharing)
일단 작성한 부분까지 업로드합니다. 위쪽의 엑셀 문서에 대한 설명을 정리해서 적어뒀습니다. 부가적인 내용은 다음 작업에서 이어가겠습니다! 
(3페이지는 그냥 무시해주세요)

### 240718 업데이트

[CH2 시스템 기획서](https://drive.google.com/file/d/19HHXqHC_Kjx7ShTztDCmGXuajWgvI9lD/view?usp=sharing)
다음주에 보완 예정. 일단 오늘 회의한 내용 정리 위주로 작성했습니다.

**고민 중인 것**
5페이지) TCG 카드 구성 1~3안 중 어느 방향으로 가는 게 좋을지 의견이 궁금합니다..
그리고 만약 이미지 포함 구성으로 간다면.. 무엇을 넣을지..?
![image](https://github.com/user-attachments/assets/792c3fd1-0636-44ae-aad2-2bd2118d4830)

### 240725 업데이트

[광신화 파르테나의 거울 영상](https://youtu.be/2fAJrLE3jXc?si=2c690alWFEgfHXSy)

[[240725] CH2 시스템](https://drive.google.com/file/d/1om8wKcAfcPILBIYyQg1VihfUT2ZrcCCD/view?usp=sharing) 기획서 업데이트

### 240729 업데이트

[CH2 접속 게임 맵](https://docs.google.com/spreadsheets/d/1Snr52RiTjTdEmte3t1v1KVSuucbWzgCWFJLCxDsFQ2s/edit?usp=sharing)

주황색 기본 타일을 기준으로 오브젝트 크기와 위치 잡았습니다.
기획서에도 써뒀지만 라플리는 기본 타일 기준 2칸 높이까지 점프할 수 있습니다!
오브젝트 종류는 써두긴 했지만 그냥 아이디어일 뿐 편하게 다른 오브젝트로 변경하셔도 되고, 만약 크기 조정 원하시면 연락주세요! 맵 수정 가능합니다.

**Comment by Sumindd** [comment]
CH2 메인 시스템 먼저 작성해오겠습니다

**Comment by Sumindd** [comment]
아직 자세한 설명은 안 적었지만.. 미리 확인 필요하신 분들도 계실 것 같아 일단 지금 CH2 메인 시스템 작업하고 있는 문서 올려두었습니다. 대충 이런 양식으로 진행 될 것 같아요. 조만간 자세한 내용 정리해서 업데이트 해두겠습니다!

**Comment by Sumindd** [comment]
240711 업데이트 완료

**Comment by fkdl0048** [comment]
UI적으로 그림판 그림이라도 있으면 좋을 것 같아요. 시스템 문서 내용이 시각적으로 보여주는게 가장 이해가 빠르지 않을까? 싶습니다..!

**Comment by Sumindd** [comment]
이어서 진행하겠습니다!

**Comment by Sumindd** [comment]
240718 업데이트 완료

**Comment by fkdl0048** [comment]
## 피드백

- 저번 회의 때 말씀드렸던 대화 이외에 발생하는 이벤트도 있을 것 같습니다. 현재 스토리 기획상 미카엘 집 탐색 -> 이걸 그냥 대사로 처리할 것인지, 포인트 클릭할 것인지
- 추가로 선택지를 고르는 타이밍에 시간제한이 있다면 (아이디어)
- 더 필요하다고 생각되는 부분들은 TCG장르의 럭키의 개입, 럭키의 존재를 좀 더 부각하는 시스템 기믹들이 필요해 보입니다!
  - 선형적이기 때문에, 나중에 부족한 호감도를 럭키가 끌어올린다 던지?
- 이미지는 게임기 이미지같은건 어떠할지.. 차라리 이미지를 빼는게 가장 좋아보이는데, 대사량 때문에 다 다를걸 생각하면 이미지가 있어야 할텐데, 라플리의 대답과 게임을 신봉하는 미카엘이라면? 게임기 모양이나 리소스가 들어간 형태라면 어떨까 생각해봤읍니다.

**Comment by Sumindd** [comment]
일단 접속 게임 파트 아트나 플밍 작업하실 수 있도록 기획서 업데이트 해뒀습니다!
나머지 내용은 추후 업데이트 예정입니다... 
TCG 카드에 대한 의견은 계속 코멘트 부탁드립니다! 이번주 기획 회의 때 의견을 토대로 확정 지을 것 같습니다.

**Comment by Sumindd** [comment]
CH2 접속 게임 맵 기획 완료해서 본문 업데이트 했습니다.
제가 7/29~8/2까지 외출이라 작업이 거의 불가합니다..ㅠㅠ 그래도 노트북으로 수정 작업이나 질문 답변은 가능하니 필요하시거나 궁금하신 게 있으시다면 개인적으로 연락 혹은 코멘트로 연락 부탁드립니다!
