### ISSUE TITLE
[CH1] 보완 기획

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/Grayed-Game#482]
CH1 빌드본 피드백을 보고 보완할 방식 고민해보기

- [x] 팩맘 코인 개수 (SLG 사용처, 한번 더 해야 하는 경우에 대해서)
- [x] SLG 자원 리스폰 되는 기준 정확히
- [x] SLG-팩맘 동선 리뉴얼?
- [x] 팩맘 기타 요소 리뉴얼(팩맘 이기는 법 설명 방식)

### 팩맘 코인 개수 (SLG 사용처, 한번 더 해야 하는 경우에 대해서)

아직 굳이 바꿀 이유 없다고 생각함. 럭키 파트 리뉴얼 후에 다같이 팩맘 플레이 해보고 평균 코인 습득량 체크 후 조정하면 될 것 같다.

### SLG 자원 리스폰 되는 기준 정확히
말풍선 클릭으로 하나 없앨 때마다
**1안) 3초 후 말풍선 리스폰** (확정)
2안) 3발자국 이동 후 리스폰 

3발자국이 조금 번거로울 수도 있어서 그냥 3초 후마다 리스폰 해도 괜찮을 것 같다. 재화 수급만 계속 랜덤으로 할 수 있다면 방식은 크게 관계 없기 때문에..

### SLG-팩맘 동선 리뉴얼
팩맘의 위치를 변경하기는 어려울 것 같다.
대신 이동 거리를 단축 시킬 수 있는 다리 건설을 추가한다.(선택 사항으로) 코인 없이 소량의 목재(20개)만 요구한다.

### 팩맘 기타 요소 리뉴얼(팩맘 이기는 법 설명 방식)
유저에게 집중력+럭키에 대한 애착을 부여하려면 모션을 통해 설명하는 것이 제일 효과적이기 때문에 팩맘 튜토리얼을 좀 더 구체화 해봤습니다.
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/84775854/ad53fa91-bec3-43b2-80b6-ecb490d38a56)

----
### 240601 업데이트

**SLG 자원 리스폰**
- 3초 후 리스폰으로 기획 회의 때 컨펌 완료
- 말풍선 클릭 시, 말풍선 속 오브젝트(목재/석재)가 UI 쪽으로 빠르게 쭉 빨려드는 애니메이션
- 말풍선이 터지고 3초 후 빈 자리 중 랜덤으로 말풍선이 리스폰 된다. 오브젝트는 터진 오브젝트의 종류와 관계 없이 목재 50%, 석재 50% 확률 유지
- 슝 빨려 들어가는 애니메이션에 들어갈 슝 사운드도 있으면 좋을 것 같습니다. (슝은 목재/석재 사운드 통일)
- [슝 애니메이션 레퍼런스(돈 빨려 들어가는 애니메이션)](https://youtu.be/ZOiT18ixuUc?si=bV8ozOOoEjVU-szL&t=5908) 
- 터지는 애니메이션과 슝 애니메이션 중 고민했는데 직전 3매치 퍼즐에서 터지는 애니메이션이 들어가서 중복되지 않는 방향으로 하는 것이 좋을 것 같아 슝으로 선택했습니다.

**Comment by Sumindd** [comment]
본문에 업데이트 했습니다.

**Comment by Sumindd** [comment]
SLG 자원 리스폰 관련 기획 회의에서 컨펌 받아서 상세 내용 업데이트 했습니다.
현정님과 기화님 참고하시면 될 것 같습니다!
@jeongopo @Songkihwa

**Comment by Songkihwa** [comment]
제가 내일 자격증 시험이라.. 시험보고와서 작업해두겠습니다 ㅠㅠ

**Comment by wooyn730** [comment]
### 팩맘 기타 요소 리뉴얼(팩맘 이기는 법 설명 방식)에 대해

> 유저에게 집중력+럭키에 대한 애착을 부여하려면 모션을 통해 설명하는 것이 제일 효과적

이 부분은 동의합니다만 다른 생각이 있어 몇가지 남겨둡니다.

1. 설명 친절함의 정도

팩맘이 룰이 간단한 편이라고는 할 수 없지만 모션을 추가하고 코인을 주고 받는 연출을 추가해가면서까지 자세히 설명해야할 필요가 있는지 궁금합니다. (현재 텍스트로는 부족한지)

2. 비용 관련 (제일 중요한 부분)

당연한 말이지만 연출을 추가하는 만큼 개발 비용이 증가합니다.
또한 접속 게임의 설명에 이 정도의 정성을 쏟는다고 하면 다른 접속 게임에도 비슷한 연출이 들어갈텐데.. 연출은 재활용되는 부분도 아닌데 이 정도의 연출이 비용을 고려하더라도 가치가 있는지 궁금합니다.

3. 조잡함

현재 럭키 뒤에 별다른 불투명한 배경을 두지 않았기 때문에 럭키와 같은 레이어에 팩맘과 코인을 두고 연출을 하면 화면이 조금 조잡해 보일 것 같습니다.. 연출이 필요하다면 좀 더 깔끔하게 넣을 수 있는 방법을 고려해보면 좋겠습니다.

**Comment by Sumindd** [comment]
### 우연님의 피드백에 대한 답변
1. 일단 제가 직접 플레이 했을 때 이 룰에서 승리하기 위한 가장 쉽고 중요한 조건은 **팩맘을 청소 시간 외에 잡아서 코인을 뺏는다.** 라고 느꼈습니다. 그래서 이 룰이 있는 한 무조건 설명해야 하는 요소라고 생각합니다. 리소스 문제로 강조까진 못하더라도 최소한 언급은 확실하게 하고 가야 할 것 같습니다. 설명을 짧게 가고 싶다면 설명 생략이 아니라 차라리 이 룰 자체를 삭제해서 게임을 간략화 하는 방향이 맞다고 생각합니다..

2. 쫓는다는 게 결국은 럭키가 달리는 모션 1개(팩맘은 어차피 발이 없어서 걍 빠르게 위치 이동만 시키면 됨) + 좌우 반전만 해도 돼서 애니메이션 중엔 가장 비용이 적게 든다고 생각합니다.. 회의 때 아트 분들의 의견을 들어보면 좋을 것 같네요

3. 사실 저는 퀄업에서 당연히 애니메이션이 들어갈 것 같아서 배경을 불투명하게 하는 방향을 고민했고, 역시 지금도 이 부분이 고민 됩니다..  
지금 떠오르는 방법으로는 배경과의 이질감이 덜 들고 녹아들 수 있도록 팩맘과 럭키의 크기를 줄이는 방법입니다. (접속 직후라 먼지 말풍선은 안 뜨니까 무시 부탁드립니다!) 유저 입장에선 화면에서 움직이는 요소에 눈길이 가기 때문에 이질감을 줄이려면 배경에 최대한 활용하는 방향으로 접근해야 할 것 같습니다. 
![Group 52](https://github.com/GG-Studio-990001/Grayed-Game/assets/84775854/e652dfb8-2477-4f54-a3f1-ac873172d079)

럭키 파트는 애니메이션이라 확실히 비용이 들어가기 때문에 좀 더 팀원들의 피드백을 받은 후에 진행하면 좋을 것 같습니다. 항상 정성스러운 피드백 감사합니다!
