### ISSUE TITLE
[CH1] SLG 사운드 제작

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/Grayed-Game#483]
이슈 생성하는 걸 깜빡했었네요 -- SLG 시스템 필요 사운드 제작하여 곧 업로드 할 예정입니다!
마우스 클릭음 / 자재 획득음 / 마마고 컴퍼니 건설음 등 .. 혹시 제가 빼먹은 거 있으면 코멘트로 적어주시면 감사하겠습니다!!

0602
SLG 마마고 컴퍼니 뚝딱뚝딲 음 + SLG팩 획득음 추가 예정

-----

[마우스 클릭음](https://drive.google.com/file/d/1mYt7rzUdvl_ZZvNf8RJb6QdGA91qfdZP/view?usp=drive_link)

[돌 획득음 ](https://drive.google.com/file/d/1Pbwu1tMPVzevGQZquXLMcZpWSVHW5i45/view?usp=drive_link)

[나무 획득음](https://drive.google.com/file/d/1fy-dSbYhIJTqxZg4gbFwmwn5VMPHHxd2/view?usp=drive_link)

이외에 SLG 팩 획득했을 때 어떤 소리가 들리면 좋을까요 ..? 의견 있으시면 주시면 감사하겠습니다!

------
0614

[마마고 컴퍼니 건설축하](https://drive.google.com/file/d/1NuuLQejcqdPEa3yuIRaXmoIIZY63Sgd0/view?usp=drive_link)
사실 요건 동물의 숲 조금 따라하긴 했어요 박수치면서 건설 축하해주면 좋을 것 같아서 ..ㅎ
별로면 빼겠습니다!!!

[마마고 컴퍼니 뚝딱뚝딱음](https://drive.google.com/file/d/1A_mvcas6eLM5u4q74xiFeTOgTXIuQBlA/view?usp=drive_link)
생각보다 넘 사실적으로 작업된 것 같긴 한데 일단 뚝딱뚝딱이긴 합니다.. 

[SLG 게임팩 획득음](https://drive.google.com/file/d/1qwFVA5VIg0dPEwaUOQa_JjUBwpqBU_ul/view?usp=drive_link)
우연님이 말씀해주신 공사장 소리는 넘 시끄럽고 효과음으로는 안 묻는 것 같아서
뭔가 장착되는 듯한 느낌 + 망치로 두들기는 소리 넣긴 했는데 뭔가 느낌이 안사네요 ..

제 마음에 썩 들지는 않지만 시험 기간이라 더 작업할 수가 없어서 .... 흑
들어보시고 고칠 부분 있으면 고치겠습니다! 재작업도 가능합니당!!!!

**Comment by wooyn730** [comment]
오 이번 효과음 몬가 ASMR 같아요 좋아요

> SLG 팩 획득했을 때 어떤 소리가 들리면 좋을까요 ..?

이건 좀 어렵네요
지금 팩 모양 망치로 나왔으니까 망치소리 + 공사장 소리...?

**Comment by wooyn730** [comment]
추가된 사운드 제가 적용하겠습니다~

**Comment by fkdl0048** [comment]
전체적으로 적용되고 어떤 느낌인지 보고 피드백을 드리면 좋을 것 같지만, 지금 추가 해주신 사운드는 전체적으로 게임틱한 사운드는 아닌 것 같습니다..

샤워하다가 생각이 난 내용으로 사운드 자체도 해당 장르에 통일성을 가져도 좋을 것 같다는 생각이 드네요,, 지금처럼 기준이 정해져 있지 않아 해당 리소스 게임의 사운드도 너무 좋지만, 이게 많이 어렵고 게임틱하지 않다면, 1챕터 장르인 쯔꾸르, 2챕터 미연시 등의 장르의 사운드의 피치나 색깔만 참고해서 통일성을 보이지 않게 유지하는 것고 방법일 것 같습니다.

**Comment by Songkihwa** [comment]
게임틱 하지 않다는게 범위가 넓어서 잘 이해가 되지 않아서 그러는데 

사실적이여서 게임틱하지 않게 들리는걸까요?

그냥 게임틱하지 않다는 말만으로 제가 알아서 재작업을 진행하기에는 또 어긋날 수도 있겠다는 생각이 들어서 자세하게 여쭤보는건데
정안님이 생각하시는 게임틱한 사운드가 무엇인지, 
또 지금 장르에 들어가야하는 사운드가 어떤 색깔이였으면 좋겠는지
(예를들면 귀여운, 뿅뿅거리는, 8bit스러운, 기존에 나온 SLG 장르와 똑같게 라는 식으로) 

정안님 머릿속에 있는 사운드의 색깔에 대해 저한테 방향성을 잡아주시면 훨씬 좋을 것 같습니다. 
레퍼런스가 있다면 들려주셔도 되고 게임을 레퍼런스로 잡아주셔도 좋을 것 같습니다. 
그만큼 더 자세하게 얘기해주시면 좋을 것 같습니다.

또 지금 이슈에 올린 사운드들 전부 다 재작업을 원하시는건지, 아니면 유독 그렇게 느낀 사운드들만 재작업을 원하시는건지도 궁금합니다.

정안님 말씀대로 기준이 없고 저 혼자 머릿속으로 상상하며 작업하는거라 이번 작업처럼 어긋나는 부분이 생긴 것 같네요..
앞으로 더 보완해나가도록 하겠습니다.



>  1챕터 장르인 쯔꾸르, 2챕터 미연시 등의 장르의 사운드의 피치나 색깔만 참고해서 통일성을 보이지 않게 유지하는 것고 방법일 것 같습니다.

이 말씀이 이해가 잘 안되서 그러는데 
앞에 말씀에서는 장르마다 사운드의 통일성을 가지는게 좋을 것 같다고 말씀하셨는데 
이게 어려울 것 같으면 각 장르의 사운드 피치나 색깔을 참고해서 통일성을 보이지 않게 유지해보라는 말씀이 이해가 잘 안되네요ㅠ 

각 장르의 사운드 피치나 색깔을 참고하면 통일성을 보인다고 생각되는데 어떻게 통일성을 보이지 않게 유지할 수 있다고 보시는지 궁금해서요ㅠ 조금 혼란스럽네요..!!

저 말에 대해 전체적으로 한번 더 풀어서 설명 해주실 수 있으실까요?

**Comment by fkdl0048** [comment]
오..! 일단 피드백 구체적으로 답변 해주셔서 정말 감사합니다 ㅜ

단순하게 재작업을 요청 드린 것 보다는 지금까지 사운드를 다 들어봤을 때, 3D공간의 느낌의 사운드가 나와서 게임틱하지 않은 것 같다고 말씀드린 건데, 저도 너무 두서 없이 딱 잘라서 말해서 오해하신 부분이 있는 것 같습니다..!

한번 기획과 기화님 포함해서 회의를 하면 좋을 것 같습니다.

> 1챕터 장르인 쯔꾸르, 2챕터 미연시 등의 장르의 사운드의 피치나 색깔만 참고해서 통일성을 보이지 않게 유지하는 것고 방법일 것 같습니다.

이 부분은 현재 팩맘의 경우엔 모두 8bit? 사운드로 통일성이 있는 것처럼 메인에서도 쯔꾸르 장르의 사운드로 통일하는게 어떠할지에 대한 생각이었습니다..! 단순한 아이디어를 말한거라 저도 기화님의 생각을 듣고싶어요!

처음 기획 당시에는 이질감과 복잡합이 필요하다고 생각되서 다양한 장르의 필요성을 느껴졌고, 장르의 다양성을 사운드가 연결해줄 수 있겠다는 생각도 했습니다. 근데, 하나하나의 시스템에서 모두 사운드가 통일성이 사라지게 된다면 너무 복잡하지 않을까? 라는 걱정도 되서 (이건 제가 사운드를 잘 몰라서 그런 것 일수도..)..

일단 위에서 말한대로 한번 회의를 가지는 게 가장 빠른 해결 방법인 것 같아요.

다음 회의 때 기화님이 말씀해주시면 날짜를 같이 잡아봐요!
