### ISSUE TITLE
[CH1] Lucky 배경음 수정

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/Grayed-Game#485]
#450 에 달린 코멘트 참고하여 럭키 배경음 수정 예정

-----

코멘트 달아주신 것들 들어봤는데 전체적인 분위기 + 9AM 을 주로 참고해서 만들어봤습니다!
템포도 120으로 올렸고 조금 엉뚱한 + 신남 + 밝지만 어딘가 이상한 ... 느낌을 가미해보려고 노력해봤는데
느껴지실지 모르겠네요 ,,,, 
레퍼런스를 참고해보니 간략한 악기 구성이 좋을 것 같아서 일단은 이런식으로 만들어봤는데 이런 느낌이 맞을까요 .,?
재작업 + 수정도 가능하니 편하게 말씀해주세요!!!!

[럭키 BGM 수정 버전 ](https://drive.google.com/file/d/1o28mIjYl5ACYTvS_OYnSlqDBN_75x81d/view?usp=drive_link)

[영상 예시](https://drive.google.com/file/d/1BAr4XBsQUg8iEOPpwuO7xLksogb7zP4s/view?usp=drive_link)

**Comment by wooyn730** [comment]
엉뚱발랄함이 느껴져서 확실히 분위기는 럭키랑 더 잘 어울리는 것 같습니다!
저는 메인 악기 다른 걸로 바꾼 버전도 들어보고 싶네요~~

**Comment by Songkihwa** [comment]
혹시 그러면 메인 악기는 어떤 느낌이였으면 좋겠나요?! 지금은 좀 왕왕거리는 웃기는 신스로 작업한건데
더 깔끔하고 깨끗한 느낌으로도 올려볼까요?!!

**Comment by wooyn730** [comment]
넹! 원하는 느낌이 있다기 보다 다른 느낌이 궁금해서요

> 더 깔끔하고 깨끗한 느낌으로도 올려볼까요?!!

죠아요
