### ISSUE TITLE
[Char] R2-Mon 캐릭터 리디자인

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/Grayed-Game#486]
**상세**
R2-Mon 스프라이트를 작업하기 전에 디자인을 확정해야 할 것 같아 마지막으로 의견 묻습니다.

**파일**
![R2mon2](https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/c6494001-9316-43e3-9ccf-f4726c0f0592)
이족보행에 조금 더 친근한 느낌으로 만들어봤습니다~ 

**06.22 추가**
![R2mon3](https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/6a761536-6e61-4430-a29e-9281763af75a)

**Comment by wooyn730** [comment]
제 기억으로 수빈님 문서에서 저 농부 모자 빼고 사이렌을 장착하는 설정으로 기억하는데 말이죠..
농부 모자 없는 버전으로 보고싶네요
근데 이렇게 네모난 얼굴 있으면 사이렌은 필요 없을 것 같기도 하고?

무엇보다 확실히 귀여워져서 좋습니다 ^_^ 👍
훨~~~~~씬 귀여워요 (이전 알투몬에겐 미안하지만..)
이족보행이랑 고양이귀도 괜찮은데요? 

근데 몸이 인간형처럼 바뀌었는데 에어프라이어 손잡이가 그대로 있어서 좀... 숭해보여요....
_(위치가....... 나만 그런거 아니라고 해줘)_

몸통에 디테일 더 들어가도 좋을 것 같고
팔다리는 유지하되 몸통만 두꺼워도 괜찮을 것 같기도 하고요
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/b4de203b-2ca6-4a98-a748-a890cffcef3b)
_비모처럼?_

**Comment by fkdl0048** [comment]
개인적으로 모자는 그대로 가져가도 귀여울 것 같습니다. 뒤의 천만 빼도 밀짚모자 느낌은 좋아서 그대로 가져가도 좋을 것 같아요. 팔이 길게 늘어진 느낌도 너무 좋고, 얼굴의 빨간 눈도 포인트가 좋은 것 같아요. (나중에 스토리를 해결하는 요소로 쓰던, 맥거핀으로 쓰던)

**Comment by Songkihwa** [comment]
오. 약간 월E 도 생각나고 귀엽고 좋아요!! 역시 귀여운게 최고인 듯 ..

**Comment by wooyn730** [comment]
모자 반대파였는데 모자가 더 이뻐보이네요 ㅠ,,
팔다리가 동글동글하고 얇아서 그런가 몸은 기존 형태가 좋아보입니닷

**Comment by Sumindd** [comment]
저도 모자 있는 쪽이(1번) 개성 있고 귀여운 것 같습니다!

**Comment by Songkihwa** [comment]
저도 모자있는게 안 허전하고 좋은 것 같아요!
