### ISSUE TITLE
[CH1] SLG 퀄리티업

### ISSUE THREAD

**Issue by jeongopo** [GG-Studio-990001/Grayed-Game#487]
이번주에 바빠서 이제서야 이슈업합니다 죄송합니다 (_ _)

## 작업내용

- [x] SLG 스폰 조건 수정 ([수정된 기획](https://github.com/GG-Studio-990001/Grayed-Game/issues/482))
- [x] 사운드 추가 대응 (관련이슈 #483 )
- [x] 자원 부족 시 텍스트 빨간색 (이라는 내용을 어디서 본것같아서 작업하겠습니다 🤔 )

## 궁금증
- SLG 아이콘 클릭 시 애니메이션같은건 없어도 될지?

**Comment by jeongopo** [comment]
코드정리하다가 본건데, 

```
 public void SLGExplainStart()
 {
     if (Managers.Data.SLGProgressData == SLGProgress.ModeOpen) // 현정님이 바꾸면 나도 바꿔야함
     {
         _lucky.transform.localPosition = _outPosition[2];
         _runner.StartDialogue("Lucky_SLG");
     }
 }
```

이거 주석 어떤 뜻일까요 우연님? @wooyn730 
제가 이해한것이 맞다면,, SLGProgress Enum 변경 예정은 없습니다 !

**Comment by wooyn730** [comment]
이해하신 거 맞습니다 확인이요~

**Comment by jeongopo** [comment]
### 240602 작업내용

- **수정된 기획에 따라 3초마다 자원 스폰되도록 변경** : 가장 처음엔 3개 스폰되고 이후 획득 시 3초마다 스폰됩니다. 건설이 시작되면 더이상 스폰하지 않습니다.
- **마우스 클릭시 , 오브젝트 사운드 출력**
- **자원 부족 시 빨간텍스트, 아니면 검정 텍스트 출력되도록 수정** (코인도 동일하게 작업)
- **게임 재시작 시 SLG UI 표시되지 않는 문제 수정**

----

### 협업
**기획**
- SLG 오브젝트 스폰조건 기획 수정됨에 따라, SLG 설명 럭키 대사 수정되어야할 것 같습니다 (@roweclaw )

**프로그래밍**
- SLGActionComponent 를 Ch1GameController 하위의 컴포넌트로 추가했는데 혹시 이후 문제있으면 알려주세요 

----
### 추가된 작업
- 오브젝트 상호작용 시 연출 추가

**Comment by jeongopo** [comment]
뭔가,, 저 pull request 랑 연결하는 방법이 있었던것같은데 이렇게하는게 맞는지 기억이 안나네요 😓
일단 무언가 연결은 해놨습니다..

**Comment by gomgom172** [comment]
![2024-06-02_212921](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/7d45f344-60bd-461c-b311-3f0a43534374)
![2024-06-02_212743](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/6a6077d3-1e23-4558-b7b7-f3edd14ca2f4)

지난 피드백 때 모았던 의견 중 전달드려야 할 것이 있어서 코멘트 드립니다.
빌드 내 구현되어 있는 SLG UI 간격 배치 관련하여 가이드 전달드립니다!

**Comment by jeongopo** [comment]
### SLG팩 리소스 적용 중 텍스쳐 포맷 문제

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/967e3195-6899-4618-8b03-4b3a0250df40)
처음 이미지를 넣었을 때 깨져서 나오는 현상이 있었습니다. 

확인해보니 
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/0a9fe329-5c19-4e7a-bb99-1a78b4db146e)
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/050258d1-83e4-4e3b-9000-ea468bfec41b)
기존의 스프라이트들과 다르게 세부 이미지 포맷이 다르게 되어있습니다 

[텍스쳐 포맷에 대한 공식 문서](https://docs.unity3d.com/kr/2018.4/Manual/class-TextureImporterOverride.html)
RGBA Compressed DXT5 로 되어있어 확인해보니 
유니티에서 자동으로 이미지 포맷을 정의해주는 과정에서 압축 버전을 사용한 모양입니다

**해결**

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/b17d8508-99a5-430c-9d01-72c67a2054fe)
직접 RGBA32로 변경해서 해결했습니다
작은 사이즈의 이미지다보니 압축과정에서 깨짐이 심하게 발생한것같습니다

이정도면 이미지 사이즈를 키워야하는것이 아닐까 싶긴한데
혹시나 여전히 많이 깨져보이면 다른 방법을 찾아보겠습니다

**Comment by jeongopo** [comment]
### 240609 작업내용

- [ ] SLG 게임팩 리소스 적용
- [ ] 건설창 UI 규격 수정

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/e1661507-2b46-4b95-b3ab-5a540ae5ca9b)
위치 조정
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/fca6589f-e093-4891-9916-241d740f2c07)
중앙 정렬


### 이후 작업
- #500 이후 수정되는 컨텐츠 대응 예정

**Comment by jeongopo** [comment]
### 0616 작업내용

https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/dbbea3f4-5878-44a6-ab82-34c8294406ca

- 자원 획득 시 HUD 상의 에셋 아이콘 확대,축소 되도록 수정

[애니메이션 타입](https://www.youtube.com/watch?v=uhEZ8hzwPTU) 중에 가장 아웃되는 InOutBack 으로 애니메이션 조절했는데
애니메이션 종류나 속도 수정해야하면 말씀해주세요

**Comment by jeongopo** [comment]
### 연출 커졌다 작아지도록 수정

https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/f3eaa54e-b084-4609-93f3-3f449e5cc227

[LOOP관련글](https://m.blog.naver.com/dooya-log/221320177107) 루프가 되는거였네요 😓
수정해서 올렸습니다~

**Comment by fkdl0048** [comment]
@jeongopo 속도가 조금 빠르면 좋을 것 같은데, 수정 위치 알려주시거나 수정 가능할까요?

**Comment by jeongopo** [comment]
헉 죄송합니다 제가 너무늦게봤네요,, 
지금 총 1초 걸리도록 되어있는데 얼마나 빠르게하면될까요?

**Comment by jeongopo** [comment]
우선 이슈 종료합니다
