### ISSUE TITLE
[Ch1] Pacmom SFX 추가

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/Grayed-Game#488]
팩맘 SFX에서 사운드 몇 가지 빠진게 있어서 추가해봤습니닷

라플리가 질 때 나오는 화면과 어울릴 것 같은 소리를 간단하게 만들어봤습니다!
[화면 지지직 사운드](https://drive.google.com/file/d/1oze9epFlz5TuRyIppRixt4R2fH-eAVOf/view?usp=drive_link)
뭔가 전기적인..? 에러난..? 그런 사운드로 만들어봤는데 어울릴지 한번 적용해봐야 알 것 같아요ㅠㅜ

[팩맘 접속음](https://drive.google.com/file/d/1FFNMisEUnQFIlvi5bjsKdN0HCCRPeN72/view?usp=drive_link)
원래 만들어뒀던 사운드인데 이걸로 적용할지 아니면 더 8비트스러운..? 깨지는..? 그런 느낌으로 만들지 고민입니다
의견 있으시면 의견 주시면 좋을 것 같습니닷ㅎㅎ

**Comment by wooyn730** [comment]
### 지지직 사운드

https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/eee66646-197c-4f35-9f4e-2db6910f4dcf

괜찮은 것 같은데 짧아서 잘 모르겠어요!
화면 이상해진채로 3초 유지하니 효과음도 3초 정도 분량으로 주시면 좋을 것 같습니다
(이 시간은 제가 임의로 정한 거긴 합니다)

### 접속음

https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/392be16f-7bc2-461c-8bb2-7a3e000954a9

화면 전환 효과(모자이크 쉐이더)는 2초입니다!
이것도 효과음이 살짝 더 길면 좋겠네요
확실히 접속한다는 느낌이라 좋아요
근데 챕터1에 더 어울리는 느낌이면 좋을 것 같기도 하고요.. 🤔🤔
