### ISSUE TITLE
[CH1] 오프닝 일러스트

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/Grayed-Game#495]
**상세**
#486 이슈가 마무리되면 이를 바탕으로 오프닝 일러스트를 제작합니다.

**파일**
https://drive.google.com/file/d/1IT3-W8krHJSFRAUEVL99wAFjXKItby6K/view?usp=drive_link

**Comment by wooyn730** [comment]
느낌 넘 좋은데요?

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/fb5c2d1b-8435-48ac-98a1-12cdcb66fc4c)

저는 이렇게 팔 아래로 내린 포즈도 괜찮을 것 같아요
아니면 십자가 모양으로 옆으로 펴기
그러면 좀 더 철푸덕 느낌이 날 것 같아요
(그리고 언터테일 느낌이 덜 날 것 같아요 ㅋㅋㅋ 지금 포즈는 많이 비슷해 보여서..)

**Comment by fkdl0048** [comment]
도트 일러스트 느낌이라 너무 취향 저격입니다..!
