### ISSUE TITLE
[Ch1] 동굴 BGM 수정 + 다리 부서지는 소리 

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/Grayed-Game#497]
피드백 참고하여 동굴에서 더 울리게 수정 예정 + 다리 부서지는 사운드 작업

------

동굴은  더울리고 몽환스럽게 만들어봤습니다!
[동굴 BGM](https://drive.google.com/file/d/1Jccnd3gaNZGEKj6nf2n-YGnyvEPU5ND7/view?usp=drive_link)

다리 부서지기 전에 화면이 흔들려서 지진..? 땅이 흔들리는 듯한 사운드를 넣어봤구
[다리 부서지기 전](https://drive.google.com/file/d/1S_MRMCwi4yA_HTPrRHt7y4TWTWCzHvc2/view?usp=drive_link)

다리 폭발할 때는 다리가 나무 재질 같아서 폭발음 + 나무가 뿌서지는 소리로 작업해봤습니닷 
[다리 폭발음](https://drive.google.com/file/d/1UND1w5moFUdOhIsOsFFRZwAh6ohgS5w8/view?usp=drive_link)

합치면 요런 식..?
[다리 예시 영상](https://drive.google.com/file/d/1l_7MtgLFRYAkwd-mlxh03YqQEDmx_DhJ/view?usp=drive_link)

**Comment by wooyn730** [comment]
적용했어요! 소리 잘 어울리네요~~
근데 대사를 느리게 넘기면 다리 부서지기 전 효과음이 끊겨서요
좀 긴 버전으로 받고 부서질 때 효과음 정지하는 게 나을 것 같기도 하네요!

**Comment by Sumindd** [comment]
흔들리는 사운드가 들어가니까 긴장감도 생기고 더 좋네요!
그리고 다리가 나무 재질이라 부서지는 사운드도 훨씬 잘 어울리는 것 같습니다

**Comment by fkdl0048** [comment]
저도 느낌이 더 사는 것 같은데, 영상으로 봐서 트레일러 느낌이 드네요 빌드 버전으로 보고 피드백을 조금 더 구체적으로 하겠읍니다!

**Comment by Songkihwa** [comment]
@wooyn730 앗 그러면 혹시 몇 초 분량으로 드리면 될까요?!

**Comment by Songkihwa** [comment]
[다리 부서지기 전 사운드 긴 버전](https://drive.google.com/file/d/1YcaiCSD_gJymwrsOjiaTGpMdsg395f-E/view?usp=drive_link)
넉넉하게 12초 정도로 했습니다!
