### ISSUE TITLE
[CH1] 대사 폴리싱

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#499]
대사 요점만 간략히, 말투, 용어, 알투몬 특수문자, 등등...

---
## 240608

> 중간 현황

[대사 폴리싱 기반 작업](https://drive.google.com/file/d/1p7q4MJdkD5SIDGwtDCJj9gmAm015XytJ/view?usp=sharing)

- 전체적인 방향성을 잡기 위해 작성
- 위 문서의 내용을 기반으로 대사 폴리싱 진행 중

> 작업 완료 대사

[[240608] s1](https://drive.google.com/file/d/1UgujLQW7DdG_Q_IkUjtWbyS6smlho_se/view?usp=sharing)
- 수정 : s1_intro, s1_npc
- 인트로가 급하게 진행된다는 피드백을 반영해 아래와 같이 플로우 변경 (대사 주석과 함께 봐주세요!)
   - 첫 등장하는 곳을 시작지점으로 변경
   - npc만 시작 지점에서 대기 지점으로 이동 (자동)
   - 라플리를 조작해 A구역으로 진입 (유저)
   - 다같이 B구역으로 진입 (자동)
   - 라플리 자유행동 (유저)
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/92532398/51dee910-85aa-4051-b2d6-32077e30c98c)

> 이후 계획 (분리해서 작업)
1. 대사만 교체할 부분
2. 대사 교체 및 연출 포함된 부분

## 240615
[대사 폴리싱 폴더](https://drive.google.com/drive/folders/1LOqqmt4PI8z3iJvpVIl52NnEE0BZuEMD?usp=drive_link)

>1. 대사 교체

[Scene2](https://drive.google.com/file/d/1gf7RtNYLcmjvrK9NReRS0BIZ_PxetBCx/view?usp=drive_link)
[Scene3](https://drive.google.com/file/d/1Y8Lzw_WjrbBVuC5aQCAVMvk7GQZ6BxaT/view?usp=drive_link)
[R2-MON](https://drive.google.com/file/d/1n8XBv3XSm2vhxxnW9waoYCRwws4dN9QC/view?usp=drive_link)
[Mamago](https://drive.google.com/file/d/19nuGdgJc6c8TDUYRwiDyYrELQqSQTxKs/view?usp=drive_link)

> 2. 대사 교체 및 연출

[s4_CutScene](https://drive.google.com/file/d/1cHwqaVv1lAXBzdWpdc1VuwFBdDKgGMw3/view?usp=drive_link)
연출 참고할 [이슈 링크](https://github.com/GG-Studio-990001/Grayed-Game/issues/491)

**Comment by roweclaw** [comment]
240608 중간 현황 본문에 추가했습니다. (시험 기간이라 작업분량이 적습니다😭...)

**Comment by wooyn730** [comment]
대기지점이랑 이후 상호작용 반복대사 생긴거 좋네요~
확실히 이전 버전보다 좋아보입니다
(내가 또 작업해야되는 건 사실 안좋ㅇ음ㅠ)

<br>

궁금한 점

**1 ) 문장 끊는 부분**

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/9a6df50f-7a4a-4de8-b348-23f9fa82fbf0)

왜 끊는지 궁금합니다
웬만하면 한 문장이라면 안 끊고 가는 게 나을 것 같습니다

<br>

**2 ) 대화창에 이름이 플레이어 > 라플리로 변경되는 부분**

저희는 플레이어 == 라플리인걸 알지만
```
    플레이어?: ...
    라플리: !!!
```
이 부분에서 처음 게임을 하는 유저들이 '내가 조작하는 캐릭터의 이름이 라플리였구나'하고 바로 알아차리기는 어렵지 않을까 싶습니다..
NPC들은 말할 때 점프라도 하는데 라플리는 가만히 있어서 전달이 잘 될까 걱정이 되는 부분입니다

**Comment by fkdl0048** [comment]
### 생각

- 파밍의 용어 변경
  - 뭔가 게임이니까 파밍도 괜찮은 것 같지만, 이 세계관에 맞는 독자적인 용어가 있으면 좋겠다는 생각이 드네요
  - 하지만, 예매하거나 전달이 잘 안되면 더 어색할 수 있을 것 같습니다.
- 우연님 2번 피드백
  - 저도 플레이할 때 같은 생각을 했던 것 같습니다. 뭔가 연출적으로 보여줘야 플레이어가 라플리구나를 알지 않을까?
- 새로 확인한 부분인데, 원래 마마고 컴퍼니가 존재하고 이를 재 건설해준다는 설정도 구체화된 것 같아서 너무 좋습니다.
- 사랑 고백 제외라니,, (근데 알투몬의 캐릭터의 깊이가 깊어지니까 빼야할 것 같긴 합니다. ^^..)

**Comment by wooyn730** [comment]
S1 적용하였습니다. [빌드본 코멘트 참고](https://github.com/GG-Studio-990001/Grayed-Game/issues/506#issuecomment-2167678601)

**부탁드릴 점**

1. 알투몬 대사에 `#`은 넣지 말아주세요 (대화 시스템에서 이미 특정 기능을 가진 친구이기 때문.. 굳이 쓰고싶다고 하면 방법을 찾아보겠지만 번거로우니 넣지 않는게 낫겠죠?) (알투몬 뿐만 아니라 모든 대사에 해당)
2. 주석을 쓸 때는 `// 주석 ~~~~~` 이렇게 슬래쉬 뒤에 띄어쓰기를 한 번 해주세요 (이건 저희 팀 코딩 규칙)
3. 폴리싱 해주실 때 제가 수정한 파일 다운받아서 그 위에 수정해주세요([위치](https://github.com/GG-Studio-990001/Grayed-Game/tree/main/Assets/_CH1/Dialogues)). 왜냐면 사이사이에 필요한 함수들을 적어두었기 때문에 그걸 고려하지 않고 대사만 새로 받으면 제가 한 번씩 더 수정해야하기 때문입니다.. 🥲<br>어렵거나 좀 복잡하거나 하면 안하셔도 괜찮아요! title 유지(S1, S1_1 등으로 바꾸어둠) + NPC 말하기 전에 점프 (`<<NpcJump 숫자>>`함수인데 뒤에 숫자는 달러 0, 파머 1, 알투몬 2)만 해주셔도 좋습니다

**그 외**

1. 상호작용 대사(컷씬 제외한 대부분)는 보통 캐릭터 파일에 하나로 모아져있습니다! ([예시](https://github.com/GG-Studio-990001/Grayed-Game/blob/main/Assets/_CH1/Dialogues/Dallar.yarn)) 컷씬이어도 NPC 1명하고만 말한다면 캐릭터 파일에 들어있습니다 ([예시2](https://github.com/GG-Studio-990001/Grayed-Game/blob/main/Assets/_CH1/Dialogues/R2-Mon.yarn))
2. 저번에 회의 때 말했던 부분 (문장 끊기), 막상 하나로 합쳐보니까 애매하게 잘려서 좀 안예쁘긴 하더라고요? 근데 또 계속 끊을 거 생각하면 CH2에 대사가 많아서 곤란할 것 같기도 하고..

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/aae351cc-1076-4e7c-9ed2-684d333d9a5a)
이렇게 대사 중간에 엔터는 어떤가요?
_(대사 중간에 줄바꾸려면 `<br>` 쓰면 됨)_

**Comment by roweclaw** [comment]
240615 중간 작업 이후 남은 대사 폴리싱 완료했습니다. 읽어보시고 내용이나 말투 관련 피드백있다면 반영하겠습니다!

@wooyn730 우연님~ `부탁드릴 점, 그 외`에서 알려주신 것들 참고했는데 잘 되었는지 확인 부탁드려요.
그리고 1번 대사 교체를 우선적으로 작업, 그 이후에 2번 연출+대사 작업 순으로 해주시면 됩니다!

**Comment by wooyn730** [comment]
대사 교체 작업 완료했습니다 주신 버전 너무 좋아요 ^_^ b

하지만  수빈님이 스크립트 수정해주신거 반영하기 전에 제가 스크립트 함수를 추가하거나 수정하기도 해서,
수빈님 스크립트로 아예 갈아끼우지는 못하고 대사 부분만 복붙했습니다 ^_ㅠ
그러니 혹~시 적용 잘못된 부분 있으면 말씀해주세요!
(이따가 빌드 올리겠습니닷)

<br>

추가로 수정된 부분 몇개 남깁니다

1. S5_1(마마고한테 번역팩 받는 연출)은 마마고만 말하기 때문에 마마고 스크립트로 옮겼습니다!!
2. 이번에 상호작용 최초인지 이후인지 구별하는 부분을 구현했는데
```c
<<if $progress == 11>>
    <<if not visited("Farmer1")>>
        <<jump Farmer1>>
    <<else>>
        <<jump Farmer1_1>>
    <<endif>>
```
이렇게 진행도 조건문 안에 또 조건문을 둬서 최초대사를 방문했는지(출력했는지) 체크하고 넘어갑니다.

상호작용 대사 수정하실 때 직접 조건문 추가해주셔도 되고요 (아니어도 괜찮아요)
최초대사랑 이후대사 노드를 분리했다는 것만 알고계셔주면 됩니다!

++
추가로 혹시 대사 수정 월요일 저녁쯤까지 더 올려주실 것 있으면 반영할게요!
연출은 럭키 첫등장은 반영되고 씬4 컷씬은 반영 안 될 것 같습니다 (미카엘이 아직이라..)

**Comment by roweclaw** [comment]
@wooyn730 맞춤법, 문장 길이가 수정된 문장입니다. 교체 부탁드려요!

## Scene1

> title: S1

23 `달러: 어서 자리에서 일어나 보게.`
37 `달러: ...아무것도 모르는군.`
38 `달러: 그러면 이름은 기억하는가?`
55 `달러: 라플리, 여기 앞까지 걸어와 보게.`

> title: S1_1

100 `파머: 으-, 생각만 해도 끔찍해!`
101 `파머: 그만큼 위험하니까 조심해서 잘 찾아봐!!`

## Scene3

> title: S3

36 `달러: 오, 맙소사...`

## R2-Mon

> title: R2_Mon5

69 `R2-MON: 드디어 준비해 온 것을 실행할 때가 되었습니다.`
74 `R2-MON: 안타깝지만, 기계식 눈물샘은 미제작 상태입니다.`
76 `R2-MON: 제가 누구보다도 더 특별히 잘 만드는 이것은...`
77 `R2-MON: 이 세상에는 아무런 영향을 끼치지 않지만,<br>'휴먼'의 시점에서는 변화를 느낄 수 있습니다.`

**Comment by wooyn730** [comment]
적용완료용
