### ISSUE TITLE
[CH1] 보완 기획 2차

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/Grayed-Game#500]
- SLG 자원 리스폰 애니메이션 구체화 2차
- SLG-팩맘 동선 리뉴얼 구체화 (다리 재건)
- SLG 애니메이션 수정
- 팩맘 튜토리얼 고민.. 
- #482 에 이어서 작업 

---
### SLG 자원 리스폰 애니메이션 구체화
**1안) 쿨타임을 2초로 줄이고 쿨타임 게이지바 제거
2안) 라플리 머리 위나 옆에 [쿨타임 게이지바](https://youtu.be/z7bR_xYcopM?si=aFIzOQ5_uCq48Jqf) 추가** 
_(쿨타임 게이지바를 넣을 위치에 대해 고민해봤는데 위치가 애매한 느낌..)_ 
![ㅇㅇ](https://github.com/GG-Studio-990001/Grayed-Game/assets/84775854/77d66bdd-5bc7-4b9e-93d1-8e4344331e73)

> 쿨타임 상세 기획

- 쿨타임은 **먼저 터진 말풍선**을 기준으로 리셋된다. (여러 개의 말풍선이 리스폰 될 상황이어도 먼저 리스폰 될 말풍선을 기준으로 쿨타임이 돌아간다.)
- 3초라는 시간에 맞춰 게이지가 왼쪽에서 오른쪽으로 차오른다.

### SLG 자원 

말풍선 클릭 시, #483 의 말풍선 속 **재화 사운드** 재생 + 해당 UI 애니메이션 (ex.석재 말풍선 클릭하면 석재 사운드 출력)

**A안)아이콘만 움직이기**
UI 안에 텍스트 값이 있어서 옆에 아이콘만 움직여도 괜찮을 것 같아서 제안 

https://github.com/GG-Studio-990001/Grayed-Game/assets/84775854/e00ed621-8932-4ee6-ad08-deab8d114870

**B안) 통째로 움직이기**
회의 시간에 나왔던 기존 아이디어?

https://github.com/GG-Studio-990001/Grayed-Game/assets/84775854/6a09a46a-11e5-440a-ba5e-6137dda66c78

### SLG-팩맘 동선 리뉴얼 구체화 (다리 재건)
![팝업](https://github.com/GG-Studio-990001/Grayed-Game/assets/84775854/615805c6-ab47-4e7c-b01b-252ceb99f7e5)
- 왼쪽 하단의 건설 버튼을 누르면 재화 요구량과 보유량을 **확인**할 수 있는 페이지 팝업(편의성)
- 재화 확인 페이지가 팝업 되었을 때는 이동/조작 불가 (재화량 변화 바로 반영 가능하다면 조작 굳이 안 막아도 상관 없음) 
- 기존의 건설 페이지는 말풍선 클릭으로만 연결
- 다리에도 건설 말풍선 추가 

---
### 240616 업데이트
저번주에 정해진 내용 & 수정한 내용 모두 정리해서 업데이트 했습니다.
[피그마](https://www.figma.com/design/LNsoGFh5f3jQ1rCPQB2O9f/Grayed-Game?node-id=0-1&t=fQGVhn9Zk4O4d9w5-1)에 정리했습니다. 
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/84775854/67db8153-5936-44d6-91c1-10ebd89652cd)

![Group 62](https://github.com/GG-Studio-990001/Grayed-Game/assets/84775854/a2a7d234-d085-4fd5-b82a-b7f1879fe7a5)
(이미지 잘 안 보일 것 같아서 확대) 
- 기존 문제점 : 다리 재건이 필수적으로 느껴질 수 있다. 그러나 튜토리얼 역할로서의 재화 확인 페이지는 도움이 될 것 같다.
- -> SLG의 캐주얼한 상점 페이지 UI느낌을 살려서 추가한다. 마마고 컴퍼니에는 강력 추천하는 표시를 자연스럽게 추가하고, 가벼운 유머용 건물(건설 불가. 단순 맥거핀) 선택지를 1~2개 추가한다.

**Comment by Sumindd** [comment]
본문 업데이트 했습니다.

**Comment by wooyn730** [comment]
### SLG 자원 리스폰 애니메이션 구체화

흠 저도 쿨타임 게이지바 위치가 좀 애매해보이네요
라플리 주변에 두는 것도 애매한 것 같아요..

두 가지 후보 중엔 1번이고, 게이지바를 동그라미로 만든다면 우측 상단이나 좌측 하단에 해도 괜찮을 것 같다는 생각도 듭니다
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/d7d2d8bc-a3b1-4ad4-bb86-aec04e4c849d)

### SLG 자원

1안 아이콘만 움직이기 한 표~~ 

돈 빨려들어가는 저번 레퍼런스처럼 슝 + 재화 움직이기는 빠진건가요?

### SLG-팩맘 동선 리뉴얼 구체화

> 재화량 변화 바로 반영 가능하다면 조작 굳이 안 막아도 상관 없음

바로 반영 가능해도 조작 막으면 좋겠습니다

근데 다리에도 건설 말풍선 추가된다면 굳이 확인만 하는 팝업이 필요할까 싶기도 하네요

**Comment by gomgom172** [comment]
### SLG 자원 리스폰 애니메이션 구체화

필수적으로 필요한 정보 제공 요소가 아니고, 쿨타임 자체도 길지 않기 때문에 게이지바가 빠지는 쪽이 나을 것 같습니다. 개발에도 한 번 더 손이 갈 것 같기도 하고요… 꼭 들어가야 한다면 말풍선 위치를 몇 개로 고정하고 그 부분에 게이지바가 들어가는 편이 가시적으로 보기 편하지 않을까 싶습니다.

### SLG 자원

아이콘만 움직이는 쪽에 한 표 추가합니다!

### SLG-팩맘 동선 리뉴얼 구체화 (다리 재건)

왼쪽 하단 아이콘에 기능이 없었어서 들어갈 내용 자체는 필요하겠지만, 유저 입장에서는 (많은 시간을 필요로 하지 않는 단발적인 파트에서) 이런 기능까지 들어있네? 싶을 것 같기도 해서 고민이 되네요… 15초~ 30초 안에 유저 대부분 목재+석재 모두 파밍할 수 있을 것 같아서 해당 창을 많이 열어보지는 않을 것 같습니다.
정말 작은 팝업(왼쪽 하단 아이콘 클릭하면 필요 자원 텍스트로만 표시하는 작은 말풍선 띄워준다거나?)만 띄워준다거나… 살짝 간략화되어서 들어가는 정도는 어떨까 의견 적어봅니다!

**Comment by Sumindd** [comment]
### 피드백에 대한 답변

> **쿨타임 게이지바**

저도 우연님처럼 게이지바를 새로운 UI로 빼는 것도 생각해봤는데 게이지바만 딱 있을 때 이게 무슨 UI인지 바로 파악이 힘들 것 같고 뭔가 굳이 럭키가 새로 설명할 거리만 늘어나는 느낌이라 고민이 많네요.. 그래서 이우님의 의견처럼 차라리 빼는 게 낫지 않을까 생각하고 있습니다. 어차피 3초면 언제 리스폰 되는 거야?하고 당황할만큼의 시간도 아닌 것 같고요. 그래서 이 부분은 회의 시간에 다시 이야기 해보면 좋을 것 같습니다!

> SLG 자원

돈 빨려 들어가는 거는 제 기억 상 그냥 젤리처럼 움직이기만 하는 걸로 하기로 저번 회의 때 얘기 되었던 것 같습니다! 지금 재화가 쌓이고 있다는 강조 표시가 부족한 상황이라 아이콘 움직이는 것 만으로도 일단은 충분할 것 같아요.

> 다리 재건

이 부분은 저도 고민을 많이 해봤는데 굳이 추가한 이유는..
1) 왼쪽 하단 아이콘에 기능이 없음
2) 삭제하기엔 없으면 화면이 빌 것 같아서 비주얼적으로 있는 게 나아보임
3) 건설 기능을 하단 아이콘에도 연결하면 마마고 컴퍼니나 다리가 보이지 않는 위치에서도 건설이 가능해서 건설 컷씬을 카메라가 해당 건설물 고정으로 따로 빼서 보여주고 라플리 위치로 카메라가 자연스럽게 이동하게 만들어야 함(컷씬 제작 코스트가 괜찮다면 저는 이 방향도 좋습니다! 오히려 짜잔하는 건설 컷씬이 새로 생기는 거니까.. )
4) 플레이 했을 때 저는 개인적으로 필요 자원 개수가 헷갈려서(특히 코인) 직접 가서 확인하는 게 번거롭다고 느꼈습니다. 크게 불편한 건 아니지만 그래도 편의성으로 제공해주면 좋겠다는 생각을 했던 것 같습니다. 특히 UI가 화면에 떠 있다보니..

**Comment by fkdl0048** [comment]
쿨타임 게이지 바를 차라리 해당 리소스 더미에 두는건 어떨까요? 해당 리소스 더미 위에 시계방향으로 쿨타임 표시를 각각 해준다면 좋지 않을까? 라는 생각입니다.

저도 A안이 좀 더 명확한 것 같습니다.

추가 UI 관련은 생각 못해봤는데, 의견을 조금 들어보니 SLG UI이면서 친절한 튜토리얼 느낌이 나기도 하는 것 같아서 좋을 것 같다는 생각이 드네요 (다리가 추가되면서..)

**Comment by Songkihwa** [comment]
항상 작업하시느라 고생 많으십니다ㅎㅎ
간단하게 제 의견 드리자면

저도 게이지바는 없는 게 좋을 것 같긴 하네요 ...! 
아니면 자원이 뜨는 말풍선에 시계 같은 아이콘을 둬서 초수를 알려주는 것도 괜찮을 것 같구.. 음 어렵네요 ㅠㅠ

SLG 자원 아이콘만 움직이는 것만으로도 괜찮을 것 같아요!!

재화 확인용 팝업은 수민님 말씀대로 원래 저 아이콘 자체에 기능이 없었어서 저런 기능이 추가되도 충분히 괜찮을 것 같습니닷

**Comment by Sumindd** [comment]
재화 확인 페이지 다시 고민해보기
팩맘 튜토리얼 다시 고민해보기

**Comment by Sumindd** [comment]
240616 업데이트 완료
