### ISSUE TITLE
[CH1] 마마고 SFX + R2-mon Text 음 + 팩맘 화면 접속음 SFX 수정

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/Grayed-Game#508]
마마고 건설 음 + 건설 완료 음 + R2-mon text 음 + 팩맘 화면 접속음 SFX 수정하여 업로드할 예정입니다

-----------------

#483 에 마마고 건설음하고 건설 완료음 업데이트 해뒀습니다!

[R2-mon text 음](https://drive.google.com/drive/folders/1WXnY-Cc4jLcHu7o5vLvMbPPdtR3rYJ1Q?usp=drive_link)
이걸로 한번 적용해보고 이상하면 또 수정하는 방향으로 가보겠습니다!

[팩맘 화면 접속음](https://drive.google.com/file/d/1nvGXqvZgDXph2gpFJt-qWvIvIllfRFtD/view?usp=drive_link)
제가 갑자기 동영상 에러가 나가지구 영상이랑 못 맞춰봤는데 한번 넣어보고 안 맞으면 다시 맞춰서 드리겠습니닷 ㅠ ㅠ

**Comment by wooyn730** [comment]
## 알투몬 텍스트음

### (1) 기존 버전 적용

(이전에 보여드렸던 영상)

https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/68b9a6bb-9825-4530-9a67-845dbd66026c

### (2) 한 음만 적용

(기존 4번 파일 활용, 회의 때 말했던 방법)

https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/2c0186b2-3ccc-4b0c-b21e-8d2e035cb3da

### (3) 새 파일 랜덤 적용

https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/b4e2ab0a-dde9-4040-b0d2-2c6ecebabab2


---

어떤가요?
저는 2번이 제일 좋아보입니다 (기존 타이핑 사운드와도 유사하고..)
볼륨만 더 키워서 주시면 좋을 것 같아요

새로운 파일은 이전 버전보다 더 말하는 느낌이 들긴 하는데 살짝 로봇보다 외계인.. 같은 느낌 👽

**Comment by fkdl0048** [comment]
개인적으로는 3번이 좀 더 명확한 것 같은데, 2번도 좋습니다. <- 대신 R2 사운드가 조금 작은 것 같습니다 . 타이핑에 비해서

**Comment by Songkihwa** [comment]
일단 [2번 음량 올린거](https://drive.google.com/file/d/17X_7q-olDDFxz90c2OAVUhyezOCRuoaG/view?usp=drive_link) 올려드립니다!

**Comment by wooyn730** [comment]
확인이요! 적용해두겠습니다

**Comment by Sumindd** [comment]
2번은 다른 NPC들이랑 자연스럽게 섞이는 느낌이고 3번은 확실히 R2-MON이 로봇이라는 게 튀는 느낌이네요
저는 둘 다 다른 느낌으로 괜찮게 느껴집니다! (선택에는 도움이 되지 못해 죄송합니다ㅠ)
