### ISSUE TITLE
[CH1] SLG UI 추가 작업

### ISSUE THREAD

**Issue by jeongopo** [GG-Studio-990001/Grayed-Game#521]
- 왼쪽 하단 버튼 클릭해서 UI 표시하는 작업

### 선행작업
- #526 
- #523 

### 필요작업
**재화창**
- [x] 재화창 추가
- [x] 재화창 표시 시 애니메이션

**관련 오브젝트 처리**
- [ ] 다리 재건설

**Comment by jeongopo** [comment]
### 0723 작업내용

https://github.com/user-attachments/assets/01d95a09-1006-4eb7-bfb5-e7f816e8fc02



- 재화창 UI 연결
- 재화창 클릭 시 표시되는 애니메이션 작업
- R2Mon의 기지는 무조건 Locked, 이후 다리 건설 여부에 따라 건설완료 표시 생기거나 없어지는 작업


**이후 작업 (일요일 예정)**
- [ ] 마우스 호버 시 설명 표시
- [ ] 다리 재건설
(위 이슈까지 작업하면 SLG는 마무리입니다)
- [ ] 수정된 내용 PR 및 씬 병합 (문제가 없길.. 🙏)

**확인 필요한 버그**
- [ ] 럭키 SLG 설명 시 뒤에 SLG 클릭되는 문제
- [ ] HUD의 코인 텍스트가 유난히 흐린 문제

**Comment by jeongopo** [comment]
@gomgom172  영상보시고 UI 제대로 적용됐는지 확인한번 부탁드립니다

**Comment by gomgom172** [comment]
기능은 문제없습니다 감사합니다!
배치랑 그래픽 관련으로 수정해야 할 게 있어서 30분 정도 내로 다시 코멘트 달아두겠습니다!

**Comment by jeongopo** [comment]
어차피 제가 오늘은 더이상 작업못해서 천천히 올려놔주시면 확인할게요!

**Comment by gomgom172** [comment]
![guide4](https://github.com/user-attachments/assets/61735810-dcdf-44e1-913d-71c5641e8a26)

화면비 고려를 못해서 전체적으로 비율 수정이 있었습니다!
[파일 링크](https://drive.google.com/drive/folders/1fxTBUHpSb1FEcbn42X1bpLGb3hefVywh?usp=share_link)
4, 5, 6 빼고 전부 수정되어서 교체해주시면 감사하겠습니다. 🙇‍♀️

<img width="857" alt="스크린샷 2024-07-24 오전 12 59 51" src="https://github.com/user-attachments/assets/5d986e5d-7583-4db4-801c-41a4520aed23">

상단 UI 오른쪽으로 살짝 당겨서 하단 UI와 좌측 정렬 부탁드립니다!
제작 완료와 제작 불가 아이콘은 두 가지를 하단 정렬해 주시면 됩니다. 감사합니다!

**Comment by Sumindd** [comment]
수정한 내용 확인했는데 카드 정보값에 비해 좀 쓸데없이 넓은 느낌이네요... 제작 불가 칸을 하나 더 늘리는 게 디자인적으론 나을 것 같은데 유저가 느낄 때 제작 불가가 2개 있는 게 괜찮을지 좀 고민이 되네요. 잡다한 내용 넣는 거라 늘리는 건 크게 문제가 안 되긴 한데...  다들 어떻게 생각하시나요?

**Comment by fkdl0048** [comment]
저도 넓은 쓸데없이 넓은 느낌이 들어서 차라리 줄이는게 더 좋을 것 같아요.

**Comment by Songkihwa** [comment]
저도 저렇게 딱 보니까 카드가 넓게 느껴지는 것 같네용,,

**Comment by gomgom172** [comment]
짧게 두면 너무 비어 보여서 늘렸더니 역시 너무 넓어 보이나 보네요 ㅠ_ㅠ
새벽 내로 조정해서 예시컷 올려볼 테니 짧게 갈지or카드 한 개 더 넣을지 의견 주시면 감사하겠습니다!

**Comment by Sumindd** [comment]
저는 SLG UI 느낌 살리려면 아래쪽 면을 최대한 채우는 게 좋을 것 같아서 카드 4장이 더 좋습니다

**Comment by gomgom172** [comment]
![guide4](https://github.com/user-attachments/assets/c1acfbf6-fb80-4365-babb-df5fa1f7a900)
![guide5](https://github.com/user-attachments/assets/42360817-595d-4968-b398-e65bb6083c0e)

확인 부탁드립니다!

**Comment by Sumindd** [comment]
저는 4칸이 더 좋은 것 같습니다!

**Comment by wooyn730** [comment]
저도 가장 마지막 버전이 좋아보이네요!


![Screenshot_20240724_170525_Chrome.png](https://github.com/user-attachments/assets/52651dc6-8068-4f3c-bb53-618073f8d4ca)

저는 설명 말풍선 좀 더 각진 버전도 보고싶고

![Screenshot_20240724_170509_Chrome.png](https://github.com/user-attachments/assets/5030eaf0-fa1d-4c7d-9ae5-0b41c1d1e0cd)

재화 사이 간격이 좀 더 여유있어도 좋을 것 같아요

**Comment by gomgom172** [comment]
![guide6](https://github.com/user-attachments/assets/5992cf02-42f1-4087-8990-38e4ebfa0d13)

우연님 피드백 적용하여 조금 더 만져봤습니다! 각진 버전이 더 괜찮은 것 같아서 피드백 확인하고 이쪽으로 가려고 합니다!

**Comment by jeongopo** [comment]
저도 4개가 좀더 나아보입니다.. ! 그런데 제작불가 2개보이는건 좀 별로인것같긴하네요 ㅜㅜ

@gomgom172 
1. 이후 수정하신다면.. 제작불가 아이콘과 제작가능 아이콘의 크기가 다르더라구요 동일한 기능의 아이콘은 크기 맞춰주시면 감사하겠습니다 !
2. UI 열기전에 하단에 사다리꼴 모양이 생각보다 너무 각져보이는 느낌이더라고요 이대로도 괜찮을까요..?

**Comment by gomgom172** [comment]
말씀주신 부분 확인했습니다!
열기 전 책갈피 올라와있는 부분은 리소스 최종 업로드 전에 조금 더 만져보겠습니다.
혹시 수정 파일 언제까지 넘겨드리면 편하실까요?

**Comment by jeongopo** [comment]
흠 일요일엔 작업끝낼예정이라 토요일밤까지 주시면될것같습니다!

**Comment by Sumindd** [comment]
제작 불가 2개가 별로라면 하나는 건설 완료 띄워 놓는 방법도 있습니다. 큰 의미가 있는 건 아니지만 단순히 봤을 때 어색해 보이는 문제라면요.. 아니면 재화 수를 말도 안 되게 높게 잡아놓는 방식도 있긴 한데 실제로 모으는 사람이 있을 것 같아서 대응을 어떻게 해줄지는 좀 고민되네요. 퀄업 관련 문제라 일단은 그냥 제작 불가로 2개 해두는 게 무난할 것 같기도 하고요.

**Comment by gomgom172** [comment]
그럼 우선… 마지막 카드에 들어갈 건물 기획 분들께서 하나 고안해 주실 수 있을까요? 임시라도 괜찮습니다! @roweclaw @Sumindd

**Comment by Sumindd** [comment]
앗 임시 건물 요청하는 디코 메세지 확인해서 답장 해뒀습니다!

**Comment by gomgom172** [comment]
앗 감사합니다!
상점 2호점 / 경비 쉼터 / 달러 동상 / (파머가 야채를 파는)트럭... 등 전달받았습니다. (깃에도 기록해둡니다!)
이중에서 하나 골라 작업하겠습니다!

**Comment by wooyn730** [comment]
저도 제작 불가 2개는 좀 답답해보일 수도 있을 것 같긴해요
아니면 재화 종류 하나 추가하기? 금이나 보석이라던가..

**Comment by jeongopo** [comment]
### 0728 작업내용


https://github.com/user-attachments/assets/b993814e-2c89-4891-91bb-3e0a135b5d79


- 기존의 SLG UI 통일화를 위한 교체 작업
- 다리 재건설 (재접 시에도 유지됨)
- 재화창 호버 시 설명 표시


https://github.com/user-attachments/assets/ad03a1d1-2af5-47fc-a4c0-21cef018dd39


- 다리 재건설 시 연출은 마마고 컴퍼니 지을때와 동일하게 넣었습니다 (Object.yarn - RebuildBridge)
- 건설 후 제작 완료로 표시되는 것 확인


### 공유사항

![image](https://github.com/user-attachments/assets/1fbc34f0-60a6-4ff6-a26f-d33c9ba3b45b)

@gomgom172 필요재화 아이콘이 시안에서 너무 커서 조금 줄였습니다 이정도도 괜찮을까요?
@Sumindd 달러 동상 임시로 넣은 설명인데 수정필요하면 말씀해주세요~

**Comment by jeongopo** [comment]
드으디어 SLG가 끝났군요.. 추가 대응은 다른 이슈에서 진행하겠습니다. 이 이슈는 닫겠습니다 😊

**Comment by wooyn730** [comment]
피드백 드림니다

(1)
![스크린샷 2024-07-29 191436](https://github.com/user-attachments/assets/8bd5715a-76cf-419b-be91-99e79e37d8e8)
럭키 나오는 동안 입력 막기
이건 이슈에 언급되긴 했는데 지금 아래 추가된 창 때문에 럭키가 가려져서 지금 좀 급함쓰

(2)
![스크린샷 2024-07-29 191549](https://github.com/user-attachments/assets/15c9a2eb-eee7-4271-bed4-0980bb8c3abb)
다리 짓는 말풍선이 너무 허공에 있는 느낌이라 위치를 조금 낮추고 말풍선 flip해서 오른쪽에 남아있는 부분(?)이라도 가리키면 어떨까 합니다.

(3)
플로야드 다리를 다시 건설했다 => 연출(페이드인아웃과 뚝딱뚝딱) 다 끝내고 출력되면 좋겠습니다

(4)
SLG 하단 창 설명하는 글씨 작은 느낌이 들고 엔터 위치도 수정되면 좋을 것 같습니다

(5)
SLG 상단 UI 폰트 교체해야함니다

(6)
지금 SLG 마우스로 아무데나 클릭해도 클릭사운드 나는데 상호작용 되는 것만 클릭음 나면 좋을 것 같습니다

**Comment by jeongopo** [comment]
(2), (4), (5) 관련해서 @gomgom172  확인부탁드립니다

**Comment by jeongopo** [comment]
@gomgom172  폰트 크기 작다는 얘기도 있는데 얼마나 키울지도 확인부탁드립니다

**Comment by gomgom172** [comment]
(2) 저도 말풍선 좀 내리는 게 나을 것 같습니다.
![image](https://github.com/user-attachments/assets/2439c7e6-b5b6-4de8-ab8c-5fb339436b7e) 이 정도?
그림자 방향 통일되는 게 좋을 것 같아 말풍선 반전한 파일 올려놨습니다. [파일 링크](https://drive.google.com/file/d/11GxaN7B8kHLJQ4CR9wA21bfy2WButoJO/view?usp=share_link)

(4)
제가 전달드린 사이즈대로 적용되어 있는 걸까요?
그대로 적용하셨다면 어도비와 유니티 프로그램 자체의 폰트 사이즈 차이 같습니다.
전달드린 가이드가 인게임 출력 화면 사이즈(1920x1080)와 동일하기 때문에, 가이드를 옆에 두고 폰트 사이즈가 비슷해지도록 맞춰주시는 게 가장 빠를 것 같습니다. 현재는 (폰트 사이즈x1.625)가 행간값입니다.
