### ISSUE TITLE
[CH1] 보완 기획 3차

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/Grayed-Game#523]
- SLG 재화 확인 페이지 구체화 (월~화)

---
- SLG 게임의 UI 배치를 참고해서 고민해봤습니다.. 언제나 그렇듯 디자인에 따른 배치 변경은 재량껏 부탁드립니다!
- [피그마](https://www.figma.com/design/LNsoGFh5f3jQ1rCPQB2O9f/Grayed-Game?node-id=0-1&t=hVsbSoHsnMzK10Om-1)에 레퍼런스 스샷 몇 장도 함께 올려뒀습니다. 작업하실 땐 피그마 참고하시면 좋을 것 같습니다!
- 상세 페이지를 굳이 따로 빼서 구상한 의도 : SLG UI의 구조를 최대한 따라가기 위해 + 스크립트를 통해 세계관에 대한 설정 디테일 소소하게 넣기 
- R2-Mon 기지의 표시 언어를 기계어 번역팩 획득 이후에 보이게 하고 싶었는데 플로우에 따르면 SLG UI가 탈피된 이후에 기계어 번역팩을 얻게 되어 아쉽게도 힘들 것 같습니다.. 대신 좀 더 확실하게 건설 불가함을 디자인으로 보여줘야 할 것 같습니다.
- 스크립트는 임시 스크립트입니다.. 일단 기획서 다시 찾아보면서 적당히 설정 붙여서 작성했는데 혹시 없어진 설정이라거나 설정 충돌 되는 내용이 있다면 말씀해주세요!!  

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/84775854/66231b61-6c60-45bc-8781-00db61387b46)

**Comment by roweclaw** [comment]
> 마마고가 운영하는 번역팩 제작 전문 회사
최근 발생한 오버플로우의 잔해에 의해 건물이 무너졌다.

'파밍' 용어 수정이 필요한 것처럼 '오버플로우'도 다른 단어로 추후에는 수정되어야 할 것 같습니다.

> 플로야드에 위치한 신설 건축물
달러의 부탁을 받아 R2-MON이 심혈을 기울여 건설했다.

기존 npc들은 R2-MON이 말하는 기계어를 못 알아 듣는 상황이라 내용이 충돌되네요... 일단 파머가 지었다고 변경하는 건 어떤지요!

**Comment by jeongopo** [comment]
깔끔한 프레임워크 감사합니다 ~ 추천 탭이 보이는것도 좀더 SLG 게임스러워서 좋은것같네요 ㅎㅎ

혹시 그런데, 필요 재화를 마우스오버에서 보는 이유가 있을까요?
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/52280545/c5ced8c6-0866-4fc4-bda9-6d007ff55e8b)

꽤 유사한 쿠키런킹덤같은 게임 보면 우선 마우스오버 없이 바로 재화를 보여주는것 같아서요 !
해당 UI를 추가하는 이유가 재화를 확인하게 하는건데, 마우스 오버를 한번 더 해서 확인하게하는게 조작 횟수가 늘어나게 되는거라 그냥 바로 화면에서 바로 확인하게 해도 좋지않을까요? 🤔

**Comment by Sumindd** [comment]
SLG 게임 레퍼런스를 좀 찾아봤는데 저렇게 구매 목록이 하단에 뜨는 구조의 게임은 대부분 이미지만 보이고 마우스 오버해야 정보가 보이게 되어있더라고요. 물론 디자인 자체가 쿠킹덤 스타일로 화면 꽉 차게 보이는 게임이랑 섞은 거라(이미지만 보이는 게 아니라 건물 이름도 보이는 등..) 재화량은 하단으로 빼도 상관은 없습니다! 지금은 카드 쪽에 들어가는 정보량이 좀 많을 것 같아서 그냥 마우스 오버 설명창으로 빼두긴 했습니다. 
![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/84775854/9fba6cf0-00e7-420d-b78d-caf4bcb938de)

**Comment by jeongopo** [comment]
흐음.. 그렇군요 장단점이 있어보이긴하는데요
혹시 @gomgom172  이우님은 어떻게 생각하시나요?

**Comment by gomgom172** [comment]
[건설 가능] 부분에 재화를 확인할 수 있게 하고 마우스오버하면 꼭 확인할 필요 없는 상세 정보를 볼 수 있게 하는 건 어떨까요?

첨부해주신 레퍼런스 경우에는 2단으로 가구가 들어가기 때문에, 정보량 조절을 위해 세부사항을 모두 마우스오버로 뺀 것 같습니다.

저희는 1단이고 건설물 개수가 많지 않아서, 바로 필요 재화를 확인할 수 있게 하는 편이 가시성이 더 좋을 것 같기는 합니다!

**Comment by Sumindd** [comment]
그러면 건설 가능과 재화 위치를 교환하면 될 것 같습니다!
혹시 작업 아직 안 하셨으면 오늘 회의 시간에 이야기 짧게 이야기 해봐도 좋을 것 같고요

**Comment by gomgom172** [comment]
아직 출력 가능할 만큼 작업되지 않아서, 오늘은 작업 화면 바로 보여드리면서 배치 의견 나누어 보면 될 것 같습니다. 회의 때 뵙겠습니다!
