### ISSUE TITLE
[CH1] SLG 재화 확인 UI

### ISSUE THREAD

**Issue by gomgom172** [GG-Studio-990001/Grayed-Game#526]
# 240630 작업 진행

![0630-01](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/0b12645e-d67c-49bf-a125-c114c3b3459f)
![0630-02](https://github.com/GG-Studio-990001/Grayed-Game/assets/162591960/2ae02057-3340-469b-bb40-41f1ffe31c08)

- [x] 전체적인 디자인 수정
- [x] 망치 벡터 그래픽으로 변경
- [x] 추천 기능
- [x] 다리, 알투몬 아이콘 그래픽
- [x] 제작 불가능 잠금 그래픽
- [x] 말풍선 안 폰트 및 행간 전달
재료 양 확인용이므로 재화 부족 확인 필요 x 

# 240720 작업 진행
말씀드린 기한보다 늦어져 죄송합니다.
아이콘 제작 포함하여 전반적인 작업 완료하였습니다.
곧 임시 개별 리소스 파일도 업로드해 놓겠습니다.
피드백 주시면 감사합니다!

![guide1](https://github.com/user-attachments/assets/037d5573-bcc8-47cb-8cc8-33317543d476)
![guide2](https://github.com/user-attachments/assets/6cd95d4b-18d5-43b3-ac47-6cc659fca1f7)
![guide3](https://github.com/user-attachments/assets/fd19143a-9797-43b0-ae00-34e462f13f09)

# 240720 작업 진행 2

![guide1](https://github.com/user-attachments/assets/6135e878-e61b-49ed-ade5-5112fc190ff6)
![guide2](https://github.com/user-attachments/assets/1262a9e0-147b-4b98-a5ca-60c1a6632750)
![guide3](https://github.com/user-attachments/assets/b95a5e5e-9750-43cb-bad3-3b1281d6763d)

[SLG 기본 UI](https://drive.google.com/drive/folders/1Tmz9LCGBzEV7Zdb8_f4jB7VcXyStMpSs?usp=share_link)
[SLG 재화 확인 UI](https://drive.google.com/drive/folders/1fxTBUHpSb1FEcbn42X1bpLGb3hefVywh?usp=share_link)

전반적인 아웃라인, 색 모두 수정되었으므로 다시 적용해주시면 감사하겠습니다!
기본 UI 새 파일: 1~ 8
재화 확인 UI 새 파일: 1~ 10

로고 아래 건축물 이름: 35pt
목재, 석재 옆 필요 자재 개수 표시용: 22pt
검정 말풍선 안 건축물 설명: 프리텐다드 R 16pt, 행간 26pt
말풍선 안 목재, 석재 스케일: 기존 리소스 37%
가장 작은 목재, 석재 스케일: 기존 리소스 25%

SLG UI 팩 수정은 비주얼노벨 팩과 함께 작업 진행하겠습니다.

++
![guide4](https://github.com/user-attachments/assets/61735810-dcdf-44e1-913d-71c5641e8a26)
비율 수정 작업 진행했습니다.

---
---
---

# 240727 작업 업데이트 (아마진짜로최종)

- 기본 UI 1, 2 업데이트
- 기본 UI 4, 4-1 업데이트 (window 있는 아이콘 큰 버전, 높이 통일됨)
- 재화 확인 UI 1~9 업데이트, '추천' 리소스 업데이트 (추천과 박스 리소스를 따로 사용하려면 1px 단위로 맞춰야 해서 추천+박스 합쳐진 버전도 업로드해두었습니다. 2-1에 추천만 분리한 파일도 함께 업로드했습니다!)
- 목재, 석재, 코인 파일 양쪽 여백 자르고 높이 통일하여 업데이트 (정렬을 위한 업데이트이므로! 배치에 문제 없다면 교체 없어도 OK)
- 다이아몬드 재화, 달러 동상 파일 추가 업로드
- 달러 동상과 R2-MON 기지 위치 변경. 제작 불가가 가장 오른쪽에 오는 게 깔끔할 것 같아 바꿨습니다. 

로고 아래 건축물 이름: 35pt
목재, 석재 옆 필요 자재 개수 표시용: 22pt
검정 말풍선 안 건축물 설명: 프리텐다드 R 16pt, 행간 26pt
말풍선 안 목재, 석재, 건물 건설 아이콘 스케일: 기존 리소스 37%
가장 작은 목재, 석재 스케일: 기존 리소스 25%

![lineguide](https://github.com/user-attachments/assets/f1e129a6-37bc-47b0-a2d7-871f994411b3)
단순 참고용 가이드이므로 임의로 배치해 주셔도 크게 문제없습니다.

![guide5](https://github.com/user-attachments/assets/d9753114-71fb-4a15-8b76-2ac8c9b82c00)
![guide6](https://github.com/user-attachments/assets/9cdfb131-3998-4107-b77c-d60a33aea4c3)
![guide7](https://github.com/user-attachments/assets/9409a627-0d5f-46a5-a3f6-1b2c5c5dcfd6)
![guide8](https://github.com/user-attachments/assets/d53f5284-ff79-4a85-b15f-0950ffb43656)

[SLG 기본 UI](https://drive.google.com/drive/folders/1Tmz9LCGBzEV7Zdb8_f4jB7VcXyStMpSs?usp=share_link)
[SLG 재화 확인 UI](https://drive.google.com/drive/folders/1fxTBUHpSb1FEcbn42X1bpLGb3hefVywh?usp=share_link)

나머지 스크립트는 피그마에서 확인 부탁드립니다. 달러 동상 스크립트도 요청드리겠습니다!
+ 플로야드 다리 재화 개수는 목재 25 / 석재 20입니다! 가이드에 기재를 잘못해둬서 같이 수정 부탁드립니다… (_ _)

**Comment by wooyn730** [comment]
![image](https://github.com/user-attachments/assets/698fa44b-3e68-421a-b951-2da5272b0fed)

저는 배경은 이전 버전이 기존 UI들이랑 더 잘 어울리는 것 같습니다.
(아웃라인과 하이라이트 들어간 느낌 등)
배경색만 바꿔도 좋을 것 같고요

<br>

![image](https://github.com/user-attachments/assets/201e7019-658e-4119-9055-912e5eeb8bf4)

요거랑 제작 완료, 제작 불가는 좋아요!
특히 알투몬 기지 아이콘이 귀엽네요

그리고 망치 아이콘도 코인, 목재, 석재랑 비슷한 느낌으로 수정되면 더 좋을 것 같습니다

**Comment by Songkihwa** [comment]
고생 많으셨습니다 ~~!!

저도 배경은 전 버전이 더 잘 어울리는 느낌이 있네요 ㅎㅎ 바꾸신다니까 수정 버전도 기대하겠읍니닷

**Comment by Sumindd** [comment]
![image](https://github.com/user-attachments/assets/3f02ab27-7caa-4c0b-b7aa-b161aae51216)
체크 아이콘은 동그란 느낌인데 자물쇠 아이콘은 각진 느낌이어서 느낌을 통일하면 좋을 것 같습니다.
저도 큰 박스는 사다리꼴이 더 좋아요!

**Comment by roweclaw** [comment]
![image](https://github.com/user-attachments/assets/28f6126e-3104-4507-8a2f-2d1778904d51)

건물이랑 망치 아이콘이 조금 더 귀엽게 바뀌면 좋을 것 같고 배경은 사다리꼴, 아웃라인 검정으로 하면 더 잘 아울릴 것 같아요~~

**Comment by jeongopo** [comment]
아 말씀드린다는걸 잊고있었는데
다리 재건설도 작업해야해서,

다리 재건설 건설 window 랑 건설 아이콘(마마고 컴퍼니에 구름 아이콘처럼 나오는거) 시안도 알려주실수있나요?

그리고 전 구름 말풍선과 그냥 재화 말풍선도 그림풍이 좀 다른느낌이 드는데 한번 확인해주시면 감사하겠습니다~

**Comment by gomgom172** [comment]
확인해보겠습니다 감사합니다!
다리 화면 가이드도 다른 UI 파일과 함께 일괄 전달드리겠습니다!

**Comment by gomgom172** [comment]
@jeongopo UI 파일 업로드 완료했습니다! 여러 번 수고스럽게 해드려 죄송합니다. 교체 부탁드립니다! 감사합니다.
파일에 문제 있으면 연락 주시면 바로 확인하겠습니다!

@Sumindd @roweclaw 4카드 마지막 오브젝트는 달러 동상으로 제작했습니다! 습득 불가한 재화(다이아몬드)를 추가했습니다. 달러 동상 스크립트 제작해 주시면 감사하겠습니다!

**Comment by Sumindd** [comment]
현정님이 유니티에 적용하실 때 다리 제작 말풍선은 좀 더 허공으로(왼쪽으로) 옮겨도 좋을 것 같습니다!  어차피 마우스 클릭으로 설치하는 거라 라플리가 서 있는 위치랑 약간 거리 생겨도 화면에만 잡힌다면 문제 없을 것 같습니다.

**Comment by jeongopo** [comment]
![image](https://github.com/user-attachments/assets/e948456b-1b20-466a-869e-1e9fdcc4ae8e)
창 내려가 있을때 버튼 아이콘 높이가 낮은것같습니다 수정 가능할까요?

@Sumindd SLG 수민님 담당이셨던것같은데, 달러동상 마우스 호버 시 나오는 설명문구 스크립트는 우선 제가 임시로 넣겠습니다

**Comment by jeongopo** [comment]
![image](https://github.com/user-attachments/assets/b39ec4fa-b4cf-4a0a-bd67-98dc851a93da)
![image](https://github.com/user-attachments/assets/f31ade33-c497-40aa-8e75-79ee1a410e52)

적용한거 확인부탁드립니다

**Comment by jeongopo** [comment]
@gomgom172 
![image](https://github.com/user-attachments/assets/a9c48dc3-ebbc-422d-b6b0-c2712c3fa34c)
다이아몬드 에셋 아이콘 너비가 다르게 나오고있어서 확인해보니

1. 석재랑 나무 아이콘은 비율이 1:1인데요
다이아몬드 아이콘은 세로가 좀 더 깁니다
2. 석재, 나무 아이콘은 외부 여백이 있는데 다이아몬드는 없습니다

![image](https://github.com/user-attachments/assets/a9c48dc3-ebbc-422d-b6b0-c2712c3fa34c)
너비가 다르게 나오고있는데 


![image](https://github.com/user-attachments/assets/8aaa7ef9-b9c7-4b32-a479-1ba20760676d)

**Comment by jeongopo** [comment]
@gomgom172 
건설UI에 들어가는 플로야드다리 아이콘 따로주실수있나요?
사이즈가 더 커야해서 깨집니다..
![image](https://github.com/user-attachments/assets/7a6b91c0-8844-4db7-8020-b720ff1f2735)

**Comment by jeongopo** [comment]
아 아니네요 UI 수정해서 올리신거였군요
제가 글을 늦게봤네요 위에 내용은 삭제하겠습니다 😓

**Comment by gomgom172** [comment]
앗 확인 늦어서 죄송합니다. 요청 주신 부분만 빠르게 수정해서 올리겠습니다!

**Comment by gomgom172** [comment]
재화 확인 UI 1번 파일 업데이트해뒀습니다!

**Comment by jeongopo** [comment]
이우님 혹시 건설 화면(건설하기 버튼있는)은 이전에 쓰던 마마고 건설 창도 같이 바꾸는거죠?
그런거면 건설하기 버튼 이미지는 있는데 빠른 건설 이미지가 없어서 확인부탁드립니당

**Comment by jeongopo** [comment]
위로만 옮기는거맞아요! 수정감사합니다~

**Comment by gomgom172** [comment]
기본 UI 파일에 넣어뒀습니다. 감사합니다! 6번 파일도 재다운로드 부탁드립니다!
