### ISSUE TITLE
[Char] R2-Mon 스프라이트 작업

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/Grayed-Game#528]
**상세**
변경된 디자인으로 R2-Mon 리소스를 재작업합니다.

**파일**
[캐릭터 폴더](https://drive.google.com/drive/folders/1n9BeEAncWHCryg3RRbfaVo6b_f3WB6Fx?usp=drive_link)에 버전2 넣어뒀습니다!

**Comment by wooyn730** [comment]
R2Mon 귀여워져야함-파로서 정말 좋네요 👍
특히 모자랑 짝눈, 배에 있는 네모가 마음에 들어요 ><

피드백도 몇가지 남깁니다

<br>

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/7df0b48e-4a7a-4261-9111-2527790716a1)

1. 가장 첫 줄 스프라이트들은 필요 없습니다 (어차피 아래에 같은 스프라이트가 있기 때문에 다른 캐릭터 파일들도 첫줄은 안씀)
(사실 각 줄의 2, 4번째도 중복이미지라 4번째도 필요 없긴 함. 1980년대가 아니니 중복에 깐깐할 필요는 없지만..^^)

2. 4번째 줄 3번째 알투몬 스프라이트 손이 잘립니다.

3. 알투몬은 왼쪽 팔이 기니까 저희가 보는 기준으로 4번째 줄에 오른쪽 팔들이 길어야하는 거 아닌가요?

4. 라플리보다 키가 꽤 작은 설정으로 알고 있는데 키가 작은 것도 표현되면 더 좋을 것 같습니다.

<br>

CH2 알투몬 스프라이트도 나오면 한 번에 적용하겠습니다~
화이팅!!

**Comment by royalbluesm** [comment]
**0702수정**
정렬 어긋남, 캐릭터 크기 및 이것저것 수정한 버전2 동일 폴더에 올려뒀습니다. 변경하여 사용하시면 될것같습니다 
@wooyn730 피드백 감사합니다 ^.^
