### ISSUE TITLE
[CH2] Scene 1 BGM 제작

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/Grayed-Game#531]
#524 참고하여 제작 

-------

게임 녹화가 안되가지고 일단 우연님이 6월 15일에 올려주셨던 영상으로 프리뷰 영상 따봤습니닷

[Ch2 #1 BGM Preview](https://drive.google.com/file/d/1Lbx6R_ag9sWXI4cYIi_pi-BJ5lI-cZ9r/view?usp=drive_link)

1챕터에서 쓰지않았던 뾰로롱 질감의 Intro 4마디 
-> 요건 그냥 장르가 바뀜에 따라 1챕터에서 쓰지 않았던 질감의 사운드를 보여주고싶어서 썼습니다!
평화로운 분위기를 보여주는 A 8마디
-> 평화롭지만 베이스가 살짝 어두운 느낌으로 기강 잡아주고 플룻 소리가 평화로워보이지만 뭔가 사연있어보이는 그런 느낌.. 으로 작업해봤는데 느껴지시나요?,,,
평화로운 분위기에서 점점 고조되는 B 8마디
레퍼런스 곡의 느낌을 따라해본 C 8마디
Outro 4마디는 사실 어떻게 마무리할지 고민중이라 급하게 집어넣었읍니다 . . 

레퍼런스 퀄리티에 비하면 많이 부족하지만,, 일단 요렇게 작업해봤습니닷
피드백, 수정요청 환영입니다 ><!!!

금요일날 12시 전까지 피드백 받고 고칠 수 있으면 고쳐서 음원으로 올리겠습니당

**Comment by fkdl0048** [comment]
피드백 없습니다. 그냥 너무 좋아서 듣기도 편하고 원하는 평화로운 느낌이라 딱 평화로운 마을 기본 BGM 같습니다. 사운드 퀄리티도 너무 좋아요,, 시연회때 이어폰이나 헤드셋을 무족권 제공해야할 듯 합니다.

약간 슬픈 느낌도 있어서 그래픽적으로 바래진 느낌이랑 잘 어울리는 것 같아요

**Comment by Sumindd** [comment]
평화로우면서도 아련한 느낌이라 흑백인 게임과도 잘 어울리고 좋은 것 같습니다! 
사운드 무한 재생 켜놓고 설레는 마음으로 2챕 작업해오겠습니다~

**Comment by roweclaw** [comment]
저는 평화로운 느낌이 나서 좋지만, BGM이 조금 서글프고 무겁게 느껴져서 이런 부분이 덜어지면 좋을 것 같아요!
플룻 소리가 변주되면서 더 그렇게 느껴지는 것 같은데, 2챕터때 기본적으로 쓰이는 BGM인 만큼 조금 더 가볍게 가도 괜찮겠다는 의견 던져봅니다..!

**Comment by wooyn730** [comment]
너무 잘 들었습니다. 중간에 플롯 변주(B?) 부분이 특히 마음에 드네요 👍

주관적인 피드백 사항은 두가지입니다.

1.
C와 Outro의 차이가 너무 두드러지지 않았으면 좋겠습니다.
_(급하게 넣었다고 하신 것을 봤지만~)_
Loop할 곡인데 끝나는 느낌이 조금 강하지 않나 싶습니다.

2.
조금 더 부드럽고 평화로워도 좋을 것 같습니다.
저는 플롯이 약간 쎄게, 그리고 꽤 구슬프게(?) 느껴지네요

암튼 느낌이 참 좋네요 기화짱 ^_^b

**Comment by Songkihwa** [comment]
피드백 해주셔서 감사합니다!!

Outro는 C와 비슷하게 수정해서 루프해도 이상하지 않게 수정하고
수빈님 우연님 의견 반영해서
플룻소리 덜 구슬프게 수정해보겠습니닷
