### ISSUE TITLE
[CH1] 미카엘 등장 컷씬 작업

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/Grayed-Game#534]
**상세**
미카엘 등장 컷씬을 작업합니다.

**파일**
[폴더](https://drive.google.com/drive/folders/1n9BeEAncWHCryg3RRbfaVo6b_f3WB6Fx?usp=drive_link)에 버전 2가지 넣어놨는데 1은 살짝 윤곽이 보이는 버전이고 2는 아예 블랙인 버전입니다. 

![캡처](https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/89e8ee5b-fe4e-4047-bd74-2ae08f2f1830)

둘중에 더 괜찮은 버전으로 적용해주시고 기획서엔 좌우이동만 나와 있어서 좌우이동만 구현했는데 상하이동도 필요하면 말씀해주세요~

**Comment by Sumindd** [comment]
깔끔하게 작업해주셔서 감사합니다! 뭔가 망토 의상 같아서 괴도 느낌도 나고 기획 의도대로 진짜 수상해서 좋네요...

**Comment by wooyn730** [comment]
은은하게 보이는 미카엘이 귀엽네요..
적용 버전입니다.

https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/1a0ab84f-fbcb-4243-93c7-dd7643e784eb

_화질은 설정 만져보는 중입니다 흑흑.._
_먼지는 어떻게 넣을지 고민되네요_

뒤지다가 멈칫하는 부분까지 블랙버전, 이후 오른쪽으로 뛰는건 윤곽 보이는 버전으로 했습니다.
왜나면 멈칫까지는 뒷모습, 뛰는 건 앞모습이 보여야된다고 생각했기 때문이죠..

저는 윤곽 버전이 훨씬 좋은 것 같습니다
어차피 잘 안보이기도 하고, 상상력을 자극(?)하는 느낌이라 좋네요..

![image](https://github.com/GG-Studio-990001/Grayed-Game/assets/80298207/59bb8b36-6526-4012-a8f2-9d0112cc63dc)

뒤지는 장면에 해당 두개 스프라이트를 사용했는데
이 두 개 사용한 거 괜찮은지 말씀해주시고
괜찮다면 요거 뒷모습 버전 주시면 좋을 것 같습니닷

**Comment by fkdl0048** [comment]
연출적인 부분이 들어가니까 3번째 맵의 정적인 느낌이 많이 사라져서 좋은 것 같습니다. (전에는 그냥 뚝 하고 들어가는 느낌인데)
2챕터 서사부분이 1챕터에 들어가니 연결된 느낌도 나고 좋아요!

**Comment by Sumindd** [comment]
적용된 컷씬 보니까 3번째 맵으로의 진입이 훨씬 자연스러워진 느낌이네요! 점점 1챕터의 완성도가 높아지고 있는 것 같아 설렙니다

**Comment by fkdl0048** [comment]
@wooyn730  화면 먼지 관련은 이거 두가지 영상 참고해서 제작 가능할까요?
https://www.youtube.com/watch?v=8pF8uTIJyKM
https://www.youtube.com/watch?v=2qeNu2QApAM

**Comment by royalbluesm** [comment]
0708 [미카엘 뒷모습 추가된 버전](https://drive.google.com/file/d/17UtKioK7-O96WFa3ptZw6q46G-kTkS8N/view?usp=drive_link) 업로드했습니다!

**Comment by wooyn730** [comment]
> 0708 [미카엘 뒷모습 추가된 버전](https://drive.google.com/file/d/17UtKioK7-O96WFa3ptZw6q46G-kTkS8N/view?usp=drive_link) 업로드했습니다!

적용했습니다 ^^b

> @wooyn730 화면 먼지 관련은 이거 두가지 영상 참고해서 제작 가능할까요?

네! 물론입니다 ~(아직 안해봤지만)~
이렇게 참고자료 주시는 거 좋습니다 감사합니다~

_(사실 위에 코멘트에서 언급한 건 미카엘이 물건 뒤질 때 나는 먼지이긴 합니다 ^^..)_
