### ISSUE TITLE
[CH1][CH2]BIC 데모 대비 개선사항

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/Grayed-Game#537]
**상세**
BIC 데모데이 대비 퀄리티 업 작업을 진행합니다.

- [x] 럭키 말풍선
- [x] CH2 알투몬 스프라이트
- [x] 럭키 폰트
- [x] CH2 폰트

작은 작업 여러개라 끝날 때마다 체크하여 전달드리겠습니다.

**파일 및 미리보기**
1. 럭키 말풍선 - [폴더](https://drive.google.com/drive/folders/1kLS6CFGIQ0-WpYepwGaxiSzNwgsZtnzv?usp=drive_link)에 넣어뒀습니다.
2. CH2 알투몬 스프라이트 - [폴더](https://drive.google.com/file/d/1854gq3x5wlKj4M8vj80OySAOKrsJSMnE/view?usp=drive_link)에 넣어뒀습니다.
3. 럭키 폰트, CH2 폰트 - 폰트 자체에 특성을 주는 것보다는 최대한 깔끔하고 특색 없이 가는 게 나을 것 같아 모두 다 프리텐다드 세미볼드체로 적용했습니다. 상업적 이용 가능한 폰트이고 폰트 전체를 다운받으신 뒤 세미볼드를 적용하시면 될 것 같습니다.

![ch2](https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/a0e2da2d-5009-4e6d-941d-43554203ea5a)
![럭키 말풍선 폰트](https://github.com/GG-Studio-990001/Grayed-Game/assets/144519956/ceb84ac2-8d77-4aec-8bc2-837d2c91dcf2)

말풍선과 폰트를 적용하면 이런 느낌입니다.

**Comment by roweclaw** [comment]
R2-MON 변경된 디자인으로 된 스프라이트 보니까 확실히 더 귀엽고 챕터2에 잘 어울리는 느낌이네요! 폰트랑 말풍선도 좋네요! 굿굿 👍

**Comment by wooyn730** [comment]
럭키 말풍선이 깨진다는 피드백이 있었는데 압축을 None으로 해도 깨지네요
말풍선 자체 사이즈가 163*41이라 작아서 그런 것 같습니다
사이즈 좀 넉넉하게 새로 부탁드려요

**Comment by royalbluesm** [comment]
@wooyn730 [완료](https://drive.google.com/file/d/12kp4fRjJMjrnIYoFPuQiy4SYri4Bigpd/view?usp=drive_link) 입니다!

**Comment by wooyn730** [comment]
![image](https://github.com/user-attachments/assets/d571fa17-9a76-4319-b558-853523564b6f)

@royalbluesm 
민지님 이거 뒤에 투명한 배경이 아니에요 ^_^....
그리고 화질 괜찮나요?
지금 사이즈로 투명 배경 + 사이즈 2배한 버전도 한 번 더 주실래요??
