### ISSUE TITLE
[CH1] 데모데이 수정사항

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/Grayed-Game#538]
데모데이 맞춰서 사운드 수정할 부분 있으면 코멘트 따로 남겨주시면 수정하겠습니다!

없으셔도 제가 빌드본 보면서 몇 가지 개인적으로 아쉬운 부분들 수정 보완 작업해서 올릴 예정입니다.

-------

[데모데이 대비 수정사항](https://drive.google.com/drive/folders/1ctG2Abl1jBn9LPMBQsgBrjpYoKBjoejR?usp=drive_link)

개인적으로 아쉬웠던 부분 조금조금씩 수정했습니다!
타이틀이랑 SLG 효과음 튀는 부분들, 3매치 효과음에서 들을 때마다 귀에 거슬렸던 부분들이 있어서 
차이 못 느끼실 수도 있지만 조금씩 수정해봤습니당

제 맘대로 그냥 조금씩 수정해본거라
적용된거 빌드본 확인해보고 전 버전이 낫다고 하시면은 원래있던 파일로 바꾸셔도 됩니다~~!!!

**Comment by roweclaw** [comment]
@Songkihwa 럭키 텍스트음 작업 요청드립니다!

[레퍼런스 : Dadish Sound Affects](https://youtu.be/8JUWidtVUmU?si=JyXmULmtrCo743AU&t=5)

럭키 BGM 자체가 좀 높고 밝아서 텍스트음은 낮게 가는 게 듣기 편하지 않을까 합니다.
그래서 **0:05 ~ 0:08** 과 같거나, 또는 조금 더 낮은 톤으로 잡으면 좋을 것 같아요!
한 번 확인하고 말씀 부탁드려요~
