### ISSUE TITLE
[CH2] Scene 1 BGM 수정

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/Grayed-Game#539]
#531  피드백 바탕으로 수정하여 완성할 예정

----

[Ch2 #1 BGM 수정](https://drive.google.com/file/d/18FsprsKcuP1hnACzyM8LkeC2EFFM5STy/view?usp=drive_link)

우연님 수빈님 의견 반영해서
플룻 소리 덜 구슬프게, 너무 돋보이지 않게 수정했고
Outro 부분을 없애고 C 다음 C'로 비슷하게 8마디 반복하게 해서 루프해도 이상하지 않게 수정하여 완성했습니닷!

제가 갑자기 작업하는 노트북 샘플레이트 이슈때문인지
제가 가지고 있는 모든 오디오 파일이 속도가 빠르고 피치가 변화된 .. 문제가 있어서 (파일들은 다 멀쩡한 상태인데 제 노트북에서 들으면 이러네요 ...) 정확하게 노멀라이징을 했는지 비교하면서 듣기가 어려워서요 흑흑

빌드본나오면 그걸로 다시 모니터링 해보고 문제 있으면 한번 더 수정해서 보내드리도록 하겠습니다!! ㅜㅜ

**Comment by roweclaw** [comment]
수정 작업 고생하셨어요! 들어보니까 C에서 C' 연결도 자연스럽고 플룻 소리도 적절하게 녹아든 느낌이 되어서 좋아졌네요! 만족합니다 ㅎㅎ 피드백 반영 감사드려요~!

**Comment by wooyn730** [comment]
https://github.com/user-attachments/assets/fdfa92ff-d9dd-469d-ae11-97d2cabe1521

루프되는 구간도 너무 자연스럽고 수정된 버전 넘 좋아요 ><
