### ISSUE TITLE
접속/탈출 연출 씬 구현

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#540]
[기획 참고 ([CH1] 장르전환 연출 구체화)](https://github.com/GG-Studio-990001/Grayed-Game/issues/527)

현재 씬>중간 씬>다음 씬

**계획**
- [x] 1. 중간 씬(접속 씬, 탈출 씬)을 만둘기 (배경만)
- [x] 2. 두 씬을 Additive Scene으로 해서 다음 씬으로 넘어가는 동안 보여주기
- [x] 3. 중간 씬에 효과를 추가
- [x] 4. 임시버전을 보여준 후 이미지와 효과음을 요청
- [x] 5. 이미지와 효과음 적용

**문제1**
중간 씬이 안 불러와짐
=> 씬 이름 잘못 적은 거였음 ㅎㅎ..

**문제2**
다음 씬이 안불러와짐
=> SceneTransform 클래스가 파괴돼서 그런거였음 => DontDestroyOnLoad 추가
_(발견한 나 장하다..)_
_~(왜 GPT는 안 알려준거야)~_

**문제3**
중간 씬 켤 때 인풋을 안막음
`PlayerInputDisable()` 이거는 되는데 
`_gameOverControls.Player.Disable();` 이거는 안됨 왜지..??

**주의**
이벤트 시스템, 오디오리스너 삭제 안하면 워닝 뜸

---

### 접속 효과

0. 입력 막기
1. 기존 씬 + 글리치 효과 1초
2. 컬러바 이미지 + 왜곡 2초
3. 다음 씬
4. 입력 풀기

### 탈출 효과

1 제외
2. 노이즈 이미지 2초 (1.5초 보여주고 0.5초 동안 꺼짐)
0, 3, 4 동일

---

문제

에디터 상에서는 효과가 잘 나오는데, 빌드하면 일부 효과만 적용됨

시도한 방법
1. 볼륨의 Weight 값 1로 설정
2. Camera-Rendering-PostProcessing 체크
3. 카메라 볼륨 트리거에 카메라 넣어보기
4. 카메라 Priority -1에서 1로 바꾸기
5. 카메라-환경-볼륨-업데이트 모드 every frame으로 바꿔보기
6. 포스트 프로세스의 글로벌 세팅 몽땅 체크하기
7. 볼륨 priority 0에서 1로 바꾸기
8. 효과 1개만 남기고 꺼보기/지워보기 => 일부 효과들은 빌드에서 적용이 안됨;;;
![image](https://github.com/user-attachments/assets/46256547-a5b1-431a-8009-8b2dc0d084cf)
와 여기에 넣으니까 됐다 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

---

`DOanchorPos` 왜 안되지....?

---

### 0722 필요한 리소스

컬러바 이미지
노이즈 이미지
라이트 이미지
=> 이우님께 요청

탈출 효과음
=> 수정사항 없는거 체크하고 기화님께 요청

**Comment by wooyn730** [comment]
https://github.com/user-attachments/assets/1d659cef-910b-4217-a125-8117382d08f5


https://github.com/user-attachments/assets/16999979-4f90-4a8f-bab4-ad2e8ff89989

접속과 탈출입니다

@roweclaw 
[장르전환 연출 구체화](https://github.com/GG-Studio-990001/Grayed-Game/issues/527) 이슈 최대한 참고하긴 했는데
연출 효과 링크랑 저희가 사용중인 효과랑 약간 다르네요ㅠㅠ; 
수정하면 좋을 점 있으면 말해주세요!! (수빈님 외 다른 분들도 포함)

그리고 컬러바랑 노이즈 이미지 피그마에 있는거 가져다 썼는데 아트분들께 요청해야할까요?

@Songkihwa 
효과음 만드실 때 이슈 하단에 시간 초 확인해주세요!

**Comment by Songkihwa** [comment]
넵 확인했습니다~!!

**Comment by wooyn730** [comment]
결론
- 접속 효과는 OK
- 기화님께 사운드 요청
- 다음 회의 때 아트분께 컬러바 요청 (비율 맞게)
<br>

- 탈출 효과는 일단 요청대로 수정
- 사운드 요청은 일단 보류
- 다음 회의 때 논의 (애니메이션으로 받을지, 효과를 쓸지, 시간을 단축시킬지)

**Comment by wooyn730** [comment]
### 탈출 연출 2차 수정 버전

https://github.com/user-attachments/assets/9eb785a1-b316-465e-950f-85fa280faf66

**Comment by roweclaw** [comment]
## 타이밍 피드백

> 3. 노이즈 이미지가 위아래로 줄어든다.

속도를 훨씬 빠르게 부탁드립니다. 거의 줄어드는 느낌이 안보일 정도로 확! 해서 화면이 꺼지는 느낌이 들면 좋을 것 같아요.

> 7. 하얀 빛이 점으로 줄어들면서 사라진다.

지금은 노이즈 선이랑 빛이 같이 사라지는데, 빛만 보이는 순간이 있으면 더 자연스러울 것 같아요!

1. 선이 먼저 사라지고, 빛만 보인다
2. 그 다음 빛이 사라진다
3. 검은화면

이 순서로 수정 부탁드려요~!

**Comment by wooyn730** [comment]
### 탈출 연출 3차 수정 버전


https://github.com/user-attachments/assets/e7a57ec0-1be6-4817-af45-f8e59d009e36

@roweclaw 확인 부탁드립니다~

노이즈 화면 1.2초
수직 수축 0.2초
수평 수축 0.2초
빛 확장 0.3초
빛 수축 0.1초
로 작업하였습니다

**Comment by roweclaw** [comment]
확인 했습니다~ 전 너무 좋네요
전체적으로 꺼지는 느낌이 확 살도록 타이밍을 세세하게 조절해주신 덕분인 것 같습니다~!

**Comment by Songkihwa** [comment]
저 그럼 이 영상에 맞춰서 사운드 작업 진행하면 될까요?

**Comment by wooyn730** [comment]
> 저 그럼 이 영상에 맞춰서 사운드 작업 진행하면 될까요?

넵 승인 받았으니 영상이랑 아래 초 참고해서 작업 부탁드려여 ^_^

**Comment by wooyn730** [comment]
## 접속 연출 이미지 교체


https://github.com/user-attachments/assets/826f8e6e-4b45-4ddf-9da4-0d2d93f87836

_접속 연출은 실행할 때마다 약간씩 타이밍이 달라지는듯..?_


## 탈출 연출 이미지 교체


https://github.com/user-attachments/assets/c649d99f-3218-4879-85ae-9f1c54ea0b0c

@roweclaw 
@Songkihwa 
@gomgom172 
이미지, 사운드 모두 적용한 버전입니다 확인 부탁드립니다

**Comment by Songkihwa** [comment]
우앗 좋네요!! 고생하셨습니다 😆😆

**Comment by gomgom172** [comment]
정말 넘 고생 많으셨습니다 👍👍

**Comment by Sumindd** [comment]
깔끔하네요!! 다들 고생하셨습니다

**Comment by roweclaw** [comment]
완성도가 높아서 좋네요~ 고생 많으셨습니다! 👍

**Comment by Songkihwa** [comment]
[역접속 글리치 사운드](https://drive.google.com/file/d/1PW3XGro2bLnhTHF3ooONJZ0gYOs4ijus/view?usp=drive_link) 잘라서 구드에 업로드 했습니당. 아마 원래 효과랑 똑같다면 딱 맞을거에요!!
