### ISSUE TITLE
[CH1] 비주얼노벨팩 아이템 리소스

### ISSUE THREAD

**Issue by gomgom172** [GG-Studio-990001/Grayed-Game#545]
SLG UI 작업 끝난 후, 퀄리티업 이전에 먼저 작업합니다.

![image](https://github.com/user-attachments/assets/80a404f9-ea5b-4ec3-9661-9514fc6419c8)

[SLG UI 아이콘 수정 파일](https://drive.google.com/file/d/1sQeyibq30_04OHliSATQubT81HcTZjJi/view?usp=drivesdk)

[비주얼노벨팩 아이콘 파일](https://drive.google.com/file/d/1WXQuSWKUJKerPIzzGvbG48Ljkxq9gCbN/view?usp=drivesdk)

비주얼노벨팩은 만능설명팩과 같은 사이즈로 작업하였습니다.

**Comment by roweclaw** [comment]
SLG 파란색으로 바뀌니까 UI랑 통일성 있어서 좋네요! 비주얼노벨도 호감도 상승 하락으로 포인트잡고 귀엽게 잘 나와서 좋습니다!! 고생하셨어요~

**Comment by wooyn730** [comment]
SLG팩 바뀐 거 정말 마음에 드네요 ^_^

비주얼노벨팩은 예쁘고 좋은데 팩 모양은 럭키랑 다르면 좋지 않을까 합니다.
장르팩만의 모양이 있으면 좋을 것 같아요.
(럭키랑 통일이 아닌 추후 나올 장르팩들과 통일되는 느낌으로) (SLG팩처럼 좀 더 커도 좋을 것 같고?)

럭키팩 형태가 활용하기 좋아보여서 차라리 럭키팩을 아예 특이하게 만들면 어떨까 싶기도 하고요
(럭키는.. 특별하니까?)

만능번역팩은 럭키랑 비슷한 사이즈면 괜찮을 것 같아요

**Comment by gomgom172** [comment]
코멘트 감사합니다! 만능번역팩을 특이하게 작업하는 방향으로 가지 않을까 싶습니다.
회의 때 한 번 여쭤보고 이번주에 만능번역팩 수정 들어가겠습니다!

**Comment by wooyn730** [comment]
만능번역팩 != 럭키팩인거 아시져...??

**Comment by fkdl0048** [comment]
전체적으로 퀄리티 올라가서 보기 좋습니다..! (도트 퀄) 우연님 말씀은 뭔지 잘 이해가 안가서 회의 때 듣겠습니다?

**Comment by gomgom172** [comment]
만능설명팩=럭키팩이라고 생각했는데 제가 뭔가 놓친 게 있나요...!? 이따가 여쭤보겠습니다!
