### ISSUE TITLE
[CH1] 접속 탈출 연출에 따른 SFX 작업

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/Grayed-Game#549]
-#540 참고하여 접속 탈출 연출 효과음 작업 예정

----

접속은 완성했습니다 혹시 몰라서 구드에도 올려뒀습니당

[접속 효과음 파일](https://drive.google.com/file/d/1TS2k-8cjd1kxXc1o68ebpcHdiY-JHS9-/view?usp=drive_link)

탈출 효과음도 완성되는대로 바로 작업할 예정입니닷 

------

[탈출 효과음 미리보기](https://drive.google.com/file/d/19uHvKC-AZSHqtEL70TcjWWPO-NoR1e9o/view?usp=drive_link)

[탈출 효과음 파일](https://drive.google.com/file/d/1KZVt-0EgDhbfKvrdgoaGnnWPnhSG1nny/view?usp=drive_link)

일단 화면에 맞게 이런식으로 작업 해봤는데 괜찮은가요?!

**Comment by wooyn730** [comment]
https://github.com/user-attachments/assets/24db9ec5-9c10-4656-841d-88add2b4a5ce

접속 연출
이건 기화님이 주신거 적용한 영상!
완전 찰떡콩떡입니다 👍

<br>

https://github.com/user-attachments/assets/f3e4b819-17dc-45f4-a45c-f371364562e2

탈출 연출
이거는 수정될 거라 효과음 요청을 보류했는데 접속에만 고퀄 효과음 들어가고
탈출에는 아무 소리도 안나니 허전?해서
유튜브에서 대충 주워서 임시로 적용햇습니다

++
효과음 네이밍 시 접속-Connection 탈출-Escape로 해주세요!

**Comment by Sumindd** [comment]
빌드로 확인했는데 접속 연출이랑 사운드 너무 잘 어울리고 좋아요! 짱!!

**Comment by wooyn730** [comment]
사운드가 타이밍이 딱딱 맞아서 신기하고 좋네요 ^_^b

저는 마지막에 빛 효과음만 빠진 것도 들어보고 싶어요!

빛 자체에는 소리가 없는 게 자연스러울 것 같기도 하고,
지금은 빛이 임시 이미지라 나중에 새로 빛 이미지 받아서 적용하면 더 옅고 자연스러워지지 않을까 싶습니다
(진짜 CRT TV를 끌 때 보이는 잔여에너지처럼?)

**Comment by Songkihwa** [comment]
앗 빛이 임시였군요? 빛사운드 뺀 버전도 올려드릴게요!

**Comment by Songkihwa** [comment]
바로 빛 사운드 없는 버전 업데이트 했습니당 ~~ 골라서 사용하시면 될 것 같아요!

**Comment by wooyn730** [comment]
감사합니다 우선 개취로 2번 적용해두겠습니다 ^_^
나중에 이미지 교체하고 사운드랑 같이 보면 좋을 것 같아요~~

**Comment by Songkihwa** [comment]
좋아용~~!!

**Comment by wooyn730** [comment]
https://github.com/user-attachments/assets/47ecc0af-a799-4880-a65d-ea74a5ee4971


앞에 노이즈 길이 좀 더 늘려주실 수 있나요
제가 제 이슈 코멘트로 남겼던 탈출 연출 영상이 앞에가 약간 짤려있었나봐요 제송 ㅠ_ㅠ...

**Comment by Songkihwa** [comment]
아앗 --!!
[수정한 버전](https://drive.google.com/file/d/16vK3Mah8DC0q63EytMkwOw3nNTWGZLbK/view?usp=drive_link) 올려드립니당

**Comment by wooyn730** [comment]
감사합니다 감사합니ㅏㄷ~~~~!!
