### ISSUE TITLE
빌드 공장

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#551]
데모데이부터 오프라인 전시까지 BIC를 위한 빌드 공장이 가동될 예정입니다
코멘트로 달리는 최신의 빌드 확인해주시고 버그, 요청사항 등 코멘트 많이많이 달아주세요

---

실시간 피드백 우선순위 정렬
https://docs.google.com/spreadsheets/d/1x_Rz09V7zD9MRT8yy9H-mmbQ7r809jbHCKjPCP-icXE/edit?gid=0#gid=0

**Comment by wooyn730** [comment]
07/17(수) 오전 2시
[ver0.0.4](https://drive.google.com/file/d/1EOTYIcbg9AjRsnm5Pfc4ldmdO8ZnEEiV/view?usp=drive_link)

<br>

주요 변경
- 럭키 말풍선 교체
- 오브젝트, 마마고 직원 대사 수정
- 접속, 탈출 효과음 추가

**Comment by fkdl0048** [comment]
- 07/17 기준 피드백

색채가 없는 지하세계에서 아직 빛을 발하고 있는 고전 게임과 장르를 소재로 이용하여 스토리를 진행해 나가는 어드벤쳐 게임입니다. 익숙한 장르와 게임을 패러디하여 잘 비틀어 배치가 되어있는데, 3match 이후 SLG 빠른 건설에 코인이 부족해 다시 벌어왔는데 3match 게임이 리셋되어있고 마지막 스테이지에서 첫 블록이 움직이지 않아 더이상 플레이하지 못한게 조금 아쉬웠습니다.
버그로 인해 끝까지 즐기진 못했으나 흥미가 생기고 앞으로가 기대가 되는 게임이네요.

**Comment by roweclaw** [comment]
럭키
- 말풍선 모퉁이 부분 화질이 깨짐

팩맘
- 설정창에서 소리 조절 불가능

다리
- 이전 씬에서 라플리 미리 조작하는 상태로 맵 넘어가면 계속 조작 가능한 상태가 유지되어 다리를 넘어갈 수 있게 됨 (디코에 스샷 참고)

동굴
- 왼쪽 동굴은 '별로 들어가고 싶지 않다'로 막혀있는데, 다리 부서지기 전에 오른쪽 동굴 입구로 건너가서 들어가면 동굴로 들어가짐. 여기도 막으면 좋을 것 같네요.

3매치
- 럭키가 물고기 소환하는 기믹과 대사의 부조화. 아직 저 물고기가 필요한 상황인지 모를 때 갑자기 튀어나와서 두고 가는 상황인데 행운이 필요해?랑 럭키 효과라고 하는게 바로 이해가 안되는 느낌이라... 우선 대사를 수정하는 방향으로?
- 3매치 클리어 후 컷신에서 R2-MON 텍스트음 적용 안 되어 있음

SLG 맵
- 미카엘이 도망갈 때 SLG 팩을 밟고 가는 동선이 이상함. 색깔 있는 거에 닿으면 위험한데 밟고도 아무일도 안일어나니까 수정 필요.

비주얼노벨 전환 연출
- 배경만 있고 효과 적용이 안 되어 있음

**Comment by Sumindd** [comment]
### 0.04 피드백
**맵1**
- 맵1 스페이스바 눌러볼 수 있도록 맵에 트리거 거는 것보단 말 거는 방식으로 변경하면 좋을 것 같습니다. 딱 그 화면에서 스페이스바와 이동키가 보여서.. 바로 적용 확인 해보고 가는 게 좋을 것 같아요.
- 추가적으로 키보드랑 스페이스바 오브젝트 있는 쪽에 빛이 은은하게 나거나 먼지가 유독 날아다니는 등의 강조가 있어도 좋을 것 같아요

**접속 게임**
- 럭키의 폰트가 좀 큰 느낌..? 글자 크기 줄여도 될 것 같습니다. 말풍선도 좀 크기가 크고 화질이 깨진 것 같아요
- 라플리가 접속게임에 '갇혔다'라는 느낌이 별로 안 들 수도 있을 것 같습니다. 럭키가 좀 더 갇혔다는 표현을 직접적으로 해주거나, 사실 탈출하기 어려웠는데 탈출해버렸다라는 느낌이 강하게 들게 만들면 더 좋을 것 같아요.
- 접속 탈출할 때 치직이는 흑백 화면이 움직였으면 좋겠어요 유독 정적으로 느껴집니다..

**Comment by fkdl0048** [comment]
07/22 
[ver 0.0.5](https://github.com/GG-Studio-990001/Grayed-Game/actions/runs/10030261996) (버그 수정버전) SLG 버그는 수정 안됨

**Comment by wooyn730** [comment]
07/22(월) 오후 10시
[ver0.0.7](https://drive.google.com/file/d/1vCspg84gZ1YBCuslaMBOfiVrZe4XNN2b/view?usp=drive_link)

<br>

주요 변경
-

**Comment by fkdl0048** [comment]
7/25 오후 11:59

[ver0.0.8](https://github.com/GG-Studio-990001/Grayed-Game/actions/runs/10096482819)

**Comment by wooyn730** [comment]
7/29 오후 7시

[ver0.0.10](https://drive.google.com/file/d/1YaICNeraRl-U9ThBTS4KpgC53U2PFef7/view?usp=drive_link)

주요 변경
- 접속/탈출 연출 완성
- SLG 하단 창 추가, 다리 짓기 가능

**Comment by wooyn730** [comment]
08/02 09:30PM

[ver0.0.11](https://github.com/GG-Studio-990001/Grayed-Game/actions/runs/10215336751/artifacts/1769070229)
누르면 바로 다운로드 됩니다

<br>

주요 변경
- SLG 퀄리티업
- 화면 먼지 추가

**Comment by wooyn730** [comment]
08/02 11:30PM

[ver0.0.12](https://drive.google.com/file/d/1ET5MRsT2z-aQgKjB1c_UAs7ol_erfd6W/view?usp=drive_link)

<br>

주요 변경
- 버그 픽스

**Comment by wooyn730** [comment]
08/09 01:30AM

[ver0.0.13](https://drive.google.com/file/d/17wRKq6-3XJg9GEu2pktBEGH9yeEpEetA/view?usp=drive_link)

주요 변경
- SLG 퀄리티업 ([이슈](https://github.com/GG-Studio-990001/Grayed-Game/issues/584#issuecomment-2267526113))
- 타이틀에서 이어하기
- 럭키팩 먹은 후 움직임 막기

**Comment by wooyn730** [comment]
08/11 10:00PM

[ver0.0.14](https://drive.google.com/file/d/15NY-krW_3ZgOI2MEisYdw-C2Dop1sWhr/view?usp=drive_link)

주요 변경
- 챕터2 연출
- 챕터2 맵 이동, 스킵 기능

**Comment by wooyn730** [comment]
08/12 07:00PM

[v0.0.15](https://drive.google.com/file/d/1gpCkUR-ldLBvzKSRPdTJ4LI630_4DUxZ/view?usp=drive_link)

주요 변경
- 럭키 대사 폴리싱 적용
- CH1 텍스트 애니메이션 적용

**Comment by wooyn730** [comment]
08/12 07:00PM

[v0.0.15](https://drive.google.com/file/d/13RGlJmsRm_3rRsF9KXwclXC41_OIog10/view?usp=drive_link)

주요 변경
- 럭키 대사 폴리싱 적용
- CH1 텍스트 애니메이션 적용

**Comment by wooyn730** [comment]
08/14 08:40PM

[v0.0.16](https://drive.google.com/file/d/1fgbjdzUpKlCcSdqzpYHcv1lvO_LTWdCK/view?usp=drive_link)

주요 변경

- 3매치 스테이지3 물고기 수정
- 대사 폴리싱
- 자잘하게 불편한 버그

**Comment by wooyn730** [comment]
08/17 03:00AM

[v0.0.18](https://drive.google.com/file/d/1kSEBDi8XTj56Nfc78fXOSoKC0sgs2Wny/view?usp=drive_link)

주요 변경

- 타이틀에서는 항상 새로 시작
- 저장 관련 리팩터링
- 버전 비교 주석처리
