### ISSUE TITLE
[CH2][Char] 라플리 / 미카엘 스탠딩 일러스트 작업

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/Grayed-Game#565]
**상세**
위 캐릭터들의 스탠딩 일러스트를 작업합니다. (표정 바리에이션 확인 후)

**파일**
[폴더](https://drive.google.com/drive/folders/1rpobgkwSOaJADqHvWNRGEsESOC3gZYKa?usp=sharing)에 파일 넣어뒀습니다!

**Comment by roweclaw** [comment]
미카엘까지 일러스트로 보니까 비주얼노벨적인 느낌이 잘 나올 것 같아서 마음에 드네요~!

필수로 수정 요청드리고 싶은 부분은 미카엘이 break 상태일 때 챕터1 도트처럼 전체적으로 어두운 그림자를 입혀주셔야 합니다.
제가 임의로 노출이랑 대비 조절해서 만든 이미지 참고해주세요!

그리고 제 개인적인 생각으로는 전체 그림자 상태가 되면 break2와 angry의 얼굴 그림자는 별로 티가 안 날 것 같아서 조금 더 찡그린 표정으로 바꾸어도 괜찮아 보이고, 링도 더 산산조각 나면 좋을 것 같아서 의견 제안드립니다!

![스크린샷 2024-07-29 125434](https://github.com/user-attachments/assets/fc874d08-2a80-475c-a0f4-7576894df779)

**Comment by fkdl0048** [comment]
break 상태를 따로 이미지로 받는 것 보다 유니티에서 처리하는게 좀 더 효율적일 것 같다는 생각이 듭니다. 아마 스프라이트 대비를 조절할 수 있는걸로 알아서 가능한지 한번 확인해보고 작업하시는게 좋을 것 같아요!

**Comment by royalbluesm** [comment]
@roweclaw @fkdl0048 확인했습니다. 그럼 일단 링 부분만 확정적으로 수정하는 걸로 알겠습니다!

**Comment by wooyn730** [comment]
@royalbluesm 
수빈님 [이슈](https://github.com/GG-Studio-990001/Grayed-Game/issues/567)에 대사 보시면 초반에도 웃는 표정이 나와서
미카엘 미소도 break 버전을 받아야할 것 같습니다

(초반에는 계속 링 부서진 상태로 아는데, 맞나요 기획자님들?)

**Comment by roweclaw** [comment]
넵 초반 미카엘은 계속 링 부서진 상태 맞습니다
