### ISSUE TITLE
[CH2] 접속게임 1스테이지

### ISSUE THREAD

**Issue by jeongopo** [GG-Studio-990001/Grayed-Game#570]
### 작업내용
- 접속게임 : 광신화 파르테나의 거울

### 관련 이슈
- #469 
- #569 
- (아트 이슈 생성 전)

### 공유사항
- 아트 8/15까지 받을것
- 8/25까지 작업 (그전에 미리 기반작업)

(이슈생성이 늦어 죄송합니다 _ _ )

**Comment by jeongopo** [comment]
@fkdl0048  @wooyn730  
우연님께 1챕터까지 작업해야한다고 따로 전달받긴했는데
혹시 정확한 마감일이 정해져 있을까요..? 🤔

**Comment by fkdl0048** [comment]
금요일 전에는 마무리 되어야 좋을 것 같긴 합니다. 온라인 전시회 빌드본이 금요일 마감입니다!

**Comment by wooyn730** [comment]
마감일은 다음 회의 때 이야기해보면 될 것 같습니다.

BIC에 포함되어야 하는 내용은 피그마에서 7월 17일 기획 회의 내용 참고해주시면 되고,
이번주 마일스톤이 챕터1 퀄리티 업과 챕터2 기획 작업인 것만 알아주시면 됩니다.

**Comment by fkdl0048** [comment]
아뇨 이번주입니다! 적용 가능하시다면 해주시면 좋습니다~!

**Comment by wooyn730** [comment]
제 생각에 정안님은 이게 CH2 이슈인 걸 모르시는 거 같은데...

**Comment by Sumindd** [comment]
접속 게임은 챕터라는 표현보다 스테이지라고 하는 게 좋을 듯요? 전체 챕터랑 헷갈리신 것 같아요 ㅋㅋㅋㅋ

**Comment by jeongopo** [comment]
수정했읍니다 .. 
일단 마감일은 회의때 다시 여쭤보는것으로 하겟습니다 ㅎㅎ..!

**Comment by fkdl0048** [comment]
아아 죄송요ㅠ

**Comment by jeongopo** [comment]
이거 작업하는건지모르겠어서 일단 이슈는 닫아놓겠습니다~ 필요하면 새로만들게요
