### ISSUE TITLE
[CH1] 텍스트 애니메이션 적용

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#573]
### 적용 대상
- 팩맘/럭키/CH1/CH2

### 개요
수빈님께 텍스트 애니메이션을 요청드렸는데 팩맘부터 달라고 했었음
팩맘은 먼지와 라플리, 말풍선에 애니메이션이 들어가있는 반면 CH1은 정적인 느낌이라 잘 어울릴지 모르겠어서임
수빈님이 빠르게 작업하셔서 지금은 CH1까지 대사가 거의 다 나온 상황
[수빈님 이슈](https://github.com/GG-Studio-990001/Grayed-Game/issues/541)

목요일 작업(플레이존 빌드에 포함되는 것)에는 팩맘과 럭키까지만 적용하기로 이야기 나눔

해당 이슈에서는 CH1 텍스트 애니메이션 관련 피드백을 나눌 예정

### 작업 내용

- `Appearances`와 `Disappearances` Effect는 제외하기로 함
- `baseAmplitude` 수치는 임의로 조절한 후 빌드본을 통해 피드백 받으려 함

---

## 문제) 직전 대사 보임 현상

Yarn Spinner로 대사를 출력하면 원래 대사가 남아있다가, 다음 대사 출력할 때 새로운 대사를 넣음.
하지만 TextAnimator를 함께 쓰면 딜레이가 걸리는 건지 이전 대사가 잔상마냥 잠깐 보임 (킹받아)

### 해결1
라인 출력할 때마다 강제로 비워주기;
럭키는 이렇게 적용함
```cs
public override void RunLine(LocalizedLine dialogueLine, Action onDialogueLineFinished)
{
    ClearLineText();
    onDialogueLineFinished();
}

private void ClearLineText()
{
    _lineTxt.text = "";
}
```
근데 CH1이나 CH2 다이얼로그는 이 방식으로 안됨
아예 대사가 안보임
_예상 이유: 이름 출력 때문? 모르겠다_

### 해결2
여러가지 실험을 해봤는데 결국 포인트는 "대화창이 꺼졌다 켜질 때" 잔상처럼 보인다는 점임
대화창이 꺼졌다 켜지는 경우는 1) 대화를 새로 시작할 때 2) 대화 중간에 wait할 때임
처음에는 매 경우의 수마다 라인을 비워줄까 하다가 에바인 것 같아서
Update 함수에서 대화창이 꺼져있을 때 라인을 비워주기로 함
(Yarn 대화창을 끌 때 Active(false)하지 않고 CanvasGroup의 alpha값을 0으로 바꿔줌)

단점: Update에서 매번 알파값을 체크하므로 부담이 있지 않을까...

alpha값이 0이 되는 그 순간에만 라인을 비워주거나, 아님 더 좋은 방법을 고안해내면 좋을 듯

**Comment by wooyn730** [comment]
### 문법 관련

@roweclaw 

`{rot}럭키님 등장이요~{/rot}`가 febucci text animator 등장 효과 문법인 건 맞는데,
대화 시스템(yarn spinner)에서도 `{}` 기호를 쓰고 있어서 오류가 났던 거였습니다!

일단 등장 효과 여는 기호 `-` 닫는 기호 `=`로 설정해두었습니다
_(괄호들은 대부분 예약어라 비슷한 거 2개로 대충... 다른 기호 추천도 받습니다)_

나중에 `-rot=럭키님 등장이요~-/rot=`처럼 적용하시면 됩니다 (퇴장도 `-`랑 `=`)
지금 럭키 스크립트는 제가 적용하면서 수정하겠습니다!

**Comment by roweclaw** [comment]
넵 확인했습니다 감사합니다~

**Comment by wooyn730** [comment]
@roweclaw 

그 외 참고사항 남깁니다

- 럭키 말풍선이 가로가 길어지고 세로는 짧아져서 세줄인 대사들은 두줄로 수정하였습니다. 앞으로도 두 줄로 작성해주세요!
- `럭키: 자세한 건 아래의<br><wave>목록을 눌러서</wave> 확인해` SLG의 이 대사는 현재 주석처리하였습니다. 현정님 작업 이후에 다시 넣을 예정입니다.
- 가끔 알투몬 텍스트음이 안나오는 버그가 보고되는데 `R2-Mon`의 이름을 `R2-MON`으로 적었을 때 생깁니다. 지금은 다 수정된 걸로 아는데 _(남아있을수도..?)_ 추후 작업하실 때 참고 부탁드립니다~
