### ISSUE TITLE
[CH1] Lucky Text SFX

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/Grayed-Game#575]
[수빈님 요청사항](https://github.com/GG-Studio-990001/Grayed-Game/issues/538#issuecomment-2249585643) 에 맞춰서 럭키 텍스트음 작업할 예정

---

레퍼런스 영상 사운드가 살짝 왕왕거리는데
럭키 BGM 자체도 왕왕하는 사운드가 있어서
비슷하게 만들되 왕왕은 뺐습니다,,!!

[럭키 텍스트 음](https://drive.google.com/file/d/17X6EaPTN4cLhkPG_GwBXiimd53rt7cnf/view?usp=drive_link)

괜찮은지 모르겠네욥 ,,, 
피드백 바로 주시면 바로 파일 올리도록 하겠습니다!!

**Comment by roweclaw** [comment]
텍스트음 자체는 좋은데 BGM이랑 조화가 덜 되는 느낌이 드네요 ㅠㅠ
처음 요청드릴 때는 톤을 낮게 가져가야 한다고 생각했는데, 의외로 톤이 높아야 어울리는지? 
또는 텍스트음 질감이 지금은 _뽁뽁_ 거리는데, 더 부드럽게 바꿔야 하는 건지?
관련해서 기화님 의견이 궁금합니다!

**Comment by Songkihwa** [comment]
솔직히 말하면 화면 폰트 효과를 생각하면 지금 효과음이랑은 안 어울리긴 해요..ㅠ BGM도 럭키의 느낌을 잘 보여주긴 해서 애초에 텍스트 효과음 자체가 의미가 있을까 싶기도 합니다ㅠㅠ 일단 최대한 레퍼런스처럼 만들어보긴 했는데 BGM때문에 처음 수빈님 말씀대로 높은 피치는 안 어울리는 게 맞는 것 같구, 넣는다면 폰트 효과랑 어울리게 다시 연구해봐야할 것 같습니다ㅠㅠ 어렵네요,,,,

**Comment by roweclaw** [comment]
저도 럭키 이미지에 어울리는 느낌을 나타낼 수 있는 레퍼런스를 찾다보니 폰트 효과까지는 고려를 못한 것 같네요 ㅠㅠ
그럼 우선 텍스트음은 온라인 빌드에는 제외하는 걸로 하고, 오늘 기획 회의가 있어서 안건으로 논의해보겠습니다!
조만간 사운드 회의도 잡아서 같이 얘기하면 좋을 것 같아요!!
