### ISSUE TITLE
온라인 사운드 및 기획 비정기 회의, 2024-08-08 [20:30]

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#582]
안건
- 럭키, 챕터2 브금 등 사운드 회의
- 2챕터 서브 게임
- TCG UI 그래픽 확정
- 색깔 상호작용 연결 필요
- 잊혀진 게임에 대한 설명 보충

## 회의록
[기획 피그마](https://www.figma.com/design/LNsoGFh5f3jQ1rCPQB2O9f/Grayed-Game?node-id=0-1&t=eMwDHk2GAfuy6kS4-1) 또는 디코 회의록 채널에서 <<8/8 사운드, 기획 비정기 회의>> 확인해주세요

**진행 안건**

- 사운드 회의 : 럭키, 챕터2 브금
- 2챕터 접속게임
- TCG UI 그래픽 확정
- 1, 2챕터 대화창 텍스트 결정
- 1챕터 텍스트 애니메이션 사용건
- 3매치 탈출 관련
- 색깔 상호작용 연결 필요
- 잊혀진 게임에 대한 설명 보충
- 오프닝 일러스트 수정

**Comment by fkdl0048** [comment]
+ 1, 2챕터 대화창 텍스트 결정
+ 1챕터 텍스트 애니메이션 사용건

**Comment by roweclaw** [comment]
@fkdl0048 @Sumindd @Songkihwa 
회의 일정 2024-08-08 [20:30] 으로 변동됨
