### ISSUE TITLE
[CH1] SLG 2차 퀄리티업

### ISSUE THREAD

**Issue by jeongopo** [GG-Studio-990001/Grayed-Game#584]
### 개선사항
**UI 위치 수정**
- [x] 다리 짓는 말풍선 위치 수정
- [x] SLG 하단 창 설명 수정 (텍스트도 기획 수정 R2-Mon -> 파머로)

**연출 수정**
- [x] 플로야드 다리를 다시 건설했다 => 연출(페이드인아웃과 뚝딱뚝딱) 다 끝내고 출력
- [x] SLG 건물창 올라가고 내려갈때 애니메이션 바운스

**조작 개선**
- [x] 건설창 떠있을 때 뒤에 라플리 조작 불가능해야함 
- [x] 럭키 SLG 설명 시 뒤 마우스 입력 막기
- [x] SLG 인터렉션 시에만 마우스 클릭 사운드 표시
- [x] 마마고 출입구가 너무 가까움

**버그**
- [x] 마마고 컴퍼니 건설 이후 파머 대화 안됨
- [x] SLG 같은 재화 연속으로 획득하면 사이즈 커져있고 원래대로 안돌아옴
- [x] SLG 마마고 컴퍼니 지은 후에 게임 껐다 켜면 말풍선 보임
- [x] 재화가 부족해도 다리가 그냥 지어지는 문제

### 0815까지 수정
- [x] SLG UI 마마고 컴퍼니 건설하면 사라지는데, 이제는 챕터 2이동하면 사라지도록 변경
- [x] 마마고 건설 연출 안나오는 문제 (위의 구조와 함께 수정해야할것같습니다)

### 참고문서
[피드백 제보문서](https://docs.google.com/spreadsheets/d/1x_Rz09V7zD9MRT8yy9H-mmbQ7r809jbHCKjPCP-icXE/edit?gid=1430539115#gid=1430539115)

----
아따 많네요 열심히 수정하겠습니다..
빼먹은 버그 있으면 추가제보 부탁드립니다

**Comment by fkdl0048** [comment]
맞습니다! 아래 UI는 상관 없습니다! 건설 UI만 인게임 플레이어를 가려서 조작 불가능이 맞습니다

**Comment by jeongopo** [comment]
### 0731 작업내용
버그들은 코드 좀 봐야할것같아서 오늘은 우선 간단한 UI들 처리했습니다
(내용이 많아 관련자분들 언급도 같이합니다. 따로 언급 없으시면 문제없는걸로 알겠습니다 ㅎㅎ..)

**1. 건물설명 폰트 변경**
- 서라운드 폰트로 변경 (cc. @wooyn730 )
- 폰트 크기 키움 (16->18) (cc. @gomgom172 )
![image](https://github.com/user-attachments/assets/c0ba3295-ed4f-4228-b01f-735fdd8ebbe5)
----

**2. 플로야드 다리 텍스트 수정** (cc. @Sumindd , @roweclaw ) : **파머**가 심혈을 기울여서 만들었다
![image](https://github.com/user-attachments/assets/aada620d-b302-4f17-a0f1-417c71ef4611)

**3. 설명 줄넘김 조정** (cc. @roweclaw , @wooyn730 ) 
![image](https://github.com/user-attachments/assets/66668837-2a42-4e91-9672-8e0c38f492fb)
![image](https://github.com/user-attachments/assets/185b5d71-c2a6-4daa-b57c-c445df7fa8a5)
![image](https://github.com/user-attachments/assets/64e8b4a0-7846-419b-8655-b7f3020aa1ef)

----

**4. 건설 말풍선 위치 조정** (cc. @wooyn730 , @gomgom172 )
![image](https://github.com/user-attachments/assets/c0dd919b-9373-49e5-bf06-419552454651)

----

**5. 건설창 표시 시 바운스 효과** (cc. @fkdl0048 )

https://github.com/user-attachments/assets/5c42ab41-6d9b-46c4-9733-b85cd2199e91

----
**6. 다리 건설 텍스트, 연출 효과 이후 표시** (cc. @wooyn730 )

https://github.com/user-attachments/assets/990bab69-25b6-4984-a18a-ef87ed04b22d

따단~ 하고 나서 텍스트 나옵니다

----

**7. 인터렉션 시에만 마우스 클릭음 나오도록 수정** (cc.@wooyn730)

https://github.com/user-attachments/assets/07e21629-1a07-457c-bebe-ff4560666707


**8. 마마고컴퍼니 입장 시 인식 범위가 넓은 문제** (cc. @fkdl0048)
![image](https://github.com/user-attachments/assets/b4dae888-5eb6-48c7-9e41-2359d46201c2)

범위를 좀더 좁게 해봤습니다

**9. 럭키 SLG 설명 시 뒤에 UI 클릭되는 문제** (cc.@wooyn730)

https://github.com/user-attachments/assets/e996ff88-84e3-4f18-b87a-162d75516092

**럭키 관련 오브젝트들을 UI보다 상단으로 옮기고, Block UI 추가했습니다.** (cc. @wooyn730, @fkdl0048)
처음부터 테스트할때 문제 없었는데, 혹시 문제 있으면 알려주세요

**10. 다리 건설 시 재화 체크 안하는 문제** : 체크도 안하고 그냥 짓고있었습니다.. 막았습니다

**11. 건설 말풍선 보이는 문제** : 컨트롤 코드 추가
![image](https://github.com/user-attachments/assets/19206f7e-e095-4cd2-9b52-cdb3ac8242dd)

**Comment by fkdl0048** [comment]
작업 내역 확인했고 저 태그 해주신 부분에서는 문제 없는 것 같습니다.

**Comment by gomgom172** [comment]
2, 4 확인했습니다.

하단 설명은 서라운드로 변경해 주신 게 더 통일성 있어 보이는 것 같네요!
상단 바 UI 폰트도 서라운드로 변경해야 할 것 같습니다!

**Comment by jeongopo** [comment]
상단 바가 코인 목재 석재 개수 나오는곳 얘기하시는건가요??

**Comment by gomgom172** [comment]
네 맞습니다!
https://github.com/GG-Studio-990001/Grayed-Game/issues/521#issuecomment-2255880935
우연님 코멘트 (5) 폰트 수정 요청이 상단 바였던 것 같은데 우연님께서 한 번 확인해주시면 좋을 것 같습니다!

**Comment by wooyn730** [comment]
네 이우님이 맞아요 재화 개수 표시하는 상단 UI 폰트 통일 말한거였습니다~~
<br>

참조 거신 부분 확인 했습니다 👍
<br>

> 건설창 표시 시 바운스 효과

저는 개인적으로 수정 전 버전이 좋았네요
지금은 창이 많이 가벼운 느낌?

<br>

>  마마고 컴퍼니 건설 이후 파머 대화 안됨

요거는 제가 체크하겠습니다
 <br>

현정님 파워 작업 하셨네요 수고하셨습니다 ><

**Comment by jeongopo** [comment]
아하 재화상단UI도 수정할게요

바운스 이펙트는 정안님과 원만한 합의를.. 
우선 결론나기전까진 바운스로 두겠습니다

감사합니다~

**Comment by jeongopo** [comment]
### 0804 작업내용

**1. 자원 획득 여러번 클릭 시 크기 커지는 문제 수정**

https://github.com/user-attachments/assets/affe564b-2c1f-4f50-ace8-ef97c1827f2a

**2. 위의 재화 표시 폰트 써라운드로 변경**
![image](https://github.com/user-attachments/assets/ee7ee85d-035e-4210-9858-3363ba554867)

**3. 챕터2 넘어가기 전까지 SLG 모드 지속되게 하기**
- 마마고를 건설한 후에도 다리를 건설할 수 있음
- 마마고를 건설한 후에도 재화가 계속 스폰됨
- 챕터 2를 넘어가면서 마우스 커서는 정상적으로 복구함


**4. 마마고컴퍼니 입구 앞에 있는 상태에서 건설하면 마마고 컴퍼니 안으로 들어와지는 문제**

https://github.com/user-attachments/assets/b56802bd-9676-4901-851f-bb868167622a

구조가 좀 꼬여서 그냥 가장 단순하게 함수 분리했습니다,, 
그나저나 아저씨가 지나가면서 저 밀쳐내네요 ㅜㅋㅋㅋㅋㅋ

**5. 건설창 떠있을 때 조작 안되게 막는 처리**

https://github.com/user-attachments/assets/59404c22-1c59-4309-a674-32bdd969f90c

마마고 컴퍼니 건설 이후 파머 대화 안되는 문제는 우연님이 해결해주신것으로 보입니다


다른 이슈 없으면 내일 회의 이후 이슈 닫겠습니다~

**Comment by jeongopo** [comment]
![image](https://github.com/user-attachments/assets/1b4408b0-3e5e-4296-9d56-091c5329fd0d)
엑셀 내용도 해결 처리했습니다 (_ _ )

**Comment by wooyn730** [comment]
> 그나저나 아저씨가 지나가면서 저 밀쳐내네요 ㅜㅋㅋㅋㅋㅋ

갑자기 생각났는데 굳이 따지자면 아줌마..? 일걸요
파란색 앵무새 파파고 <-> 핑크색 앵무새 `마마`고... (사실 핑크임..)

![image](https://github.com/user-attachments/assets/e89240f5-24e3-428d-a7b1-dde4ff9f7e33)

**Comment by jeongopo** [comment]
헐 충격
