### ISSUE TITLE
[CH2] UI작업

### ISSUE THREAD

**Issue by royalbluesm** [GG-Studio-990001/Grayed-Game#586]
**상세**
CH2 로그, 선택지, 알림, 하단바 UI를 작업합니다.

**미리보기**

![Log](https://github.com/user-attachments/assets/841d0237-1bc1-4246-b49d-f450c7ac6161)

로그: 프리텐다드 30pt에 줄간격 160%, 유니티에서 지정이 가능한지 모르겠지만 칼같이 크기나 간격을 지킬 필요는 없습니다. 적용하실 때 상하좌우 여백이 너무 좁지 않으면 좋을 것 같습니다.

![Alarm](https://github.com/user-attachments/assets/b6668b60-b972-4f2f-b184-25d2e626de26)

알림/하단바: 이미지에 쓰인 대로 가운데 정렬에 배경색이 반투명이 아닌 불투명이었으면 좋겠습니다. 확인/취소는 선택 시 배경이 하얗고 글씨가 검어지는 식으로 보이면 좋겠습니다. 하단바는 마찬가지로 가운데 정렬, 버튼 간 간격만 맞춰주시면 좋을 것 같습니다.

![Select](https://github.com/user-attachments/assets/9ca11665-e48f-4857-98fb-8865ec0876ef)

선택지: 이미지에 쓰인 대로 선택 시 배경이 하얗고 글씨가 검어지는 식으로 활성화시키면 좋을 것 같습니다. 선택지가 줄어들면 선택지 창의 크기도 줄어드는 식으로 적용할 수 있을까요?

**파일**
현재 적용가능한 파일들 [폴더](https://drive.google.com/drive/folders/1dRfpHVSv_KVHIXGtPB9jmGeF0FpOoel6?usp=sharing)에 넣어뒀습니다. 누락되었거나 상태가 이상한 파일 있으면 말씀해주세요.

**Comment by Sumindd** [comment]
- #569 의 [아트 리소스 관리 문서](https://docs.google.com/spreadsheets/d/1Dm7b5r5Cmk4YC4DTW4ureRnq3Xmny8bs/edit?usp=sharing&ouid=102142728386857128653&rtpof=true&sd=true) 25번부터 30번 작업을 확인하셔야 하는데 제가 좀 늦게 올려서 누락된 것 같네요ㅠㅠ 
- 기존 기획서에는 "CH2 고유의 UI이므로 위 버튼 3가지와 동일한 그래픽 스타일이다. 대화창 디자인(페르소나st)과는 별개임을 주의! 풍이 완전 다를 필요까진 없지만 보자마자 동일한 스타일의 알림창이라는 느낌이 들진 않도록"이라고 적혀있는데 UI 스타일은 기존 대화창 스타일과 달라지면 확실히 이질감이 많이 들 것 같아 설정상으로 이번에 민지님이 작업해주신 작업물이 말이 되게 변경하는 방안으로 생각  중입니다(이쪽이 훨씬 자연스러울 것 같아 정안님과 이야기 나눴고, 자세한 사항은 다음 기획 회의에서 이야기 할 예정) 
- 다만, 로그 시스템 자체를 없앴습니다.. 그리고 **UI숨김, 스킵, 자동진행** 버튼은 기존 기획에 따르면 오른쪽 상단 아이콘 형태로 대화창과 분리 되어야 할 것 같은데 이것도 위의 기획 설정에 따라 지금 형태로 변동 되어도 문제 없을 것 같아 일단은 그대로 두고, **로그 시스템과 관련된 UI만 삭제** 부탁드립니다!
- 디자인 자체는 너무 깔끔하고 통일감 있고 이쁩니다!! 저도 장소 선택 UI의 길이는 선택지 개수에 따라 유동적으로 바뀌면 좋을 것 같네요!

**Comment by wooyn730** [comment]
UI 너무 깔끔하게 잘 나왔습니다!!!!!!
매우x10000 만족이에요 이쁘네요 고생하셨습니다 ^_^

<br>

> 프리텐다드 30pt에 줄간격 160%, 유니티에서 지정이 가능한지 모르겠지만 칼같이 크기나 간격을 지킬 필요는 없습니다.

유니티 내에서 지정이 가능합니다. 근데 똑같이 지정을 해도 다른 요인 때문에 거의 똑같진 않아요! (폰트가 들어간 오브젝트의 사이즈라던가.. 카메라 설정이라던가..)
하지만 요청해주시면 최대한 비슷하게 하려고 하겠습니다 (로그는 삭제되긴 했지만...)

<br>

> 확인/취소는 선택 시 배경이 하얗고 글씨가 검어지는 식으로 보이면 좋겠습니다.

> 이미지에 쓰인 대로 선택 시 배경이 하얗고 글씨가 검어지는 식으로 활성화시키면 좋을 것 같습니다. 선택지가 줄어들면 선택지 창의 크기도 줄어드는 식으로 적용할 수 있을까요?

모두 가능합니다!

<br>

> (수민) UI숨김, 스킵, 자동진행 버튼은 기존 기획에 따르면 오른쪽 상단 아이콘 형태로 대화창과 분리 되어야 할 것 같은데

이건 저도 지금 알긴 했는데 사실 지금 키입력(하단바) UI 임시로 넣어뒀는데 대화창이 많이 좁아지는 느낌이 들긴 해요..
민지님이 UI 잘 만들어주셨지만 대사 많아질 거 생각하면 상단으로 빼는 게 나을 것 같습니다.

**Comment by wooyn730** [comment]
@royalbluesm 
장소 선택지 UI `Select_background.png`가 반투명한데 확인 부탁드려요

**Comment by royalbluesm** [comment]
@wooyn730 원래 반투명한 친구라 그렇게 드리긴 했는데 반투명 파일들 전부 불투명으로 드리는게 좋을까요? 만약 전부 불투명으로 통일해서 드리면 흰색으로 된 제목이랑 백그라운드 파일을 따로 나눠서 드려야 해서 편하게 합쳐서 드리느라 그렇게 됐습니다

**Comment by royalbluesm** [comment]
@Sumindd 아이고 저도 차마 확인을 못했었네요...그럼 일단 로그 시스템은 안씀 폴더에 넣어두겠습니다 (혹시 모르니 ^^;) 기획 회의에서 UI 확정되면 말씀해주세요 !

**Comment by wooyn730** [comment]
이슈에 있는 배치된 이미지가 불투명해서 잘못 주신 줄 알았습니다 (알람도 불투명해서..)

의도하신 거 맞으면 괜찮습니다^^!!

**Comment by royalbluesm** [comment]
아아 알람은 불투명한 거 맞고 프리뷰 이미지는 찍을때 실수한것 같네요 ㅎㅎ 머쓱... 드린 파일 그대로 사용해주시면 됩니다!
