### ISSUE TITLE
[CH1] 기계어번역팩 아이템 리소스

### ISSUE THREAD

**Issue by gomgom172** [GG-Studio-990001/Grayed-Game#589]
기계어번역팩 함께 제작합니다.
지난번에 전달드린다고 했는데 빠뜨렸네요... 죄송합니다!

**Comment by roweclaw** [comment]
이우님 기계어번역팩 리소스 없어도 됩니다!!
저번 기획회의 내용 보시면 번역팩 말고 번역탭 기믹으로 변경됐어요!! 지금 당장의 우선순위가 아니라서 간단하게 설명하다보니 팩 리소스 필요가 없어진 부분을 확실히 전달 못드렸네요 죄송합니다... 추후에 번역탭 UI 우선순위가 되면 기획서랑 다시 말씀드릴게요!! ㅠㅠ

**Comment by gomgom172** [comment]
헉 확인했습니다. 저번 회의 때 정신이 좀 없었어서 제가 제대로 캐치를 못했나봐요. 죄송합니다! 말씀해주셔서 감사해요!

이슈는 우선 닫아두고 나중에 번역탭 UI 제작 때 오픈하겠습니다 (_ _)
