### ISSUE TITLE
[CH1] 시스템 기획 수정 내용 정리

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/Grayed-Game#591]
- #564 에서 변경된 CH1 기획 수정 내용을 ppt로 정리해 업로드한다.

- 재화 사용처 변경 사항 
- SLG 탈피가 챕터 2로 이동할 때 이루어져야 하는 이유
- 설정창 -> 번역팩 적용
- 3매치 스테이지1 젤리 줄이기, 스테이지3 물고기 통로로 수정

더 있을 수도 있음.. 작업 할 때 다시 회의록 보고 점검

### 240809 업데이트

[[240809] CH1 기획 변경](https://drive.google.com/file/d/1oJQnH7DIvsAdgWVZdT4ltYsNOaMdmT87/view?usp=sharing)
마지막 페이지는 다음 업데이트에 마저 정리하겠습니다.... 무시해주세요

**3매치 1스테이지 젤리 줄이기**
유저들이 플레이 할 때 전부 터뜨리는 룰로 오해를 해서 줄이기로 했는데 막상 줄이다보니 오히려 더 오해하기 쉬울 것 같고 목적 달성은 되지 않을 것 같습니다.
차라리 도달해야 하는 통로에 반짝이나 빛으로 강조를 한다던지, 럭키가 클리어 조건을 강조해서 설명해주는 식으로 보완하는 것이 낫지 않을까 의견 내봅니다.
(일단 줄인 맵도 제작 완료 했기 때문에 의견 들어보고 원하신다면 바로 업로드 하겠습니다!)

### 240812 업데이트

[CH2 메인 시스템 세부 기획](https://drive.google.com/file/d/1r_x9BIv2H_m6SIoQkTItqaR1QOdUKd8A/view?usp=sharing) 

세로줄이 선행 상황, 가로줄이 후행 상황입니다. 혹시 이해 안 되면 말씀해주세요!

**Comment by Sumindd** [comment]
BIC 관련 내용은 아니어서 일단 이번주에 ppt로 정리해서 올려두겠습니다

**Comment by Sumindd** [comment]
240809 업데이트 완료

**Comment by wooyn730** [comment]
3매치 3스테이지 변경된 부분 좋습니다.
하지만 2초 기다리기는 좀 애매하다고 생각하는게 기말발표 전시 해보니 트리거 안 밟고 돌아다니면서 고민하실 분들도 많을 것 같아서 없어도 되지 않을까 싶긴 해요!

<br>

> 럭키가 클리어 조건을 강조해서 설명해주는 식

저도 이거 좋습니다. 빨리 나가라는 느낌으로 말해주면 좋을 것 같아요.

<br>

줄인 맵도 한번 보고싶긴 하네요?
근데 스테이지1이 맵도 작은데 젤리도 더 없으면 다 터뜨려야될 것 같은 느낌이 들 것 같긴해서 이해됨요

<br>

번역팩 그럼 이우님이 그려주시나여?

<br>

번역팩 강매 좋은데 _(무시해달라고 하셨지만 ㅎㅎ..)_
저는 혹시 코인 모자라면 팩맘 다시 해야해서 피로도가 높을 것 같으니
플레이어가 소지하고 있는 코인 개수에 맞게 요청하면 좋을 것 같아요
(10개 있으면 20개 달라고 했다가 10개로 깎아준다거나.. 0개면 눈 딱 감고 원래 ~코인인데 깎아준다고 한다거나)

**Comment by Sumindd** [comment]
CH2 메인 시스템 세부 기획(자동 진행, 스킵, UI숨김) 일단 이미지로 업로드 했습니다.
복제한 줄 알고 원본 파일에다가 CH1 보완 기획서 써서 CH2 시스템 기획서 원본을 날려먹었습니다......... 추후에 방안 고민 좀 해보고 한 번에 파일 정리해서 새로 이슈 파고 올리겠습니다..

**Comment by wooyn730** [comment]
> CH2 메인 시스템 세부 기획(자동 진행, 스킵, UI숨김) 일단 이미지로 업로드 했습니다.

확인했습니다
근데 작업할 때 또 연락 드릴 것 같네요..

<br>

> CH2 시스템 기획서 원본을 날려먹었습니다.........

마음이 너무 아프네요.......................................

<br>

> 럭키 트리거를 이렇게 위쪽으로 올리고 2초

필요성 제쳐두고서도 라플리랑 럭키가 같은 좌표계?를 공유하고 있지 않아서
![image](https://github.com/user-attachments/assets/f882f081-7172-4c6b-a832-3840a5afe7f8)
라플리가 움직이면 럭키 좌표를 따로 새로 조정해줘야할 것 같은데
안되....는 건 없지만 시간이 좀 걸릴 것 같네요 ^_^...

의견은 이해했고, 일단 물고기 위치 바꾼 후에 다시 이야기해보면 좋을 것 같습니다.

<br>

럭키팩과 번역팩, 번역탭은 빨리 기획 나오면 8월 끝나기 전에 아트분들께 요청드리면 좋겠네요
(이우님이 팩 작업 해오셨고, UI는 민지님이 다 작업하신거니까..)

**Comment by Sumindd** [comment]
[CH1 보완 기획 추가 예정]
SLG 숨김
화살표 기획
번역탭 기획
