### ISSUE TITLE
CI Warning 제거

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#593]
### 1. actions/upload-artifact@v3 버전 수정
![image](https://github.com/user-attachments/assets/d00c0d33-cb8b-47f4-9ac3-00bf941c2887)
`CI_Action.yml` 수정함 v3 => v4
874336f5d80f0f4138ae32fe92d01747899d230c

<br>

### 2. 사운드 리소스명 문제
![image](https://github.com/user-attachments/assets/444793a1-b736-4ecb-a9c4-e80d1d4c390d)
대괄호 사용 안됨
[해결](https://github.com/GG-Studio-990001/Grayed-Game/issues/581#issuecomment-2263198250)

<br>

### 3. NewGlitch Missing Scripts
![image](https://github.com/user-attachments/assets/db084dbe-5139-4ebb-85f5-fadd25ab7492)
![스크린샷 2024-08-02 174204](https://github.com/user-attachments/assets/c41dbd0c-6770-4ebb-ba27-e09560c70885)
음.. 뭘 넣어줘야 될지 몰라서 일단 NewGlitch1 2개에 각각 `Glitch1`과 NewGlitch20에 `Glitch2` 넣어줌
현재 사용중인지는 모르겠음 넣으니까 에러가 사라지긴 함
[해결](https://github.com/GG-Studio-990001/Grayed-Game/pull/592#issue-2444423856)
<br>

### 4. Node.js 16 => Node.js 20으로 전환 (?)
![image](https://github.com/user-attachments/assets/859a955a-a8fa-4e52-b9ab-79eccd4a498f)
Node.js 20 버전을 명시적으로 설정함
76754d2a902ef418bacdfef4632d35bb80eb93ec

![image](https://github.com/user-attachments/assets/1f4c3c38-31c6-4c58-ba09-91996120f1df)
**그래도 경고 계속 뜨는데 냅둬도 된다고 함..**

<br>

### 5. 쉐이더 파일의 벡터 타입의 암묵적 잘림
![image](https://github.com/user-attachments/assets/867a4113-f8fe-40e7-8920-e3336389c195)

`resScale`은 `float` 타입이므로
`resScale*=_ScreenParams.zw;` => `resScale *= _ScreenParams.z * _ScreenParams.w;`
[해결](https://github.com/GG-Studio-990001/Grayed-Game/commit/b5f0667c64d09e20b56fb6ec5591a2cb0a693d2b)

<br>

### 6. 명령어 해석
![image](https://github.com/user-attachments/assets/7bffea3c-3a8c-4383-a41e-1d40d46fbb74)

[관련 링크](https://github.com/game-ci/unity-builder/issues/163)
헐 `ver0.0.13` 이렇게 써서 문제난거였고 `v0.0.14`이건 괜찮음........

**Comment by fkdl0048** [comment]
지속적으로 주마다 빌드를 뽑아야 해서 CI쪽 정리 한번 해야했었는데 나이스입니다.

**Comment by wooyn730** [comment]
![image](https://github.com/user-attachments/assets/97dce2ed-d09b-4687-9afe-666a72d3a9a7)
**깃허브 액션에서 빌드 다운받을 때 예쁜 이름(?)으로 보이도록 `CI_Action.yml` 수정**
[PR](https://github.com/GG-Studio-990001/Grayed-Game/pull/597)

<br>

### 전
![화면 캡처 2024-08-02 190336](https://github.com/user-attachments/assets/73f102d8-0238-4d5e-a069-22c196198505)

### 후
![화면 캡처 2024-08-02 190352](https://github.com/user-attachments/assets/e323e69d-f1ff-46b6-82dc-a5b846892443)

**Comment by wooyn730** [comment]
4번 제외 제거 완료!
