### ISSUE TITLE
[CH1] 맵 퀄리티업 작업

### ISSUE THREAD

**Issue by gomgom172** [GG-Studio-990001/Grayed-Game#603]
SLG UI에 들어갈 화살표 아이콘, 백그라운드 맵 디테일 업 작업합니다.
그 외 필요하신 리소스 있으시면 개인 연락 부탁드립니다! 우선 작업하겠습니다.

![guide6_1](https://github.com/user-attachments/assets/d89ecc86-64ca-4b28-8725-1062c25c5118)

[화살 아이콘 파일 링크](https://drive.google.com/file/d/1INSziha2_LCm3JLEhtuRcHQ8XcwrZrPU/view?usp=sharing)

<img width="1070" alt="스크린샷 2024-08-12 오후 8 58 20" src="https://github.com/user-attachments/assets/7972656e-ca18-4f0e-ac83-71d617781dbb">
플레이어가 직접 상호작용할 수 없는 곳에 최대한 실루엣을 죽인 오브젝트+게임 기기(조이스틱 등…) 쌓는 방식으로 진행하려고 합니다. BIC 기간 틈틈이 작업해 넘겨드리려고 합니다.

# 240826
![FloyardBackground-cut](https://github.com/user-attachments/assets/f098bf45-a29e-4a8c-bd09-d705879fafc5)

맵 작업 진행중입니다.
가능한 이번 주차(~9/2)에 전부 마무리하고(+필요하면 코멘트 받은 후 다음주 수정) 3매치 타일맵 약 폴리싱(가시 튀어나온 부분 정리)까지 진행할 예정입니다!

# 240909

![FloyardBackground0909](https://github.com/user-attachments/assets/da190cde-879a-40c3-a0e4-33100a8166a7)

앞쪽 부분(~동굴 앞까지)은 마무리되었습니다!
SLG 부분이 아직 작업이 덜 되어 오브젝트 조금 더 채운 후 끝내게 될 것 같습니다.
타일맵 파일 이번 주차 내로 업로드 예정입니다.
코멘트 있으시면 말씀 부탁드립니다!

# 240914

[백그라운드 맵](https://drive.google.com/file/d/18KQQAJYrYacgW4OJNT3CwQrXNMCymwJ-/view?usp=share_link)
[3매치 타일맵](https://drive.google.com/file/d/12Kem7uOFVaWsKgInNrLrxZZIZ5siFk-8/view?usp=share_link)
가시 튀어나온 부분 포함하여 폴리싱했습니다.
텍스쳐가 들어간 바닥(7번째 칸)도 같이 넣어뒀는데 필요에 따라 사용해주시면 될 것 같아요!
적용하시고 문제 있으면 말씀 부탁드립니다!

**Comment by gomgom172** [comment]
화살 아이콘 파일 먼저 업데이트해두었습니다! 좌우는 flip해서 사용해주시면 감사하겠습니다.

**Comment by wooyn730** [comment]
화살 기존 UI들이랑 잘 어울리게 이쁘게 나왔네요 굿 ^_^b

**Comment by Sumindd** [comment]
SLG랑 어울리게 잘 뽑혔네요 귀여워요!!
달러 동상은 마을쪽으로, R2-Mon 기지는 수상하게 동굴 방향으로 돌리면 될 것 같습니다!(아마 맥거핀으로 남길 것 같아요)

**Comment by wooyn730** [comment]
좋은데요?? 점점 퀄리티가 올라가고 있네요~
빨리 적용해보고 싶습니다 ><

**Comment by fkdl0048** [comment]
확실히 맵 퀄리티가 높아진 것 같습니다!

**Comment by roweclaw** [comment]
뒷배경에 리소스들이 채워지니까 확실히 느낌이 점점 살아나고 있네요! 너무 잘 작업중이십니다 화이팅입니다~! 👍

**Comment by Songkihwa** [comment]
오모 뒷 배경 너무 마음에 드네요!! 고생하셨습니다 ><!!!

**Comment by wooyn730** [comment]
수고하셨습니다!!
맵은 내일 바로 적용해볼게요~~

**Comment by fkdl0048** [comment]
@gomgom172 이우님 고생하셨습니다..! 3M쪽도 타일 수정하겠습니다~

**Comment by roweclaw** [comment]
맵이 진짜 퀄리티가 발전되는게 눈에 보입니다 정말로 고생 많으셨어요~!!
