### ISSUE TITLE
[CH2] 비주얼노벨 기본 기능 구현

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#614]
[[CH1][CH2] 빌드 공장 가동 4주차](https://github.com/GG-Studio-990001/Grayed-Game/issues/606)에서 CH2 비주얼노벨 관련 내용 분리

## 작업

- ~CH2 스크립트 적용~
- ~CH2 맵 이동~
- ~페이드아웃/인 추가~
- ~미카엘 스탠딩 추가~
- ~NPC 표정 변화~
- ~맵 배경 변화~
- ~CH2 스킵~
- CH2 UI 숨기기
- CH2 자동진행
- CH2 세이브

---
### 버튼 안눌림
텍스트 오브젝트의 Raycast Target 설정이 켜져 있다면 텍스트가 버튼 위의 클릭을 차단할 수 있음

### 취소 버튼 누르고 패널 다시 켜면 취소버튼 하이라이트 제대로 안돌아옴
Navigation을 None으로 하면 됨 와!
[참고](https://issuetracker.unity3d.com/issues/ugui-button-does-not-get-highlighted-if-it-has-been-pressed-at-least-once)

### UI 숨기기 문제
1) 대사 타이핑효과 도중에 대사창 숨기면 다시 활성화됐을 때 마저 타이핑이 안됨
2) 대사창 숨기고 다시 활성화하면 스페이스바가 안먹음..
=> 조금 더 고민해볼 것 (Yarn Spinner 공부 필요)

### 자동 진행
UI 숨기기랑 자동 진행 모두 현재 대화 시스템으로 Yarn Spinner를 사용중이라 자료가 별로 없어서 어려움을 겪는 중... ㅠ
자동 진행 기능이 인스펙터에 있는데 왜 코드로는 못가져옴..? 어렵다..

자동 진행은 명확한 기획도 필요할 듯
Auto 중일 때 표시도 해줘야되고, Auto동안 Auto해제 말고 다른 건 못하는 건 맞는지도 궁금하고 (직접 넘기거나, 스킵, UI 숨기기 등 불가?), 몇초 기다렸다가 넘길지도...
기획이 아직 구체적이지 않아서 더 어렵 ㅠ

**Comment by Sumindd** [comment]
자동 진행 기획 확인했습니다! 내일 바로 작성해서 올리겠습니다

**Comment by wooyn730** [comment]
새 이슈로 다룰 예정
