### ISSUE TITLE
[CH1] 시스템 기획 수정2 

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/Grayed-Game#626]
- #591 에 이어서 진행합니다.

[CH1 보완 기획 추가 예정]
SLG 숨김
화살표 기획
번역탭 기획
3매치 1스테이지 마지막 젤리는 터져서 길이 뚫리도록 수정

수요일에 기획 회의 진행 후 추가 될 것 같습니다

### 240823 업데이트
[[240823] CH1 기획 변경 사항](https://drive.google.com/file/d/1WnTZKQ4dD6Ba80iSaIr9gUiztlPkpc6q/view?usp=sharing) 작성했습니다.

To. 새로 오신 아트 팀원들에게...
제 기획서 속 이미지는 모두 이해를 돕기 위한 예시용 임시 이미지입니다.
UI 위치 배치 및 모양은 의도에 맞는 선이라면 자유롭게 갈아엎어주세요!!! 

**완료**
팩의 형태
번역탭과 번역팩
 SLG 화살표
색 있는 오브젝트 일러스트 컷씬
3매치 퍼즐 
팩맘 

**미완료**
SLG 오브젝트 배치, 튜토리얼 및 플로우 수정, 맵 수정... SLG 관련 수정 많음

아마 다음주에 마저 작업 가능할 것 같습니다..
일단 **마마고 컴퍼니 건설 시간 단축 비용은 코인 100개로 줄여주세요!**

**Comment by fkdl0048** [comment]
@fkdl0048

**Comment by Sumindd** [comment]
업데이트 완료

**Comment by Sumindd** [comment]
그냥 건설이 불가능하다는 뜻으로 잠가둔 거라 클릭이나 설명 뜨는 건 열어놓는다고 생각했는데 실제로 해봤을 때 어색할 것 같으면 그냥 클릭을 막아둬도 괜찮을 것 같습니다!

**Comment by jeongopo** [comment]
넵 이미 건설끝났거나 잠겨있는건물은 클릭해도 안뜨게 하겠습니당 ㅎㅎ

**Comment by fkdl0048** [comment]
## 피드백

![image](https://github.com/user-attachments/assets/6e9bc49d-2468-4e82-8d1f-6abd51999ef0)

저도 설명대로 럭키가 빼곰하고 있는 모습이 제일 잘 어울리는 것 같습니다.

#### 번역탭과 번역팩

기존 설정창의 경우 언어(한국어, 영어)의 변경이 메인에서만 가능하도록 하자고 제한하려 했는데, 이 부분이 오히려 혼선일 수 있겠다는 생각도 드는 것 같습니다.

지금과 같이 번역팩의 형태로 번역팩이 획득 시 쌓이는 부분은 필수인데, 번역<->언어 오용되거나 설정창과 결합된 느낌이 조금 부족할 수 있겠다는 느낌이 들어서 탭을 [언어]로 변경하고 언어자체도 변경하는 설정도 두고, 그 아래 번역을 따로 두는 건 어떨까요?

#### 번역탭과 번역팩

번역팩의 색이 있어야 하냐의 논의에서 출발한 아이디어가 되게 매력적으로 변경된 것 같아서 너무 좋습니다..! 개발 비용이 증가하긴 했지만 다른 분들도 매력적으로 느끼셨으면 좋겠네요 게임의 색을 잘 보여주는 시스템이라 너무 좋습니다! 잠깐 이야기한 내용 구체화해주셔서 감사합니다~!

#### SLG 화살표

내용도 깔끔합니다! 표시중에 이동해도 위치가 변하지 않는다는 느낌이 잘 이해가 안되는데 라플리가 움직이면 화살표의 회전값은 계속 변경되어야 하는게 아닌가요?

#### 색이 있는 오브젝트 설명 컷씬

제가 생각한 컷씬의 느낌을 부족한 그림판으로..

![image](https://github.com/user-attachments/assets/52f66589-d342-48e2-9b31-ff343520b8d6)

이런 느낌의 그림을 상상했습니다! 추가적으로 `색이 있는 게임 오브젝트`는 뒤에서 복선으로 활용하면 좋을 것 같다는 생각이 들어서 `스페이스인베이더` 오브젝트로 두고 나중에 3챕에 가서는 해당 주민을 게임속 세상에서 만나도 웃기고 재밌을 것 같아요! 해당 세계관에 안어울리지만 (이질적인 존재이지만) 적응을 해버린 게임이 뒤섞인 느낌을 주면 재밌을 것 같습니다! 보스몹으로?

#### 3M 변경

변경안이 훨씬 더 좋습니다! 변경된 버전으로 데모를 진행해보고 문제를 파악할 수 있으면 좋겠네요

#### 팩맘

룰이 간단하고 명확해진 것 같습니다! 이후에 플레이 해보면서 속도나 코인 수를 밸런스 조절해봐야 할 것 같네요!

**Comment by wooyn730** [comment]
팩맘 기획에 대해 코멘트 남깁니다.

어떤 의견을 주장하기보다는 그냥 이런저런 생각을 계속 해봤는데
일단 회의 시간 전에 남겨두려고 작성합니다.

시스템 기획서에 변경된 부분 외에는 모두 그대로라고 이해한 상태로 적습니다.

### 접속게임에서의 라플리의 존재
접속게임에 대한 명확한 규칙을 세운 것은 아니지만
저는 팩맘을 개발하면서 라플리는 '먼지3' 같은 존재라고 생각했습니다.
먼지와 다르게 코인을 얻을 수는 있지만 팩맘과의 먹이사슬은 먼지랑 동일하기 때문입니다. (먼지3 + 플레이어만의 능력)
근데 만약 라플리는 팩맘을 잡을 수 없는, 팩맘의 기존 NPC들과 다른 존재라면 라플리는 접속게임에서 어떤 존재가 될까요?
슈퍼마리오가 챕터2 접속게임이 된다면 저는 어렴풋이 라플리가 마리오를 대체하는 역할이라고 생각했는데,
팩맘에서 제3의 역할로 나오면 다른 접속게임에서도 그렇게 나와야하지 않을까?(어떻게 접속게임 간 통일감을 줄 것인가)라는 생각도 들었습니다.

또한 아직 대사가 새로 안나와서 모르겠지만
팩맘과 먼지의 먹이사슬은 그대로고 라플리만 항상 잡히는 존재라면
이것도 이거대로 기존에 라플리가 팩맘을 잡아야하는 걸 알았던 플레이어들에게 어려움을 주지 않을까 싶기도 했습니다.

++
![먼지라플리](https://github.com/user-attachments/assets/ff13cd60-b216-4522-b72a-84441d528601)
라플리가 팩맘을 잡아야한다 / 먼지와의 통일성을 주기 위해
라플리를 더 먼지화하면 어떨까 라는 생각도 해봤습니다.. ^_^ ㅋ

### 접속게임 자체로서의 존재
이것 또한 명확한 규칙이 있는 것은 아니지만
저는 접속게임은 '색이 있는, 아직은 거의 잊혀지지 않은 온전한 게임'이라고 생각했습니다.
그래서 라플리가 없더라도 게임의 룰 자체가 있어야한다고 생각했는데
팩맘의 목숨 개수 UI를 삭제하면 온전하지 않은 게임이 되지 않나 싶었습니다.
기존 팩맘이 원래 있던 게임이라면 플레이어가 팩맘을 조작하고,
먼지를 잡거나 피하며 3번까지 죽지 않고 코인을 최대한 많이 모으는 게 목표였겠죠.
그래서 목숨이 사라지면 좀 애매하지 않을까...
_근데 또 그렇게 생각하면 라플리가 슈퍼마리오에서 '마리오'를 대체하면 안될 것 같고..
(마리오가 없으면 완전한 게임이 아니니까)
근데 뭐 또 라플리가 NPC 중 하나에 빙의 했다던가 라플리가 있어야할 자리에 있던 NPC는 튕겨져서 마을 NPC로 존재한다거나.. 이런 유저는 몰라도 되는 설정 같은게 있으면 될 것 같기도 하고..._

### 결론
룰을 간소화하는 것은 좋습니다.
청소기 삭제 같은 난이도 조절도 좋고요.
근데 단순히 몇개 규칙을 삭제한 것으로는 저는 접속게임의 정의를 더 의문스럽게 하거나 유저에게 더 어려움(먼지와 라플리와의 불일치)을 줄 수도 있다는 생각이 들었습니다.

**Comment by wooyn730** [comment]
저 위의 코멘트는 라플리는 팩맘 못잡고 먼지는 팩맘 잡을 수 있다고 이해하고 쓴거였습니다 ㅎㅎㅎㅎ?
이제 잘 이해했고 작업 열심히 하겠습니다 ^_^
