### ISSUE TITLE
[Pacmom] 버그 픽스

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#629]
### 팩맘 버그
- [x] 팩맘 시작 시 라플리 위치 초기화
   - 위치 바뀌는 원인은 안찾아봄
   - 타임라인 시작할 때 초기 위치 설정해줌
- [x] 팩맘 청소기 버그
- [x] 팩맘 안움직이는 버그

### 팩맘 청소기 버그 (해결)
간헐적으로 팩맘이 청소모드여도 주변 코인을 안빨아들임
심지어 가끔은 이상한 곳에서 빨아들이거나 벽을 넘어 빨아들인다거나 하기도 함

원인을 찾았는데 그건 "팩맘이 청소모드일 때 통로를 통과했을 때"임
한 번 청소모드에서 통과하면 그 이후로는 이상해짐
청소기는 팩맘의 자식 오브젝트로 Collider만 가지고 있는데 통로를 통과하면
청소기의 Collider 위치가 팩맘과 어긋나는 것 같음..

**=> 통로를 이동할 때 Collider을 가진 친구들을 이동시키는데,
청소기는 팩맘의 자식이므로 청소기 태그만 무시함으로써 해결**

### 팩맘 안움직이는 버그 (해결??)
이거는 지금까지 4번 정도 리포트되고 나는 딱 한 번 목격해봄
오늘도 팩맘 몇십번은 넘게 플레이했는데 발견하지 못함

**=> 발견이 정말 잘 안되어서 어려운데,
`팩맘이 청소기를 들고있을 때 코너에서` 막혀있던 걸 발견한 기억이 있음.
안전장치 코드를 한 줄 추가했는데.. 확실히 고쳐졌을지는 모르겠음
또 같은 버그가 있다면 위치와 상태를 리포트 받고 싶음.**

**Comment by wooyn730** [comment]
@JIJI037 
이슈 업데이트 했습니다 확인 부탁드립니다~~

**Comment by fkdl0048** [comment]
글리치 관련은 따로 씬 만들어서 테스트를 해봐도 좋을 것 같습니다. 현재 버그 원인이 명확하게 4회 이상 연출 사용 시 제대로 동작하지 않는 문제인 것 같은데 따로 쉐이더 연속적으로 사용하는 걸 만들어서 테스트 해보면 좀 더 쉽게 테스트가 가능하지 않을까라고 생각해봤습니다!

**Comment by wooyn730** [comment]
처음엔 씬 전환과 관련 있나 싶었는데 아니었어서..
그래야겠어요 😱

**Comment by wooyn730** [comment]
Pacmom과 CH1 이슈 분리
