### ISSUE TITLE
[CH1] SLG 3차 퀄리티업

### ISSUE THREAD

**Issue by jeongopo** [GG-Studio-990001/Grayed-Game#633]
### 작업 목표

- [x] SLG 타겟건물 화살표 표시
- [x] SLG 코인 개수 100개로 수정

![image](https://github.com/user-attachments/assets/ed0a1a4d-31de-46c7-a536-3fec668bc03e)

### 관련 이슈
- #626

**Comment by jeongopo** [comment]
화살표작업하는데 생각보다 좀 까다로워서 
일단 코인만 수정하고 다시작업하겠슴니다,,

**Comment by jeongopo** [comment]
### 240902 작업내용

![image](https://github.com/user-attachments/assets/d74116e3-3305-43eb-8c1f-1102d529abe0)

![image](https://github.com/user-attachments/assets/93461568-77da-4b66-8375-57c5c8abc096)


- 클릭 시 해당 건물로 화살표 표시
- 건설완료된 건물, 금지된 건물(R2Mon) 은 클릭불가

**Comment by wooyn730** [comment]
![스크린샷 2024-09-12 154208](https://github.com/user-attachments/assets/993d7ad2-586f-44b1-949e-c75a855b7f9c)

빌드 0.1.3 버전으로 확인했습니다!
근데 맵3은 좁아서 하단 UI를 펼치고 커서를 클릭했을 때(특히 플로야드 브릿지) 너무 제대로 가려지네요...
차라리 클릭했을 때 하단 UI가 내려가면 어떨까 합니다.

그리고 화살표가 머리 위에 뜨는게 아닌 기획서처럼 라플리의 주변에 배치될 수 있으면 더 좋을 것 같습니다.

**Comment by jeongopo** [comment]
### 240914 작업내용

- 플로야드 브릿지 재화 개수 수정 (@Sumindd )
![image](https://github.com/user-attachments/assets/9639894e-b5a0-465b-87ce-37a56a93ace9)


- 화살표 위치 조정 (@wooyn730 ) , 화살표 클릭 시 건설창 내려가도록 수정

https://github.com/user-attachments/assets/9239f7a2-ef7e-4894-aef8-a963ecaa653a

**Comment by Sumindd** [comment]
플로야드 브릿지도 재화수 부족할 땐 붉은 색 글씨, 재화 충족 됐을 때는 파란색으로 모두 통일 부탁드려요!

**Comment by jeongopo** [comment]
+ 글씨색상 수정
![image](https://github.com/user-attachments/assets/449c03af-b53b-4aa3-927e-318dc72ba626)

**Comment by wooyn730** [comment]
![image](https://github.com/user-attachments/assets/9fcb8463-bc7d-4df8-bac2-d13120054984)

다리 건설하려고 말풍선 누르면 그 이후로 클릭이 안먹네요.. (가장 오른쪽 맵으로 다시 가도)
확인해보진 않았지만 아마 브릿지 건설 패널이 꺼져있고 뒤에 클릭 막는? 창만 활성화되지 않나 싶습니다

**Comment by jeongopo** [comment]
아 아까 씬 꼬여서 막 다 끄다가꺼졌나.. 잠깐 밖에나와서 10시에 다시확인해볼게요

**Comment by wooyn730** [comment]
그리고 말씀드린거 바로 적용될 줄 몰랐는데 좋네요 ㅎㅎ
전 적용된 버전이 더 보기 좋은 것 같습니다!

근데 몬가 허전한 느낌이라 버튼 pressed color를 지정해주거나,
클릭할 때나 화살표가 활성화되는 3초 동안 효과음을 넣는다거나 하면 더 좋을 것 같네요

**Comment by fkdl0048** [comment]
위 영상에서는 안그러는데 저는 SLG 클릭하면 화살표가 주춤거리는 느낌이 있는데 다른 분들도 그러신가요? 회의 빌드본으로 확인해보면 될 것 같긴합니다!

**Comment by wooyn730** [comment]
저는 화살표가 쪼금 덜덜거린다?라고 느껴지긴 합니다

**Comment by jeongopo** [comment]
### 240918 작업내용

- **변경된 SLG 팩, 맵 배치오브젝트 추가**
![image](https://github.com/user-attachments/assets/f07c4ce6-53f3-44d2-accb-26159db236d7)

관련하여 @Sumindd 님께 확인+공유사항
1. 마마고 위치 20일 이후에 반영할거라 우선 저 위치에 애매하게 오브젝트 배치된상태인데라 **임시 위치 좋은곳 추천받습니다**
2. 묘하게 픽셀깨짐이 있어서 이건일단 지은님께 문의드려놨습니다
3. 오브젝트 조사 시 나오는 텍스트 추가

- 서브 오브젝트들 컷신 이전엔 나타나지 않고, 이후에 표시되도록 수정

- **미하엘이 자리를 떠날 때 SLG 팩 떨어지는 연출 추가**
![image](https://github.com/user-attachments/assets/d71da855-5770-4a64-9bd0-0b3b1e432f96)


https://github.com/user-attachments/assets/5671dcdb-ccad-4e36-9e5c-30abc90d406e

초반에 하나씩 오브젝트 튀어나오고 위쪽에서 팩 떨어지는 연출까지 작업했습니다.

내일 (9/19) 저녁8시 이후 작업 예정, 20일은 작업불가능이라,, 피드백주시면 내일까지는 반영가능합니다 


+ 화살표 흔들리는건 캐릭터 기반으로 좌표를 잡았는데 캐릭터가 이동할때 흔들려서그런듯한데
최대한 덜 흔들리게 해보려곤했는데 개선이안돼서 틈틈히 다시 보겠습니다 🤔

**Comment by jeongopo** [comment]
###240919 작업

- 지은님이 수정해주신 SLG 팩으로 교체 (외곽선이 조금더 깔끔해졌네요 좋습니다 ㅎㅎ) @JIJI037  

![image](https://github.com/user-attachments/assets/ddf616b0-68f9-4958-834a-a9182a1accc9)

- SLG 튜토리얼 수정. 중간 에셋 획득, 창 표시 튜토리얼 추가

![image](https://github.com/user-attachments/assets/31ea4761-6fe6-4395-9b69-4c8af0276716)

**Comment by wooyn730** [comment]
![스크린샷 2024-09-19 235047](https://github.com/user-attachments/assets/e352bc26-093d-4eec-89da-f12171d8efb0)

빛과 커서 등장할 때 워닝 떠요

럭키가 `눌러봐!`라고 말하고 있을 때 목재나 석재 클릭하면 오류나요 ㅎㅎㅠㅠ.....
(꼭 `눌러봐!` 대사 끝난 후에 눌러야 진행 가능)

**Comment by wooyn730** [comment]
++
빛은 알파값 변화해서 등장/퇴장하면 더 예쁠 것 같고
효과음도 있으면 좋을 것 같네요
(정안: 가능하다면 오리지널 사운드보다 SLG 짝퉁 사운드로..)

**Comment by wooyn730** [comment]
> 럭키가 눌러봐!라고 말하고 있을 때 목재나 석재 클릭하면 오류나요 ㅎㅎㅠㅠ..... (진행불가)

이거 좀 심각쓰 버그라 제가 처리해두었습니다 (럭키 말 씹을수 있게 ㅎㅎㅋㅋ)

`럭키: 왼쪽 아래에 있는<br>탭도 눌러봐`라고 말하는 중에 하단 탭을 누를 수 있게도 수정했어요

**Comment by jeongopo** [comment]
에궁 대신 수정해주셔서 감사합니다 ❤️
마우스이슈는 먼저수정하겠습니다

**Comment by jeongopo** [comment]
![image](https://github.com/user-attachments/assets/7b10276c-17f9-4343-abbf-caea131864ce)

마우스 커서는 RGBA32 + Read/Write 옵션을 모두 켜줘야하는군요.. 
수정해서 올렸습니당

**Comment by jeongopo** [comment]
#683  다른것들은 필요한경우 다음 이슈에서 수정하겠습니다.. (끝없이 이어지는 퀄리티업)
