### ISSUE TITLE
스토리 방향성

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#636]
[[240826] 스토리 방향성](https://drive.google.com/file/d/1SQLwwhqEXqq3h_av0U2VCh8g57HnIQaL/view?usp=sharing)

CH2 스토리 구체와 작업이 더디어지면서 그 이유가 뭘까 생각하다가
너무 지엽적인 것들에 빠져서 고민하는 시간이 길어지는 것 같다는 결론이 났습니다.

따라서 게임의 전체적인 스토리 속에 중요하게 다뤄야 할 우선순위를 잡고
앞으로 스토리 작업에서 어떤 부분이 필요한 지를 파악할 수 있도록
스토리 방향성 문서를 작업했습니다.

해당 문서의 내용을 전부 가져가겠다는 뜻은 아니며
읽어보시고 게임에서 다뤄지면 좋을 부분만 구체화 하고 싶기 때문에
작성된 것들 중 '이건 불필요하다, 다른 내용이 있으면 좋겠다' 등의 의견을 적극적으로 주시면 좋을 것 같습니다.
피드백 많이 주세요~!!

**Comment by fkdl0048** [comment]
## 피드백

*그냥 생각나는대로 적은 피드백입니닷 적어놓고 나중에 구체화나 회의 때 말해보면 좋을 것 같아요*

### 1.3 개연성을 위해 필요한 기획

저도 머릿속으로는 필요하다고 생각한 내용들을 목록으로 정리해 주셔서 좀 더 깊게 고민해 볼 수 있을 것 같습니다. 좀 깊게 생각해 보고 기획회의 때 이야기를 나눠보면 너무 좋을 것 같습니다. 

#### 1) R2-Mon이 GG의 오리지널 캐릭터로서 유저를 돕는 명확한 목적 설정

확실히 R2-MON의 목적성이 부족한 느낌이라 말해주신 웜홀이 엔딩을 보고 끄는 행위로 봐도 매력적일 것 같고 R2Mon이 자신의 Grayed Game자체의 연관성을 생각해봐도 좋을 것 같습니다. 원래는 자신만 있던 게임에 여러 게임들이 떨어지면서 벌어지는 현상들이라고 생각해도 R2MON의 최종 목적을 좀 고민해보면 주민들이나 라플리처럼 원래 자신의 세계로 돌아가고 싶어하니까..?

#### 2) R2-Mon의 계획 내용을 상세 설정하고, 라플리를 만났을 때 어느정도 브리핑 필요

위 내용대로 유저임을 알아차린 상태로 간다면 유저를 이용하는 측에 속할 것 같네요 주민들을 원래 게임들로 돌려보내고 인위적으로 웜홀이라는 현상을 일으키기 위해서? 결국 Grayed Game자체가 현재 플레이어가 플레이 중인 게임의 대분류에 속하긴 하니 원래 게임의 목적성을 가진 NPC로 봐도 재밌을 것 같습니다. 결국에는 메타적인 존재이지만 자신에게 주어진 목적을 위해 일하는 수동적인 NPC느낌도 나고..?

근데 뭔가 어두워지는 느낌,,?

#### 3) R2-Mon의 캐릭터성 강화

럭키에 의해 방해받아서 다른 게임들의 게임성이 손해? 망가지며 제대로된 기억(웜홀)을 하지 못하게 되어서 R2MOn이 티 안나게 조력을 해주는 역할을 생각하게 되는 것 같습니다. 위에 내용을 적어서인지..

R2-Mon을 얼마나 중요한 역할로 둘 것인지도 설정이 되면 더 구체화가 될 것 같은데 언더테일과 같이 적당한 조력자인 샌즈처럼 둘 것인지 아니면 럭키와 대립 구도를 가져갈지..도 고민이네요

#### 4) 라플리는 뭐가 다르길래 색깔 만져도 멀쩡한 지 궁금증 유발과 정체에 대한 힌트

세계관을 설명하는 내용이 조금 추가되었어도 유저와 라플리의 관계성을 어떻게 설명하느냐가 진짜 어려운 것 같습니다. 근데 이 부분은 명확하게 알려주는 순간 게임성이 떨어질 것 같은 느낌이 있어요 바로 눈치 챌 수 없어야 하는 부분이 유저의 존재아닐까? 생각됩니다.

궁금증 유발은 계속 필요할듯요

#### 5) 럭키가 악역으로 흑화하는 트리거가 무엇이며, 고밀도 뒤섞임때 무슨 일을 벌일지

트리거는 지속적인 메타력의 향상과 유저의 무시가 원인으로 보여줘야 하는데 이 부분은 계속 떡밥을 던지는 부분이라고 생각되며 결국엔 럭키를 쓰지 않는다 라는 선택지가 필요하지 않을까? 싶습니다. 럭키를 떼어내려고 하는 행동에서 뭔가 트리거가 생겨야 할 것 같습니다?

고밀도 뒤섞임때는 다른 게임들의 게임성 훼손? 다른 게임들의 세계관을 망가뜨리거나 룰을 변경하거나 현재 적용된 서브게임들을 이상하게 변경하거나 설정창을 바꾸거나 등등 매우 다양한 아이디어들이 가능해서 최대한 신박한 부분들만 선별해서 보여주고 싶은 마음이 있네요!

#### 6) 웜홀과 엔딩의 연관성

현재 기획상으로는 웜홀이 기억됨으로써 발생하는 현상으로 나오니 엔딩에선 현재 플레이중인 유저에 의해 기억된다? 라는 추상적인 그림만 있는데 확실하게 연관성을 맺는 것이 필요하다고 생각합니다! 저도

### 서브스토리

#### 주요 사건

> 처음 이곳에 왔을 때 소감 등 주민들의 다양한 반응으로 먼저 이 세계에 온 사람들이 각기 다른 게임에서 오게 되었다는 것을 간접적으로 알려주기.

이 부분 너무 좋은 것 같습니다. 하늘에서 떨어진다 라는 중요한 세계관과 각각 게임의 다양성을 보여줄 수 있는 설정같습니다.

> 달러와 빌이 처음부터 마을을 만든 것은 아니라는 점을 말해야 한다. 이들이 떨어지기 전에도 이 세상은 존재했을 것이기 때문이다.

저도 뭔가 월E같이 계속해서 반복되는 인류사처럼 보여지면 좋을 것 같네요 결코 달러가 처음 떨어진 것이 아닌? 

> 과연 유저 없이도 웜홀을 경험한 것이 사실일까? 흑화한 럭키가 “조작”한 것일수도.

이 부분 저도 기획오류가 생길까 걱정했는데, 말씀해주신 대로 럭키의 소행과 조작이라면 매력적이고 반전이 있어서 좋습니다. 근데 타임라인이 꼬이지 않는지가 궁금하네요!

뒤 읽어보니까 생각하신 내용이 있는 것 같은데 약 70% 정도만 이해된 것 같아서 회의 때 듣겠습니다!

**Comment by wooyn730** [comment]
> 처음 이곳에 왔을 때 소감 등 주민들의 다양한 반응으로 먼저 이 세계에 온 사람들이 각기 다른 게임에서 오게 되었다는 것을 간접적으로 알려주기.

좋네요~
저는 이거 시간이 지날수록 대부분 까먹는 설정으로 가도 좋을 듯
그럼 뭔가.. 마을 분위기가 좀 더 밝아지지 않을까나

<br>

> 달러와 빌

초창기에 달러와 함께하는 친구 이름이 Bill이라니..!!! ㅋㅋㅋㅋ 너무 좋은데요?
저는 빌은 미국 아저씨 이름 같아서 처음에 이름만 전해 듣다가
알고보니 약간 반전으로 젊은 포니테일 여자여도 재밌지 않을까 싶네요

![image](https://github.com/user-attachments/assets/67cacb95-9239-4e22-ba62-0e9a794a36a6)
_먼가 언다인같은.._

<br>

> A. 트루커의 비밀 상점, 그 뒤에는 빌이 있었다.

트루커 스토리 훌륭하네요!! 👍

<br>

> ‘유저 없이도 웜홀이 발생해야 한다’라는 문제점

이거는 왜인가요? 가상의 유저로 하면 안되는 부분인가...? _(뭔가 놓쳤나?)_
그리고 만약 럭키가 웜홀을 숨기고 싶다면 아예 웜홀 경험도 조작하지 않아야되는 거 아닌가요?
(진짜 잘 모르겠어서 하는 질문..)

조작에 대한 상세 설명은 재밌네요!
레퍼도 너무 잘 찾으셨네요
_그나저나 파워가 어마어마한 럭키.._

> 1.3 개연성을 위해 필요한 기획

이건 저도 몇가지 생각이 떠오르는데 (정안님과 비슷한 생각도 있고)
조금 더 다양하게 생각해보겠습니다!

<br>

잘 읽었고 정말 수고 많으셨습니다
저도 전부 다~까진 이해하지는 못했지만..ㅎㅎ
고민도 많이 보였고 재밌는 설정들도 있어서 재밌었네요!

**Comment by Sumindd** [comment]
1.3
기존엔 R2-MON의 캐릭터성인 메타가 럭키에게도 부여됐는데 럭키의 캐릭터성이 워낙 강하다보니 R2-MON이 애매해진 것 같았는데 앞으로도 목적성이 뚜렷해지면 좋을 것 같아요. 저도 이 부분에 대해 고민이 있었는데 짚어주셔서 감사합니다.
럭키와 대립되는 것이나 GG의 고유 캐릭터라는 특징을 잘 챙길 수 있으면 좋을 것 같아요!


2.2
주민들에 대한 설정도 확실하게 잡고 가는 게 좋네요. 게임엔 직접적으로 드러나지 않더라도 간접적인 대사로 느껴지면 세계관이 좀 더 탄탄해질 것 같아요. 각자 떨어질 때 다른 기억을 갖고 있다는 설정 맘에 듭니다.

예전에 3챕터에서 마을 외부에 사는 캐릭터 이야기를 잠깐 했던 것 같은데 빌이라는 캐릭터로 구체화가 된 것 같네요.
빌이라는 이름이 달러랑 세트라서 좋긴한데 같은 게임에서 떨어졌나?라는 생각도 들어서 오히려 관계 없는 이름이어도 좋지 않을까 싶네요. (임시 이름일 것 같지만?)

그리고 특히 럭키의 조작은 시스템적으로도 재밌게 활용할 수 있을 것 같아서 흥미롭습니다. 저도 시스템적으로 활용 방안을 좀 더 생각해볼게요


전체적으로 저는 흥미롭게 읽었고, 이 방향으로 구체화 돼도 괜찮을 것 같다고 생각했습니다!

**Comment by roweclaw** [comment]
@wooyn730 답변이 늦어 죄송합니다 ㅠㅠ

> ‘유저 없이도 웜홀이 발생해야 한다’라는 문제점
이거는 왜인가요? 가상의 유저로 하면 안되는 부분인가...? (뭔가 놓쳤나?)

가상의 유저로 하는 방법도 물론 가능하긴 합니다.
그러나 그 경우에 라플리(유저)가 아닌 다른 가상의 유저라는 존재가 등장하면
게임에서 중요한 웜홀이라는 키워드를 미리 소모하여
후반에 유저가 경험할 `유저와 웜홀의 연결` 같은 메시지를 명확히 전달하기 어렵다고 느꼈습니다.
즉, 스토리와 엔딩을 고려했을 때 최후의 보루이기 때문에 그 방법은 웬만해서 피하고 싶었어요!!

그리고 [최근 기획회의](https://github.com/GG-Studio-990001/Grayed-Game/issues/639)에서 R2-Mon의 설정이 바뀌면서
라플리가 가장 처음 맞이하는 유저이기 때문에, 라플리 이전에 가상의 유저가 왔다는 것은 기획 오류가 될 것 같습니다.

> 그리고 만약 럭키가 웜홀을 숨기고 싶다면 아예 웜홀 경험도 조작하지 않아야되는 거 아닌가요?
(진짜 잘 모르겠어서 하는 질문..)

럭키는 유저가 웜홀을 찾게 되면 자신을 떠날 것이라는 불안함이 있습니다.
그래서 잘못된 정보로 혼동을 주어서 웜홀을 찾는 것을 방해하려는 심산으로 조작된 웜홀 경험을 의도적으로 만든 것입니다.

저의 답변이 이해가 되었으면 좋겠네용. 혹시 더 궁금한 점 있으면 물어봐주세요!!

**Comment by wooyn730** [comment]
제가 다르게 생각하고 있던 거 같은데 일단 써볼게요!

저는
`게임이 마을에 떨어지는 이유: 세상 모든 사람들이 그 게임을 까먹었기 때문`
`웜홀이 열리는 이유: 이 세상에 있는 누군가가 특정 게임을 기억해내서 해당 게임을 세계로 돌려놓기 위해 열리는 문`
이라고 생각하고 있었습니다. (떨어지는 것과 반대)
그래서 가상의 유저는 게임 밖의 인물이라고 생각했습니다.
(게임 밖의 누군가가 팩맘을 기억하면 웜홀이 열려 팩맘이 웜홀로 들어가서 그 세계로 돌아감)

다시 이해하기로는
`잊혀진 게임들이 모종의 이유로 Grayed Game에 모이고,
Grayed Game을 플레이하는 유저(나)가 웜홀을 찾아 마을 주민들과 함께 원래의 세계로 돌아간다.
(웜홀로 마을 주민이 들어가면 그 게임은 세계에 다시 존재하게 된다)`
`따라서 가상의 유저를 추가하면 안된다. 이 세계관에서의 유저는 Grayed Game을 플레이하는 인간 뿐
(만약 가상의 유저가 들어간다면 언더테일의 여섯 인간(6개의 영혼) 같은 느낌??)`
인데 맞나요? 잘못된 게 있을까요?

웜홀의 정확한 역할은 아직 정해지지 않았으며 1.3. `(6) 웜홀과 엔딩의 연관성`에서 결정되는 것 맞나요?

**Comment by fkdl0048** [comment]
- 웜홀에 대한 정보는 떡밥과 같습니다. 이후 럭키 스토리에 따라 조작된 정보에 가까우며 현재 다르고 있는 정보는 럭키에 의해 조작된 정보일 가능성이 높습니다. 
우연님이 웜홀 설정에 대해서 어디가 이해가 안갔는지 알려주시면 좋을 것 같아요!

**Comment by roweclaw** [comment]
### 1) 
> 게임이 마을에 떨어지는 이유: 세상 모든 사람들이 그 게임을 까먹었기 때문

맞습니다!


### 2)
> 웜홀이 열리는 이유: 이 세상에 있는 **누군가**가 특정 게임을 기억해내서 해당 게임을 세계로 돌려놓기 위해 열리는 문
> 그래서 **가상의 유저**는 **게임 밖의 인물**이라고 생각했습니다.
(**게임 밖의 누군가**가 팩맘을 기억하면 웜홀이 열려 팩맘이 웜홀로 들어가서 그 세계로 돌아감)

이것도 맞습니다만, `누군가, 가상의 유저, 게임 밖의 인물, 게임 밖의 누군가` 와 같이 불특정 대상이 아니라
**라플리이자 현재 GG를 플레이하고 있는 유저**로 특정하는 것이 메시지 전달에 효과적이라고 생각합니다.
게임이 수동적이기 때문에 라플리(유저)가 있어야 진행되고 웜홀도 나타난다는 맥락으로 봐주시면 될 것 같아요.

### 3)
> Grayed Game을 플레이하는 유저(나)가 웜홀을 찾아 마을 주민들과 함께 원래의 세계로 돌아간다. (웜홀로 마을 주민이 들어가면 그 게임은 세계에 다시 존재하게 된다)

이 부분은 엔딩으로 일어날 결과가 될 것 같습니다.

### 4)
> 따라서 가상의 유저를 추가하면 안된다. 이 세계관에서의 유저는 Grayed Game을 플레이하는 인간 뿐 (만약 가상의 유저가 들어간다면 언더테일의 여섯 인간(6개의 영혼) 같은 느낌??)

맞습니다. 2번과 같은 맥락으로 생각해주세요.

### 5)
> 웜홀의 정확한 역할은 아직 정해지지 않았으며 1.3. (6) 웜홀과 엔딩의 연관성에서 결정되는 것 맞나요?

넵 지금은 미정이 맞고, 다음 기획회의 안건입니다.
그래서 1~4번도 다시 얘기해보면서 맞춰가야 할 것 같네요!!

### 6)
> 2번째 질문은 애초에 마을에 웜홀에 대한 아무 정보도 없다면
럭키가 굳이 '웜홀' 정보를 조작하는 것은 오히려 유저들에게 웜홀이 존재한다는 **힌트를 주는 것** 아닌지?
(그럼 애초에 '웜홀' 정보가 마을에 돌아다니고 있던 상태인지?)

마을에는 럭키의 조작으로 인해 잘못된 웜홀에 대한 정보가 돌아다니게 되고
말씀하신 `힌트를 주는 것`이 곧 스토리 개연성이 될 것이라 생각합니다.
정안님 코멘트처럼 미리 떡밥을 주어서 웜홀이란 것을 이 세상에서 찾아야 한다고 인식시키는 것이 필요하기 때문입니다.

_코멘트로 적는 거는 한계가 있어서 이 내용들을 가지고 기획회의에서 전체적으로 검토하면 좋겠네요!!_

**Comment by fkdl0048** [comment]
> 2번째 질문은 애초에 마을에 웜홀에 대한 아무 정보도 없다면 럭키가 굳이 '웜홀' 정보를 조작하는 것은 오히려 유저들에게 웜홀이 존재한다는 힌트를 주는 것 아닌지?
(그럼 애초에 '웜홀' 정보가 마을에 돌아다니고 있던 상태인지?).

이 웜홀이 결국 엔딩요소로 결정된 이상 각자 생각하는 문제점들이 있을 것 같아요(제가 생각하지 못한?) 같이 인터뷰 시간에 이야기 해봐도 좋을 것 같습니다
