### ISSUE TITLE
[CH1] 시스템 기획 수정 3차

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/Grayed-Game#638]
- #626 에 이어서 작업합니다.

SLG 화살표 방향 연동으로 수정
기획서 11페이지 SLG 기획 작성
오프닝 신규 쓰레기 산 맵 + 플로우 기획
저장&불러오기 스크립트(연출) 기획

### 240831 업데이트

[[240831] CH1 기획 변경 사항](https://drive.google.com/file/d/1EhRy5fBCMSalE_mOfgU47OOoQ4_SdZmk/view?usp=sharing) 업데이트 했습니다.

**수정된 파트**
5페이지) 화살표 실시간으로 변화 수정 / 달러 동상 위치 오른쪽으로 고정
6페이지) R2-Mon 기지는 방향 표시가 안 뜨게 클릭을 막아둔다는 내용 추가
10페이지) 라플리가 팩맘을 잡는 룰 삭제 -> 먼지와 라플리가 팩맘을 잡는 룰 삭제로 표현 확실하게 수정
**추가된 파트**
11페이지) SLG 맵 배치 수정 기획
12페이지) SLG 럭키 튜토리얼 수정본 플로우 기획
13페이지) 저장하기, 이어하기 스크립트 기획
14페이지) 게임 쓰레기 산 기획

게임 쓰레기 산 맵은 고민되는 내용이 좀 있어서 지은님과 따로 한 번 회의 진행 후에 세부 기획서 작성하고 싶습니다.
[핀터 레퍼런스](https://pin.it/2P9AiLRb9)를 조금 찾아두긴 했는데.. 회의 진행 때 자세히 이야기 해보겠습니다! 
관련 의견 코멘트는 환영입니다!!

**Comment by Songkihwa** [comment]
이 순간을 기억하는 중이라니 넘 좋네요 ! 
작업하시느라 고생하셨습니닷

게임 쓰레기 산은 1안이나 2안이 좋을 것 같긴 한데 음 진짜 어렵네요 ,,,,

**Comment by fkdl0048** [comment]
기획문서 쭉 컴토 해봤는데 빠진부분 없이 잘 작성해주신 것 같습니다! 회의 때 한번 이야기해보고 결정되면 작업자 할당하고 바로 진행하면 될 것 같아요

**Comment by wooyn730** [comment]
> 저장하기, 이어하기 스크립트 기획

이거 귀여운데 실제로는 저장을 꽤 자주해서...
(특히 컷씬은 끝날 때마다 저장함)
실제 저장할 때마다 저 문구가 뜨면 너무 잦을 것 같아서 걱정이 되네요
자동 저장이라 더 애매한 것 같기도 하고 (수시로 알아서 하니까)

라플리가 무한히 걷는 건 귀여운데 다른 챕터에서도 사용하기 애매하지 않을까 싶어요 챕터마다 비주얼이 다르니까?

> 게임 쓰레기 산

이거 오프닝 스토리보드 이슈에서 자동컷씬이라고 보긴 했는데
일단 전 1안에 한표 할게요
그리고 자동진행은 최소화하는 게 좋을 것 같다는 생각 ...
