### ISSUE TITLE
[CH1] 팩맘 대사 수정

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#640]
팩맘의 승리 조건이 변경됨에 따라 아래 대사를 수정합니다.

- [x] 럭키 팩맘 설명 대사
- [x] 먼지 첫진입 대사
- [x] 먼지 재진입 대사

---
**Lucky_Pacmom**

```
럭키: 럭키가 왔어~<br>도움이 필요해?
럭키: 아하, 나 <slide>팩맘</slide> 알아!
럭키: 팩맘보다 코인을<br>많이 모으는 거라구

<<Showing>>
<<ShowDrawing true>>
// 팩맘을 보여준다.
럭키: 이게 바로 팩맘!<br>잡히면 코인을 뺏긴대
럭키: 특히 청소기를 든 팩맘은<br>엄청 무서우니까 조심해

<<ShowDrawing false>>
<<Idle>>
럭키: 어쨌거나 팩맘보다<br><wave>코인이 많으면 끝!</wave>
럭키: 럭키는 이만 갈게~
```
- 기존에 있던 `<<Pointing>>` 은 애매해서 삭제했습니다.

**PacmomDialogue**
> title: PMStart

9 `DustB: 너도 팩맘 몰래<br><wave>코인</wave> 모으러 온 거야?`
17 `DustA: 코인을 싹 쓸어서<br>복수해 주마!`
19 `DustB: 잔뜩 쓸어주마!`
21 `DustA: 하지만 청소 시간에는<br>꼭 <shake>도망</shake>가야 해`
27 `DustB: 이제 곧 시작한다!`

> title: PMRetry

34 `DustA: 역시 다시 왔구나!`
37 `DustB: 이번엔 제대로<br><wave>코인</wave>을 쓸어가 주마!`
41 `DustB: 다시 시작이다!`

> title: PMStartAgain

48 `DustA: 오오, 또 온 거야?`
53 `DustA: 한 번 더 <wave>코인</wave>을 모아보자!`
55 `DustB: 모으는 거다!`

**Comment by wooyn730** [comment]
> 코인을 싹 쓸어서 복수해 주마!

먼지는 코인을 못모으는데 코인을 먹는 이야기는 오해의 소지가 있지 않을까 싶네여
먼지는 도망과 청소시간 위주로만 언급하면 부족할까요??
청소시간 설명은 좀 더 디테일해도 될 것 같슴다
(주변에 코인을 빨아들이고 빨라진다 등)

<br>

럭키 대사는 깔끔하고 좋습니다!!

**Comment by fkdl0048** [comment]
그럼 코인을 싹쓸어서 복수해줘! 같은 대사는 어때요

**Comment by roweclaw** [comment]
넵넵 먼지 대사에서 코인 얘기 수정하고, 청소시간 설명 추가하겠습니다!!

**Comment by roweclaw** [comment]
_여기서 더 수정할 점 있다면 말씀해주세요~!_

**title: PMStart**

```
---
<<DustASpeak>>
DustA: 뭐야, 여기에는<br>어떻게 들어온 거야?
<<DustBSpeak>>
DustB: 팩맘이 너한테도<br>모욕감을 줬어?
<<RapleySpeak>>
Player: 
<<DustBSpeak>>
DustB: 얘는 아직 모르나 봐!
<<DustASpeak>>
DustA: 팩맘이 우리 보고<br>드~러운 먼지들이래
<<DustBSpeak>>
DustB: 정말 미워!
<<DustASpeak>>
DustA: 여기서 나가면 <wave>코인</wave>을<br>싹 쓸어서 복수해 줘!
<<DustBSpeak>>
DustB: 잔뜩 복수해 줘!
<<DustASpeak>>
DustA: 그리고 청소 시간은<br>꼭 <shake>조심</shake>해
DustA: 팩맘이 빨라지고<br>코인도 휩쓸어 가거든
<<DustBSpeak>>
DustB: 청소기 소리도 싫어!<br>움직이기 힘들단 말이야
<<DustASpeak>>
DustA: 아무튼 파이팅이야!
<<DustBSpeak>>
DustB: 이제 곧 시작한다!
<<OpeningDialogueFin>>
===
```

**title: PMRetry**
```
---
<<DustASpeak>>
DustA: 역시 다시 왔구나!
DustA: 아까는 정말 아까웠어
<<DustBSpeak>>
DustB: 이번엔 제대로 복수해 줘!
<<DustASpeak>>
DustA: <wave>코인</wave>을 싹 쓸어버려!
<<DustBSpeak>>
DustB: 다시 시작이다!
<<OpeningDialogueFin>>
===
```

**Comment by wooyn730** [comment]
> 팩맘이 너한테도 모욕감을 줬어?

> 팩맘이 우리 보고 드~러운 먼지들이래

이거 너무 웃겨요
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

### 피드백

팩맘한테 잡히면(부딪히면) 안된다라는 것도 먼지가 한 번 언급해주면 좋을 것 같아요

> DustB: 잔뜩 복수해 줘!

`잔뜩`보다는 `꼭`이 더 어울릴 것 같아요 (이건 주관적)

### 그 외

랜덤으로 출력되는 대사는 제가 임의로 수정해봤는데 피드백 받을게여
(팩맘은 미운데 무서워하는 그런 느낌?으로 쓰려고 했는데 좀 어려븜)

```
title: PMRandom
position: 163,31
---
// 자주 나오지 않으며, 구분 없이 사용됨
<<declare $RandomInt = 0>>
<<set $RandomInt = dice(4)>>

<<if $RandomInt is 1>>
    Dust: 어딨지?
<<elseif $RandomInt is 2>>
    Dust: (쒸익쒸익)
<<elseif $RandomInt is 3>>
    Dust: (두리번)
<<else>>
    Dust: (살금살금)
<<endif>>
===
```

랜덤 대사를 6개에서 4개로 줄이고 나오는 간격도 늘리려고 해요
그리고 청소기 모드가 아닌데 팩맘에게 쫓길 때의 대사(랜덤 출력)을 추가하면 좋을 것 같은데 어떤가요?

**Comment by wooyn730** [comment]
![스크린샷 2024-08-31 003016](https://github.com/user-attachments/assets/4d90f295-ceb1-4cea-b0f0-0c0a373f47f5)

이거 3줄로 가면 좀 낑겨 보여서 딱 한자만 줄이면 좋을 것 같은데...

**Comment by roweclaw** [comment]
**피드백 반영 버전 title: PMStart**

- 단어 수정 : 잔뜩 -> 마구마구
- 글자수 줄이기 : 힘들단 말이야 -> 힘들단 말야
- 잡히지 말라는 대사 추가

```
---
<<DustASpeak>>
DustA: 뭐야, 여기에는<br>어떻게 들어온 거야?
<<DustBSpeak>>
DustB: 팩맘이 너한테도<br>모욕감을 줬어?
<<RapleySpeak>>
Player: 
<<DustBSpeak>>
DustB: 얘는 아직 모르나 봐!
<<DustASpeak>>
DustA: 팩맘이 우리 보고<br>드~러운 먼지들이래
<<DustBSpeak>>
DustB: 정말 미워!
<<DustASpeak>>
DustA: 여기서 나가면 <wave>코인</wave>을<br>싹 쓸어서 복수해 줘!
<<DustBSpeak>>
DustB: 마구마구 복수해 줘!
<<DustASpeak>>
DustA: 그리고 청소 시간은<br>꼭 <shake>조심</shake>해
DustA: 팩맘이 빨라지고<br>코인도 휩쓸어 가거든
<<DustBSpeak>>
DustB: 청소기 소리도 싫어!<br>움직이기 힘들단 말야
<<DustASpeak>>
DustA: 그래도 잡히지 않게<br>도망가야 돼
<<DustBSpeak>>
DustB: 잡히면 코인 빼앗겨!
<<DustASpeak>>
DustA: 아무튼 파이팅이야!
<<DustBSpeak>>
DustB: 이제 곧 시작한다!
<<OpeningDialogueFin>>
===
```

**그 외**
- 써주신 랜덤 대사 괜찮은데요? 그대로 사용해도 좋을 것 같아요!!
- 청소기 모드가 아닌데 팩맘에게 쫓길 때의 대사 추가한다면 이런 느낌..??
   - 오지 마!
   - 튀어!
   - (내적비명)
   - 들켰다!
