### ISSUE TITLE
[Pacmom] 변경된 기획 반영

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#642]
[[CH1] 시스템 기획 수정 2차](https://github.com/GG-Studio-990001/Grayed-Game/issues/626) 참고

---

### 작업
- ===**1주차**===
- [x] 중앙 청소기 2개 삭제
- [x] 팩맘 UI 목숨 삭제
- [x] 팩맘은 항상 먼지와 라플리를 잡음
- [x] 청소시간이 아닌데 먼지와 라플리가 잡혔을 때
   - => 기획엔 없는 내용, 바로 방에서 나올 수 있게 처리?
- 수정된 대사 적용
   - [x] 먼지 대사
   - [x] 럭키 대사
   - [x] 먼지 랜덤 대사 임의 수정
   - [x] 먼지 대사 2차
   - [x] 먼지 대사 3차
- TODO 구현
   - [x] 필드에 코인 없으면 먼지 종료대사 출력
   - [x] 팩맘 이긴 적 있어도 마지막에 졌으면 아깝다 대사 출력
   - [x] 포식자와 피식자 AI 분리
   - [x] 먼지 쫓길 때 대사 추가
- 필요없는 코드 정리
   - [x] 필드에 남은 코인 라플리가 흡수 이제 필요 없을 듯
- ===**2주차**===
- UI 수정
   - [x] 상단 타이머 제거
   - [x] 상단 UI에 남은 코인 표시
   - [x] 하단 코인 개수 UI 위치 교체
   - [x] 재시작 버튼 배치
- ===**3주차**===
- [x] 재시작 수정
   - 필드 코인+라플리 코인이 팩맘 코인보다 적거나 같으면 역전 불가능으로 판단
   - 'press r to restart' 띄우고 r 버튼 활성화
   - r 누르면 재시작 가능하며 이전 판은 진 것으로 처리
   - 'press r' 텍스트 깜빡임
- 팩맘
   - [x] 시작 전 움직이지 않게
   - [x] 약간의 속도 패치 (팩맘 속도 6 -> 5.5)
- [x] 먼지 청소모드 대사 랜덤하게 출력될 수 있도록 추가
   - ![image](https://github.com/user-attachments/assets/8ece3afa-b816-46fc-948e-61de4070464a)
- 리팩터링
   - `DustExitRoom`과 `DustExitRoomSoon` 네이밍 등
   - 그 외 주석처리 해둔 것들
- 필요없는 코드 정리
   - 안쓰는 효과음도 정리

### 생각
룰은 꽤 간단해짐
그러나 청소기가 줄었음에도 코인 모으기는 더 어려워진다 (당연함)
=> 팩맘의 기본 속도를 더 느리게 하거나, 라플리가 팩맘에게 잡히면 코인을 절반이 아닌 10정도만 뺏기게 한다거나(아님 랜덤으로 10~30?)

먼지의 역할이 너무 애매해졌다 (잡히기/길막하기)
=> 팩맘이 먼지를 먹으면 콜록콜록하면서 약 3초 동안 느려진다거나?

++
방에 들어가자마자 위방향키가 눌려있어서 나올 때
방 앞에 팩맘이 있으면 바로 잡힘

**Comment by fkdl0048** [comment]
우선 우연님이 생각하신대로 밸런스를 맞춰주시면 다같이 빌드 테스트할 때 피드백을 받아보면 좋을 것 같습니다.

> 바로 방에서 나올 수 있게 처리?

이것도 생각 못한 내용이라 우연님 생각대로 해도 될 것 같다고 생각하는데 @Sumindd 수민님 생각도 들어보고 바로 반영해주셕도 될 것 같아요

**Comment by Sumindd** [comment]
팩맘이 먼지 먹었을 때의 효과는 추가돼도 장점만 있을 것 같아서 플밍쪽에서 번거롭지만 않으면 추가해도 문제 없을 것 같습니다!

**Comment by wooyn730** [comment]
우선 이번 주는 팩맘 수정된 기획 반영하고 다듬는 정도로만 갈게요!
밸런싱과 기능 추가는 다음 주로 넘기겠습니다

**Comment by Songkihwa** [comment]
먼지 콜록 저도 좋은 것 같아요 !!

**Comment by wooyn730** [comment]
## 09/07 
### UI 수정 작업

해당 작업 진행함

![image](https://github.com/user-attachments/assets/ba584bd9-dbf4-4f48-aae1-e259bd68ae4b)

![스크린샷 2024-09-07 214950](https://github.com/user-attachments/assets/373174d8-aefa-47eb-a13b-651ee98fab4d)

LOGIN 시연회 때 느낀 것 + 수민님과 이야기 나눈 것 토대로 작업 진행
확실히 더 직관적이고 편리한 느낌
_(자세한 건 회의 때 말씀드릴게요 궁금하시면 질문 받음)_

### 필요한 것
'필드 남은 코인 개수 어떻게 보여줄지'랑 (지금은 `~ coin left`라고 임시로 해둠)
'재시작 버튼 어디에 어떻게 배치하면 좋을지' 피드백과 아이디어 필요

### 재시작 버튼에 대한 생각
- 재시작 버튼이 세계관 설정을 해치지 않는지
- 다른 접속 게임에도 재시작 버튼이 존재하게 될지?
- 재시작 버튼이 버튼 이미지가 없으니까 버튼 안 같음
- 구석에 두면 쉐이더 때문에 왜곡이 있어 실제 버튼 위치와 보이는 버튼 위치가 다름
- 재시작 버튼을 설정창에 넣기?
- 역전 가망이 없을 때 press 'r' to restart 이런 걸 띄운다던가? (근데 이건 다른 접속게임과 통일하기 어려워 보임 (만약 통일한다면))

**Comment by Sumindd** [comment]
방에 잡혀 있는 시간을 일괄적으로 5초로 통일하는 건 어떨까요?

**Comment by wooyn730** [comment]
지금은
노말 모드 - 거의 바로 나옴 (방문이 계속 열려 있음)
청소 모드 - 청소모드가 종료되면 나옴 (방문이 계속 닫혀 있다가 끝나면 열리고 순서대로 나움)

이렇게 두 가진데 5초로 통일한다면... 고민이 되네요?
먼지는 5초 뒤에 알아서 나오고, 라플리는 5초 뒤에 방문을 열어서 알아서 나오게 해야하는 건지...
지금 써보니까 좀 복잡한 것 같네여 (유저에게 5초 뒤에 방문이 열린다는 것을 인지하게 하는 것이)

플레이 피드백을 좀 받아보고 싶네요
방 갇힘 억까가 예상되긴 하지만 이제 재시작 가능하게 해두어서 전보단 괜찮지 않을까 싶기도 하고 그렇네요

**Comment by fkdl0048** [comment]
플레이 해보니까 저는 기존에도 어렵다고 느끼지 않아서 인지 크게 문제 없었습니다. 아직 재시작이 적용 안된 버전인게 맞나요?

**Comment by wooyn730** [comment]
재시작 적용 되어있습니다!
역전이 불가능한 상황(패배가 확실시 된 상황)에만 'press r to restart' 문구를 띄우고, 이때부터 r로 재시작 가능하도록 구현하였습니다.
