### ISSUE TITLE
[CH2][Char] 라플리, 미카엘 스탠딩 작업

### ISSUE THREAD

**Issue by JIJI037** [GG-Studio-990001/Grayed-Game#645]
라플리, 미카엘 ~,R2-mon~ 기본 스탠딩 작업합니다.

24.09.18
피드백 수용해서 제작하였습니다. 선화 느낌을 강하게 했는데  이에 대해 힘을 더 빼야 할지 유지할지 의견 남겨주시면 감사하겠습니다. uu

24.10.07
피드백 수용해 1차 러프입니다 기존에 그린 라플리는 키를 줄이고 조금 더 어린아이 처럼 그렸습니다 알투몬은 예시가 두 개라... 일단 둘 다 그려봤습니다 미카엘 러프는 이전과 동일합니다

24.10.21
라플리 수정 버전입니다. 미카엘과 알투몬은 진행 중입니다. (지난 주에 손목을 다쳐서 업데이트가 늦어졌네요 죄송합니다ㅜ)

24.10.28
라플리, 미카엘 최종입니다.
![라플리 스탠딩_최종](https://github.com/user-attachments/assets/1c2afd3c-2a04-4ce1-a672-bacf94978972)
![미카엘 스탠딩_최종](https://github.com/user-attachments/assets/9891dd5a-e8a0-4993-b6f1-aae66f2e8241)

**Comment by wooyn730** [comment]
### 문서
[CH2 아트 리소스 관리 문서](https://docs.google.com/spreadsheets/d/1Dm7b5r5Cmk4YC4DTW4ureRnq3Xmny8bs/edit?gid=1580449727#gid=1580449727)
=> 작업 완료 초기화해뒀으니 1, 3, 10 작업하고 체크 부탁드려요!

### 캐릭터 설정
_(가져오긴 했는데 꽤 바뀌어서 필요하다면 수빈님께 업데이트 요청을 드려야겠네요? ^\_^)_

[R2-Mon 캐릭터 설정](https://drive.google.com/drive/folders/1Pbyjg_Fi56Jz2wkP0JPZUUAMtKAEgMzF)
=> 비교적 최근 문서인데도 현재는 사이렌이 빠지는 등 많이 바뀌어서 '키가 작고 팔이 늘어나는 로봇이다' 정도만 참고해주시면 되겠네요

[라플리 캐릭터 설정](https://drive.google.com/drive/folders/1Dyfgohz_Q9LkiHMICLO094bx0fZTD1Qb)
=> 이건 너무 옛날 버전이네요 키, 몸무게, 의상, 행동 양식 + 중성적인 외모 정도만 참고해주시면 되겠습니다

[미카엘 캐릭터 설정](https://drive.google.com/drive/folders/1Dyfgohz_Q9LkiHMICLO094bx0fZTD1Qb)
=> 다른 NPC랑 섞여있습니다 이것도 꽤 옛날 버전이라 헤어, 의상 +링/날개/게임보이 정도만 참고해주세요!

### 기존 아트

[CH2 캐릭터 폴더 위치](https://drive.google.com/drive/folders/1rpobgkwSOaJADqHvWNRGEsESOC3gZYKa)
=> 현재 이전 버전 스프라이트들 있으니 참고~

[캐릭터 컨셉아트](https://drive.google.com/drive/folders/1GDFNSA8pbgwOhaIabEDjXjqG7O83M_dQ)
=> 알투몬 빼고 참고가 되겠네요

[CH1 캐릭터 스프라이트](https://drive.google.com/drive/folders/1n9BeEAncWHCryg3RRbfaVo6b_f3WB6Fx)
=> 알투몬은 이름 뒤에 2가 붙은게 최신입니다. CH1과 다르게 그려져도 같은 캐릭터니 이게 가장 참고할만하지 않을까 싶습니다 (엑스트라는 사용안하는 중)

**Comment by fkdl0048** [comment]
캬.. PM님 일 잘하시네요?

**Comment by roweclaw** [comment]
- #648 

캐릭터 설정 문서 업데이트 되었습니다!!

**Comment by JIJI037** [comment]
피그마 레퍼런스 참고하며 스탠딩 제작 중 의견이 있어 남겨봅니다 ^-^

레퍼런스 특성상 고전 만화 그림체로 안광이 크다는 특징이 있습니다
현재 캐릭터들의 안광 유무나 고전 그림체의 경우 데포르메가 강해 성인, 학생의 체격 차이와 눈 크기 차이도 꽤나 큽니다
라플리와 미카엘 두 캐릭터 모두 안광이 없어 이대로 작업 시 공포 게임처럼... 예시로 쓰르라미 울 적에라는 게임의 일러스트처럼 보여 뭔가 감이 안 잡히네요...

다른 의견 제시로 요즘 미연시 그림체... 까진 아니지만 현대의 그림체, 또는 조금 먼 이야기이지만 아예 카툰 식의 그림체도 제시해 봅니다
최대한 캐릭터와 맞게끔 레퍼런스를 찾아와봤는데 편하게 말씀 주세요,,
![CharFull_Yuki_S000](https://github.com/user-attachments/assets/f137ea28-9d08-4e7d-8f25-6993c1e0ad67)
![187ada97505520c65](https://github.com/user-attachments/assets/8e31799f-5064-46e4-b049-17bb4d834786)

해당 게임은 앤디와 레일리의 관으로 플레이 추천은 안 드립니다...
![ae4bfe80c8cadf41a88eb39302b60385](https://github.com/user-attachments/assets/3be8664b-62ef-49d8-9edb-ba543188e9b5)
![187ada98e94520c65](https://github.com/user-attachments/assets/28ade515-b5d8-4d23-a96f-52638a37fc9d)

**Comment by Sumindd** [comment]
사실 기획 단계에서 이런 부분까지 고려를 하진 못했습니다. 흑백에 표정도 크게 없는 캐릭터다보니 GG의 특징적인 문제로 확실히 고전 만화 스타일은 살리기 힘들 것 같네요.. (쓰르라미만 봐도 안광 사라지면 게임이 바로 무서워져서..ㅋㅋㅋㅠ)
저는 카툰 스타일은 비주얼 노벨(그 중에서도 미연시)과 좀 멀어질 것 같아 차라리 전에 보여주셨던 라플리처럼 요즘 미연시 스타일로 가는 게 나을 것 같습니다. 애초에 고전 만화랑 요즘 미연시 (최신 서브컬쳐 일러스트 스타일.. 지은님이 처음에 그려주셨던 버전 느낌) 중에 고민했던 거라 개인적으론 돌아가는 게 나을 것 같다는 의견입니다!

**Comment by wooyn730** [comment]
![image](https://github.com/user-attachments/assets/e6307fe4-9d21-4683-8214-dce1ab6cb694)
![image](https://github.com/user-attachments/assets/3a420c1c-49ec-49dd-b321-07cc9637fab7)
저는 '가짜하트' 느낌도 좋다고 생각했습니다

![image](https://github.com/user-attachments/assets/10cdeabb-1182-4c00-b684-b1a5a62db0b6)
옛날 레퍼로는 '그 섬'도 있었고요

둘 다 기존의 CH2 아트와 비슷한 결이라고 생각하고 모던하고 차분한 느낌?? 이랄까..
지금의 기획 추구방향이랑은 다르지만요

카툰 느낌은 갠취로 마음에 드는데 이것도 방향성과 다르긴 하네요 ㅎㅎ 

암튼 다양한 의견 주시는 것 좋네요! (고전 순정만화 반대파로서 더 ㅎㅎㅋㅋㅋ)

<br>

저는 2번째 느낌 마음에 드네요 (빙과인가? 1번째 사진은 모바일게임 느낌)

저번에 보여주신 사춘기 고딩 라플리(?)나 스케치를 본문에 남겨주시면 어떤 생각을 하시고 어떻게 바뀌는지 체크하기 좋을 것 같네염~~!

**Comment by JIJI037** [comment]
헉 가짜하트 그림체 너무 좋네요 GG랑도 잘 맞을듯...? 저번 피드백이랑 같이 참고해서 선화 완성시키고 올려보겠습니다 ^-^

**Comment by JIJI037** [comment]
혹시 이런 느낌 괜찮으실까용... 레퍼런스 참고하여 단순한 채색보단 선 느낌도 같이 내면 좋을 거 같아 시도해봤습니당
![image](https://github.com/user-attachments/assets/b2587f4d-edab-4ce7-8abe-3040d06bcf82)

**Comment by fkdl0048** [comment]
> 라플리와 미카엘 두 캐릭터 모두 안광이 없어 이대로 작업 시 공포 게임처럼... 예시로 쓰르라미 울 적에라는 게임의 일러스트처럼 보여 뭔가 감이 안 잡히네요...

저도 기획당시에 생각하지 못한 부분이라 공포게임처럼 보일지 몰랐습니다.. 현재 보여주신 미연시, 비주얼노벨 성격만 잘 보이면 만족합니다. 현재 CH2의 스탠딩에서 부족하다고 느끼는 부분은 CH1 -> CH2로 변할 때 임펙트가 부족하다는 느낌이 강합니다 (장르가 바뀌지만 바뀐다는 느낌이 덜받음)  따라서 퀄리티가 좀 더 올라가고 미연시나 비주얼노벨 성격이 강한 그림체를 원합니다!

위에 올려주신 스탠딩이면 저는 너무 만족입니다.

### 개인적인 생각

장르가 바뀌어서 GG에서 하고 싶은 이야기는 저는 억지스러움, 개그스러움이 있었으면 좋겠습니다. GG게임이 끌고 가야 할 호흡은 상당히 긴데 그 과정이 심각하고 무거우면 안된다는 생각입니다. 하고자 하는 이야기는 당연히 깊이감이 있고 잘 짜여져있는 치밀한 이이갸이지만, 그걸 설명하는 방식과 연출은 재미가 있어야 한다고 생각합니다!

게임은 결국 플레이어가 재미가 있어야 하는데, CH2가 비주얼노벨이라는 장르(게임)에 깊게 묶이게 되는 순간 GG라는 장르성이 사라질 것 같기에 비주얼노벨+미연시라는 장르를 이용하다고 하는 것이 더 적합하다는 생각이 듭니다.

그 과정에서 CH1 -> CH2의 전환이 매우 중요하고 집중도를 확 끌어올리는 중요한 포인트입니다. 현재 CH2는 임펙트가 부족하다는게 제 판단이고 그 이유는 아마 그레이스케일을 계속 가져가야 하기 때문일거라 생각합니다.. 도트에서 달라진 모습을 보여주기 위해선 고퀄리티의 해상도, (비주얼노벨, 미연시) 장르의 대표적인 장르가 생각나야 한다고 생각했는데, 안광이 기괴할 것 같다는 생각을 못해서.. 현재 작업해주신 느낌의 일러스트라면 만족할 것 같습니다.

위에 적은 생각들은 기획회의 당시에 좀 이야기하기도 했지만 이번 회의가 없어서 따로 글로 적어봅니다.. 다른 분들도 읽어보시면 좋을 것 같아요.

@wooyn730 @Sumindd @roweclaw @JIJI037 @vprwolf @Songkihwa @jeongopo

**Comment by fkdl0048** [comment]
좀 더 보니까 채색이 아니라 선 느낌이 더 느낌이 확 다가올 것 같네요!

**Comment by JIJI037** [comment]
한 번 해봤는데 보시고 편하게 의견 남겨주세용~....
![스크린샷 2024-09-18 042947](https://github.com/user-attachments/assets/ac544ac7-3454-4d44-ac4f-bb285ee79657)

**Comment by fkdl0048** [comment]
저는 너무 만족합니다! 고생하셨습니다!!

바로 다음 캐릭터 작업으로 넘어가기 전에 배경과 마마고 같은 캐릭터를 먼저 보는 것도 좋을 것 같아요! 배경이랑 캐릭터 배치도 인게임으로 보고 결정해도 좋을 것 같고, 마마고 같은 캐릭터가 해당 그림체로 그려졌을 모습을 먼저 보고 방향을 잡는 것도 좋을 것 같습니다.

**Comment by wooyn730** [comment]
느낌 정말정말 좋은데요? (요즘말로 느좋 ...)
완전 제 취향입니다 ^_^b

앞으로 여러 리소스가 필요할 테니 이 정도 퀄리티면 시간이 얼마나 걸리는지 궁금하네요?
(새 캐릭터를 그릴 때와 캐릭터 표정만 바꿀 때)

라플리에 대해서는... 저는 조금 더 기존 기획을 반영했으면 좋겠습니다!
좀 더 키가 작고, 어깨가 좁고, 볼살이 있는 느낌으로 그려졌으면 합니다.
(지금의 라플리는 너무 멋있고 잘생겨서 오히려 안된다고 생각..ㅎㅎ)

유저가 플레이하는 게임 주인공이 중성적으로 그려졌을 때의 효과에는 여러가지가 있다고 생각하는데,
(유저들이 더 쉽게 이입 가능, NPC들이 라플리를 여자or남자로 착각해서 하는 다양한 대사나 행동에서 오는 재미 등)
특히 Grayed Game에서의 라플리는 자아가 없는 수동적인 존재이며 유저와 Grayed Game을 이어주는? 존재라고 생각하기 때문에
성격을 최대한 죽이고 중성적으로 보여졌으면 합니다.
(자아 없음 => 말이 없음이니 소심한 성격 정도는 어울린다고 생각)

**Comment by Songkihwa** [comment]
헉 지금 라플리 너무 좋네요!
미연시+요즘 느낌도 낭낭한 것 같구 전 지금도 충분히 중성적인 느낌도 나서 좋은 것 같아요 
잘생쁨이 공존해서 좋네요 ㅎㅎ
작업하시느라 고생하셨습니다 ><!!

**Comment by JIJI037** [comment]
> 느낌 정말정말 좋은데요? (요즘말로 느좋 ...) 완전 제 취향입니다 ^_^b
> 
> 앞으로 여러 리소스가 필요할 테니 이 정도 퀄리티면 시간이 얼마나 걸리는지 궁금하네요? (새 캐릭터를 그릴 때와 캐릭터 표정만 바꿀 때)
> 
> 라플리에 대해서는... 저는 조금 더 기존 기획을 반영했으면 좋겠습니다! 좀 더 키가 작고, 어깨가 좁고, 볼살이 있는 느낌으로 그려졌으면 합니다. (지금의 라플리는 너무 멋있고 잘생겨서 오히려 안된다고 생각..ㅎㅎ)
> 
> 유저가 플레이하는 게임 주인공이 중성적으로 그려졌을 때의 효과에는 여러가지가 있다고 생각하는데, (유저들이 더 쉽게 이입 가능, NPC들이 라플리를 여자or남자로 착각해서 하는 다양한 대사나 행동에서 오는 재미 등) 특히 Grayed Game에서의 라플리는 자아가 없는 수동적인 존재이며 유저와 Grayed Game을 이어주는? 존재라고 생각하기 때문에 성격을 최대한 죽이고 중성적으로 보여졌으면 합니다. (자아 없음 => 말이 없음이니 소심한 성격 정도는 어울린다고 생각)

이 퀄리티 그대로 간다면 기본 스탠딩의 경우 2~3일 정도 걸릴 거 같고 표정 변경은 기본 스탠딩의 얼굴 부분만 고치면 되는 사항이라 오래 걸리진 않습니다

사실 묘사 전이면 수정이 가능한 사항이지만... 묘사 후라 지우고 다시 하기 좀.. 어렵습니다ㅜ 그리고 청소년기의 데포르메는 이 정도면 적당하다 생각해 다른 분들의 의견도 괜찮다 하시면 이대로 유지하되, 다음 작업부터는 묘사 전 선화로 먼저 보여드리고 피드백 받은 후 수용되었다면 묘사로 넘어가 최종 완료하는 게 좋을 거 같다는 의견입니다... (저도 편하고 다른 분들도 편할 듯 합니다)

**Comment by wooyn730** [comment]
일단 가장 오른쪽 알투몬은 변경 전 기존의 알투몬이고, 왼쪽이 현재입니다!
원래 저렇게 뚱이집(?)처럼 생겼었는데 너무 못생겨서 수정을 요청해 지금의 모습이 되었습니다...

러프에 다리도 대충이라도 그려주시면 좀 더 보기 좋을 것 같아요
![gdgdgd](https://github.com/user-attachments/assets/6fdacb60-659d-4332-9043-d869dfdbd17b)
![fjvm](https://github.com/user-attachments/assets/22d1317e-500a-43d5-b01e-c8c8a1a6d395)

알투몬이 키가 작긴 한데 게임적 허용이 있더라도 몸통(상체?)이 좀 더 길게 그려지면 좋을 것 같습니다
(가랑이는 안 보였으면 좋겠다 정도..? 그냥 취향일지도)

라플리는 수정된 거 더 앳된 느낌이 보여서 좋고, 캐릭터들 묶어서 러프 주신 것도 좋네요!!!
주관적이지만 라플리는 좀 더 곧게 서있으면 좋겠다는 생각...

**Comment by wooyn730** [comment]
지은님 완성본 구드에 올려주시고,
캐릭터들 사이즈 가로 세로 각각 4의 배수가 되게 맞춰주세요!
(유니티 내 기본 압축이 4x4 블록을 기준으로 하기 때문에 4의 배수가 아니면 경고가 뜨네요)
