### ISSUE TITLE
온라인 단체 인터뷰, 2024-09-08 [21:00] 

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/Grayed-Game#646]
# 온라인 단체 인터뷰, 2024-09-08 [21:00] 

## 목차
개인 인터뷰를 제외하고 모든 작업자가 팀, 게임에 대해서 이야기 합니다.

- 버닝비버 출품 관련
- 타겟 유저층
- 게임 방향성
- 팀 활동에 대한 이야기(10월 워크숍, 대면, 온라인 게임 등)
- 협업 관련 제안?
- 솔직한 이야기?!
- 팀원에게 하고 싶은 이야기?
- ETC

### 충청권 인디게임 공모전 <인디유>
지원하기로 함
보민님이 대표 ^_^~

### 버닝비버 전시
전시 11/29~12/1 DDP에서
도전~~

### 타겟층 & 방향성

정안) 장르를 많이 타는 것 같다
스토리겜이다

우연) 아직은 스토리가 많이 안나와서 세계관과 시스템에 호기심을 가지시는 분들이 많은 듯

정안) 세계관도 스토리, 떡밥을 던진다

수민) 스토리 좋아하면 컨트롤 빡센 겜 안좋아하니 
앞으로 밸런스를 잘 생각해야 할 듯...

정안) 장르에 대한 깊이보다 장르 간의 결합이 중요
번역팩 부분이 잘 비튼 것 같아서 앞으로 만드는 건 그렇게 색 확실했으면 좋겠다
GG 만의 오리지널 비틈

수민) 장르 고유의 재미보다 장르 결합의 재미를 살리라는 말이죠?

정안) 그쵸그쵸

수민) 고려해서 장르선정 하겠다...

정안) 방향성 이야기하면, 스토리 깊게 가져가고
시스템은 게임을 지루하지 않게 하는 도구나 장치의 역할?

수민) 고민중인게 챕터2에 서브 하나 더 넣을지말지 고민

정안) 챕터1 장르 많다는 부정적인 피드백 있었음 (난잡)

수민) 챕터2 안넣으려고 했는데 너무 미연시 느낌이 날까함

정안) 챕터2가 길어지면 그거에 대한 것이 해소되지 않을까

수민) 챕터2 예상 분량?
수빈) 최소 40분 생각함

정안) 저번에 말한 창고(인벤토리)도 괜찮다고 생각

수민) 좋은데 장르 결합 중에 흔한 느낌

정안) 그쵸 백팩히어로때문에

수민) 그 시스템 좋아하는데 새로운 느낌은 없을 듯

우연) 챕터2는 기니까 챕터1과 같은 개수의 시스템을 가져가도 덜 난잡하고 안정적이지 않을까...

정안) TCG, 인벤토리 같이 가져가는게 난잡할 것 같다는 생각이 들었는데 하나씩 하다 갈아끼면 괜찮을듯

기화) 챕터2 기니까 챕터1에서 느낀 당황스러움은 없지 않을까
정안) 아무래도..

수민) 바에 길이 나오고 접속게임 3번 들어가고... 봐야 알 듯

### 팀 활동

시험기간 피해서 10월 막주쯤 워크샵?
26~27

현정) 토일만 되면....

차 한대 빌려서 + 기화차 해서 차타고? ^_^

9월 30일에 한 번 더 이야기

9월말 ~ 10월 초에 간단하게 만나서 밥이라도 먹자..

10월 6일 (일)

**결론**
10/6 일요일 간단 저녁먹고 놀기
11/2~11/3 주말 워크숍

### 게임 후보

갈틱폰 -> 구스구스덕 -> 롤토체스

(롤토체스 모바일, PC?)
처음할 때는 모바일이 어려울 수 있다
롤을 까는 거임 (그 안에 있는거임)

### 협업 제안
(우연이 정안님 이메일 넘김 ㅈㅅ)
뭐하자는 건지 잘 모르겠다
아직은 이르다

### 솔직한 이야기

개인인터뷰 오실 때 할 이야기 준비하기
주고싶은 피드백이나 ... 정안님도 준비해갈거임..

우연) 인디게임에 대한 각자의 가치관을 물어보고 싶긴 했는데 오늘은 시간이 짧음 ㅎㅎ 다음에 대면으로 만나서 이야기하면 좋을 듯

앞으로 단체 인터뷰는 우리 대면 만남의 앞부분에 낄 것 같다

기화) 개강하고 영화작품 끝냈고 새로 영화 들어오고 애니메이션도 하고
수민이 게임팀에도 들어갔고 학교다니고 공강 없고 ....

정안) 대학 졸업 못할 뻔했는데 천사 만나서 하게된 이야기

보민) 복전 잘못 선택해서 학교 5년 다님..

수민) 데이터전공 복전했다가 심화로 돌아옴
교양 8학점 초과.... 1년남았는데 풀학점으로 들었는데...... 
이번학기 졸업하시는분 많겠네여

수빈) 저는 막학긴데 몰라요
자격증 해야하는데...... 2개 필요하다는 썰이 들림

우연) 얼마 전에 졸업해서 진짜 백수됨...

현정) 공연 와주셔서 감사
연말에 공연 또 있긴 한데 그전까진 연습 안해도 됨

기화) 인터뷰 왜 취재하냐고 물어봤더니 자기는 C자 들어간 CEO 이런 사람들만 만나니까 학생들도 만나서 동향을 파악하고 싶었다고 함
게임에 도움될 이야기 많이 해주셨다 함
집갔는데도 게임 관련된 것도 많이 보내주심
인터뷰 내용은 사적인 거 많고 게임 토크 마니함
좋은일있으면 메일로 알려달라구 함
서울오면 밥사주신다고도 함

정안) 블로그 글도 감동이었음
하나 더 올라옴

기화)
공모전 심사위원은 플레이 잘 안하고
플레이영상이랑 서류 잘 써야 한다고 함
취업 목표여도 게임 출시 여부가 영향을 미침

우연) wasd 각 10명씩 다단계처럼 홍보하자

**Comment by wooyn730** [comment]
고생하셨습니다~~

이야기하면서 최대한 기록해 놓으려고 했는데 왜곡이 있을 수 있음
수정 환영 ㅎㅎ
