### ISSUE TITLE
[Char] 럭키 스프라이트 작업

### ISSUE THREAD

**Issue by vprwolf** [GG-Studio-990001/Grayed-Game#647]
**2023.09.05**
### **기획 읽어보면서 생각한 점**
-럭키 설정을 읽다 보니 조력자적 성향에서 인디고 파크의 '램블리'가 생각났고, 어두운 뒷면(?)을 가진 면에서 언더테일의 '플라위'가 생각났습니당. 
인디고파크 램블리: https://www.youtube.com/watch?v=TYfpwwFiSPk
언더테일 플라위: https://www.youtube.com/watch?v=O6RNVHQOjJ8

- 한번 다른 느낌으로 럭키를 뽑아보려는 시도로.. 위 두 캐릭터(램블리, 플라위)를 참고해 봤을 때.
플레이어와 가까운 거리에서 조력자 역할을 한다는 공통점이 있었고, 플레이어와 감정적 거리 또한 가까운 느낌이었어요. 
그만큼 캐릭터의 감정 전달도 중요한 부분으로 작용된다고 생각했습니다.

-또 감정하면 표정에서 보이는 것이 직관적인데, 램블리/플라위 또한 표정이 꽤 풍부하더라구요..!
기존 럭키와 다른 설정으로 생각해봤는데, 움직임 표현이 어려운 전신 대신,
얼굴을 중점적으로 감정을 전달하는 방식은 어떨까 하고 다른 럭키 시안을 생각해봤습니다.
(한번 기획을 읽어보면서 생각한거라... 한번 제안해봅니다! 기존 럭키로 진행해야 할 작업도 병행할 예정입니다!)

![럭키구상](https://github.com/user-attachments/assets/158d00d5-bb15-4cde-be2d-e530ddc4e871)
컬러도 갈색럭키/검정럭키 두가지가 있던 것 같은데,
평소에는 갈색이었다가 흑화할 때 검정으로 변하면 어떨까...도 생각해봤습니다.

![럭키구상02](https://github.com/user-attachments/assets/ce0ee429-8e5e-41f6-b750-6800049f150f)
가능하다면 버튜버 표정리깅하는 것처럼 표정범위 내에서 움직임을 넣는건 어떨까 합니다

만약 인게임에서 본다면 이런 느낌이겠네요.
![Lucky02](https://github.com/user-attachments/assets/e4cb6e44-39b0-4280-9857-f90aa979f90f)

-----------------------------------------

**2023.09.07**
### **Idle 예시**
위 설정으로 idle부분을 간단히 만들어봤습니다

https://github.com/user-attachments/assets/806afdec-bb50-4b77-b29d-632789afc25c

인게임에서는 이런느낌일 것 같습니다.

https://github.com/user-attachments/assets/035ba9b7-a2f8-4de8-9dc7-ca2735d4faf6

**Comment by wooyn730** [comment]
[럭키 스프라이트 폴더](https://drive.google.com/drive/folders/1hozMbw0V2MmUbt_LXK9i5ZBUPZ6XnYl8)
=> 원본 획득하면 따로 드리겠습니다

[럭키 캐릭터 설정 (아래)](https://drive.google.com/file/d/1i7P1LfC8UfYQ-Jtf8zyyejerkKHVnUew/view?usp=sharing)
=> 가볍게 읽어보시고 외형은 '열쇠가 달린 목줄을 찬 강아지' 정도만 참고해주세요!

[럭키 초기 설정](https://drive.google.com/file/d/1jrROe19BBoFIMRs899jdWlpLlME4jbit/view?usp=sharing)
=> 럭키가 나온 바탕이 되는 기획인데 가볍게 읽어보셔도 좋을 것 같아요!

++
아까 말씀 드린대로 다양한 개선안 제안, 리깅 공부 등 환영입니다 ^_^

**Comment by roweclaw** [comment]
- #648

캐릭터 설정 문서 업데이트 되었습니다!!

**Comment by wooyn730** [comment]
[럭키 psd 파일과 파츠](https://drive.google.com/drive/folders/1zQNmSEiOSpruOPPFBmq5njBv1RlhM73K) 전달드립니다

**Comment by vprwolf** [comment]
앗 제가 월/화가 조금 바빴어서 드라이브를 지금 확인했는데, 제 계정이 엑세스 거부가 돼서 ㅠ 엑세스 허용 부탁드립니다!

**Comment by wooyn730** [comment]
@fkdl0048

**Comment by vprwolf** [comment]
사실 럭키는 처음 받았을 때 한번 새로운 대안 내보는 것도 어떤지 제안도 받은 바 있어서 냈던것이고,
기존 럭키가 낫다하면 에셋만 잘 살아 있을경우 이전 시안으로 계속 진행하는 것도 저는 좋다 생각합니다!
사실 저는 어느쪽이든 상관 없어서 종합적으로 결정만 내려주시면 될 것 같습니다!
스파인의 경우는 50만원 정도 되는 프로그램이라 좀 고려를 해야할 것 같습니다 :)
비용 지원을 받기 어려울 경우 좀 진행이 어려울 것 같습니다:)

**Comment by wooyn730** [comment]
보민님이 내주신 대안도 정말 좋았고, 회의 때 나눈 이야기는 '기존 럭키가 새 럭키보다 낫다'와는 거리가 많이 멉니다.
회의 때 어떠한 결론을 내리지는 않았고 보민님의 의견을 들어보자는 것으로 마무리가 되었습니다.
많은 의견이 오간걸 급하게 적은 글로 보여드려 오해를 하시거나 기분이 상하시진 않을까 걱정이 되네요..ㅠㅠ

정리해보자면 _(제 개인적인 생각에 근거하여..)_
보민님의 자유로운 해석이 들어가는 것은 좋으나 (정말)
기존에 전시 경험들을 통해 럭키가 가진 매력을 검증했다고 생각하여
그 매력을 최대한 유지하는 방안으로 보민님이 절충안을 내주시면 좋겠다는 것입니다.
(매력: 오피스 길잡이st, 몸통과 팔다리의 존재, 귀여움, 친근함, BGM과의 어울림)

근데 저는 몸통yes파이고 갈렸던 의견 중 하나라서 제 코멘트가 팀의 전체 의견이나 결론이 아닌 걸 알아주시구... (중요)
암튼 다양한 대안을 러프하게 주시면 좋을 것 같아요
럭키가 굉장히 중요한 캐릭터이다보니 신중할, 고민할 가치가 있다고 생각합니다.. 🥹

**Comment by vprwolf** [comment]
절충안..도 낼 수 있다면 좋지만
이미 기존 럭키가 어느정도 인지도가 보장된 상태에서는
기존 럭키 에셋을 유지하는 것이 좋지 않을까 생각합니다..ㅠ
일단 
1.비용적인 면을 고려한다면 뉴럭키쪽
2.인지도 측면을 고려하면 에셋 조정기간을 조금 마련한 후 기존 럭키 유지하기
이 두 방향성 중 하나로 이어가는 것으로 생각하고 있는데
사실 또 새로운 시안을 내는 것도 모든 사람의 만족을 가져오긴 어려울 것 같아,
방향성을 고려해 둘 중 하나의 방식으로 이어가는 것이 낫지 않을까 싶습니다!

**Comment by Songkihwa** [comment]
먼저 앞에 말했던 내용들이 보민님께 부담이 되셨을수도 있을 것 같아서 죄송합니다 .....ㅠ

기존 럭키 에셋..? 이라면 전 럭키를 그대로 쓴다는 말씀이 맞을까요?! 
아니면 기존 럭키를 보민님이 다시 그린다는 말씀이실까요?!

그대로 사용하진 못하는 상황인걸로 알아서

저는 조정 기간을 마련해서 기존 느낌을 살려서 보민님이 디자인해주시면 좋을 것 같다는 생각이 드는데
이거 자체가 부담이라는 거 알아서 정말 정말 죄송합니다 .... ㅠㅠ 
모두가 만족할 수 없음을 압니다! 전 럭키도 사실 모두가 마음에 들어했던 디자인이 아니였구요 

제 생각에는 전 럭키의 반응이 좋았던 이유가 럭키 기획의 중점이였던 튜토리얼 역의 윈도우 도우미 느낌 + 유저들의 입장에서 볼 때의 귀여움 (하찮고 단순한 느낌의 그림체여서 일 수도 있지만) 이였다고 생각이 듭니다. 그래서 이런 좋았던 점들은 가져갔으면 해서 이런 얘기를 꺼낸거구요....
(저도 얘기 꺼내기가 쉽지 않았습니다 . . . )

보민님이 새로 그려주신 럭키도 너무 좋았지만!! <<< 정말이에요 ㅠㅠ
전에 느꼈던 좋은 점들이 계속 아른아른 생각이 나서 아쉬움에 의견을 드립니다.. ㅠㅠ 

지금 뉴럭키도 좋지만 뉴럭키로 진행한다면 몸통이 없다보니 지금 디자인에서 조금 더 단순한?! 그림체면 좋을 것 같습니다!!
다시 디자인하신다면 기존 레퍼런스 느낌처럼 진행되면 좋을 것 같습니다.

자세한 사항은 기획자분들과 디렉터님과 소통하실거고
어디까지나 그냥 다 제 생각이고.. 의견이기 때문에!!! 듣고 그냥 넘기셔도 좋아요!!!!

괜히 제가 힘들게 한 것 같아서 죄송하네요..
아무튼 죄송합니다 ...ㅠㅠ
