### ISSUE TITLE
[CH1] 오프닝 기획

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/Grayed-Game#652]
- 지은님과 회의 후 상세 기획서 작성
- #653 회의 진행 완료! 회의록 확인해주세요

----
[오프닝 스토리 보드](https://drive.google.com/file/d/1LW16bP60gUfUjp_xZrONsRHj4ONs5iSE/view?usp=sharing) 작성했습니다.

고민 중인 내용 : 언제 타이틀 BGM에서 플로야드 BGM으로 변경할까? 
*0.07에선 럭키 BGM이 나옵니다.

1. 0.01 이후
2. 0.04 이후
3. 플로야드 진입 (0.08 이후)

**Comment by Songkihwa** [comment]
작업 하시느라 고생하셨습니다!

0.05에 플로야드 비지엠 나오면 바로 럭키 비지엠이 나오게 되니
일단은 0.01이나 0.08 이후가 좋을 듯 합니다.

사실 지금 타이틀 BGM이 타이틀에 어울리게만 제작되가지고 좀 무겁고 판타지스러운 느낌이 강하기도 해서
게임 쓰레기 산 일러스트 나온 거에 BGM 올려보고 결정하는게 좋을 것 같습니닷ㅎㅎ

**Comment by wooyn730** [comment]
ㅋㅋㅋㅋ 저 스토리 보드에 맵 그린거 귀엽네요 취저임
떨어지는 거 구체화, 팩맘과 럭키의 분리 부분 좋네요

근데 이후에 기존 진행과 동일하게 하기에는 라플리가 이미 깨어있어서 바뀌어야 하지 않나요?
그리고 파머가 색 있는 거 만지지 말라고 하는 것도 이미 만졌으니까 수정해야하나..?

브금은 저도 일단 쓰레기산 일러스트에 올려보는 의견에 동의하고,
오프닝 씬1은 타이틀 브금, 오프닝 씬2는 엠비언스? 공간감?만 따로 넣는 것도 괜찮을 것 같아요 (럭키 앞뒤 연출을 짧게 가져간다면)

**Comment by roweclaw** [comment]
스토리 보드로 보니까 잘 이해가 되네요! 리소스들 사이에서 라플리 엎어져 있는 거 너무 귀엽네요 ㅎㅎ

저도 플로야드 bgm은 0.08이후가 나을 것 같은데, 우선 타이틀 bgm 올려보고 결정하면 될 것 같습니다~!

우연님이 말씀하신 기존 진행 수정사항에서는 라플리 깨우는 부분 대사 내용 삭제 정도가 해당될 것 같아요
색깔 만지는 거는 말해도 괜찮지 않을까요? npc는 라플리가 색깔 만진 거를 모르기도 하고 팩맘 유도도 쉽고...?

**Comment by fkdl0048** [comment]
의도 3가지가 정말 중요한 포인트라고 생각됩니다! 잘 짚어주신 것 같아서 좋습니다.

조금 고민이 있는 부분은 자동진행부분으로 현재 연출에서도 라플리는 유저가 조정하기에 움직이지 않지만, 현재 버전에선 라플리가 걸어다니는 부분이 조금 걸리네요.. 메타적인 느낌이 빠질 수 있겠다는 생각이 듭니다.
