### ISSUE TITLE
[CH1] 대사 스크립트 추가 작성

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#654]
- [x] slg 럭키 대사에 '화살표' 내용 추가
- [x] 마마고 대사로 '번역탭 강매' 내용 작성
- [x] 럭키 대사로 '번역팩 장착' 내용 작성
- [x] R2-Mon 대사로 '놀란 반응' 내용 작성

---

title: LuckySlg
```
럭키: 와아- <bounce>건설</bounce>할 시간이다!
럭키: 근데 이거이거<br>모아둔 자원도 없고
럭키: 멍 때렸구만!
럭키: 그럴 줄 알고 가져왔지

// 마우스 커서가 화면 중앙에 나타남
럭키: 어때, 간지나지?
럭키: 지금 목재나 석재<br>하나 <bounce>클릭</bounce>해 봐

// 유저 클릭 인식 (목재 또는 석재)
럭키: 좋아, 그렇게 모으면 돼
럭키: 왼쪽 아래에 있는<br>탭도 눌러봐

// 유저 클릭 인식 (건설탭)
럭키: 그걸로 개수랑 방향<br>알 수 있대
럭키: 아, <bounce>코인</bounce>은 부족하면<br>다시 팩맘으로 가면 돼
럭키: 그럼 뚝딱뚝딱 잘 해보라구~
```

title: Mamago2
```
// 시점: 컷씬 5.1
// 상황: 건물 내부에서 마마고의 감사인사 및 번역기 강매

마마고: 우리 건물을 다시 지어 준 은인!<br>웰컴이에요~
마마고: 감사의 의미로 방금 막 완성한<br>'기계어 번역팩'을 드릴게요!

// 획득 모션 자동 재생
: '기계어 번역팩'을 획득했다.

마마고: 이런, 베리베리 중요한 사실을<br>말씀 안 드렸네요.
마마고: 번역팩을 사용하려면 저희 마마고 컴퍼니에서만<br>단독 판매하는 '마마고 번역기'가 필요하답니다!
마마고: 우리 은인한테는 스페셜하게 초특가로<br>모실 테니 어서 구매하세요~
```

title: Mamago3
```
// 상황: 마마고 번역기 구입 후 반복 출력 대사

마마고: 앞으로 모르는 언어를 번역하고 싶다면<br>저희 마마고 컴퍼니를 꼭 찾아주세요~
마마고: 그럼 다시 만날 때까지, 굿바이!
```

title: LuckyTranslation
- 새로 작성한 대사라 [파일](https://drive.google.com/file/d/1w2A6cWIaCQg3cu8vmdcx0AESlGN8PM_E/view?usp=sharing) 올립니다!
```
// 시점 : 컷씬 5.2
// 상황 : 럭키의 번역탭, 번역팩 튜토리얼

럭키: 하이~ 내 도움 필요하지?
럭키: 번역팩을 설정 방법은<br>ESC로 설정창 켜기!
럭키: 완전 두말하면 잔소리라구<br>빨리 해 봐

// 유저 클릭 인식 (설정창)
럭키: 여기서 '번역'탭을 눌러봐

// 유저 클릭 인식 (번역탭)
럭키: 이제 버튼을 눌러서<br>활성화 하면 끝!

// 유저 클릭 인식 (기계어 번역팩 활성화)
럭키: 앞으로 기계의 언어가<br>자동으로 번역된대
럭키: 그럼 럭키는 이만~
```

title: R2_Mon4
```
R2-Mon: ...왜 날 쳐다보지...?
R2-Mon: 설마... 내 말을... 알아듣나...요...?
R2-Mon: 그, 그럴 리가 없을 텐데...
R2-Mon: 저기, 혹시, 정말, 진짜,<br>내 말을 알아듣는다면
R2-Mon: 나한테 <bounce>한 번 더</bounce> 말을 걸어봐...요...!
```

title: R2_Mon5
```
// 다시 말을 걸었을 때
R2-Mon: 내 말을... 진짜 알아들었어...요...?
R2-Mon: ... ... ...
<<NpcJump 2>>
R2-Mon: <shake>!!! 뭐야 !!!</shake>
// 마을 안으로 도망가면서 비주얼노벨팩을 흘린다.
```

**Comment by wooyn730** [comment]
> 럭키: 근데 이거이거 모아둔 자원도 없고
럭키: 멍 때렸구만!
럭키: 그럴 줄 알고 가져왔지

좀 재수없어 보인다는 위험성이 있지 않을까.. (ㅎㅎ ㅈㅅ 전 좀 재섭네요 챕터1까지는 귀요미&도우미 느낌만 있어도 되지 않을까)

<br>

> 럭키: 아, <bounce>코인</bounce>은 부족하면<br>다시 팩맘으로 가면 돼

이거는 저번에도 말씀드리긴 했는데 이 대사에 대해서는 이런 생각을 가지고 있습니다.

1. 건설 시 필요한 것은 '코인'이 아닌 '시간'이 메인이고 코인은 시간을 단축시킬 수 있는 재화라고 생각함
1-1. 따라서 코인에 대해 돌려서 말하거나, `시간은 코인이다! 앗, 시간은 금이다였나?` 같은 대사를 추가하면 자연스러울 것 같음
1-2. 건설에 코인이 필요하다는 것은 개발자적 마인드라고 생각함 (그게 가장 빠른 길은 맞지만)
2. 현재는 요구되는 코인 수를 확 줄였기 때문에 이제는 꼭 필요한 대사가 아닌 것 같기도 함

**Comment by roweclaw** [comment]
### SLG

> 좀 재수없어 보인다는 위험성이 있지 않을까.. (ㅎㅎ ㅈㅅ 전 좀 재섭네요 챕터1까지는 귀요미&도우미 느낌만 있어도 되지 않을까)

재수없을 거라는 생각은 못했는데 다시 보니까 그렇게 느낄 수도 있을 것 같네요!ㅋㅋㅋㅋ 수정하겠습니다~

> 1-1. 따라서 코인에 대해 돌려서 말하거나, 시간은 코인이다! 앗, 시간은 금이다였나? 같은 대사를 추가하면 자연스러울 것 같음

저는 오히려 이런 대사를 넣는 게 좀 부자연스럽다고 생각이 들어서 기존 대사를 고수했던 것 같습니다.
현재 럭키의 상호작용 느낌을 강화하기 위해서 상세 정보를 하나하나 알려주는 느낌이 강한데
`시간이 금이다` 라는 은유가 갑자기 뜬구름 잡는 소리처럼 들릴 것 같다고 생각했었네요.

>1-2. 건설에 코인이 필요하다는 것은 개발자적 마인드라고 생각함 (그게 가장 빠른 길은 맞지만)
> 2. 현재는 요구되는 코인 수를 확 줄였기 때문에 이제는 꼭 필요한 대사가 아닌 것 같기도 함

근데 짚어주신 부분에서 너무 개발자적 시선이 포함된 대사였음을 깨닫고 피드백을 수용하고 싶은데요!!
`시간이 금이다` 와 같은 대사가 말미에 나와도 어울릴지? 아니면 팩맘을 무조건 다시 할 필요가 없으니 아예 삭제를 할지?
2가지 중에 고민이 되는데 일단 수정해서 작성해올 테니 괜찮은지 확인 후 결정하는 걸로 하면 좋을 것 같네요~

### 번역팩
> 번역을 키는 난이도에 비해 친절함의 정도가 너무 강하지 않나 라는 생각...
(특히 팩맘과 비교하면 더)

![스크린샷 2024-09-18 214930](https://github.com/user-attachments/assets/698bd665-d4e7-4f38-9de7-5c12e26e83f9)

기획서를 참고해서 상호작용을 하는 과정으로 작성해본 거긴 합니다만 그래도 너무 친절할까요?
팩맘은 팩맨의 패러디로써 이미지도 친숙하고 럭키와 상호작용을 할 수 있는 부분이 없어서 일방적으로 진행되고 있는데,
이와 달리 번역팩은 난이도는 단순하지만 그 개념은 생소할 것 같아서 현재 정도의 친절함을 가져가면 좋을 것 같다는 생각이긴 합니다.!!

**Comment by roweclaw** [comment]
수정할 대사

- [ ] title: LuckySlg

**Comment by wooyn730** [comment]
> 일단 수정해서 작성해올 테니 괜찮은지 확인 후 결정하는 걸로 하면 좋을 것 같네요~

확인이요!
`시간이 금이다` 같은 비유는 1번의 이유로 말씀 드렸던 거긴 한데 (저 비유가 아니더라도 시간을 먼저 짚어줘야 한다고 생각)
아무튼 지금은 대사 삭제에 조금 더 마음이 가네요~~

> 개발자적 시선

팩맘 수정 전 설명 때에도, 팩맘을 잡으라고 설명 넣는 것을 꺼렸던 이유도 같았습니다.
잡으면 가장 빠르게 이길 수 있지만 실제로는 그냥 피해서 열심히 코인을 먹거나, 타이머 종료 시 필드+라플리코인 > 팩맘코인이거나의 승리 조건도 있었으니까요.
(제가 그저 디테일충인 걸지도 ㅋㅋㅎㅎㅎ)

> 번역팩은 난이도는 단순하지만 그 개념은 생소할 것 같아서

이해했습니다! 맞는 말 같네요
아시겠지만 저는 제 의견도 미래의 제가 반려하기도 하기 때문에 (e.g., 먼지 콜록)
근거와 함께 주장해주시는 것 너무 좋습니다 ^_^ b

**Comment by wooyn730** [comment]
적용 완료
