### ISSUE TITLE
웜홀 및 엔딩 정리 문서화

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#662]
- #659 에서 논의한 웜홀 설정 및 엔딩 관련 내용을 문서로 정리합니다.

[[240915] 웜홀 및 엔딩 정리](https://drive.google.com/file/d/1UeB8jtGlFmbHSrRurAMrx-Hk-Vx-VJj_/view?usp=sharing)

문서 작업 완료 했습니다. 다가올 정기 회의 때 이 문서를 기반으로 자세하게 설명 드릴 예정인데요
혹시 그 전에 질문 있으시면 코멘트 달아주세요!
@fkdl0048 @Sumindd 정안님, 수민님은 정기 회의 전까지 한 번 읽어보시고 오류 없는지 확인 부탁드립니다~!

**Comment by fkdl0048** [comment]
확인했습니다. 이 내용은 이번 회의 때 시간을 많이 쓰더라도 한번 팀원들이 모두 이해하고 넘어가야 할 것 같습니다.

- #674

가능하다면 키워드나 문장으로 게임을 좀 더 설명할 수 있으면 좋을 것 같다는 생각도 듭니다. (수동적, 잊힘, 게임 등등 메시지)

웜홀에 대한 설정도 결국엔 게임에 존재하는 설정 정도로 보여줘도 좋을 것 같다는 생각입니다.

> 이로 인해 GG 는 메타게임인 척하는 게임이 된다. 메타게임도 게임이라는 맥락.

사실 적은 내용은 이미 수빈님이 다 적어주셔서 팀원들과 질문 형식으로 시간을 가지면 좋을 것 같습니다.
