### ISSUE TITLE
[CH1] SLG 마마고 컴퍼니 건설 단계 대사 추가

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/Grayed-Game#665]
# [CH1] SLG 마마고 컴퍼니 건설 단계 대사 추가

- #661 
- 소라고동에서 선정된 안건으로 마마고 컴퍼니 건설 단계에 상호작용 시 대사 추가

*건살 단계의 스프라이트 기획은 @Sumindd 님이 기획서로 올려주실 내용입니다.*

작업자 @wooyn730 @roweclaw 두 분이서 수정사항 확인하시고 작업하시면 됩니다.

**Comment by roweclaw** [comment]
대사 작업 되었고, `Object.yarn` 파일에 추가 부탁드립니다.

- 건설 전인 마마고 컴퍼니 부지 상호작용시 출력 대사

```
title: MamagoCompany1
---
     :무너져 내린 마마고 컴퍼니의 흔적이다.
===
```

- 건설 중간 단계인 마마고 컴퍼니 부지 상호작용시 출력 대사

```
title: MamagoCompany2
---
     :마마고 컴퍼니가 다시 지어지는 중이다.
===
```

**Comment by wooyn730** [comment]
@jeongopo 

Object.yarn 파일 하단에 대사만 넣어두었습니다
작업하려고 했는데 생각해보니 건설 단계랑 연관 있어서 현정님이 해주시는 게 좋을 것 같습니다. (〃^▽^〃)ゝ

**Comment by jeongopo** [comment]
으음 이거 대사 추가하려고보니까 건설단계 수정해야할것같아서 규모가 생각보다 커집니다
오브젝트 한개라서 기존 오브젝트 처리방식처럼 이름가지고 제어할수도없어서
건설전 건설중 오브젝트 분리해서 작업할까싶은데 .. 🤔 그럼 오브젝트관리 코드도 다 바꿔야할것같습니다,,
(누가 코드를 이렇게 더럽게 짜놨을까요.. 😔접니다,,)

20일 이후에 건설단계 수정할때 한번에 수정하는게나을것같은디 그때 같이 작업해도되나용?

**Comment by fkdl0048** [comment]
네네 확인했습니다!

**Comment by jeongopo** [comment]
241110 기준 작업되어있습니다.
내일 테스트 후 이슈 닫겠습니다
