### ISSUE TITLE
[CH1] 다리 건설 자재 수정

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/Grayed-Game#666]
# [CH1] 다리 건설 자재 수정

- #661 
- 소라고동 선정 안건으로 건설 자재 수정 및 대사 수정

> 참고로 맵3에서 파머 상호작용 대사가 '헛둘헛둘'인데 이것도 수정되면 좋겠네요. (원래는 땅을 판다는 컨셉이었던걸로 기억...)
추가로 다리짓기도 약간의 시간 또는 코인을 요구하는 것,
다리짓기 시 목재 20에 철 5 정도로 목재 위주로 요구하면 좀 더 현실적..?일 것 같네요
(나무다리니까)

위 내용에 맞게 건설 자재와 파머 대사 수정해주세요

*건설전 스프라이트는 기획서로 나올 예정입니다.*

- @wooyn730 @jeongopo @Sumindd @roweclaw  작업 확인해주시고 말씀해주세요

**Comment by jeongopo** [comment]
우선 리소스나 변경사항 다 17일밤까지는 나왔으면좋겠습니다~
18일 작업예정이고 19,20 작업불가입니다 (필요하면 시간 땡겨보겠지만요..)

**Comment by Sumindd** [comment]
건설 과정 스프라이트는 이번 버전에 들어가지 않을 것 같습니다. 일단 이번 버전엔 플로야드 석재 요구량과 마마고 번역기만 먼저 반영 부탁드려요!
![image](https://github.com/user-attachments/assets/bd8a2d4c-1c6a-49ac-9b50-654da6422932)

**Comment by jeongopo** [comment]
넵 오늘 수정해서 올리겠습니다~

**Comment by roweclaw** [comment]
파머 대사 수정본입니다~

- Farmer.yarn
```
title: Farmer2
// 시점: 컷씬 4.0
// 설명: 구덩이를 파는 파머
---
파머: 달러님은 구덩이를 파는 게 싫다고 하셨어...
파머: 하지만, 달러님이 없는 지금!<br>그 누구도 나에게 뭐라고 하지 않는 이 순간!
파머: 마음껏 파헤쳐서 구덩이 안에서도<br>좋은 물건을 발굴할 수 있다는 걸 증명하겠어.
파머: 라플리도 기대하라고. 파하핫!
<<NpcDialogueFin 1>>
===
```

**Comment by wooyn730** [comment]
> 파머 대사 수정본

적용완룡

**Comment by jeongopo** [comment]
이건 수정된것같은데 나중에 확인해보시면 이슈 닫아주세용

**Comment by jeongopo** [comment]
이것도 수정된것같아서 닫겠습니다
