### ISSUE TITLE
[CH1] 시스템 기획 수정 4차

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/Grayed-Game#668]
- #638 에 이어서 작업합니다.
- 오프닝 스토리 보드는 문서를 분리했기 때문에 관련 페이지 삭제
- SLG 관련 재화 수정 및 정리
- 건설 중간 단계 추가
- 컷씬 영화 프레임 기획

---

### 240918 업데이트
영화 프레임 어떤 연출이 좋은지 확인 한 번 부탁드립니다

1. 왼쪽에서 등장 - 오른쪽으로 퇴장
2. 위 아래에서 등장 - 위 아래로 퇴장 (영상에선 이상하게 갑자기 나타나는 것처럼 보이네요ㅠ 1번처럼 부드럽게 등장합니다..)
3. 페이드인 - 페이드 아웃

https://github.com/user-attachments/assets/19ae818e-de31-42f7-b4e4-f85a5897945d

[애니메이션 직접 확인 링크](https://docs.google.com/presentation/d/1pO6tA_5Jpt6jize8kS3lZm_xKvkn4x6uqghLCLQXQJA/edit?usp=sharing)
컷씬 영화 프레임 기획이 스크립트 박스를 어떻게 배치해야 할지.. 여러모로 좀 고민 되는 것들이 꽤 있어서 업로드가 조금 더 늦어질 것 같습니다..  

---

### 240920 업데이트
[[240920] CH1 기획 변경 사항](https://drive.google.com/file/d/1sWEgaJ4GjkUAeMpIe3Uz5vsN4zVBKMsd/view?usp=sharing)
(14 페이지 추가) SLG 관련 재화 수정 및 정리 
(15 페이지 추가) 건설 중간 단계 추가

**영화 프레임에 대해서** 
개인적으로 넣고 싶어서 저도 이것저것 레퍼런스도 찾아보고 고민해봤는데 결론은 Grayed Game엔 어울리지 않는다는 생각이 들었습니다. 물론 뒤쪽 챕터에서 넣자면 넣을 수 있겠지만 최소한 1챕터, 2챕터엔 넣기 힘들 것 같습니다.
영화 프레임 연출을 넣기 위해서는 UI는 기본적으로 전부 OFF 되어야 합니다. (스크립트 박스도 포함)
영화 자막처럼 스크립트를 띄우거나, 말풍선으로 스크립트를 띄워야 자연스럽고 이쁘게 영화 프레임이 적용될텐데 전자는 CH1 장르인 탑뷰 쯔꾸르에 어울리지 않고, 후자는 너무 쓸데 없이 많은 리소스 투자라고 생각이 듭니다(딱히 더 좋은 것 같지도 않음)
유일하게 자연스러울 것 같은 부분은 럭키 등장 컷씬인 것 같은데 (럭키는 말풍선을 사용하고 위치 이동이 자유로워서) 이것도 SLG 처럼 UI 활용 튜토리얼이 들어간다면 어려울 것 같습니다. 

이러한 이유로 제 개인적 판단 하에 작업 목록에서 제외했습니다..

**Comment by wooyn730** [comment]
### 3 Match에 대해

변경 적용된 부분 확인했고, 전시를 하면서 유저들이 헷갈리거나 불편했던 부분들이 잘 해소가 된 것 같습니다!

사소한 개인 취향으로는 피드백 2가지가 있습니다

![화면 캡처 2024-09-14 204552](https://github.com/user-attachments/assets/c9eca4a5-7783-44eb-becd-eae1fbab2afa)
원래 스테이지1을 꽉 채웠던 의도는 애니팡 같은 느낌을 주기 위함인데,
어차피 다른 스테이지에서 난이도 조절을 위해 빈 공간이 많이 생겼고
오히려 이제 비교해보니 스테이지1이 너무 꽉차 있어 답답한 느낌이 드네요
그래서 접근하지 못하는 부분에 빈 공간을 만들어두면 어떨까 합니다

<br>

![화면 캡처 2024-09-14 204747](https://github.com/user-attachments/assets/93c46955-c65a-44f7-8506-e80623097e2f)
여기는 길이가 쓸데없이 긴 느낌?
조금 줄여도 괜찮지 않을까 해요

**Comment by Sumindd** [comment]
일단 스테이지1은 노골적으로 정답을 알려주기 위해서(튜토리얼 맵이라) 딱 정답인 부분만 비워둔 의도가 있습니다! 
그리고 아래는 길게 느껴진다면 좀 줄여도 관계 없을 것 같습니다!

**Comment by Sumindd** [comment]
240918 업데이트
영화 프레임 어떤 연출이 좋은지 확인 한 번 부탁드립니다

**Comment by Sumindd** [comment]
아뇨 비율은 아직 안 정했습니다
보통 이런 식의 프레임이 중간에 들어가는 경우엔 하단 스크립트 박스가 안 떠서 아직 고민 중입니다...

**Comment by wooyn730** [comment]
대화창 하단의 세모 (컨티뉴 버튼?) 말씀하시는 건가요? 
프레임을 대화창 레이어 뒤에 배치하면 되지 않나여

**Comment by Sumindd** [comment]
아 아뇨 그냥 지금은 잘라 놓은 건데 대화창 자체가 지금 깔끔하게 안 가려지고 애매하고 못생기게 잘려서... 
비율이랑 이것저것 고민해봐야 할 듯요

**Comment by fkdl0048** [comment]
가장 자연스러울 것 같은건 아래에서 위로 올라오며 페이드효과를 주는게 자연스러울 것 같다는 생각이 듭니다!

**Comment by Songkihwa** [comment]
저도 2번 아니면 3번이 좋을 것 같습니다!

**Comment by Sumindd** [comment]
SLG UI는 제가 임시로 가려둔 거고.. 아마 실제론 UI OFF를 따로 설정해야 할 것 같아요
영화 화면 비율 쓰면 실제론 21:9 비율을 써서 이 정도 가려집니다!
![image](https://github.com/user-attachments/assets/1ae74241-90c8-4443-a656-bffbe4858fdc)
