### ISSUE TITLE
[CH1] 버닝비버

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#671]
## 작업

버닝비버(20일)까지 처리할 작업 모음

- ===**1차 (0914토)**===
- [x] SceneTransform 할당 문제 수정
- [x] 3 Match 럭키와 말풍선 위치 수정
- [x] 탈출 연출 이후 회색 선 지우기
   - 노트북으로 체크 필요
- [x] 대화창 폰트 사이즈 줄이기
   - 네임택 65->62 대사 35->33으로 우선 조금씩만 우정
- [x] 파머 맵3 상호작용 대사 추가
- [x] 팩맘 접속 연타 안되도록 수정
- ===**2차 (0915일)**===
- [x] 맵 교체
- [x] 럭키팩 획득 모션 추가
- [x] SLG팩 획득 모션 추가
- [x] 알투몬이 비주얼노벨팩 흘리고, 비주얼노벨팩 획득하는 것 구현
   - [x] 알투몬한테 안 치이게 길 비켜주기
- ===**3차 (0919목)**===
- [x] 획득 모션 제거
- [x] SLG 폰트, 리소스 교체
- [x] 마마고 번역탭 판매 구현
- [x] 기계어 번역팩 획득 구현
- [x] 중간에 접속해도 마마고 버블 띄워두기
- [x] 번역탭 럭키 대사
- [x] 번역탭 배치
- [x] 번역탭 구현
- [x] 대사 최신 버전으로 모두 적용
- [x] 번역팩, 오브젝트 G F 리소스 교체
- [x] 커서 빛 리소스 교체
- [x] 번역탭 럭키 상호작용 구현
- ===**후순위**===
- 마마고랑 이야기하다가 마마고 번역기 사명 안됨
- 마마고가 마마고 컴퍼니 들어갈 때 길 비켜주기 (마마고 동선에 있다면)
- 길 비켜줄 때 애니메이션 적용
- 연출 레터박스 구현 (기획서 참고 예정)
- 럭키팩 리소스 교체 => 럭키 변경 이후
- 럭키 없이 미리 동굴 가는 분기 구현
- CH1 데이터 묶기
- 깃허브에 gitignore로 에셋 빼고 올리기!!
- 치트 json파일 갈아끼는 것으로 교체

### 기획
- #654 
- #684 
- #668 
### 아트

**Comment by wooyn730** [comment]
버닝비버용으로 작업할게 이것저것 있어서 이슈를 따로 생성했습니다.
1차 작업 완료하였습니다.
좀 더 작업하고 내일 빌드 한 번 드릴 예정입니다.

**Comment by wooyn730** [comment]
### 빌드
[v0.1.4 빌드본](https://drive.google.com/file/d/1UVngv1cWAP8kf3dBbnHGSFaJHay3mJ4w/view?usp=drive_link)

제 2차까지의 작업과 SLG, 3Match 최신 버전이 포함되어 있습니다.
플레이하고 피드백과 버그 리포트 부탁드려요 plz.....................

### 고민
지금 획득 애니메이션 넣는 작업을 하고 있습니다 (1프레임이지만...)
현재 획득 가능한 것이 총 4개(럭키팩, SLG팩, 번역팩, 비주얼노벨팩)이며,
럭키팩과 SLG팩은 고유의 획득 효과음이 있습니다.

예전에 기화님이 획득 효과음 만들어 주신 게 있긴 할텐데 (근데 못찾음)
남은 2개의 팩에 해당 효과음을 공통으로 넣어야할지, 아니면 두 팩에도 각각 고유의 효과음을 요청하는 게 좋을지 고민입니다.

나중에도 장르팩과 번역팩 획득할 거 생각하면 후자가 좋을 것 같긴 합니다.

**Comment by Sumindd** [comment]
획득 애니메이션은 번역팩을 얻었을 때만 등장합니다!!! 
나머지는 접속과 역접속이 발생하기 때문에 들어올릴 시간도 없이 빨려들어갑니다.....

**Comment by wooyn730** [comment]
> 획득 애니메이션은 번역팩을 얻었을 때만 등장합니다!!!

네??? 이럴수가.. 이건 또 언제 정해진거죠;; 
어디 적혀있나요?

**Comment by Sumindd** [comment]
[변경 기획서](https://drive.google.com/file/d/1EhRy5fBCMSalE_mOfgU47OOoQ4_SdZmk/view?usp=sharing) 여기 3페이지에 적혀있고.. (다음부턴 이런 내용은 좀 더 강조하겠습니다ㅠㅠ) 
[획득 사운드](https://drive.google.com/file/d/1t12iEJlEHfIMaGISBjjN4iaU59YOBACU/view?usp=sharing)는 이쪽인 것 같아요!

**Comment by wooyn730** [comment]
읽긴 했었는데 번역팩 전에 작업한거라 자세히는 확인 안했네요...
그래서 처음에 획득 모션 이야기 나온대로 생각했습니다 제 잘못이네요...
아 지우기 아까워,..ㅋㅋㅋㅋ🥲🥲

**Comment by fkdl0048** [comment]
수민님 말씀이 맞습니다! 획득은 인게임에 존재하는 회색 아이템?에 해당하는 내용입니다. 현재 획득 가능한 번역팩에서만 획득 애니메이션이 나오는데, 획득 애니메이션은 깔끔한 것 같아요 근데, 효과음은 재생 안되는게 맞나요? 저는 간헐적으로 나오는 것 같습니다.

**Comment by wooyn730** [comment]
### 번역탭 럭키 고민

원래는 설정창이 활성화되면 게임을 멈추게 구현해두었습니다
그래서 설정창이 켜지면 럭키와 대사가 다 멈추기 때문에
번역탭 설명 구현을 위해 설정창을 따로 두고 럭키가 설명할 때는 복제된 가짜 설정창을 띄우려고 했습니다.

근데 새로운 기획에 따르면 럭키가 아예 설정창보다 높은 레이어에 존재하는 것 같아서
앞으로 럭키가 말하는 도중에 설정창을 활성화하면 럭키는 멈추지 않게 해야하는지 궁금합니다.
(럭키가 설정창보다 높은 레이어라면 설정창이 럭키에게 영향을 미치지 못하는 것이 자연스럽지 않을까)
(근데 이러면 좀 복잡해짐...)

**Comment by wooyn730** [comment]
작업 완료!

일단 고민 끝에 '럭키 연출 중에는 설정창을 활성화 할 수 없다'는 전제를 두고 구현하였고,
복제된 짭설정창이 아닌 찐 설정창으로 구현했습니다.

자잘한 것들만 남았는데 일단 닫겠슴다

**Comment by wooyn730** [comment]
++
그리고 번역팩 럭키 설명 대사 제가 좀 수정했어요
esc 누르지 말고 럭키가 설정창 띄우게 하면서 이것저것..
죄송합니다 수빈님 ㅠ_ㅠ
확인 부탁드려요 ...

**Comment by roweclaw** [comment]
앗 괜찮습니다~
빌드로 확인하면 더 좋을 것 같긴 한데 제가 오늘은 시간이 안돼서 ㅠㅠ
일단 Translator.yarn 으로 확인했는데 플로우에 맞춰서 잘 수정해주셨네요!!
급하게 고칠 부분은 없는 것 같아서 추후에 다시 봐볼게요! 고생하셨습니당 👍

**Comment by wooyn730** [comment]
버그 위주로 일부 수정되었습니다

[빌드본 v0.2.0](https://drive.google.com/file/d/1e4_Uuj-oM3bOfqORVMLSMJEWVuXPuAeK/view?usp=drive_link)
