### ISSUE TITLE
[UI] 마마고 번역기

### ISSUE THREAD

**Issue by vprwolf** [GG-Studio-990001/Grayed-Game#677]
**2024.09.17**
### 마마고 번역기 UI 1차

**마마고 번역기 UI(?) 에 대한 생각**
- 해당 UI는 SLG시스템 범주에 들어가는 UI로 알고 있습니다!
   개인적으로 SLG의 경우 게임의 형식으로, 
    SLG시스템으로 넘어가는 부분도 UI의 분위기는
    Grayed Game의 톤앤 매너와 맞추는 것이 좋지 않을까 생각했습니다.
- 해당 UI가 일회성으로 나오는 것인지, 다른 번역기 구매 시 재활용되는 UI인지가 확실치는 않지만,
  만약 일회성이라면 UI내부를 이미지로 가져와 조금 꾸밈의 자유도를 높이는 것도 좋지 않을까 싶습니다.
  (디자인한 시안이 재활용이 가능할 것 같다 하면 그대로 사용해도 좋을 것 같습니다!)

**1차 시안**
Grayed Game UI의 톤앤매너와 맞춰서 제작해보았습니다.

![Frame 2](https://github.com/user-attachments/assets/3ab50c58-a43f-46b5-9731-321364d9e24b)

---------------------------
**2024.09.18**
### 마마고 번역기 UI 2차

스타일을 변경해 다시 수정해 보았습니다!
스타일 차이가 크다면 색도 흑백으로 하는 것도 나쁘지 않을 것 같은 개인적 생각도 있는데,
일단 컬러본까지 작업해보았습니다.
피드백 부탁드립니다!

**흑백본(high fidelity wireframe)**
![Frame 3](https://github.com/user-attachments/assets/dc4fa2f2-c6c9-4312-955e-9a2a61519315)
흑백을 쓴다면 명도 조절을 좀 해서 사용해도 좋을 것 같습니다.

**컬러본**
![Frame 4](https://github.com/user-attachments/assets/89574780-7c05-442d-b385-361ca5fdcab6)

**적용예시**
![Slide 16_9 - 15](https://github.com/user-attachments/assets/8ce524df-3d13-422b-8520-c6cf9da70506)
![Slide 16_9 - 16](https://github.com/user-attachments/assets/91b2baf4-40cd-40ff-9273-4149ed7cff2c)

결정이 된다면 나중에 다른 UI도 조정이 필요할 수 있을 것 같습니다.

---------------------------------
**2024.09.18**
### 마마고 번역기 UI 3차

리소스 수정했습니다!
동전 아이콘은 기존 리소스를 가져다 사용했습니다!
혹시 몰라 팝업 자체 색상도 기존 UI와 맞춘 버전도 만들었습니다!

**색상조정.ver**
![Frame 5](https://github.com/user-attachments/assets/3fea4941-a9cc-438a-a24f-01dfab9b2237)

**작업하던 색상.ver**
![Frame 6](https://github.com/user-attachments/assets/b10e6e08-5aca-483d-b4f8-5c1d363218a3)

**적용본**
![Slide 16_9 - 18](https://github.com/user-attachments/assets/0ef13641-67cf-42de-b196-1f81c526b65d)
![Slide 16_9 - 17](https://github.com/user-attachments/assets/bed64367-7f9a-4468-b652-6e6115e581b4)

---------------------------------
**2024.09.18**
### 마마고 번역기 UI 4차

수정 반영했습니다!
![Frame 8](https://github.com/user-attachments/assets/960a9e45-a6e3-4f2c-981d-ba3b1d3aae07)
![Slide 16_9 - 19](https://github.com/user-attachments/assets/2aebfd7b-af7f-4433-951c-a0ae6fb32749)

**Comment by fkdl0048** [comment]
> 해당 UI는 SLG시스템 범주에 들어가는 UI로 알고 있습니다! 개인적으로 SLG의 경우 게임의 형식으로, SLG시스템으로 넘어가는 부분도 UI의 분위기는 Grayed Game의 톤앤 매너와 맞추는 것이 좋지 않을까 생각했습니다.

이 부분은 SLG 분위기가 Grayed Game의 톤앤 매너와 통일되면 안됩니다! 게임에서 강조하고자 하는 부분이 결국엔 이질적인 다른 UI를 통해 전혀 다른 시스템이 현재 라플리를 통해 결합되었다고 보여줘야 하기 때문에, 독자적인 `시티 타이쿤`이라는 게임의 UI시스템이라고 봐주시면 좋을 것 같습니다.

보여주신 UI가 너무 매력적이라 정말 어렵지만,, 현재 기획상으로 보여주신 설정창으로 비트는 것도 가능하지만 개인적으로 이질적인 디자인으로 다른 게임 시스템이 결합되었다는 점을 보여주는게 핵심인 것 같습니다.

**Comment by vprwolf** [comment]
2024.09.18
작업내용을 업데이트 했습니다:)

**Comment by wooyn730** [comment]
색과 관련해서는 [세계관 설정 정리](https://drive.google.com/file/d/1rNvWDoRXRVBcxbDB8ZCTmXdZGtbi2BP3/view?usp=sharing) 파일을 읽어보시면 참고가 될 것 같아요!
앞으로도 접속이나 역접속 게임들은 모두 색이 있을 것 같습니다.

마마고는 [CH1 마마고](https://drive.google.com/file/d/1pFNSoUuCJg7lE4Rb70lCkpol7IXTKrwa/view?usp=sharing)와 [캐릭터 컨셉아트](https://drive.google.com/file/d/1_wLeqEuVPFdfWZsOEfHGOlD8UZGs0r2f/view?usp=sharing)를 참고해주세요. 
SLG UI로 보여지는 것이니 마마고 색도 표현되면 좋겠네요.

기획서 이미지를 반영해주셨지만 수민님이 임시로 해두신 것 같아서...
무조건 사야하니 x 버튼을 제거하고, '건설시작!'을 '구매하기'로 바꾸는 게 자연스럽지 않을까 합니다.

작업 방향성은 너무 좋네요! UI도 깔끔하고요 마마고도 같은 느낌으로 잘 그려진 것 같아요
(뭔가 계속 느껴지는 북미풍향 ㅋㅋ)

조금 걱정되는 것은 기존 리소스랑 결이 다른 것 같아서 이러면 다른 것도 다 손대야 하지 않을까...
럭키도 작업할 것 많고 다음 달에는 접속 게임도 들어갈 것 같은 데 괜찮을까... 정도가 있습니다.

**Comment by Sumindd** [comment]
마마고 번역기는 건설이 아니라 구매하기라서 구매하기로 버튼 글자를 변경해야 할 듯합니다.
마마고도 흑백이 좀 튀어서 기존 마마고 설정의 색만 넣어주면 저는 완전 만족이요

**우연님 피드백에 대한 내용**
혹시 10코인이 부족한 경우가 있을 수도 있고, 유저에 따라 바로 구매하지 않을 수도 있기 때문에 x 버튼은 그대로 있는 게 나을 것 같습니다!
그리고 이정도면 기존 SLG 리소스랑 많이 튀진 않아서 구매창(건설창) 리소스들만 교체해도 괜찮지 않을까요?

**Comment by wooyn730** [comment]
> x 버튼

맞네요!
그러면 구입했을 때의 대사, 다시 방문했을 때의 대사, 구입안했을 때의 대사가 필요할 것 같습니다.

> 리소스 교체

![image](https://github.com/user-attachments/assets/8e314966-cc58-4c95-986f-3a495b0b6ded)

전 좀 튄다고 생각해서... 리소스 비용 최소화할거면 보민님이 기존 리소스에 맞게 수정해주시는 게 나을 것 같습니다!

**Comment by vprwolf** [comment]
2024.09.18
작업내용을 3차 업데이트 했습니다:)

**Comment by wooyn730** [comment]
오 좋은데요??!

팝업만 봤을 때는 작업하던 색상ver이 훨씬 더 이쁜데 통일성 생각하면 역시 전자가 낫나 싶기도 합니다...

마마고 색 좋고요
괜찮으시다면 모노클도 끼우고 목에 리본도 달아서 CH1 마마고랑 좀 더 통일성을 주면 좋을 것 같습니다 ㅎㅎ
![image](https://github.com/user-attachments/assets/a05d4a09-4606-4791-a6a4-357570ffa903)

**Comment by vprwolf** [comment]
**2024.09.18**
작업내용을 4차 업데이트 했습니다:)

**Comment by Sumindd** [comment]
건설 시작을 구매하기로 수정 부탁드려요!
그 외엔 좋습니다

**Comment by vprwolf** [comment]
**2024.09.18**
구매하기 수정 반영했습니다!
