### ISSUE TITLE
[Icons]럭키팩, 번역팩, 번역기

### ISSUE THREAD

**Issue by vprwolf** [GG-Studio-990001/Grayed-Game#678]
**2024.09.17**

### 럭키팩 아이콘 1차

럭키팩 아이콘을 1차로 제작했습니다!
![lck](https://github.com/user-attachments/assets/d0d4c8a6-03c9-4f25-8b74-da780bb5cfc2)
피드백 부탁드립니다!

**질문**
-사실 정안님께도 한번 설명을 들었긴한데, 번역팩, 번역기의 차이가 조금 헷갈려서
 설명이 가능하다면 설명을 한번 더 해주시면 감사하겠습니다..! :)
-번역팩, 번역기에도 특별히 원하는 컨셉이 있는지가 궁금합니다!

---------------------------
**2024.09.18**

### 번역팩 아이콘 1차

번역팩 아이콘을 1차로 제작했습니다!
![cog](https://github.com/user-attachments/assets/f950a6ff-ad4c-487f-9862-3955ac68248c)
피드백 부탁드립니다!

---------------------------
**2024.09.18**

### 번역기 아이콘 1차

번역기 아이콘을 1차로 제작했습니다!
![Frame 7](https://github.com/user-attachments/assets/bc116c9c-c562-4f56-9e21-c442f2919467)
피드백 부탁드립니다!

---------------------------
**2024.09.18**

### 마마고 번역기 아이콘 _ UI제작본 차용
![mamago 1](https://github.com/user-attachments/assets/39f1c266-8a56-4f4b-925d-77fa40f18a6b)

-----------------------------
**2024.09.19**

### 기계어 번역팩 아이콘

색상, 사이즈 수정 진행해보았습니다!
![cog02](https://github.com/user-attachments/assets/8d8ee294-33bc-4cdf-9fa9-eecb39305cdf)

이정도 크기가 될 것 같은데 어떻게 생각하나요..! 붉은 칸에 있는 것이 수정본입니다.
![Group 67](https://github.com/user-attachments/assets/e8956d24-eaae-414e-8e52-e3657780fc06)

-----------------------------
**2024.09.19**

### 럭키팩 아이콘

검은럭키버전 갈색럭키 버전 두가지로 제작했습니다!

**검은럭키**
![lck_blck](https://github.com/user-attachments/assets/e526dddb-a3eb-474c-aaf3-f2c1c5f4eae2)

**갈색럭키**
![lck_brown](https://github.com/user-attachments/assets/c438e90d-972b-48a9-bd35-2b266722f0dc)

적용본
![Group 72](https://github.com/user-attachments/assets/6a1f2250-bf00-48da-8b3f-f194bf206986)

**Comment by fkdl0048** [comment]
저는 완전 만족입니다. 실제 기존 도트와 문제 없이 적용되느지는 적용해봐야 느낌을 볼 수 있을 것 같긴한데, 기획서 내용대로 구현되어서 좋은 것 같습니다.

번역탭과 번역기 현재 접속과 역접속의 시스템을 먼저 이해하는게 좋을 것 같습니다. 번역탭과 번역기는 같은 내용이지만 유저에 의해 발생한 역접속에 의해 라플리의 설정 UI에 변환된 상태입니다. 번역기는 현재 색깔이 있는 번역기 오브젝트가 라플리가 만짐으로써, **역접속**되어 설정창의 일부로 역접속되었다고 보시면 될 것 같습니다.

그래서 맵에 배치되어 있는 오브젝트 번역기(라플리가 인게임에서 만지게 되는 오브젝트), UI에서 표시되는 번역기 형태 (SLG UI로 획득하기 때문에, SLG 디자인 형태로 색이 있어야 함)이후에 설정창은 라플리 기존 설정 UI에 역접속되어 결합된다고 보면 됩니다.

**Comment by vprwolf** [comment]
**2024.09.18**
1차 번역팩 시안 업데이트 했습니다 :)

**Comment by vprwolf** [comment]
**2024.09.18**
1차 번역기 시안 업데이트 했습니다 :)

**Comment by Sumindd** [comment]
### 설정
덜 잊혀진 게임 리소스엔 색이 남아 있고, 따라서 GG에선 접속(혹은 역접속)처럼 반응이 일어나는 것들에만 색이 있습니다. 이걸 만지면 라플리에게 적용되어 인게임에서 UI처럼 보이게 되거나 팩맘 접속처럼 라플리가 빨려 들어가게 됩니다.
접속과 역접속이라는 용어로 저희끼린 구분하고 있지만 인게임에선 '**접속**' 이라는 개념만 존재합니다. **색이 있는 리소스가 다른 리소스와 접촉 했을 때 더 큰 개념의 리소스쪽으로 작은 리소스가 빨려 들어가는 것이 '접속'입니다.** 그래서 CH1에선 라플리가 팩맘에 빨려 들어갈 때만 접속이 일어나고 나머지 서브 게임은(SLG, 3매치. 럭키팩 등..) 라플리보다 더 작은 개념이기에 역접속 되고 있습니다. 라플리는 게임이라는 큰 개념이기에 팩맘 같은 거대한 게임이 아니라면 색 있는 걸 만져도 대부분 역접속 되어 문제 없지만, 리소스 조각인 대부분의 NPC는 접속이 되어 갇히게 됩니다. 그래서 색 있는 물건은 위험하다고 합니다.
(예외: 본인과 같은 출신의 리소스는 색 있는 상태를 만져도 문제 없음. 따라서 마마고가 색 있는 마마고 번역기는 만져도 문제 없는데 파머가 만지면 빨려 들어감)
 
번역탭=번역기 (개발적으론 번역탭인데 인게임에선 **번역기**라는 이름만 사용)
번역팩은 번역기에 끼우는 팩으로 대표적으론 기계어를 번역해주는 **기계어 번역팩**이 있습니다.
번역기는 번역기 앱이라고 생각하시면 될 것 같아요. (마마고는 앱 파파고의 패러디 캐릭터)
라플리가 마마고 번역기를 구매하면서 마마고 번역기가 라플리에게 역접속 되고, 기계어 번역팩은 접속의 단위조차 될 수 없는 작은 리소스 조각 형태의 단순 아이템으로 흑백입니다. 그냥 진짜로 아이템을 얻어서(젤다 모션) 라플리가 끼웠다고 생각하시면 됩니다!

설정이 다소 헷갈릴 수 있어서 [리소스 리스트](https://docs.google.com/spreadsheets/d/1xLu0o7xpz4A3foy7fB_kl-RDrlTBvMuX/edit?usp=sharing&ouid=102142728386857128653&rtpof=true&sd=true)에 색 있고/없고, 도트/벡터 표시를 전부 해놨습니다.  (근데 지금 확인해보니까 4번을 기계어 번역기라고 써놨네요;;; 죄송합니다ㅠㅠ 마마고 번역기입니다....) 

### 작업물 피드백
기계어 번역팩은 R2-MON의 언어를 알아들을 수 있게 만들어주는 팩으로 지금 형태로 가도 좋을 것 같습니다! (흑백 도트)
마마고 번역기는 컬러라는 이미지가 뚜렷해야 하고, 변역기 구매창에 마마고 이미지를 사용했기 때문에 번역기 이미지도 비슷하게 마마고 이미지를 넣으면 될 것 같습니다. (말풍선 안에 들어갈 마마고 번역기 아이콘이며, 누르면 보민님이 작업해주신 마마고 번역기 판매창이 뜹니다! )
헷갈리게 리스트를 작성해서 죄송합니다..

**Comment by vprwolf** [comment]
앗 아닙니다! 자세한 설명 감사드립니다:)

**Comment by vprwolf** [comment]
혹시 마마고 번역기도 따로 특정된 레퍼런스가 있는지 궁금합니다!

**Comment by vprwolf** [comment]
> 변역기 구매창에 마마고 이미지를 사용했기 때문에 번역기 이미지도 비슷하게 마마고 이미지를 넣으면 될 것 같습니다. 

아하 혹시 UI에 사용했던 마마고로 사용하면 되는 부분인가요..!

**Comment by Sumindd** [comment]
네 맞습니다 UI에 사용한 마마고를 사이즈에 맞게 정리해주세요!
어차피 마마고 번역기라는 게 특정한 물체보단 앱에 가까워서 추상적인(아이콘 느낌) 마마고 이미지로 가도 괜찮을 것 같습니다

**Comment by vprwolf** [comment]
아하 네네! 감사합니다:)

**Comment by vprwolf** [comment]
**2024.09.18**
마마고 번역기관련 내용 업데이트 합니다 :)

**Comment by vprwolf** [comment]
아하 해당 폴더에 추가했습니다!
0918날짜로 추가했습니다!
https://drive.google.com/drive/folders/1Ev4wLdt2JVngAtFRKGvI_zRAjLE3gCDj
감사합니다!

**Comment by wooyn730** [comment]
(1)
사이즈가 288*288 이던데 둘 다 확대해서 주신 건가요?
원본 사이즈(최소 사이즈?)로 주셔도 됩니다..!

(2)
럭키팩은 나중에 럭키 외형 바꾸고 바꾸는 게 좋을 것 같아서 추후 적용하겠습니다!
(그러니 요건 수정하게 된다면 천천히 수정해주셔도 됩니다)

(3)
럭키팩과 번역팩은 조~금씩 더 작아도 좋을 것 같긴 합니다.
라플리에게 역접속되는 친구들인데 라플리랑 사이즈가 비슷한 느낌...
![스크린샷 2024-09-19 154636](https://github.com/user-attachments/assets/55612c0f-dbbf-4fc3-948a-dc34702f473f)

(4)
기존 오브젝트들과 지은님이 작업해주신 오브젝트들은 아웃라인이 검정인데,
보민님 작업물은 하이라이트처럼 빛 받는 부분 아웃라인은 밝게 처리해주신 것 같습니다.
예쁘긴 하지만 (특히 번역팩은 정말 마음에 드네요 반짝이는 금속 느낌)
통일감을 주기 위해서는 아웃라인을 통일하면 좋을 것 같습니다.

(5)
럭키팩은 폴더 부분 점점점? 말고 더 심플한 버전으로도 보고싶네요!
(위에 캡쳐 보면 살짝 줄무늬같은 느낌쓰)
![image](https://github.com/user-attachments/assets/5c7cd26b-3b6e-4f68-9b71-2e6a4c2420be)

(6)
![image](https://github.com/user-attachments/assets/e3860c54-1683-4045-a654-3fe4b2f94000)
다른 팩에 획득 모션을 적용했을 때는 (실수로 ㅋㅋㅠ) 색이 있어서 딱 돋보였는데, 
번역팩은 위치 상 뒤에 마마고도 있고 흑백이라 잘 눈에 띄지 않는 느낌이네요.
SLG 커서 빛 이펙트처럼 얘도 뒤에 뭔가 깔아줘야되나 싶네요.. (한다면 도트로 해야할지?)
보민님과 다른 분들 의견이 궁금합니다.

**Comment by fkdl0048** [comment]
확실히 적용해보니 보이는 문제점들이 있네요. 6번은 이펙트가 필요할 것 같고, 7번도 수정된 버전으로 가야할 것 같네요

**Comment by wooyn730** [comment]
7번은 먼가요?

**Comment by vprwolf** [comment]
아하 색상부분은 수정 진행하겠습니다!
다만 사이즈부분이 좀 시간이 걸릴 수 있을 것 같습니다 ㅠ

**Comment by vprwolf** [comment]
**2024.09.18**

기계어 번역팩 아이콘 수정 업데이트 합니다:)

**Comment by vprwolf** [comment]
구드에 올렸습니다!
혹시 몰라 2배 크기 이미지도 함께 보내드립니다
https://drive.google.com/drive/folders/1Ev4wLdt2JVngAtFRKGvI_zRAjLE3gCDj?usp=sharing

**Comment by wooyn730** [comment]
적용 완료용~ (작은거 썼습니다 ㅎㅎㅋㅋ)
이슈는 닫아드릴게요 번역팩 후광 관련은 다음에 더 이야기 해봐요!

**Comment by vprwolf** [comment]
아하 네네! 감사합니다:)
