### ISSUE TITLE
[Icons] 게임 리소스 F, G/SLG UI팩

### ISSUE THREAD

**Issue by JIJI037** [GG-Studio-990001/Grayed-Game#679]
![게임리소스F](https://github.com/user-attachments/assets/5ee4ecb0-7c80-41b7-9c40-cf0453d1388f)
![게임리소스G](https://github.com/user-attachments/assets/623ebacd-7e52-41a8-9306-d0048d8187fa)
어떤 형태로 진행할까 고민 중 고전 게임 중 하나인 조이스틱과 다마고치를 채택했습니다

![0722SLGicon](https://github.com/user-attachments/assets/cf989537-365d-43e1-9e8d-577a0321f011)
기존 아트를 따라 모바일 아이콘으로 재제작 하였습니다

빛 이펙트 작업 진행했습니다
![SLG포인트 UI_적용 예시](https://github.com/user-attachments/assets/a8409ad4-2f34-4ee9-8c68-89b7c33f72d4)
![SLG포인트 UI_후광](https://github.com/user-attachments/assets/ad280429-0974-4b32-ae19-7736e9fd6b6c)

**Comment by jeongopo** [comment]
혹시 이거 파일 어디에 들어있나요..? 구드 보는데 안보여서요 ㅜㅜ

**Comment by JIJI037** [comment]
헉 구드에 안 넣었나봐요 이름 수정해서 바로 넣겠습니다ㅜㅜ

**Comment by jeongopo** [comment]
헉 빠른확인 감사합니당 ❤️

**Comment by JIJI037** [comment]
구드에 CH1 Art 리소스 파일에 올렸습니다!

**Comment by jeongopo** [comment]
![image](https://github.com/user-attachments/assets/69cf3b2f-49d4-46d6-b4ec-992105f462fa)

혹시 이거 9번도 올라와있나요 .. ?

**Comment by JIJI037** [comment]
아직 제작 중이라 . . .. . .. .. 제작 시 업데이트 하겠습니다 8-8

**Comment by JIJI037** [comment]
오늘 지나가는쯤에 드릴 수 있을 것 같습니다!

**Comment by jeongopo** [comment]
앗 제가 늦게는 작업이 어려워서 ㅜㅜ 내일 8시전까지 천천히올려주세요 ㅎㅎ..!
그리고 저 아이콘팩

![image](https://github.com/user-attachments/assets/53fae5d6-8af3-4e29-99a9-5f3632a995f9)

테두리쪽이 깨져서나와서

![image](https://github.com/user-attachments/assets/e4932733-ddfa-4d81-bb92-3ca88400faf8)

(기존 아이콘)

한번 확인부탁드립니다 !

**Comment by jeongopo** [comment]
내일확인해볼게요 감사합니다~

**Comment by Sumindd** [comment]
조이스틱이랑 다마고치 딱 적당하고 빛 이펙트도 너무 귀엽네요 짱!!

**Comment by Songkihwa** [comment]
조이스틱이랑 다마고치 넘 귀엽고 잘 어울리는 것 같아요! 빛 이펙트도 좋네요 ㅎㅎ 고생하셨습니다!!

**Comment by wooyn730** [comment]
빛 이펙트 좋네요!!

조이스틱이랑 다마고치는 톤도 잘 맞춰주셨는데 살짝 무거운 느낌이 들어서
기존 리소스들과 조금 비교를 해봤는데요
![스크린샷 2024-09-19 191350](https://github.com/user-attachments/assets/2c86b4e9-6db1-4b7e-a92a-77b7cd930748)
아웃라인이 두꺼워서 그런 것 같습니다

![2](https://github.com/user-attachments/assets/49bfab1c-4cf0-4555-9dcd-4d0daf49c6bb)
_(그림판으로 열심히 깎아본 버전 ... 빨간 동그라미 안의 느낌만 봐주세여)_

아웃라인이 얇게? 처리되면 기존 리소스들과 더 잘 어울릴 것 같습니다.

**Comment by JIJI037** [comment]
아웃라인 얇게 수정해서 다시 올렸습니다 확인 부탁드려용

**Comment by wooyn730** [comment]
좋아요!! 제가 적용해두었습니다
이슈 닫아드릴게요 ^_^ ~~

**Comment by wooyn730** [comment]
![image](https://github.com/user-attachments/assets/cf2ce90e-8649-4a89-a9c8-6bc66525bdb6)

테두리가 조금 잘리네요 확인 부탁드려요~

**Comment by JIJI037** [comment]
수정해서 올렸습니당 이상 있으시면 말씀주세용

**Comment by wooyn730** [comment]
죄송한데 조금 더 깔끔하게 될까요?

**Comment by wooyn730** [comment]
최종본 적용 완료요! 수고하셨습니다
_(까탈스러워서 죄송합니다 앞으로도 잘 부탁드립니다,, ^_^)_

다음엔 리소스명은 영어로, 수정되었으면 리소스명도 바꿔주세요! (숫자를 하나씩 올린다던가)
알아들을 수만 있게 적당히 지어주시면 됩니다 ㅎㅎ
