### ISSUE TITLE
[CH1] 폰트 교체

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/Grayed-Game#680]
# [CH1] 폰트 교체 

1챕터 도트 폰트로 교체건입니다.

- https://github.com/GG-Studio-990001/Grayed-Game/issues/643#issuecomment-2350965942

@Sumindd 님이 저작권 없는 폰트로 @wooyn730 님에게 전달 해주시면 될 것 같습니다.

@wooyn730 우연님은 20일 전에 적용 가능한지 확인 부탁드립니다!

## 요청사항

1. CH1 도트 폰트
2. SLG 자체 폰트

둘 다 저작권 없는 어울리는 폰트로 교체 필요

----------------------------------------
**2024.09.29**
### CH1기준 폰트

**-기본 폰트(설정창/SLG 등): 배민 한나체**
![한나](https://github.com/user-attachments/assets/3faf8d82-d4c0-4987-8b27-9aff8fc68af9)
![image](https://github.com/user-attachments/assets/72053846-a66c-48c8-8651-0c9bca001686)
https://www.woowahan.com/fonts
이번 UI를 제작할때 사용한 폰트입니다!
레퍼런스로 삼았던 페르소나UI의 볼드한 UI분위기와
흑백 위주의 색상인 Grayed Game의 색상 대비가 큰 느낌과 잘 맞다고 생각해
선정하게 되었습니다!
공통되는 UI의 텍스트는 해당 폰트를 사용하는건 어떨까 생각했습니다:)

**-SLG폰트: 배민 한나체**
 SLG또한 캐주얼하고 깔끔한 느낌의 UI로 진행되는 것 같아
선정한 기본폰트를 유지해도 좋을 것 같습니다.

**-일부 강조폰트**
일부 강조폰트는 각 상황이나 분위기에 따라 다양하게 차용하는 것도 좋을 것 같습니다.
이러한 문자들은 기본UI폰트만큼 자주쓰이지는 않기 때문에 그때그때 필요한 부분에 사용하고
이미지 파일 형태로 적용하는 것도 좋을 것 같습니다!
ex)마마고 ‘파격세일’문구 (코트라 볼드체)

**-도트파트 (추후 작성하겠습니다!)**
이름 폰트
본문 폰트

----------------------------------------------------
**2024.10.03**
### 메뉴 대안 폰트, 도트폰트

메뉴에 쓰일 수 있는 몇가지 폰트를 더 조사했습니다!

### 메뉴폰트

**1.더잠실체**
![더잠실_01](https://github.com/user-attachments/assets/0b28a058-f316-496b-b6d2-d0c1f7c37e96)
![더잠실](https://github.com/user-attachments/assets/c57601d4-6f6e-4012-83a5-45542987337e)

**2.페이퍼로지**
![페이퍼로지_01](https://github.com/user-attachments/assets/91937a5e-f843-493a-bcba-28c23159af53)
![페이퍼로지](https://github.com/user-attachments/assets/36e32743-a378-4ea3-ac5e-ebd2d3882d1b)

**3.원스토어 모바일 타이틀**
![원모바일 타이틀_01](https://github.com/user-attachments/assets/b6476c09-faf1-4bf5-9bf7-bd1ff8cc4695)
![원모바일 타이틀](https://github.com/user-attachments/assets/ac675a83-43cd-433c-ad9c-b63c7de414ca)

개인적으로는 더잠실/페이퍼로지쪽이 마음에 듭니다 :)

### 도트폰트

도트의경우는 무료폰트 범위 안에서는 가짓수가 한정적인지라
현재 인게임 폰트와 중복을 피하기는 어려울 것 같습니다!

**1.도트 이름,타이틀**
-둥근모꼴+ Fixedsys
![둥근모꼴](https://github.com/user-attachments/assets/e1540fd8-9548-49a2-9b51-ab69460d2341)

-픽셀로보로보체(무료 도트 폰트 가짓수가 적은 가운데.. 그나마 특색을 넣을 수 있는 폰트인 것 같아 가져왔습니당,.)
![image](https://github.com/user-attachments/assets/8625cae1-cfde-442c-9594-5e46934d7fe9)

**2.도트 본문**
-둥근모꼴+ Fixedsys

-갈무리14
![rkf](https://github.com/user-attachments/assets/9c247237-0467-43f1-bd18-79a41ce93664)

적용예시

![픽둥](https://github.com/user-attachments/assets/51ebbb97-ef4c-44e7-88b9-e9bca4a6d2e2)
![vlrrkf](https://github.com/user-attachments/assets/9c549a0c-4023-41cc-b053-e4c39271863e)
![endrkf](https://github.com/user-attachments/assets/bfc64bfb-39b8-40e7-9b24-36c469269f60)
![endend](https://github.com/user-attachments/assets/0dd7f9c4-0221-4ae5-95a7-cedaa9b5f757)

사실 전 현재 인게임 폰트도 괜찮다고 생각합니다..ㅎ

**Comment by Sumindd** [comment]
폰트를 제가 고르나요..??

**Comment by wooyn730** [comment]
> 폰트를 제가 고르나요..??

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 저도 궁금했는뎋
아트 시키죠~~

**Comment by fkdl0048** [comment]
아트분들이 고르는게 일반적이군요..? 잘 몰랐읍니다.. 일단 그럼 이 이슈는 이번 마일스톤말고 다음 작업으로 넘기죠! 현재 아트분들 기획적 설명이 우선 되어야 할 것 같습니다!

**Comment by fkdl0048** [comment]
@vprwolf 이번 주 작업은 해당 이슈로 생각해주시면 됩니다. 여기서 본문 수정하시면서 업데이트 하시면 될 것 같아요!

**Comment by vprwolf** [comment]
**2024.09.29**
1차 업데이트 했습니다! (추후 이어서 작성 예정)

**Comment by fkdl0048** [comment]
레퍼런스가 많아서 좋습니다.. 

- SLG폰트의 경우 배민 한나체가 가장 마음에 듭니다!
- 일부 강조 폰트의 경우 가능하다면 -> 영어로 그림을 그려서 처리? (나중에 지역화에 문제 없도록?)
- 메뉴폰트는 3개 다 마음에 들어서 보민님이 선택하시는게 더 좋을 것 같습니다.
- 도트폰트 (둥근모꼴+ Fixedsys) 해당 폰트가 마음에 듭니다!

현재 인게임 폰트를 변경하려는 이유는 도트 글씨체가 해상도가 깨져서 교체하려고 하고 있습니다! 그리고 아마 눈은 보민님이 제일 정확하셔서 잘 골라주시면 될 것 같습니다!

**Comment by fkdl0048** [comment]
@wooyn730 회의 때 잠깐 이야기 했는데, 둥근모꼴 +Fixedsys폰트를 유니티내에서 해상도 좋게 수정을 하는 방향이 제일 좋을 것 같습니다. @NearthYou 가능하다면 시원님도 한번 봐주시면 좋을 것 같아요.

나머지 폰트는 적용해주시면 될 것 같습니다. @vprwolf 각 UI에 적용할 폰트로 정리해주세요

**Comment by fkdl0048** [comment]
@wooyn730 `둥근모꼴 +Fixedsys폰트` TMP 가능한지 좀 더 연구해주시면 좋을 것 같습니다. 1주 정도 작업해보시고 어려우시면 말씀해주세요
