### ISSUE TITLE
[CH1] 대사 스크립트 추가 작성 2차

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#684]
**추가 작성 대사**
- [x] LuckyFish (수정)
- [x] Mamago2_1 (Mamago2 이후 ~ 번역기 구입 전)

**참고**
- 디코 피드백 채널
- https://github.com/GG-Studio-990001/Grayed-Game/issues/677#issuecomment-2357643302

---
### title: LuckyFish

39 `럭키: 왜 그러나 했더니만<br>길이 막혔잖아!`
40 `럭키: 잠깐 기다려 봐<br><incr>럭키 효과 발동~!</incr>`
49 `럭키: 이제 지나갈 수 있겠지?`

### title: Mamago2_1

```
// 시점: 컷씬 5.1
// 상황: Mamago2 이후인데 번역기 구입 전
---
마마고: 날이면 날마다 오는 혜택이 아닙니다~
마마고: 오직 우리 은인만을 위하여 제공하는 초특가!<br>놓치지 마세요~
===
```

**Comment by wooyn730** [comment]
기획서 다시 읽어봤는데... 말풍선을 눌렀을 때 마마고와 상호작용하는 느낌(구매 전후 대화)이 아닌 그냥 마마고 패널 띄워주는 거였네요
그러면 마마고 번역기 관련 추가 대사가 필요 없을 것 같습니다 ㅎㅎ;

**Comment by roweclaw** [comment]
넵넵 구입 후 대사인 `Mamago3`은 아래 위치에 작성했습니다~
- https://github.com/GG-Studio-990001/Grayed-Game/issues/654#issuecomment-2360516344

**Comment by wooyn730** [comment]
적용 완료
