### ISSUE TITLE
[CH0][CH1][CH2] v0.3.0 작업

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#695]
마일스톤 ~11/4 (6주)
마일스톤용 통합 문서.. 
하나씩 분리 예정

예정
~10/07: CH1 마무리, CH1 플밍 작업
~10/14: 구글 스프레드 시트 연동, CH2 설계
~10/21: 병가
~10/28: CH2 ~Turn3
~11/04: CH2 구조 수정

오프닝 작업은 다음 마일스톤에 진행할 듯

### CH1 작업 ✅
- #705 

### CH1 플밍 작업 ✅
- #710 

### 오프닝 맵 작업
- #713

### CH2 작업
- 관련 이슈
   - #697 
   - #703 
   - #747 
- 내 작업
   - #712 
   - #741 

### 기타 작업
- [x] 커넥티드 씬 수정 !!!!!!! 플레이어 인풋 이자식아....
- 접속 연출 중에 스페이스바 상호작용 안되게 막기
- CH1 폰트 교체 및 둥근모꼴 해상도조정 도전
- CH1 치트용 데이터 교체 (SLG 관련 데이터 수정됨)
- CH2 개발자용 스킵 적용
- 라플리 자동이동 제거 (오프닝 변경 후)
- CH2 장소 UI 방향 정해지면 수정 (보민, 수민 작업 선행)

### 버그 끝장 작업 ~(이번 마일스톤에 무조건 처리)~
- ~글리치 효과 안나옴 버그~
   - => 다른 에셋으로 교체하기로 함
- ~가끔 팩맘 탈출 연출에 검은화면 전에 잠깐 팩맘 화면이 보임~
   - => 글리치 에셋 때문으로 유추됨
-  CI/CD 자동 빌드에서 비디오 안 나오는 버그

**Comment by fkdl0048** [comment]
작업 이슈가 너무 큰 것 같습니다! 작업 내용 확인을 위해 분리해서 만들어주시면 좀 더 좋을 것 같아요 CH1은 너무 사소한게 많으니까 하나로 묶고, 플밍 작업은 각각 이슈로 묶어서 만들어주세요 만들어주시면 좀 더 쉽게 보고 피드백할 것 같습니다. 아래 버그도 마찬가지로 이슈로 만들어주세요

> 깃허브에 gitignore로 에셋 빼고 올리기!!

현재 플러그인 폴더 자체를 ignore한 상태라 다른 작업자 분들 오시면 플러그인 파일 공유가 되어야 하니 따로 플러그인만 구드에 백업을 해두셔야 합니다!

**Comment by wooyn730** [comment]
CI 오류남 체크 필요...

**Comment by wooyn730** [comment]
(_회의 때 저저번 작업 이야기할 걸 깜빡했네요.._)

이번 주는 CH2 Turn3까지 구글 스프레드시트 연동 + 대사 출력 + 장소 이동,
아트 제외 프로토타입 보여드리겠습니다~!!
