### ISSUE TITLE
[CH2] 스토리 분기 엑셀

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#697]
- 챕터2 스토리의 진행과 분기를 엑셀로 정리합니다.

---

[스토리 분기 엑셀](https://docs.google.com/spreadsheets/d/1VRmG8Bv0I-4TSoCNACvhbK5IHR1_2LsF/edit?usp=sharing&ouid=114884729391256580060&rtpof=true&sd=true) 링크에서 장소 구조, 스토리 분기를 작업했습니다.
이벤트의 상세 내용은 다 넣기엔 길어서 최대한 간단하게 적었으니, 셀을 클릭해서 요약 내용 확인해주시면 됩니다.

**Comment by fkdl0048** [comment]
- https://github.com/GG-Studio-990001/Grayed-Game/issues/700

우선은 수빈님 보기 편하시게 분기를 만들어주시고 위 이슈에서 우연님이랑 수민님이 데이터 정리 방식 확정되면 거기에 맞춰서 작업 해주시면 됩니다

**Comment by Sumindd** [comment]
리소스 리스트는 현재 엑셀 참고해서 적어도 넘겨드려도 될까요? 배경 종류나 NPC 포트레잇이요! (표정은 일단 제외)

**Comment by Sumindd** [comment]
혹시 [CH2 리소스 리스트](https://docs.google.com/spreadsheets/d/1Dm7b5r5Cmk4YC4DTW4ureRnq3Xmny8bs/edit?usp=sharing&ouid=102142728386857128653&rtpof=true&sd=true) 중에서 메인 리소스는 수빈님이 작성해주실 수 있으실까요..? UI 관련은 추가되더라도 제가 계속 관리할 예정입니다!
그런데 CH2가 스토리와 관련이 깊다보니 배경과 캐릭터 표정 같은 부분에서 저보다 수빈님이 스크립트 구상하시면서 상상한 구도나 묘사를 작성해주시는 게 좋을 것 같아서 부탁드리고 싶습니다.. 레퍼런스 이미지 같은 것도 그렇고요

엑셀은 확인해봤습니다! 일단 마마고 컴퍼니의 위치가 옮겨져서 '마마고 컴퍼니 앞'이라는 배경을 경비소와 합치거나 마을 입구 정도로 통일해도 될 것 같습니다(진도, 비글과 경비소에서 유의미한 상황이 발생하진 않는 것 같아서 최대한 배경 개수 줄이기)
그리고 마마고 컴퍼니와 마마고가 CH2 이후엔 등장하기 힘들 것 같아서 CH2에서 활용할 수 있으면 좋을 것 같습니다!(이건 그냥 의견) 마마고 컴퍼니까진 안 나오더라도 최소한 마마고라도 등장하면 좋을 것 같아요. 워낙 마마고 컴퍼니가 설정적으로 붕 뜬 느낌이라..ㅠㅠ 

스토리 흐름 자체는 재밌는 것 같고 스크립트가 기대됩니다!! 고생하셨습니다!

**Comment by roweclaw** [comment]
앗 그러게요 마마고 컴퍼니 위치가 바뀌었으니 경비소로 통일하면 될 것 같습니다! 수정해둘게요
저도 배경이랑 캐릭터 관련이 수민님이 보셔야할게 많아서 걱정이었는데 그럼 아예 따로 메인 리소스는 제가 관리하는 걸로 하겠습니다!!
그리고 마마고에 대해서는 현재 스토리 기획상 챕터3 초반에 등장이 예정되어 있긴 한데... (슬라임이 가져온 쪽지를 해석해준다는 내용) N이벤트는 작성 하려면 가능할 것 같은데, 혹시 S이벤트로 등장하는 걸 원하시나요? 지금은 완전 선형적 구조라서 마마고가 비중있게 나오려면 불가피하게 스토리 일부가 수정되어야 할 것 같아요..!

**Comment by Sumindd** [comment]
아하 챕터3에 등장한다면 괜찮을 것 같습니다! 챕터3에서 마을을 떠나게 되다보니 마을쪽에 있던 애들은 나오기 힘들지 않을까 싶어서 얘기했던 거라.. 마마고 컴퍼니 브금이 나올 수 있는 파트가 있으면 좋겠다고 생각했는데 없어서 조금 아쉽긴하지만 이것 때문에 스토리를 수정하기는 또 아깝네요..ㅠㅠ 지금대로 가도 될 것 같습니다!

**Comment by fkdl0048** [comment]
저도 제대로 읽어봤고 따로 피드백할 내용은 없습니다. 수민님 밀대로 CH2의 전체적인 그림 자체를 수빈님이 잡아주시는게 좀 더 좋아보입니다!
 고생하셨습니다!
