### ISSUE TITLE
9/25 기획 회의 시스템 문서 정리

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/Grayed-Game#700]
- #693 에서 정해진 내용을 구체화 및 문서화합니다. 
-  TCG UI 기획서 구체화
-  원본 날아간 CH2 시스템 기획서 복구(ㅠㅠ)

- 럭키 애니메이션 + 위치 + 레이어 순위
- 럭키 아트 리소스 리스트 작성
- 설정창 명칭 정리

--------

### 240929 업데이트

[CH2 시스템 문서 복구](https://drive.google.com/file/d/1wAyRP3dUnF0OvmMd_iXZ0eMHd-vxL6nD/view?usp=sharing)

**작업 내용**
-  TCG UI 기획서 구체화
-  원본 날아간 CH2 시스템 기획서 복구(ㅠㅠ)

**주요 변경 사항**
2페이지) 상황별 기능 처리 규칙 이미지 추가
4페이지) 문장 다듬기
6페이지) Wizard Stone 구체화 (신규 내용) - **보민님** 확인 필수

문서 복구하면서 자잘하게 이미지 수정이나 문장 수정이 들어가기도 했고 2달 이상 된 문서라 전체적으로 다시 훑어보시는 걸 권장합니다..

### 240930 업데이트

[[240930] 챕터 공통 시스템](https://drive.google.com/file/d/11wVblQ0qqLt1vxfcKAgdAmc_-2_8BhC0/view?usp=sharing)

**작업 내용**
- 럭키 애니메이션 + 위치 + 레이어 순위
- 설정창 명칭 정리
- 번역탭 튜토리얼

번역탭 튜토리얼에서 흑백 설정 때문에 빨간점 기획을 NEW 표시로 변경했습니다.
그리고 럭키를 얼굴만 잘라놓으니까 목걸이 때문에 불안정하게 보여서 좀 고민되네요..

----
**회의 끝나고 당일 업데이트 예정**
[CH1 아트 리소스 리스트](https://docs.google.com/spreadsheets/d/1xLu0o7xpz4A3foy7fB_kl-RDrlTBvMuX/edit?usp=sharing&ouid=102142728386857128653&rtpof=true&sd=true)
[CH2 아트 리소스 리스트](https://docs.google.com/spreadsheets/d/1Dm7b5r5Cmk4YC4DTW4ureRnq3Xmny8bs/edit?usp=sharing&ouid=102142728386857128653&rtpof=true&sd=true)

- 설정창 UI 기획 컨펌 후 작성 예정
- 럭키 애니메이션 작성 예정
- CH2 리스트 배경/스탠딩은 스토리에 따라 점검 필요(그 외엔 점검 완료)
------

### 241001 업데이트

[CH1 아트 리소스 관리 문서](https://docs.google.com/spreadsheets/d/1xLu0o7xpz4A3foy7fB_kl-RDrlTBvMuX/edit?usp=sharing&ouid=102142728386857128653&rtpof=true&sd=true) 업데이트

추가 리소스 탭 19번부터 추가했습니다. 
럭키 모션 관련 리스트는 컨펌 한 번 부탁드려요!

[CH2 아트 리소스 관리 문서](https://docs.google.com/spreadsheets/d/1Dm7b5r5Cmk4YC4DTW4ureRnq3Xmny8bs/edit?usp=sharing&ouid=102142728386857128653&rtpof=true&sd=true)
위자드 스톤 탭 수정 완료
메인탭 UI와 관련된 1~6번은 수정 완료 (CH2 메인 리소스는 일단 수빈님께 부탁드렸습니다.. )

**고민**
1. 28번 럭키 모션을 어떻게 연출할까요?
요술봉 같은 걸 손에 들고 나타나서 한 번 바닥에 뿅 내리치면 물고기가 생기게?
그냥 진짜로 물고기를 들고 나타나서 내려두게?

2. 31번 모션도 회의 때 나왔던 내용이 떠올라서 넣긴 했는데 호불호가 조금 갈릴 수도 있을 것 같아 의견을 듣고 싶네요

**Comment by fkdl0048** [comment]
@Sumindd @wooyn730 수민님이랑 우연님이랑 한번 이야기해서 CH2 메인 시스템 내용을 좀 정해야 할 것 같습니다.
CH2의 경우 비주얼 노벨 장르라 엑셀파일로만 동작해야 해서 두분이서 데이터 어떻게 다룰지, 컨벤션 등 정하면 좀 더 작업 수월하실 것 같아요

예상 현재 엑셀이 방문 가능한 장소와 해당 장소에 이벤트 ID 작성 (아마 이벤트 ID는 yarn으로 다루지 않을까 싶습니다.) 이벤트 리스트 엑셀이나 TCG 데이터 파일 등 생각보다 다룰 데이터가 적어서 금방 되실 것 같아요

기획쪽에서 구드만 수정하면 데이터 적용될 수 있도록 에디터에서 따로 웹서버에서 받아오는 툴팁을 만들어야 더 편하게 작업하실 것 같아요 (매번 받아오는게 아니라, 버튼 누르거나 에디터 시작할 때)

**Comment by Sumindd** [comment]
240929 업데이트 완료

**Comment by Sumindd** [comment]
240930 업데이트 완료

**Comment by fkdl0048** [comment]
## 번역탭 튜토리얼

라플리 기존 UI와 비슷한 디자인인데 너무 SLG UI같은 느낌이 드는 것 같아요. 붙어 있어서 그런 것 같기도 하고.. - < 3개로 표현된 형태가 제일 깔끔하지 않을까? 싶습니다. 뒤에서도 보여주기 위해서는?

## 럭키 위치 고정

말씀해주신대로 목걸이가 조금 불안해보이는 느낌이 있네요. 외발로 서있는 느낌이라 보민님이나 다른 분들 생각도 들어보면 좋을 것 같습니다.

다른 내용은 다 확인했읍니다!

**Comment by Songkihwa** [comment]
문서 복구하시느라 고생 많으셨습니다!
확실히 설정창의 번역탭은 유저에게 알려줄 필요가 있어보이네요. 

럭키 같은 경우는 팔 다리가 꼭 있어야될 것 같다고 말했었는데 흑흑
(이 게임에서 사운드 제외 가장 강력하게 주장한 의견이였읍니다 ..) 

> 그냥 개인적인 아쉬움인거라 무시하셔두 됩니다 

일단 저도 럭키가  열쇠를 매달고 있다기보다는 몸이 열쇠같은 느낌이 들기도 해서
얼굴만 나오는거니까 열쇠를 빼는 것도 방법일 것 같고 아니면 
열쇠를 입에 물거나, 머리 위에 얹거나 하는 방법들도 괜찮을 것 같습니다.

**Comment by roweclaw** [comment]
new 표시 자체는 괜찮은데 저도 설정창 디자인이 살짝 slg스러운 느낌이라
깃발 같은 모양을 빼고 톱니바퀴만 사용하거나, 줄 3개로 이뤄진 형태로 사용하는 등 좀 더 심플한 디자인이 좋을 것 같습니다.

럭키도 이제는 얼굴만 나오는 상황이라 달랑달랑 있는 열쇠가 자꾸 신경이 쓰이네요...
열쇠가 얼굴 밑에 없어야지 딱 얼굴로 집중이 될 것 같아서 기화님 말씀처럼 다른 방법이나 아예 빼야 할 것 같네요!

**Comment by Sumindd** [comment]
241001 업데이트 완료
럭키 모션에서 고민이 있어서 적어뒀습니다. 코멘트 부탁드려요!

**Comment by fkdl0048** [comment]
> 28번 럭키 모션을 어떻게 연출할까요?

저도 조금 고민이긴 해서 보민님 의견 들어봐도 좋을 것 같습니다. 럭키라는 존재가 자유롭다 보니 연출적으로 편하고, 납득만 되면 될 것 같다는 생각이라.. 뭔가 소환하거나 만들어내는 느낌이니까 마술사 손으로 딱 하는 그 모션으로 해도 되지 않을까? 싶어요
물고기고 럭키 등장하는 뭉개뭉개 구름 이펙트가 나오고 럭키 손이 마술사 손으로 딱 하는 모션?

> 31번 모션도 회의 때 나왔던 내용이 떠올라서 넣긴 했는데 호불호가 조금 갈릴 수도 있을 것 같아 의견을 듣고 싶네요

저도 이건 보민님 의견을 들어보고 싶습니다! 변경전 럭키도 정면보다는 옆을 바라보고 있는데, 뉴럭키가 유저를 바라본다는 정면 설정도 좋고, 인게임을 바라보는 듯한 옆모습이 나오면 좀 더 메타적일 것 같은 느낌?

**Comment by wooyn730** [comment]
> 28번 럭키 모션을 어떻게 연출할까요?

완전히 물고기 등장용으로 모션을 만들면 재활용 할 수 없어 비효율적일 것 같습니다.
수민님과 정안님 의견도 좋고 제 아이디어는 핑거 스냅?
나중에 또 무언가를 등장시킬 때 재활용할 수 있는 모션이면 좋겠네요

> 31번 모션도 회의 때 나왔던 내용이 떠올라서 넣긴 했는데 호불호가 조금 갈릴 수도 있을 것 같아 의견을 듣고 싶네요

완전 왼쪽보다는 살짝 왼쪽에 관심을 기울이는 느낌...?으로 표현되면 좋을 것 같아요ㅎㅎ

**Comment by roweclaw** [comment]
[CH2 아트 리소스 관리 문서](https://docs.google.com/spreadsheets/d/1Dm7b5r5Cmk4YC4DTW4ureRnq3Xmny8bs/edit?usp=sharing&ouid=102142728386857128653&rtpof=true&sd=true) 중 'CH2 메인 탭'의 관리를 제가 맡게 되어서 7번부터 수정했습니다.
- 수민님은 전체적으로 잘 작성되었는지 확인 한 번 부탁드려요! @Sumindd 
- 31, 32, 44, 49, 52번은 애매하면 컷씬으로 넘겨야 할 것 같은데 의견 주시면 감사합니다!

**Comment by Sumindd** [comment]
원래도 비주얼 노벨 장르 특징 때문에 중요한 장면이나 연출적인 장면은 컷씬으로 처리하고 싶었어서 컷씬으로 몇 개 넘기는 건 괜찮은 것 같아요! 나중에 스크립트 어느정도 작성된 후에 하이라이트에 해당하는 부분도 추가하면 좋을 것 같네요

**Comment by roweclaw** [comment]
네 좋습니다!  31, 32, 49, 52번은 후순위로 변경했고, 아마 추후 기획회의 할 때 컷씬 부분 논의한 뒤 확정 될 것 같습니다.

**Comment by fkdl0048** [comment]
넵 중요한 분기에서는 좀 더 논의하고 정해도 좋을 것 같네요!
