### ISSUE TITLE
[CH2] 장소 표시 UI 수정

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/Grayed-Game#704]
# [CH2] 장소 표시 UI 수정

![{0735C962-4525-44CB-8D9E-990058EAAADA}](https://github.com/user-attachments/assets/250b030f-cd8e-4a19-b9ab-854a901f5571)

CH2의 장소 이동 UI가 등장 후 사라져야 함

연출에 관한 내용이라 fade in/out으로 하는지, 왼쪽에서 등장해서 다시 들어가는지..? 정해지면 다른 연출도 비슷하게 써야할 듯 만약 fade로 가면 현재처럼 장면 이동 시 fade를 쓰는 형태로 통일되지 않을까?

등장으로 사용하면 장소 이동 시, 페르소나 처럼 화면을 가리는 UI가 등장하고 장소가 이동되는? (대각선의 검정 선이 화면을 덮고 다시 열리는?) 느낌이 나야할 것 같음 -> 현재 UI에는 이게 맞을 것 같다는 생각도 듬

**Comment by fkdl0048** [comment]
@wooyn730 @Sumindd 확인 해주시고 여기서 작업 해주시면 됩니다!

**Comment by wooyn730** [comment]
보민님 설정창 버튼 -> 수민님 정리 -> 우연 적용
순으로 진행할 예정입니다~!

**Comment by Sumindd** [comment]
![Group 189](https://github.com/user-attachments/assets/e8f2981b-e95b-4e26-96f0-66e67d7d78c9)
근데 저도 여기저기 위치 좀 옮겨봤는데 위치가 애매하게 못생긴 것 같기도 하네요... 계획에 없던 메뉴바가 생겨서ㅠㅠ
보민님이 배치 의견 주시면 좋을 것 같아요 

![제목 없는 동영상 - Clipchamp로 제작](https://github.com/user-attachments/assets/bda103e6-4ca1-4e4e-b09b-2fac3f59c9fd)
일단 등장 속도만 확인해서 gif 뽑아봤습니다   
![image](https://github.com/user-attachments/assets/868a1abf-8e1b-4a3d-ac73-33a48c82f665)
Dotween 기준 InQuad 0.5 정도가 적당하게 느껴졌어요

GG가 흑백이기도 하고 개인적으로 비주얼 노벨 장소 전환이나 화면 전환이 느린 페이드인 아웃인 건 좀 올드하게 느껴질 수도 있을 것 같아요
그래서 배경 전환도 속도를 올리거나 화면 변환 연출 고민해보면 좋을 것 같네요. 예를 들면 정안님이 말씀하신 것처럼 화면 가리고 갈라서 나오는 연출이라거나?

**Comment by wooyn730** [comment]
설정 아이콘을 차라리 오른쪽 상단으로 이동하면 어떤가요?
어차피 SLG UI들도 왼쪽 상단에 있어서 위치가 애매해질 것 같네요
비주얼 노벨 아이콘(자동진행, UI 숨기기)은 아직 안나왔지만 수민님 예시?를 보면 설정창이랑 붙여도 다른 것보다 어울릴 것 같아요

**Comment by Sumindd** [comment]
- #742 비주얼 노벨 아이콘 아이콘은 보민님이 작업해주신 1차 시안 모습이긴 합니다!
그러면 CH2에서만 설정 아이콘 위치를 옮긴다는 걸까요? 
설정적으론 문제 없을 것 같은데 통일성 떨어져서 조금 호불호가 갈릴 것 같네요.. 왼쪽 상단이 메뉴 아이콘의 국룰 위치기도 하고요.. 다른 분들의 의견도 궁금합니다

**Comment by wooyn730** [comment]
헐~ 보민님이 작업해주신 건 줄 몰랐네요 알림 지금 확인했어요 어쩐지 잘어울리더라...ㅎㅎ
