### ISSUE TITLE
[CH1] 마마고 컴퍼니 위치 변경에 따른 디자인 결정

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/Grayed-Game#706]
# [CH1] 마마고 컴퍼니 위치 변경에 따른 디자인 결정

- https://github.com/GG-Studio-990001/Grayed-Game/issues/683#issuecomment-2380639363
@JIJI037 위 이슈 참고하셔서 지은님이 위치 잡아주시면 됩니다!

작업은 여기서 하시면 됩니다.

**Comment by wooyn730** [comment]
저는 이건 현정님이 수민님 피드백 한 번 수용해서 수정하고,
이후에 빌드랑 캡쳐 확인해서 지은님이 피드백 주시면 좋을 것 같아요

**Comment by fkdl0048** [comment]
@jeongopo 확인 부탁드립니다~
