### ISSUE TITLE
[CH1] SLG 마우스 등장 효과음 (@Songkihwa )

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/Grayed-Game#707]
# [CH1] SLG 마우스 등장 효과음 (@Songkihwa )

SLG UI 튜토리얼에서 등장하는 마우스 등장 시 효과음 제작

- 현재 번역팩 쪽은 수정이 들어가서 확정된 마우스 부분만 사운드가 필요합니다!

[SLG 마우스 등장 효과음 1](https://drive.google.com/file/d/15bvp6vHQHh5YA2Dn1SVaxAwG0hj5wVOG/view?usp=drive_link)
뭔가 등장하는 효과..?! 애니메이션..?! 같은게 없고 갑자기 장면이 뽁 하고 바뀌면서 등장하는 것 같아서 깔끔한 UI 사운드 느낌으로 뽁 하고 등장하게 만들어봤습니다.

[SLG 마우스 등장 효과음 2](https://drive.google.com/file/d/1U5N1KvrWrS_U3o4XDjd8fW2UAEuztX6w/view?usp=drive_link)
요건 고전적인 빠밤~ 효과음을 추가해서 마마고 완공 효과음 깔과 비슷 + 고전적인 느낌으로 해봤습니다!

요거 마음에 안들어도 다시 만드는거 빨리 할 수 있으니까 의견 맘껏 주셔도 됩니당.
확정나면 최종 버전 파일로 올리겠습니다!

**Comment by fkdl0048** [comment]
이건 그냥 사운드분에게 궁금증인데, 럭키 디자인이 바뀌게 될텐데 사운드도 바꿔야 한다고 생각하시나요? @Songkihwa

**Comment by Songkihwa** [comment]
제 개인적인 욕심으로는 많은 분들이 럭키 비지엠도 많이 좋아해주셨고 저도 만들때 잘 나왔다고 생각이 든 작업물이라 바꾸고싶지 않아요. 
그치만 게임적으로 봤을 때 럭키 이미지에 담긴 성격과 분위기가 달라져서 사운드와 안 맞는다고 느껴진다면 바꿔야 한다고 생각합니다.

열심히 만든 마음에 드는 작업물 없어지는게 만든 사람 입장에선 슬프고 힘 빠지는 일이기도 해서,, (럭키 비지엠은 유독 그러네요?)
앞으로는 사운드 비용적인 측면이나, 관련되어서 얘기하는 제 의견들도 잘 들어주시고 더 생각해주시면 감사하겠습니다.

**Comment by Songkihwa** [comment]
@wooyn730 우연님 저 갑자기 윈도우에서 게임 녹화가 안되서 그러는데 혹시 마우스 등장 부분만 녹화해서 올려주실 수 있으실까요 ..?!

**Comment by wooyn730** [comment]
물론이죠!!

https://github.com/user-attachments/assets/45cbbe7e-4cd4-4def-84f5-454ebb55084b

**Comment by Songkihwa** [comment]
감사합니당!

**Comment by Sumindd** [comment]
효과음2가 적당한 것 같아요. 너무 과하지도 않으면서 적당히 시선 끌어주는 느낌이라 좋네요!

**Comment by roweclaw** [comment]
저도 마우스 뒤의 빛 효과가 뽁! 보다는 빠밤~ 하는 효과음2랑 잘 어울리는 것 같습니다! 마우스가 새로 등장해서 앞으로 사용할 수 있다는 것을 알려주는 용도의 효과음으로 적합한 것 같네용

**Comment by wooyn730** [comment]
뽁 없이 빠밤~만 있는건 어떨까요?

그리고 _(저번에도 코멘트 달긴 했지만?)_ 등장 이펙트도 추가해서 스케일이나 알파값에 영향을 주면 좋을 것 같네요

**Comment by wooyn730** [comment]
저는 빠밤~ 좋네요

등장 이펙트는 저는 있었으면 좋겠는데 다른 분들 생각이 궁금합니다
수민님이나 현정님이 정해주시면 좋지 않을까...
