### ISSUE TITLE
[CH1] SLG 관련 버그 (@jeongopo )

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/Grayed-Game#708]
# [CH1] SLG 관련 버그

현재까지 제보된 CH 1 SLG 관련 버그들입니다. 확인하고 빠진 거 있는지 말씀해주세요

- [x] SLG 마마고 건설 이후 업데이트 안됨 (아래 패널)
- [x] SLG 마우스 등장 시 흔들림

### 11/11 발견 버그
- [x] 건설중 스프라이트 깨지는 버그
![image](https://github.com/user-attachments/assets/63991e7a-d31c-4f98-a80a-4f15544fd3e8)

- [x] 마마고 건설 페이드 이후에 건물 스프라이트 바뀌게 수정

~기계어 번역팩 획득 이후 알투몬 위치 수정. 마마고 안에서 나오자마자 보이게 (기획에서 요구생기면 수정하기로함)~
- [x] 마마고 건설중간단계 스프라이트 위에 건설말풍선이 라플리 위치에 따라 레이어가 바뀜

**Comment by jeongopo** [comment]
241110 기준 모두 수정했습니다.
빌드에서 체크해주시고 이상없으면 내일 이슈 닫겠습니다.

**Comment by jeongopo** [comment]
일감 다시 살려서 여기서 버그 작업하겠습니다

**Comment by jeongopo** [comment]
![image](https://github.com/user-attachments/assets/58308fdb-547f-45d8-ba79-9d78c1c02ac9)

스프라이트 깨지는거랑 말풍선 위치 바뀌는건 에디터에서 재현은 안돼서
일단 말풍선 위치 우선순위 조정해보긴했는데 빌드테스트에서 다시 발생하면 다시 확인해봐야할것같습니다 (；′⌒`)

**Comment by jeongopo** [comment]
내일 테스트 이후 문제없으면 이슈 닫겠습니다.

**Comment by jeongopo** [comment]
이상 없는걸로 보여서 이슈 닫겠습니다~
