### ISSUE TITLE
전체 기획 설명서 V0.3.0

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#716]
게임의 성격, 속성, 엔딩 등의 전체적인 기획 내용을 한 눈에 파악할 수 있는 문서로 정리합니다.

---

[[241015] 전체 기획 설명서 V0.3.0](https://drive.google.com/file/d/1dU5Y-jF81-cBmtWxGpWx3UyZYANiRtm1/view?usp=sharing)

챕터별 상세 시스템 기획을 제외한 모든 기획 사항을 요약 정리 했습니다.
내용이 많은 문서는 따로 원본 링크를 좌측 하단에 걸어두었어요.
빠진 내용이 있거나 수정사항 등 검토해주시면 반영하겠습니다.

**18시10분 기준 업데이트**
- 8페이지 : `잊혀진 게임이 떨어지는 형태` 추가
- 9페이지 : `접속/역접속` 설명 수정

**241015 업데이트**
- 12페이지 : `리소스 규모` 추가
- 13페이지 : `리소스 보충설명` 추가

**Comment by roweclaw** [comment]
241014 업데이트 했습니다!

**Comment by fkdl0048** [comment]
잘 정리해주셔서 감사합니다! 제가 빼먹고 생각한 부분도 잘 넣어주셔서 다시 보니까 더 잘 이해가 되네요 좀 더 추가하면 좋을 것 같은 부분은 따로 적어두겠습니다.

- 게임 설정부분에 하늘에서 게임이 어떠한 형태로 떨어지는 것인지 에 대한 설명이 추가되면 좋을 것 같습니다. 제각기 다른 형태로 존재할 수 있다. (추상적, 리소스, 게임이라는 형태) 
- 속성/접속의 경우 역접속과 접속의 차이를 사람이 인지하는 덩어리의 크기(개념적인)로 발생한다는 점이 추가되면 역접속과 접속의 차이를 이해하는데 도움이 될 것 같습니다.
- `장르란 메타적인 세계를 바라볼 수 있는 시각이다.` 말 정리가 너무 잘 된 것 같습니다.

가능하면 새로 참여하신 분들이 읽고 이해가 안되거나 이상하다고 생각하시는 부분들을 짚어주시면 더 좋을 것 같습니다!

**Comment by roweclaw** [comment]
18시10분 기준 업데이트 했습니다!

**Comment by Sumindd** [comment]
내용 오류 없고 너무 깔끔하게 잘 정리해주신 것 같습니다!

아래 내용은 개인적으로 나중에 설명회 할 일이 있으면 쓰려고 메모 해뒀던 내용이 있어서.. 추가할만 한 게 있다면 참고해서 추가해주셔도 좋을 것 같습니다!

--- 
라플리가 게임이라고 하는 이유 - 라플리는 NPC 리소스 조각이 아니라 게임이다. 그래서 유저가 '플레이'가능하고, 고유 UI또한 라플리라는 게임의 UI이다. 유저는 라플리라는 게임을 통해 Grayed Game이라는 게임을 바라보고 있는 것이다. 

라플리 - UI + NPC 리소스 + 설정이라는 시스템 일부 남아있는 상태
완전한 게임의 형태보다 바로 아래 단계쯤

알투몬은 Grayed Game의 오리지널 캐릭터다. 그래서 모든 색 있는 게임을 만져도 접속이 일어나지 않는다. 메타적으로 GG에 등장하는 모든 게임은 GG에 속해있는 리소스 일부일 뿐이므로.. 

접속과 역접속을 구분하는 기준 - 규모
더 큰 규모의 리소스 뭉치가 이기는 구조다. 
3매치는 그냥 리소스 조각 아닌가?  - '시스템'이 남아있는 게임의 일부이다. 파머 달러 같은 NPC 리소스 조각이 만지면 빨려 들어갈 수도 있음


![image](https://github.com/user-attachments/assets/2d9c0518-754e-4f62-93ee-59b5986cc7e4)
(제 상상속 구조.. 오류나 조금씩 다르게 생각하는 부분이 있을 것 같습니다. 코멘트나 기획 회의에서 내부 설정적으로 단계 조율 해봐도 좋을 것 같네요!)

**Comment by fkdl0048** [comment]
> 알투몬은 Grayed Game의 오리지널 캐릭터다. 그래서 모든 색 있는 게임을 만져도 접속이 일어나지 않는다. 메타적으로 GG에 등장하는 모든 게임은 GG에 속해있는 리소스 일부일 뿐이므로..

이거 정말 말을 잘 설명하는 문장인 것 같습니다. 마마고도 마찬가지로 설명이 가능해질 것 같아요

규모에 대한 계급도 잘 정리된 것 같읍니다.

**Comment by fkdl0048** [comment]
@Sumindd 

- https://github.com/GG-Studio-990001/Grayed-Game/issues/716

현재 이슈 0.3.0 마일스톤으로 넣어주시고, 제목도 버전에 맞게 수정하고 지속적으로 버전관리 되면 좋을 것 같습니다. 0.4.0/0.5.0/... 이후로 뭔가 수정사항이 생기면 업데이트 하면 더 관리가 잘 될 것 같아요!

**Comment by NearthYou** [comment]
기획서 잘 읽었습니다! 한 눈에 보기 편하게 정리해주셔서 금방 읽었던 것 같아요. 
혹시 저희 게임 공모전 같은 곳 낼 때 장르 뭐라고 적어서 내나요? 메타 어드벤처? 퍼즐?

**Comment by fkdl0048** [comment]
@NearthYou 대표 장르는 `어드벤처` 장르로 제출하고 있습니다! 홍보할 때는 `장르없음`으로 밀고 나가는 느낌..

**Comment by vprwolf** [comment]
정리를 잘해주셔서 저도 큰 흐름을 잘 이해할 수 있었습니다!
재차 읽어보고 혹시나 질문이 생기면 여기에 질문드려도 되나요..!

**Comment by roweclaw** [comment]
다행이네요~ 질문은 여기다가 해주시면 됩니다!

**Comment by fkdl0048** [comment]
@roweclaw 리소스 규모 부분 수정 부탁드립니당

**Comment by roweclaw** [comment]
241016 업데이트 완료용

**Comment by wooyn730** [comment]
잘 읽었습니다 고생하셨어요!
개요~성격 까지는 발표를 듣는 기분이 들기도 하네요 ㅋㅋ

> 다시하기

`다시하기`가 기획에 포함되니 더 명확해졌네요. (슈아브에 다시하기 포함된 것도 확인했고)
이것과 접속게임 문서를 읽으니 '접속게임을 플레이하다가 게임을 껐다 켜면 어디서부터 시작하느냐'가 문득 궁금해졌네요.
탈출이 '접속게임을 클리어하여 밖으로 빠져나오게 됨'이라면 게임을 다시 켰을 때 접속게임부터 시작하는 게 맞는지, 아니면 접속게임을 시작 전 상태로 저장된 셈 치고 그 전 상태로 돌아가는지..??
(_참고로 원래 팩맘은 지면 게임오버되는 설정이었는데, 당시 게임오버도 따로 구체화되지 않아서 간단하게 제가 '게임을 지면 그냥 갇힌 채로 다시 플레이하게 하는 건 어떠냐'고 의견을 제시했던 걸로 기억합니다. 그리고 지금 팩맘은 1트에 게임 실패하고 껐을 때 실패한 상태는 저장하되 다시 게임을 켜면 맵1에서 팩맘기계 앞에 라플리가 서있습니다.._)

>

**Comment by roweclaw** [comment]
제 생각에는 접속게임을 플레이하는 중에 게임을 껐다 킨다면, 클리어된 상태가 아니기 때문에 탈출하지 않고 그대로 접속되고 있는 것으로 간주할 것 같긴 합니다. 따라서 접속게임에서 저장된 순간이 있다면 그 상태로 돌아가서 시작할 것 같네요!

**Comment by roweclaw** [comment]
- #728

위 이슈 참고해서 **16~19페이지: 기획 방향성(게임공통의도/시스템) 추가** 업데이트 했습니다~!
