### ISSUE TITLE
[Bug] 설정창 화면 모드 변경 버그

### ISSUE THREAD

**Issue by NearthYou** [GG-Studio-990001/Grayed-Game#721]
# BUG: 설정창 화면 모드 변경 버그 수정

## Description
- 설정창 전체 화면, 창모드 버그 (두개 다 선택되는 경우 생기면 이상하게 작동)

## Solution
- [x] 창모드 기본 포맷 1920*1080 에서 수정 필요.
- [x] 하나가 선택되면, 나머지 하나가 꺼지는 플립플롭 구조로 변경 필요.

## ETC
- [x] 설정창 SFX 예시 효과음 추가. SFX 중에 짧은 사운드 하나 골라서 넣기.
- [x] 스크린 설정 왼쪽 정렬.

**Comment by Sumindd** [comment]
설정창에서 SFX 음량 크기를 조절할 때마다 [SLG 석재 사운드](https://drive.google.com/file/d/1Pbwu1tMPVzevGQZquXLMcZpWSVHW5i45/view?usp=sharing) 1회씩 출력해서 음량 조절 용이하게 수정해주시면 될 것 같습니다! 배경 음악은 따로 넣지 않으셔도 됩니다.

**Comment by wooyn730** [comment]
저는 Alt+Enter로 창모드 변경을 자주 하는데 이것도 적용되게 변경되면 좋겠어요~
(현재: 전체화면에서 Alt+Enter하면 창모드 되긴 하는데 토글은 전체화면임. 그 상태에서 다른 씬 넘어가면 다시 전체화면으로 바뀜)
