### ISSUE TITLE
[CH1] 번역팩 획득 이펙트

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/Grayed-Game#734]
# [CH1] 번역팩 획득 이펙트

![{9EBC3E70-31ED-46CD-92E4-01527D2D9FD2}](https://github.com/user-attachments/assets/2647ab84-2ed5-4d0f-9cd1-cc0b4e5ba74b)

해당 그림 흑백으로 재해석한 이펙트 필요
현재 라플리가 번역팩을 획득해도 같은 그레이스케일을 공유하여 눈에 보이지가 않음 (이펙트도 마찬가지로 흑백이어야 하지만, 하양색을 좀 강조해야 하지 않을까..?)

**Comment by wooyn730** [comment]
- #737 로 합침
