### ISSUE TITLE
[UI] 설정창 아이콘

### ISSUE THREAD

**Issue by vprwolf** [GG-Studio-990001/Grayed-Game#736]
**2024.10.25**

### 설정창 태그 1차

1차 시안 먼저 보내드립니다
![Slide 16_9 - 35](https://github.com/user-attachments/assets/0a9be9df-389b-4e23-9d07-6780e16ecc1b)
--------
**2024.11.04**

**바 형태**
![Slide 16_9 - 36](https://github.com/user-attachments/assets/146979ca-b5e6-492e-a9f6-5afb61a11570)

**new**
![Slide 16_9 - 37](https://github.com/user-attachments/assets/0045924a-cb17-4286-a6f8-3cfae71baa03)

**Comment by wooyn730** [comment]
`PDF에 있는 번역팩 튜토리얼에서 설정창 UI 일반적인 선 3개로 표현하는 설장창 UI로 교체`
![image](https://github.com/user-attachments/assets/bb49e2e7-f6c1-47e9-825c-a57de70b7ce1)

정안님 코멘트 전달 드릴 때 저는 이런 걸로 이해했습니다...

**Comment by vprwolf** [comment]
**2024.11.04**

바형태 설정창으로 수정했습니다!

**Comment by roweclaw** [comment]
바 두께가 다른 디테일이 있어서 좋은 것 같습니다. NEW 표시도 잘 보여서  좋아요!!
