### ISSUE TITLE
[CH1] 번역팩 효과

### ISSUE THREAD

**Issue by vprwolf** [GG-Studio-990001/Grayed-Game#737]
![{9EBC3E70-31ED-46CD-92E4-01527D2D9FD2}](https://github.com/user-attachments/assets/2647ab84-2ed5-4d0f-9cd1-cc0b4e5ba74b)

해당 그림 흑백으로 재해석한 이펙트 필요
현재 라플리가 번역팩을 획득해도 같은 그레이스케일을 공유하여 눈에 보이지가 않음 (이펙트도 마찬가지로 흑백이어야 하지만, 하양색을 좀 강조해야 하지 않을까..?)

---

**2024.10.25**

### 번역팩 효과 (도트X버전)

![light](https://github.com/user-attachments/assets/995028cb-743f-42e2-a2f5-00ca658852d0)

**2024.11.03**

### 번역팩 효과 (도트 버전)
![light2_back](https://github.com/user-attachments/assets/c7a2da92-1122-417b-b0f8-504e9bdcc9c1)

---

**2024.11.17**

효과 수정
![light0202_01](https://github.com/user-attachments/assets/303b0238-4b76-42d0-b966-fc9a5dc4b029)

밝은면적을 조금 더 키워봤습니다!

**Comment by wooyn730** [comment]
회의때 도트로 이야기 나눴던 거 같은 데 아닌가요?
저는 도트 버전으로 보고싶고 번역팩에만 사용되는 빛이니 번역팩 스프라이트를 수정해주시면 좋을 것 같아요!

**Comment by vprwolf** [comment]
**2024.11.03**
도트버전도 업데이트 합니다!

**Comment by roweclaw** [comment]
도트 버전 퀄리티 좋네요!! 고생하셨습니다~ 👍

**Comment by fkdl0048** [comment]
깔끔하네요! 적용된 버전으로 보면 좋을 것 같습니닷

**Comment by wooyn730** [comment]
![스크린샷 2024-11-11 183100](https://github.com/user-attachments/assets/3deb9f39-4154-4c06-8c36-f8ff79de9a94)
![스크린샷 2024-11-11 183214](https://github.com/user-attachments/assets/e529eec5-9935-449c-b1d9-a27cd03836fc)

느낌 괜찮네요!
저는 효과 이미지가 사이즈(반지름?)가 더 작고, 번역팩과 가까운 부분이 좀 더 불투명하면 좋을 것 같아요~

**Comment by vprwolf** [comment]
**2024.11.17**

효과 수정본 업로드 합니다!

**Comment by wooyn730** [comment]
구드에 올리고 링크 남겨주세요!

**Comment by wooyn730** [comment]
![image](https://github.com/user-attachments/assets/b0a02827-70cd-407c-88f6-6873b83eb110)
빛 사이즈(이미지에 존재하는 네모의 개수)는 줄은 거 같은데
이미지 사이즈는 이전 이미지보다 오히려 커져서 (왜죠? ㅠㅠ.....)
임의로 조절했는데 의도하신게 이게 맞나요?

![image](https://github.com/user-attachments/assets/2d45671b-c327-4fc4-91da-fb9c8e4ee310)
하나의 픽셀 안에서는 그라데이션 없이 같은 색상이었으면 좋겠어요

![화면 캡처 2024-11-18 200019](https://github.com/user-attachments/assets/e598ad4a-c2d3-4b55-a447-8cb3871d0157)
그리고 저는 이렇게 빛의 네모(픽셀?) 크기랑 번역팩 네모 크기랑 동일하게 배치하고 싶은데

![스크린샷 2024-11-18 200031](https://github.com/user-attachments/assets/a8687564-f423-40a6-aa4f-f65640832d04)
그러면 사이즈가 이렇게 너무 작아지네요..



---

사이즈 줄여주신 거 감사해요! 사이즈는 이전보다 작은 게 좋은 거 같아요

근데 작업을 어떤 툴로 하고 계신지 여쭤봐도 될까요?
번역팩 그리신 것처럼 주변에 빛 추가해서 그리고 빛+번역팩 하나의 이미지로 주시면 안될까여 ........

**Comment by wooyn730** [comment]
감사합니다🥹!
저 너무 까다롭죠..? ㅋㅋㅋㅋ 죄송해요......
_(제가 디테일 잡는다고 아트 많이 갈궈봤습니다 죄송합니다.............)_
