### ISSUE TITLE
[CH2] 아리오 브라더스 캐릭터

### ISSUE THREAD

**Issue by vprwolf** [GG-Studio-990001/Grayed-Game#738]
**2024.10.25**
### 캐릭터 시안 1차

라플리 형태를 버섯(?)에 가까운 형태로 가야 할지 현재 도트 그래픽의 비율로 가야 할지 파악하지 못해 일단
두 사이즈 형태로 시안을 만들었습니다! 
라플리 형태에 따라 엔젤 브라더스의 비율도 재조정 할 것 같습니다. 피드백 부탁드립니다.

![캐릭터](https://github.com/user-attachments/assets/de5f0ca3-5217-4588-ba72-6c9a472d5e93)

------------------------------------------

**2024.11.03**

수정사항 반영해 2차 시안을 올립니다
![도트2](https://github.com/user-attachments/assets/d63852e2-ff28-4f64-a91e-e20c2f153fd1)

------------------------------------------

**2024.11.16**

수정사항 반영해 3차 올립니다!
![도트](https://github.com/user-attachments/assets/9e6a97f4-3221-4439-a1bb-30a352c1fbe3)

**Comment by wooyn730** [comment]
저는 버섯에 가까운 형태라고 생각했습니다!
라플리 머리에 흰색 점박이를 추가하면 좀 더 버섯 느낌이 날 것 같습니다.

아리오버전 미카엘 느낌 좋은데요?
엔젤링이 좀 더 링처럼 보이면 좋을 것 같아요

**Comment by jeongopo** [comment]
넘귀엽네용
전 2번이 좀더 쨍해서 색감 구분이 잘될것같아서 더좋은것같습니당

![image](https://github.com/user-attachments/assets/bee0d4ed-1d75-47af-b1e9-a4a0e97b6347)

**Comment by vprwolf** [comment]
**2024.11.03**

수정사항을 반영해 2차시안을 올립니다

**Comment by wooyn730** [comment]
미카엘 링 수정된 거 아주 좋아요!
저저번 회의 때 말한 것처럼 색이 살짝 더 들어가면 좋겠는데 파란 눈이라던가 이런건 어떤지...
(천사 눈은 보통 무슨 색이죠..?)

버섯 점박이는 사실 저도 최신 버전 생각해서 흰색 요청드린건데
레퍼런스 보니 아주 옛날 버전 느낌의 버섯이 좋겠네용 ^_^.., 제송

**Comment by vprwolf** [comment]
**2024.11.16**

3차 수정 업데이트 합니다!

**Comment by roweclaw** [comment]
눈 색이 진해져서 알아보기 좋네요! 고생하셨습니다 👍
