### ISSUE TITLE
[CH2] UI 작업

### ISSUE THREAD

**Issue by vprwolf** [GG-Studio-990001/Grayed-Game#742]
**2024.11.03**

상단 가시성, 자동재생 버튼 1차 작업을 업로드합니다 :)
![novel](https://github.com/user-attachments/assets/31e567bf-2aaa-4bac-96f6-64bf19ade06c)
----------------

**2024.11.17**

-장소 부분 디자인 수정 추가
-가시성, 자동 버튼 눌렀을때 추가
2차 업로드합니다 :)

![Slide 16_9 - 38](https://github.com/user-attachments/assets/68f01a0e-d1e5-43b6-8f2f-172d27fc3ac6)
![Slide 16_9 - 39](https://github.com/user-attachments/assets/6d980b63-17d2-425d-8c3b-f5c1fabcad1c)

올리고 보니 눌렀을때와 누르기 전 색상을 바꾸는게 나아보이네요.. 한번 더 적용해 봐야겠습니다!

**Comment by vprwolf** [comment]
**2024.11.03**

상단UI 1차 작업 업로드합니다:)

**Comment by Sumindd** [comment]
on/off 되었을 때의 모습도 각각 보여주시면 좋을 것 같습니다!

**Comment by wooyn730** [comment]
저도 수민님 코멘트 동의요~

라플리 고유의 각진 느낌이 여기서도 드러나서 좋네요
다만 왼쪽의 위치 UI랑은 다른 느낌이 나서(특히 안의 아이콘) 위치 UI도 새로 만들어주시면 좋을 것 같아요!

**Comment by vprwolf** [comment]
**2024.11.17**

수정및 추가 업로드 합니다 :)

**Comment by wooyn730** [comment]
구드에 올리고 링크 남겨주세요!

**Comment by vprwolf** [comment]
https://drive.google.com/drive/folders/1cw3jX3S_83PwLmOsrFBP5Eu02wEEvR7N?usp=drive_link
에 올렸습니다!

**Comment by vprwolf** [comment]
**2024.12.18**
상단 가시성/오토 아이콘 수정본 업로드합니다!
on/off 시 색상과 빗금으로 구분하도록 수정했습니다!
![예시1](https://github.com/user-attachments/assets/f431b88e-9ba0-4fb7-954d-c5438cf5e61f)
![예시2](https://github.com/user-attachments/assets/b27f9f05-56d8-4373-aa3d-a23b59607748)

구드에도 v2로 업로드 했습니다:)
https://drive.google.com/drive/folders/1cw3jX3S_83PwLmOsrFBP5Eu02wEEvR7N

**Comment by wooyn730** [comment]
수정 감사합니다!!
저는 빗금으로 차이 두는 이번 버전이 더 좋은 거 같아요!

![스크린샷 2024-12-23 032812](https://github.com/user-attachments/assets/99b57742-5782-42b0-a249-08dac0d6b01d)
![스크린샷 2024-12-23 032929](https://github.com/user-attachments/assets/a35a592f-0fb5-4ba3-8272-5a8470f7c07a)

다만 저는 빗금 있는게 밝은 색, 빗금 없는게 어두운 색이면 어떨까 합니다 (색 거꾸로)
왜냐면 UI 숨김 X랑 자동진행 X가 디폴트인 거 같아서,,,??
