### ISSUE TITLE
[CH1] 신규맵 자료 문서화

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/Grayed-Game#744]
- CH1 초반 라플리 자동 이동 삭제 플로우 정리 (우연님께 전달)
- CH1 신규맵 자료 문서화 (지은님께 전달)

### 241101 업데이트

[CH1 신규맵 자료 문서화](https://drive.google.com/file/d/1hTxUCF92nNda_YGsW-tSfLONU4sWgeSG/view?usp=sharing)

**바로 작업x**
다음 회의에서 추가 논의 필요할 듯하고 지은님과 추가 구두 전달 회의도 짧게 잡는 게 좋을 것 같습니다. 

저와 지은님 둘 다 이번 맵 구도에 대한 문제로 너무 헤매고 있는 것 같습니다..
애초에 해결하기 힘든 문제를 고민하고 있나, 너무 과하게 고민하고 있지 않나 고민이 듭니다.. 

이 신규맵을 만들게 된 계기를 정리해보자면
1. 잊혀진 게임의 리소스가 떨어지는 세계관임을 일러스트와 신규맵을 통해 유저에게 설명한다.
2. 게임의 첫인상인 오프닝 퀄업
3. 럭키팩 접속과 팩맘 접속 사이에 간격을 둔다.

이렇게 3가지 이유였는데 오프닝 일러스트를 통해 1,2번은 해결이 가능하고, 사실상 3번을 위해 신규맵을 만든다고 볼 수 있을 것 같습니다.
그래서 만약 이번 자료 전달로도 작업에 어려움을 겪을 것 같다면 신규맵을 만들지 않고 일러스트만 추가한 채로 기존 그대로 가거나 3번 문제에 대한 해결법을 찾아보는 방안을 제안하고 싶습니다.

**Comment by Sumindd** [comment]
@wooyn730 생각해보니 어차피 CH1 맵 제작된 이후에 초반 스토리랑 플로우가 약간 수정될 예정이라 라플리 자동 진행은 일단 수정하지 않고 맵이 나온 이후에 작업하는 게 좋을 것 같습니다!

**Comment by wooyn730** [comment]
아하 확인해주셔서 감사합니다 ><~
