### ISSUE TITLE
온라인 CH2 기획 비정기 회의, 2024-10-28 [22:00]

### ISSUE THREAD

**Issue by wooyn730** [GG-Studio-990001/Grayed-Game#745]
**개요**
CH2 비주얼 노벨 소통 오류를 느끼고
누가 갈아엎을지 이야기하다가 갑자기 회의 진행
(약 70분 진행)

---

[CH2 스토리 분기 엑셀](https://docs.google.com/spreadsheets/d/1VRmG8Bv0I-4TSoCNACvhbK5IHR1_2LsF/edit?gid=1719426662#gid=1719426662)

### 선택지 등장, 선택지 종류 줄이기

1) 선택지 등장
A 장소에서 B 장소로 무조건 이동해야 한다면 1개 뿐인 선택지를 띄울 필요가 없음.
자동 이동으로 변경, 스크립트도 하나로 합치기.

2) 선택지 종류 줄이기
기존 장소는 무조건 광장을 거쳐서 창고, 달러 동상을 가야했기 때문에 depth가 높았음. 자동 이동으로만 갈 수 있는 장소를 설정하고 메인 장소인 마을 입구, 광장, 신전, 달러 동상을 같은 레벨로 둠.

두 방식 모두 불필요한 단계를 없애 피로도를 낮춤

### 장소 이동

광장/신전/달러 동상: 4가지 중 현재 위치 빼고 표시
마을입구: 광장, 신전, 달러 동상 + 동굴
동굴: 마을입구

동굴을 분리하는 이유: 플로야드 구역이라 마을과 분리해야 했고, 달러 동상 등 마을 내에서 동굴로 바로 이동하는 오류를 만들지 못하게 하기 위함.

### N 이벤트

S가 진행되면 Turn이 넘어감,
N은 S를 보기 전에 N 이벤트가 있는 장소를 선택할 시 볼 수 있음.
다음 S 이벤트를 보면 이전 N 이벤트는 영영 못본다.

### 아무 이벤트 없는 장소

`아무도 없다` 등의 스크립트를 만들어 모든 이벤트 없는 장소에서 해당 대사 출력

### 장소 비활성화

장소를 선택지로 띄우되 비활성화하는 기능은
스크립트가 합쳐지고 선택지 노출 횟수가 줄어듦으로써 필요없을 것 같음.

### 선행작업
- 수빈: 스크립트 합쳐서 새로 파일 올리기

기존 선택지가 1개만 있던 S 이벤트들을 하나로 합치는 작업. (스크립트 내에서 장소 이동이 자동으로 이뤄짐)

### 이후
- 수빈: 스크립트 개수에 따라 분기 엑셀 생성
   - 너무 적으면 필요 없을수도
- 우연: 대사 연동할지 정하기
   - 대사가 길어지면 한 스크립트가 수정될 횟수도 많기 때문에 연동하는 게 나을 듯
   - 대사를 연동해야 한다면 플밍이 적용하기 위해 기획쪽에서 어떤 전처리가 필요한지 회의해야 함

**Comment by wooyn730** [comment]
@Sumindd @roweclaw 
빠진 내용 있으면 추가 부탁드려요~~!

**Comment by Sumindd** [comment]
스크립트 읽다가 떠올랐는데 N이벤트나 S이벤트 모두 한 번 진행 완료 됐으면 같은 스크립트가 또 출력 되지 않게 처리 부탁드립니다! S이벤트는 괜찮은데 N이벤트는 여기저기 이동하다가 같은 대화가 2번 나오는 경우도 있을 것 같아 적어둡니다
회의 내용은 잘 정리된 것 같아요 고생하셨어요!!
