### ISSUE TITLE
[CH2] 대사 스크립트 합치기

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#747]
## 작업 진행

- #745 에서 논의한 대로 작성된 스크립트를 합치는 작업을 진행했습니다.
- [[241029] 대사 스크립트 합치기 폴더](https://drive.google.com/drive/folders/1ZPEYw_0wtNODYvQejuJBLg1rsLd5d5d0)에 업로드 했습니다.

## 참고 사항

- Turn의 총 개수는 8개(0~7)입니다.
- Turn 1, 2, 4, 6에만 N이벤트가 존재합니다.
- 아무도 없을 시 `Nobody.yarn` 출력
- 장소 변동사항 : `기지 외관`을 삭제, `기지 내부` -> `기지`로 이름 변경 ([엑셀의 장소 구조(241029기준)](https://docs.google.com/spreadsheets/d/1VRmG8Bv0I-4TSoCNACvhbK5IHR1_2LsF/edit?gid=1896276393#gid=1896276393) 탭 참고)

## 건의 사항

장소 중 `달러 동상`은 Turn2_S 에서 최초로 방문하는데 그 전까지는 따로 N이벤트도 없어서...
Turn4부터 장소 선택지에 포함 시키면 좋을 것 같은데 어떤가요?
( Turn4부터인 이유: Turn3은 어차피 쭉 자동진행이라서 )

**Comment by Sumindd** [comment]
선택지를 중간에 늘리는 거 저는 찬성입니다! 
우연님 작업이 너무 번거롭지만 않다면...

**Comment by roweclaw** [comment]
@wooyn730 
방금 생각났는데 Turn 0번부터 해달라고 한거 까먹었어요... 오늘 안으로 다시 수정해두겠습니다..!

**Comment by roweclaw** [comment]
Turn 번호 수정되었습니다!

**Comment by wooyn730** [comment]
> 선택지 중간에 늘리기

안 될 거 없죠!
우선 Turn0부터 차근차근 작업해보겠습니다

> 분기 엑셀

분기 엑셀은 지금 개수 봐서는 없어도 될 것 같은데 혹시 필요해지면 말씀 드릴게요

> 대사 연동

대사 연동은 필요할 것 같긴 한데, 원래대로라면 이 순서입니다
수빈: 깃허브에서 다운로드 → 수정 → 구드에 올리기
우연: 구드에서 다운로드 → 유니티에 임포트 → 수정

이전 작업에 분기 엑셀 연동한 방식대로 다운로드 버튼을 만들면 이렇게 됩니다
수빈: 깃허브에서 다운로드 → 수정 → 구드에 올리기
우연: 유니티 내에서 다운로드 → 수정

구드에서 바로 유니티로 다운받는 버튼을 유니티 내에 만드는 건 할 수 있을 거 같은데 (아직 안해봤지만ㅎㅎ)
생각해보니 수빈님 과정이 더 번거롭지 않을까 싶습니다.
수빈님이 유니티 설치해서 바로 수정하고 올려주시는 게 수빈님께 더 편할지..도...? ^_^
고민 좀 더 해볼게요...

**Comment by wooyn730** [comment]
작업하려고 잘 생각해보다가 역시 엑셀이 필요한 것 같긴 해서 만들었습니다.
Turn0부터 7까지 연결 지점 위주로만 먼저 파악해봤습니다.

![image](https://github.com/user-attachments/assets/879b8c72-9426-467d-8563-e65542f2b007)
_틀린 점 있으면 말씀해주세요_

## 궁금한 점

### 1 동굴 선택지
마을 입구에서는 동굴로도 갈 수 있다고 이야기했는데
정리해보니 마을 입구에서 동굴을 선택하여 갈 일은 없는 것 같습니다.
선택지에서 제외되나요..??

### 2 끝나는 장소
끝나는 장소가 보라색이 아닌 곳이 3번 있습니다.
예를 들어 창고 내부에서 끝나면 보라색 장소로 가려면 창고랑 광장을 거쳐야합니다.
그럼 여기서 직접 창고랑 광장 선택지를 거쳐서 나오나요 아니면 광장으로 자동으로 나오게 처리해야 하나요?
그리고 후자라면 광장 N 스크립트가 사실상 S 아닌지...??

### 3 들어가기
만약 턴1에서 Turn1_N_Square 스크립트를 실행했다면
광장이니 마을입구와 신전 선택지를 보여주는 거 맞나요?
(광장에서 창고로 갈 수는 있지만 보여주진 않는 거 맞죠?)

**Comment by roweclaw** [comment]
우연님, 우선 저 대신 엑셀 만들어주셔서 감사합니다... 👍 

그런데 혹시 장소 선택지가 Turn마다 다른 이유가 있을까요?
저번 회의에서 선택가능한(보라색) 장소는 다 띄우고, 만약 띄울 스크립트가 없는 장소를 선택한다면 Nobody.yarn을 출력하기로 했던 것 같아서요!

아래는 질문에 대한 답변입니다!

### 1 동굴 선택지
> 마을 입구에서는 동굴로도 갈 수 있다고 이야기했는데
정리해보니 마을 입구에서 동굴을 선택하여 갈 일은 없는 것 같습니다.
선택지에서 제외되나요..??

스크립트를 합치게 되면서 동굴로 가는 게 다 자동 이동으로 처리된 것 같습니다. 따라서 선택지에서 제외되는 게 맞네요!

### 2 끝나는 장소
> 끝나는 장소가 보라색이 아닌 곳이 3번 있습니다.
예를 들어 창고 내부에서 끝나면 보라색 장소로 가려면 창고랑 광장을 거쳐야합니다.
그럼 여기서 직접 창고랑 광장 선택지를 거쳐서 나오나요 아니면 광장으로 자동으로 나오게 처리해야 하나요?
그리고 후자라면 광장 N 스크립트가 사실상 S 아닌지...??

저는 마지막으로 끝나는 장소가 꼭 보라색(선택지 장소)가 아니어도 된다고 생각했어요!
예를 들어 Turn0이 창고 내부에서 끝나는데, 이때 선택지는 '마을 입구, 광장, 신전'이 뜹니다. 
그러면 어디를 선택하더라도 창고에서는 빠져 나와야 할 텐데, 실제로 그 과정(장소를 거쳐서 나가는 것)은 생략한다고 생각했어요. 
그 대신 발걸음 sfx 를 출력하고 도착한 곳에서 "창고를 나와서 OO으로 도착했다."라는 스크립트 등을 추가해서 긴 장소를 이동했다는 연출을 사용할 필요가 있겠네요!!


### 3 들어가기
> 만약 턴1에서 Turn1_N_Square 스크립트를 실행했다면
광장이니 마을입구와 신전 선택지를 보여주는 거 맞나요?
(광장에서 창고로 갈 수는 있지만 보여주진 않는 거 맞죠?)

네 맞습니다. 선택 가능한 장소는 보라색 장소로만 한정되며, 이제 동굴이 제외되었으니
'마을 입구, 광장, 신전, 달러 동상' 총 4곳이 되겠네요!

**Comment by wooyn730** [comment]
> 장소 선택지가 Turn마다 다른 이유

`선택가능한(보라색) 장소는 다 띄우고, 만약 띄울 스크립트가 없는 장소를 선택한다면 Nobody.yarn을 출력` 이렇게 생각한 거 맞습니다!
'달러 동상'이 중간에 추가돼야 하고, 2번을 아직 정확히 모르겠어서 가장 가까운 보라색 장소로 이동한다는 전제로 작성하였습니다.

> 1 동굴 선택지 / 3 들어가기

1, 3번 이해했습니다

> 2 끝나는 장소

보라색 장소에서 꼭 마지막으로 끝날 필요가 없는 건 맞습니다.
근데 Turn0에서 창고 내부에서 끝나는데 마을 입구랑 광장으로 바로 이동하는 게 좋은 건지 잘 모르겠어요.
순서가 생략되니 간단하긴 하겠지만 그럼 장소 구조 정해둔게 별 의미 없는 거 아닌가요..??

저는 구조를 어느정도 이해시키려면
발자국sfx → 광장으로 이동 → '창고를 나와 광장에 도착했다' → 선택지 출력
(가장 가까운 보라 장소로 이동) 
이 순서가 되어야 하는 게 아닌지... 궁금합니다.

@Sumindd 수민님 생각도 궁금합니다!

**Comment by roweclaw** [comment]
> 순서가 생략되니 간단하긴 하겠지만 그럼 장소 구조 정해둔게 별 의미 없는 거 아닌가요..??

저는 간단하게 바로 이동해도 괜찮을 것이라고 생각했는데
그 이유는 미연시에서는 큰 흐름으로 스토리가 쭉 이어지기 때문에
기존 스크립트를 합쳐서 자동 이동을 만들었고, 수민님의 Turn 시스템에 따라서 이미 장소 구조 자체가 간소화됐기 때문입니다!
그래서 지금의 장소 구조는 스토리의 에피소드 진행을 선택하는 차원으로 구분된 느낌이 크네용

그럼에도 구조를 이해시키는 작업이 필요하다면 우연님이 말씀해주신 `발자국sfx → 광장으로 이동 → '창고를 나와 광장에 도착했다' → 선택지 출력 (가장 가까운 보라 장소로 이동)` 이 방안도 괜찮은 것 같아요!

저도 수민님 의견 궁금합니다!!

**Comment by Sumindd** [comment]
장소 구조는 스토리를 짜는 개발 입장에서의 이해를 위한 구조고 저는 마을 구조를 굳이 유저들에게 이해시킬 필요가 없다고 생각합니다. 추리 장르의 게임 같이 구조 파악이 필요한 특별한 의도가 있지 않는 한 비주얼 노벨 게임을 하면서 장소 구조에 대해 생각해본 적도 없는 것 같고요! 그래서 신전 내부처럼 수빈님이 스토리적으로 구조 이해가 필요할 것 같다 싶은 부분 제외하면 굳이 현재 위치를 신경 쓰지 않고 진행하는 쪽이 깔끔할 것 같습니다. 
구조 이해가 필요한 상황이라면 발자국sfx → 광장으로 이동 → '창고를 나와 광장에 도착했다' → **광장에서 특정 사건 발생** → 선택지 출력 이런 식으로 자연스럽게 돌려서 연출해도 충분할 것 같고요.

**Comment by wooyn730** [comment]
이해했습니다!

`Turn0이 창고 내부에서 끝나는데, 이때 선택지는 '마을 입구, 광장, 신전'`
이대로 끝나는 장소가 어디든 보라색 3가지(turn4이후 4가지) 장소가 뜨도록 구현하겠습니다

**Comment by wooyn730** [comment]
스탠딩 위치 궁금한 점 있어 질문 드립니다!

### 1 - Turn0 시작 마을입구

![1102_2](https://github.com/user-attachments/assets/33f7fc85-0415-4aeb-8cd0-2c635e4827bf)
![1102_1](https://github.com/user-attachments/assets/d0216ba8-e6a3-4c36-9e19-a15474bd7fdb)

Turn0에서는 라플리와 파머가 대화하다가 중간에 진도랑 비글이 말을 겁니다.
이렇게 오른쪽에 둘 추가되는 그림 맞나요?

### 2 - Turn0 광장

Turn0 광장에서는 주민1, 2, 3이 파머랑 이야기 하는데
주민1, 2, 3도 스탠딩이 제작되나요? 
아니면 스탠딩 없이 파머가 오른쪽에 있나요?

---

근데 1은 파머랑 진도&비글이랑 말하고
2는 파머랑 주민 1, 2, 3이랑 말해서
파머가 왼쪽에 가야하나 싶기도 하고요...??

그리고 라플리가 알투몬이나 달러랑 이야기할 땐 아예 대사가 없는데 항상 왼쪽에 어두운 스탠딩 세워두는 거 맞을까여?

**Comment by roweclaw** [comment]
대화 상대가 중간에 추가될 경우, 그림과 같이 오른쪽에 추가해주시면 됩니다!

주민 1,2,3 의 경우, 스탠딩 제작 없이 대사만 나온다고 생각하고 기획했습니다! (있으면 좋긴 하겠지만 우선순위 최하위라...)

라플리의 경우, 모든 장면에 항상 스탠딩이 있어야 하며 대사가 없을 때는 어둡게 처리해주시면 됩니다!

**Comment by fkdl0048** [comment]
저번 비정기 회의 내용이랑 여기서 논의중인 내용 회의 때 말씀해주시면 좋을 것 같습니다!
