### ISSUE TITLE
[CH2] 캐릭터 스탠딩 규칙 구체화

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/Grayed-Game#754]
- 비주얼 노벨에서 캐릭터 스탠딩을 출력하는 기준을 구체화해서 우연님께 전달

---

### 241111 업데이트
비주얼 노벨에서의 스탠딩 출력 기준을 정하기 위해 몇 개의 게임을 해봤습니다.
미연시인 경우 : 몰입해야하고 유저와의 일대일 대화가 주를 이뤄야 하기 때문에 유저 입장의 캐릭터(GG에선 라플리)의 스탠딩이 없는 편입니다. 
미연시가 아닌 경우 : 캐릭터들 사이에서 대사를 기준으로 스탠딩이 출력 됩니다.
그런데 GG는 라플리가 주인공이지만 스탠딩이 있음에도 대사가 적은 편이라 다른 게임들을 참고하는 것은 의미가 없다고 판단했습니다.

현재 빌드에선 라플리가 왼쪽에 항상 서있고, 오른쪽에 대화하는 캐릭터가 바뀌는 형태인데 라플리의 대사가 워낙 없다보니 라플리는 거의 항상 어둡게 처리(대사 안 함 상태) 되어 있는 상태가 대부분입니다. 그래서 라플리가 왼쪽에 항상 있으면서 어두운 상태로 있는 것보단 아래 방안 중 하나로 선택하는 것이 좋을 것 같습니다.

1안) 항상 라플리는 밝은 상태로 둔 채로 왼쪽 캐릭터만 바꾸거나
2안) 미연시처럼 라플리의 스탠딩을 없애고 진행

스크립트를 읽어봤을 때 캐릭터가 2명 등장하는 것보단 라플리와 1명의 캐릭터가 대화하는 장면이 더 많은 것 같아 2안으로 간다면 중앙에 스탠딩을 두는 방식도 생각해보면 좋을 것 같습니다.

**Comment by roweclaw** [comment]
> 1안) 항상 라플리는 밝은 상태로 둔 채로 왼쪽 캐릭터만 바꾸거나
2안) 미연시처럼 라플리의 스탠딩을 없애고 진행

예전 회의때 한 번 말씀드렸던 것 같은데, 2안처럼 라플리가 화면에 없다면 `라플리 = 유저 자신`이라고 생각하게 될까봐
라플리 스탠딩에 변화가 없더라도 화면 안에 있는 게 나을 것 같다는 생각이 있어서 1안이 좋은 것 같습니다!

**Comment by wooyn730** [comment]
저도 수빈님과 같이 회의 때 이야기 나눴던 부분이 기억납니다. 

유저가 '라플리를 통해' 게임을 플레이한다는 걸 계속 인식시켜줘야 하기 때문에 라플리 스탠딩은 필수라고 생각합니다!

**Comment by Sumindd** [comment]
그럼 말하는 사람만 밝게 보이는 시스템을 아예 없애고 라플리는 왼쪽에 항상 고정 + 오른쪽에 말하고 있는 캐릭터 출력, 독백 시엔 오른쪽 비우기 이렇게 간단하게 처리하는 게 GG엔 가장 잘 어울릴 것 같네요
