### ISSUE TITLE
[CH2] 호감도 시스템 구체화

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/Grayed-Game#756]
- CH2에 들어갈 미카엘 호감도 시스템을 구체화합니다.
- TCG 시스템과 엮어서 초기 밸런싱 포함 
- ---
[[241111] CH2 호감도 시스템](https://drive.google.com/file/d/1_Seu3ddvRzjIXMf7wqsmps_1PZdQHjgj/view?usp=sharing)
TCG에서 새 카드 추가되는 걸 랜덤 출력으로 하려고 기획서를 작성했다가 고정으로 하기로 정하고 엎어서 막상 문서는 분리하기도 애매할 정도로 엄청 단순해졌네요. 그냥 가볍게 읽어주시면 될 것 같습니다.
카드별 질문과 점수 배치에 대한 자세한 이야기는 수빈님과 이야기 나눴습니다! 아마 수빈님 문서에서 표현 될 것 같아요.

**Comment by wooyn730** [comment]
잘 읽었습니다~
깔끔하고 좋네요!!

**Comment by Sumindd** [comment]
내용 추가로 인한 업데이트 완료
