### ISSUE TITLE
[CH2] TCG카드반응 대사

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#757]
- TCG카드반응대사 우선 작업

---

[TCG카드반응대사 엑셀](https://docs.google.com/spreadsheets/d/1uadxmQaKmTIFNRXc2Y0P2edJn8l6RCODntDq94aa9xA/edit?usp=sharing)

미카엘의 질문에 제시할 카드의 내용과 그에 따른 미카엘의 답변을 작성했습니다.
피드백 부탁드립니다!

**Comment by roweclaw** [comment]
TCG 대사 업데이트 했습니다! 예상보다 조금 지체된 점 죄송합니닷ㅠㅠ

**Comment by wooyn730** [comment]
작업 고생하셨겠는데요.. 쉽지않아보이네요 ㅠ
피드백하기도 좀 어려워보이네요 흑흑...
역시 적용된 걸 봐야겠어요

일단 색으로 표현해주셔서 표 보고 이해하기는 쉽네요!
그리고 제 이름이 많이 나와서 좋아요^_^ㅎㅎ,,,,,,,,,,,,
