### ISSUE TITLE
[CH2][Char] R2-mon 스탠딩 작업

### ISSUE THREAD

**Issue by JIJI037** [GG-Studio-990001/Grayed-Game#760]
R2-mon 기본 스탠딩 작업합니다.

24.11.11

현재 알투몬 데포르메론 대화창에 나오기 어려워... 도구를 하나 줬습니다...
가방을 메고? 아니면 등에 장치가 있다는 설정으로 긴 팔이 나와 (예시: 스파이더맨에 나오는 빌런 닥터 옥토퍼스) 서 있는 걸 지탱할 수 있는... 그런 설정을 줘봤습니다 별로다!! 싶으면 아예 알투몬 외형을 처음부터 다시 짜야합니다,,

![알투몬 스탠딩_중간](https://github.com/user-attachments/assets/62f0d8e9-3fbb-41da-b6f0-79718acaad41)
![대화창 스탠딩 알투몬 버전](https://github.com/user-attachments/assets/2953c9f8-201d-4972-b295-9383b9498319)

24.11.17
팔 길이 수정했습니다
![알투몬 스탠딩_최종](https://github.com/user-attachments/assets/14bae942-dbf7-41fb-9d95-892d5c622440)

**Comment by JIJI037** [comment]
업데이트 했습니다

**Comment by JIJI037** [comment]
24.11.17
업데이트 했습니다

**Comment by wooyn730** [comment]
팔 줄어든 거 좋네요~!!
회의 때 구두로 얼굴에 모니터 버튼 같은 꾸밈요소 의견 드렸었는데 그 버전도 한번 볼 수 있을까요?
상대적으로 라플리랑 미카엘에 비해 민둥?해보여서 모자도 밀짚모자 재질 표현 돼도 좋겠네요~

그리고 구드에 올리고 링크도 같이 부탁드려요!!!
