### ISSUE TITLE
[CH1] SLG 획득 시 럭키 위치 버그

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/Grayed-Game#761]
# [CH1] SLG 획득 시 럭키 위치 버그

- https://github.com/GG-Studio-990001/Grayed-Game/issues/746#issuecomment-2454753244

![{29552460-D0FA-4603-B7A3-F003707AEB99}](https://github.com/user-attachments/assets/edb130c7-6e1e-4fdf-8909-33ccdd1aed64)

럭키 등장 위치 버그

**Comment by jeongopo** [comment]
241110 수정했습니다.
내일 빌드 테스트 후 이슈 닫겠습니다.
