### ISSUE TITLE
[CH2] 장소 이동 UI 줄 넘김

### ISSUE THREAD

**Issue by fkdl0048** [GG-Studio-990001/Grayed-Game#763]
# [CH2] 장소 이동 UI 줄 넘김 

![image](https://github.com/user-attachments/assets/b47ce135-5701-451f-a00e-1bab63c82d7e)

줄넘김이 발생하면 글씨 크기를 줄이도록 변경해야 함

**Comment by wooyn730** [comment]
현재는 글씨 안튀어나오도록 간단하게 세팅해둠
추후 아마 현지화할 때 이슈 다시 열어서 해당 기능 작업할 듯
