### ISSUE TITLE
[CH2][Char] 파머 스탠딩 작업 

### ISSUE THREAD

**Issue by JIJI037** [GG-Studio-990001/Grayed-Game#769]
파머 스탠딩 작업을 진행합니다.

24.11.25
파머 스탠딩입니다.
![파머 스탠딩_최종](https://github.com/user-attachments/assets/23b476a5-20f1-440f-8095-7d0279b6b2bd)

대화창에 맞춰 라플리, 미카엘 길이가 수정되었으며 알투몬 외관 수정되었습니다.
![스탠딩 모음](https://github.com/user-attachments/assets/ab7b3261-24fb-4e48-aec7-59e3df7d3422)

24.12.01
파머 표정 수정되었습니다 (안광 추가,,)'
![파머 스탠딩_최종](https://github.com/user-attachments/assets/a842dcfd-5fa0-4bfd-aa85-902c3e3891c6)

**Comment by wooyn730** [comment]
와 잘생겼다 ^_________^
구드에 둘 다 올리고 링크 주세여~!
바로 적용하겠습니다

**Comment by roweclaw** [comment]
저번에 봤을 때부터 이미 잘 그려졌는데 이번에 덩치 살짝 줄이고 얼굴 보니까 확실히 완성된 느낌이네요! 고생하셨습니다👍

**Comment by JIJI037** [comment]
> 와 잘생겼다 ^_________^ 구드에 둘 다 올리고 링크 주세여~! 바로 적용하겠습니다

구드에 올렸습니당
https://drive.google.com/drive/mobile/folders/1AuqR6TALr7arVGaI9_ECUM91Yrqa6cgL/16IJf4zp3pB2sFD26-cwPVlJY4_2Eilh1/11DbHcKLt5XRhbH-5RJI9kEsUVvtbpDyq/1LkxFVElHHhJn5o97LoEKIo0kc0bsocdL?usp=sharing_eil&ts=66bb2414&sort=13&direction=a

**Comment by JIJI037** [comment]
24.12.01
표정 수정되었습니다

**Comment by wooyn730** [comment]
좀 더 쾌활st여도 좋을 거 같은데 `환하게 웃는 표정`이 따로 있으니까 지금이 딱 적당한 거 같기도 하고요?!
암튼 수정된 거 좋습니다~~

(잘생긴 파머를 보면 나도 웃게 돼... ^______^)
