### ISSUE TITLE
[CH2] 슈아브 대사

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#772]
슈아브 대사 작성예정입니다.

---

[[241116] Angel](https://drive.google.com/file/d/1TyZ1lzLA6zk466jb4XowxPEBMjzaYI0d/view?usp=sharing) 

제가 기획서 확인했을 땐 보상의 방에서 엔젤 브라더스들 대사만 있는 걸로 알고있는데,
혹시 다른 대사가 더 필요하다면 알려주세요! (럭키 제외)

엔젤 브라더스들 이름은 미카엘 따라서 가브리엘, 라파엘로 지어줬고
미카엘은 실제로 게임에 없지만 보상의 방 대사는 항상 출력되어야 한다고 생각해서 살짝 오류난 느낌으로 작성해봤습니다!

**Comment by wooyn730** [comment]
가짜 미카엘 대사 으스스하고 재밌네요... ㅋㅋㅋ
적용하고 이해가 잘 되나 한번 보면 좋을 것 같아요!

그리고 시원님 얀 스피너 안써보셨으면 설명 한번 드려야겠네용
