### ISSUE TITLE
[CH2] TCG카드 이미지 기획

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#780]
카드에 들어갈 이미지(레퍼런스) 작업합니다.
- 참고 링크 : [TCG카드반응대사 엑셀](https://docs.google.com/spreadsheets/d/1uadxmQaKmTIFNRXc2Y0P2edJn8l6RCODntDq94aa9xA/edit?usp=sharing)

---

[[241125] TCG카드 이미지 기획](https://drive.google.com/file/d/1wFXUO2SmYdbx9QT8nLD3xk0DRmMswjaO/view?usp=sharing) 작성했습니다.
보민님은 확인 부탁드리고 이대로도 작업 가능하신지 말씀해주시면 감사해요! (@vprwolf)

추가로 저번 회의때 카드마다 제목이 있으면 좋을 것 같다는 의견이 있었는데요.
저도 동의하는 바여서 시도를 해봤지만, 우선 보류해야 할 것 같습니다.
이유는 여러 질문에 각기 다른 반응을 낼 수 있도록 문장을 모호하게 작성했기 때문에
그 문장의 뜻을 임의의 제목으로 규정해버리면 너무 다 드러날 것 같기도 해서 이 점이 우려되고
제목 짓기 꽤 어려운 문장이 몇 개 있기도 합니다. _(우연한 이끌림... 달의 이면... 등...)_
여기에 대해서 그래도 있는게 좋다, 없어도 된다 등 의견 주시면 감사합니다!

---
### 업데이트
[[241202] TCG카드 이미지 기획](https://drive.google.com/file/d/1_541P1o1Z7N8okVkmHHCv1LmsWki078u/view?usp=sharing)

카드 제목이 추가되었습니다!

1. <무언의 속삭임> 우연한 이끌림이 있습니다.
2. <선물> 순수함이 깃든 호의입니다.
3. <반사된 이면> 달의 이면과도 같습니다.
4. <침묵의 수호> 비밀은 지켜야 하는 법입니다.
5. <구원자> 도움의 정령이 나타났습니다.
6. <간절한 바람> 염원의 눈빛이 보이는군요.
7. <검은 그림자> 의심의 그림자가 드리웁니다.

**Comment by roweclaw** [comment]
카드 제목 작성해봤습니다. 어울리는지 피드백 받고 수정 또는 확정할게요!

1.  <무언의 속삭임> 우연한 이끌림이 있습니다.
2.  <선물> 순수함이 깃든 호의입니다.
3.  <반사된 균형> 달의 이면과도 같습니다.
4.  <침묵의 수호> 비밀은 지켜야 하는 법입니다.
5.  <구원자> 도움의 정령이 나타났습니다.
6.  <간절한 바람> 염원의 눈빛이 보이는군요.
7.  <검은 악령> 의심의 그림자가 드리웁니다.

**Comment by Songkihwa** [comment]
다 너무 찰떡이고 좋으네요 고생하셨어요!
개인적으로 7번은 <검은 그림자>도  좋을 것 같다는 생각이 드네요. 
직접적으로 말하지 않음에서 오는 그런 악한.. 느낌이 더 좋은 것 같은 저의 개인적인 생각 ....ㅎ...

또 3번은 <반사된 이면>도 좋을 것 같아요! 반응 대사도 그렇고 달의 앞면, 뒷면이 달라서 균형보다도 이면이 잘 어울릴 것 같은 생각이 듭니다!
