### ISSUE TITLE
[CH2] 사운드 리소스 2차 리스트 작성

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#782]
- #569
- 기존에 수민님 작업하신 이슈에서 추가로 작성 예정입니다.

---

[CH2 메인 사운드 리스트](https://docs.google.com/spreadsheets/d/1xm1i3QOiWb2R3wsLEWM1UQqv6JVTBene/edit?usp=sharing&rtpof=true&sd=true) 2차 작성을 완료했습니다.

기화님은 확인 부탁드리고 이대로도 작업 가능하신지 말씀해주시면 감사해요!
BGM은 레퍼런스 같이 첨부했고, SFX는 최대한 원하는 사운드를 글로 표현했는데 혹시 이것도 레퍼런스 필요하시면 알려주세요!(@Songkihwa )

**Comment by Songkihwa** [comment]
확인했습니다! 여기서 더 추가할 부분이나 각 사운드들의 세부적인 사항들은 회의 잡고 같이 논의해보면 좋을 것 같습니당 

본격적으로 작업 들어간다면 챕터 2 메인 BGM 먼저 작업 하고 접속 BGM 만들고 SFX들 쭈루룩 만들어갈 것 같습니다 :)
