### ISSUE TITLE
[CH2] 배경아트 구도배치

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#784]
배경아트의 구도, 배치 관련 레퍼런스를 작업합니다.

- 참고 링크 : [CH2 아트 리소스 엑셀](https://docs.google.com/spreadsheets/d/1Dm7b5r5Cmk4YC4DTW4ureRnq3Xmny8bs/edit?gid=1580449727#gid=1580449727)

---

[CH2 배경아트 구도배치](https://drive.google.com/file/d/1r7mufye-l9Zdn-sbXMzgKlAsX8TetEEX/view?usp=sharing)

피그마로 작업 후 레퍼런스와 설명을 같이 보실 수 있도록 하나로 문서화 했습니다.
지은님은 확인 부탁드리고 이대로도 작업 가능하신지 말씀해주시면 감사해요! (@JIJI037)

**Comment by fkdl0048** [comment]
저도 한번에 잘 이해가 된 것 같습니다.

CH2의 가장 중요한 부분은 모든 장르에서 시각적으로 가장 디테일하게 보여줄 수 있다는 점이 있기 때문에 모든 배경적 요소에 이 세계관이 잊혀진 게임들이 떨어지는 곳이다라는 설정이 많이 묻어도 한번에 잘 이해가 된 것 같습니다.

CH2의 가장 중요한 부분은 모든 장르에서 시각적으로 가장 디테일하게 보여줄 수 있다는 점이 있기 때문에 모든 배경적 요소에 이 세계관이 잊혀진 게임들이 떨어지는 곳이다라는 설정이 많이 묻어있었으면 합니다! 가장 어려운 부분이기도 한데, 추상적인 게임요소가 보였으면 하네요 게임적 요소에 대한 레퍼런스 문서가 있었는데 구드에서 못 찾았읍니다..

**Comment by roweclaw** [comment]
[[241126] CH2 배경아트 구도배치](https://drive.google.com/file/d/1VFCCipMsibA2vV70iiCk5aWWtEWP8sZn/view?usp=sharing)

@JIJI037 지은님! 레이어 분리 필요한 것들 문서에 강조해서 수정했고, 엑셀에도 적었습니다~ 새 문서로 작업부탁드려요!

**Comment by roweclaw** [comment]
[[250316] CH2 배경아트 레퍼런스](https://drive.google.com/file/d/1q1JUFQgBVhAgE1bE70kQ41sx34hslqHW/view?usp=sharing) 업데이트 했습니다. 주미님 확인 부탁드려요! ( @seojumi )

**Comment by roweclaw** [comment]
[250510 신전외관](https://drive.google.com/file/d/1cq-dCI3RMeD-7bABcmAg-kLBjlI2tvS0/view?usp=sharing)

5번 신전 외관 -> 구도배치 변경
6번 신전 내부 -> 아예 배경자체를 삭제
