### ISSUE TITLE
[CH2] Main BGM 작업

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/Grayed-Game#790]
#782 참고해서 사운드 회의 진행 후 작업 예정 

----

"미카엘이 돌변해 라플리를 방에 가둘 때
거래 현장을 몰래 보다가 발각될 때" 나오는[ 심각한 상황 BGM ](https://drive.google.com/file/d/10lZGtGgmUTRFIdKmcuL4FKBuknOEByDp/view?usp=drive_link)

긴장감을 고조시키고 무슨 일이 생길 것만 같은 느낌을 강조하면서 만들었습니다.
레퍼런스 참고해서 분위기 + 레퍼런스의 피아노 베이스 라인을 킥 드럼으로 비슷하게 가져가고 이외에 피아노 음색 등을 다르게 해서 좀 더 긴장감에 집중되게 만들어봤습니다.

"미카엘과 슬라임 재회 및 이후 상황" [[감동적인 BGM](https://drive.google.com/file/d/1Lbd1RlDM2ZrMhprX9p8sLxsaCKalXNy9/view?usp=drive_link)]
수빈님이 올려주신 레퍼런스의 일본 애니메이션 OST 같은 느낌 + 감동적인 느낌을 넣어서 만들었습니다. 이거 너무 어렵네요 ..
클래식은 특히 부족해서 짧은 곡이지만 만들었던 BGM 중에 시간 제일 오래 걸린 곡입니다 . . ㅠ
수빈님이 피드백 주시면 수정하고 디벨롭해서 완성하겠습니당

**Comment by roweclaw** [comment]
BGM 둘 다 너무너무 좋네요! 레퍼런스에 더해서 기화님이 게임에 맞는 분위기로 더 강조해서 만들어주셔서 만족합니다
그래서 수정할 부분이 없는 것 같아요. (긴장감 BGM에 맞춰서 제가 대사를 더 오금저리게 써보겠습니다....ㅎㅎ) 굿입니다!! 👍

**Comment by wooyn730** [comment]
두 가지 모두 CH2 분위기를 잘 그리면서 만드신 거 같아요!!!
CH2 아트 보면서 들었는데 잘 어울리네요~~
음악도 너무 좋습니다 ><
심각 BGM은 소리 빵빵하게 하고 들으니까 고조되는 부분이 진짜 무섭네요 ㅋㅋㅋ

그리고 이건 적용해봐야 알겠지만 심각 BGM이 많이 반복(loop)된다면 고조되는 부분이 너무 무섭거나 튀지 않을지 쪼~금 걱정이 됩니다
