### ISSUE TITLE
[CH2] Main BGM 작업_2

### ISSUE THREAD

**Issue by Songkihwa** [GG-Studio-990001/Grayed-Game#806]
2챕터 Main BGM [CH2 메인 사운드 리스트](https://docs.google.com/spreadsheets/d/1xm1i3QOiWb2R3wsLEWM1UQqv6JVTBene/edit?usp=sharing&rtpof=true&sd=true) 1~2곡 완성 예정입니다. 

----
[04번 BGM](https://drive.google.com/file/d/1iyIbaYrLlCO72KQipa6NmDIWENO6iJTQ/view?usp=drive_link) 미카엘이 라플리를 경계하는 모든 상황 (첫 만남, 탈출 후 만남) 에서 나오는 BGM을 만들었습니다.
주신 레퍼런스 느낌을 살리려고 리듬을 똑같이 가져갔고 공백이 중요한 것 같아서 악기 중간중간에 텀을 많이 뒀습니다.
@roweclaw  어떤지 피드백 주시면 수정해드리겠습니당

[05번 BGM](https://drive.google.com/file/d/1eHBymJc3UM8BJlKF3H5cJ8AgbyxbiiTn/view?usp=drive_link) 미카엘이 슬라임과의 추억을 회상하는 상황에서 나오는 BGM을 만들었습니다.
이건 레퍼런스랑 너무 비슷해지면 안될 것 같아서 레퍼런스를 한번만 듣고 만들었고 슬프기도 하지만 아련한 느낌을 메인으로 넣었고 피아노로 그 느낌을 살려보려고 해봤습니다!
이것도 피드백 주시면 수정해드리겠습니다.

**Comment by roweclaw** [comment]
둘 다 너무 잘 표현해주셨네요! 이번에도 수정할 부분은 못 찾은 것 같아요 ㅎㅎ
다만 4번 BGM 구간의 대사가 그렇게 길지 않아서 BGM 길이에 비해 빨리 넘어가질까봐 걱정되네요. 추후 빌드 적용해보고 대사를 추가로 작성 또는 BGM 길이를 줄이는 형식으로 조정해보면 좋을 것 같습니다! (물론 다른 사운드들도 다 마찬가지일 것 같네용)
5번 BGM도 아련아련한 분위기가 잘 담긴 것 같아서 너무 좋습니다 고생하셨어요! 👍

**Comment by wooyn730** [comment]
잘 들었습니다!!
특히 5번 BGM 정말 좋네요 😄
_아주 개인적인 취향으로는 앞에 '동~동~동~동' 없는 게 좋을지도..? 무시해도됩니다.._

4번 BGM에 대해서는 수빈님과 같은 생각이 들었고, 또 긴장감과 불편함이 잘 드러나는 거 같아서 좋습니다!
_귱금한 점은 이런 음악은 이정도의 유사성은 괜찮은지..? (잘 몰라서,,,)_

**Comment by Songkihwa** [comment]
5번 이번주 내로 둥둥둥 빼고 업로드해두겠습니다. 
4번 BGM 유사성 같은 경우는 레퍼런스와 표절의 경계가 한끗차이라 저도 참 어려운 부분인데요.. 간단한 설명과 레퍼런스 곡밖에 없는 상황에서 최대한 원하는 느낌을 살리려고 멜로디가 같진 않지만 리듬과 구성을 비슷하게 가져가서 더 유사하게 들리는 것 같습니다. 사람들이 생각하는 저런 상황에 나오는 리듬이라는게 보편적으로 딱 있는 것도 있고 레퍼런스를 듣고나면 쉽게 다른 방향으로 생각해서 만들기가 조금 어렵습니다. 후에 문제가 될 것 같아서 걱정되신다면 다른 느낌으로 바꿔보던지 해보겠습니다.

**Comment by fkdl0048** [comment]
사운드 잘 모르는데도 듣기 좋네요! 적용된 버전을 빨리 보면 좋을 것 같습니당
