### ISSUE TITLE
[CH2] 사운드 삽입구간 엑셀

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#808]
사운드의 삽입구간을 엑셀로 정리합니다.
- BGM, SFX
- 루프 유무 체크

---

[CH2 사운드 삽입구간](https://docs.google.com/spreadsheets/d/1rRibyJ3_OrO2Rrk3fZ_K0i2Fmqud4fElIb-DMgHCYcs/edit?usp=sharing) 엑셀 작성했습니다.

대사 폴리싱 이후 행번호가 바뀌면 그에 따라 추후에 수정될 것 같아서, 우선 어떤 상황에 들어가야 하는지도 같이 적어두었어요!

**Comment by wooyn730** [comment]
제가 이것저것 많이 추가했나봐요 행번호가 거의 다 밀렸는데.. ㅋㅋㅋ
일단 눈치껏 넣었는데 빌드 확인해주셔야 될 것 같아요!!
`미카엘: ...그렇구나.` 이런 시작과 끝 대사를 엑셀에 넣으면 어떨까요..
(대사도 수정될 가능성이 있긴 하지만 행번호가 훨씬 많이 바뀌어서...)

그리고 제작과 적용 현황 보려고 오른쪽에 체크박스도 만들어두었습니다~~

**Comment by roweclaw** [comment]
빌드 봤는데 Turn1_S 미카엘 문전박대 BGM 4 시작대사만 달라서 `60 미카엘: 뭐야, 또 왔어?`랑 같이 시작되는 걸로 변경 부탁드려요!!

**Comment by wooyn730** [comment]
![Image](https://github.com/user-attachments/assets/ef652b7e-2c86-463e-8100-3ab6bc38be4c)

Turn0에 진도비글 창 내려치는 효과음 리스트에 아예 없네여?
