### ISSUE TITLE
[CH2 UI] 호감도UI

### ISSUE THREAD

**Issue by vprwolf** [GG-Studio-990001/Grayed-Game#809]
**2024.12.08**
장염 증세가 심해서 너무 늦게 업로드했네요..ㅠ
일단 호감도 UI외형을 제작했습니다.
![호감도1](https://github.com/user-attachments/assets/a150a31e-9007-4db0-bd3d-8be4ff41c756)
![호감도2](https://github.com/user-attachments/assets/32566815-cc9e-4e27-9a64-ca1f16217d3a)
숫자 공간을 좀 줘서 이런 비현실적 수치를 주는 연출도 재미있을 것 같네요.
하트에는 스케일값 조정으로 심장뛰는 느낌을 줘도 좋을 것 같습니다.

이어스 화면에 사이즈 맞춰보는 것과 하트모양 뛰는 모습은 필요하다면 스프라이트 작업을 해보겠습니다.

**Comment by vprwolf** [comment]
**2024.12.08**
업데이트 했습니다!

**Comment by Sumindd** [comment]
깔끔하고 기존 UI 스타일과 잘 어울릴 것 같아서 좋네요! 
혹시 배치 예시 합성해서 올려주실 수 있을까요? 
![Group 2391](https://github.com/user-attachments/assets/efd3a968-8370-4a21-8c56-2f806ef9041d)
