### ISSUE TITLE
공모전 제출용 기획서 수정

### ISSUE THREAD

**Issue by Sumindd** [GG-Studio-990001/Grayed-Game#814]
- #694 참고해서 버전업 

[241213 통합 기획서](https://drive.google.com/file/d/1hVo-FQYBt6Vw_2p1WSQx65XYck43YBEx/view?usp=sharing)

업데이트 했고, 통합 기획서 관리 이슈에 원본 링크 공유해뒀습니다. 수정 시 참고해주세요!

**업데이트**
1. 기획 의도 내부 공유용 기획서 버전으로 수정
2. 기획 방향성 추가(공통은 1. 게임 소개 쪽에, 메인 장르/서브게임/접속게임은 3. 게임 시스템 쪽에 정리)
3. CH2 접속 게임 슈아브 페이지 추가
4. 변경된 리소스는 이미지 변경
5. 자잘하게 바뀐 내용 점검 및 단어 수정

**Comment by fkdl0048** [comment]
제출용 자료 정리해주셔서 감사합니다~ 수정사항도 따로 없는 것 같습니다.

정말 작은 부분이라 신경 안써도 되긴 하는데, `잊힘`과 `잊혀짐`이라는 표현에서 `잊힘`이 표준어라는 것을 잘 알지만? 게임 분위기와 특성상 `잊혀짐`이 더 잘 어울린다고 생각합니다?

잊힘은 뭔가 자연발생한 것 같고, 잊혀짐은 누군가에 의해서 발생한 것 같은 느낌과 미련, 아련? 한느낌이 있어서 `잊혀진 게임`과 `잊힌 게임`을 놓고 봤을 때 전자가 더 매력적으로 보이는 것 같아요

유튜브를 보다가 관련해서 재밌는 설명 영상이 있어서 첨부합니닷

https://www.youtube.com/shorts/gyyFWGs_jRo

**Comment by wooyn730** [comment]
잘 읽었습니다
18, 19페이지랑 그 외 CH1의 맵3이 보이는 부분도 현재 버전 캡쳐해서 이미지 교체하면 좋겠습니다 (사소한 변화지만 ...)
TCG도 이미지 교체할 수 있게 이번 주에 조금 더 보기 좋게 해둘게요 ^^

저는 `잊혀짐`이 `잊힘`과는 다른 특유의 느낌이 있다고 생각했지만 표준어는 아니라 쓰면서도 좀 불편한 느낌이 있었습니다
근데 저 국어 강사님 영상 보니까 납득이 되고 편안해지네요 ㅋㅋㅋ

**Comment by Sumindd** [comment]
통합 기획서 241217 업데이트 완료
