### ISSUE TITLE
[CH2 UI] 말풍선UI

### ISSUE THREAD

**Issue by vprwolf** [GG-Studio-990001/Grayed-Game#815]
**2024.12.14**

안녕하세요. 말풍선UI 1차,호감도 화면 배치본을 올립니다.
![이미지1](https://github.com/user-attachments/assets/c1806d2f-08b6-4854-940b-46f0bfd03dc9)
![이미지2](https://github.com/user-attachments/assets/bc0700cb-2257-47db-8458-0175df0cd7b8)

**Comment by vprwolf** [comment]
**2024.12.14**
UI 부분 화면 배치본을 업로드 합니다!

**Comment by wooyn730** [comment]
말풍선 심플하고 깔끔하네요!
말풍선이랑 호감도 구드 올리고 링크 남겨주시면 다음 회의 전까지 반영하겠습니다!!
