### ISSUE TITLE
럭키 스킵버튼 구체화

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#819]
### 구체화 1차

- #810 에서 말씀드린 아이디어를 구체화했습니다.

![스크린샷 2024-12-15 213626](https://github.com/user-attachments/assets/fc2eba8c-a0f4-4177-b2b2-38dec857d186)

**Comment by fkdl0048** [comment]
회의에서 나온 내용을 잘 정리해주셔서 좋네요! 스킵에 관해서 조금 헷갈릴 수 있는 부분이 있는 것 같아서 회의 때 해당 내용을 팀원분들에게 잘 설명해주면 좋을 것 같습니다. 추가로 스킵 버튼의 위치가 예매할 수 있겠다는 생각이 드네요

**Comment by wooyn730** [comment]
![image](https://github.com/user-attachments/assets/c10eff94-b873-4a19-9b61-be3f193fd2f3)
지금 빌드에는 이렇게 적용해두었습니다!
저는 스킵버튼이 첫등장 할 때 좀 더 임팩트 있으면 좋을 것 같네요~
