### ISSUE TITLE
[CH2] 호감도 막판 상승 구체화

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#820]
### 구체화 1차
- #810 에서 말씀드린 아이디어를 구체화했습니다.

![image](https://github.com/user-attachments/assets/07f366f1-f512-4240-850d-32f17462c47f)

**Comment by fkdl0048** [comment]
카드 더미가 생기고 동일한 슬라임 카드 4장을 뽑는다는 것일까요?

**Comment by roweclaw** [comment]
네 우선 기본적인 카드 구성이 4장이라서 동일하게 했습니다. 근데 뭘 뽑아도 슬라임이랑 재회하게 되는 거라서, 아이디어로 작성했었던 '럭키가 직접 슬라임 카드 한 장을 준다' 등등... 좀 더 직관적이고 간단한 다른 방안을 고민해봐도 좋을 것 같아요.
