### ISSUE TITLE
[CH2] 대사 폴리싱

### ISSUE THREAD

**Issue by roweclaw** [GG-Studio-990001/Grayed-Game#826]
미카엘 말투를 고급스러운 싸가지st로 변경하고 장소이동 멘트 삭제 등 문맥을 자연스럽게 만드는 작업 진행했습니다.
이후 폴리싱은 CH2 기능이 모두 구현된 후 전체 대사를 빌드로 확인할 수 있을 때 진행할 예정입니다.
그 전까지 읽어보시고 피드백있으면 남겨주세요!

> 대사 수정

[CH2 대사폴더 위치](https://drive.google.com/drive/folders/1ymh1p_T7iYEcxC33MOyuKi41yVN4vbnL?usp=drive_link)
[Turn0](https://drive.google.com/file/d/149f2ihaItjt3shvDBcNoaAvMM1dK4taA/view?usp=sharing)
[Turn1](https://drive.google.com/file/d/140cj27VxEq_MEwXVm6j1bb5y7rxHBe57/view?usp=sharing)
[Turn2](https://drive.google.com/file/d/1sN6_NuH2F3G_wbpxFQwSjDO4AOC9d1aw/view?usp=sharing)
[Turn3](https://drive.google.com/file/d/12rG-TovUnbM8XKxlZhv63oMXN43YewzB/view?usp=sharing)
[Turn5](https://drive.google.com/file/d/1N2PNGFTJ5jBD2unCLUFEgBAbJ1dtFjmY/view?usp=sharing)
[Turn7](https://drive.google.com/file/d/1KSM1Hj1r17FmYg0vZi8T6ym_wrICKyBJ/view?usp=sharing)
[LuckyTCG](https://drive.google.com/file/d/1eZuPz0tnUi-y7K2LJQhchqkFT7fcXjyD/view?usp=sharing)

> TCG 질문 수정

TCG1 : 나한테 새 링을 준 이유가 뭐야?
TCG4 : 그런데 청결의 기도상은 어디서 찾은 거야?

**Comment by wooyn730** [comment]
대박이에요 미카엘이 더 매력적으로, 더 개성있게 느껴지네요 😍😍
바뀐거 아주 좋습니다! 잘 읽었습니다~~

---

피드백 죠금~~

(테스트하면서 엔터 몇개 수정했습니다)
(현재 Turn2까지 + TCG까지 수정 적용했습니다 / 확인도 Turn2까지만 함..ㅎㅎ)

1)
![image](https://github.com/user-attachments/assets/28f7f8c0-574e-4a9f-b125-7a9c0f1a82d8)
여기에 '야'만 3번째 줄로 넘어와서 일단 '괜찮을 거야'를 통째로 내리긴 했는데
대부분 대사가 2줄이라 통일할거면 대사 줄이는 게 좋을지도..??

<br>

2)
`Turn0: 다시 광장으로 돌아가기 위해 골목길에 들어섰는데, 갑자기 누군가 튀어나와 부딪혔다.`
`Turn2: 지하로 들어가니 긴 통로가 펼쳐졌고 R2-Mon을 뒤따라 나아갔다.`
요 문장들은 두 줄로 쪼개면 더 자연스러울 것 같아요

<br>
